#include <string.h>
#include "../common/common.h"
#include "lookup.h"

const LookupName lookup_f_table[] = {
    { "f15se", "F-15 스트라이크 이글" },
    { "f15se21", "F-15 스트라이크 이글 (개정판2.1)" },
    { "f15se22", "F-15 스트라이크 이글 (개정판2.2)" },
    { "f1dream", "F-1 드림" },
    { "f1dreamb", "F-1 드림 (해적판,세트1)" },
    { "f1dreamba", "F-1 드림 (해적판,세트2)" },
    { "f1en", "F1 익저스트 노트 (세계판,개정판A)" },
    { "f1enj", "F1 익저스트 노트 (일본판,개정판A)" },
    { "f1enu", "F1 익저스트 노트 (미국판,개정판A)" },
    { "f1gp", "F-1 그랑프리" },
    { "f1gp2", "F-1 그랑프리 파트 2" },
    { "f1gpa", "F-1 그랑프리" },
    { "f1gpb", "F-1 그랑프리" },
    { "f1gpbl", "F-1 그랑프리 (플레이마크 해적판)" },
    { "f1gpstar", "F-1 그랑프리 스타 (버전4.0)" },
    { "f1gpstar2", "F-1 그랑프리 스타 (버전2.0)" },
    { "f1gpstar3", "F-1 그랑프리 스타 (버전3.0)" },
    { "f1gpstr2", "F-1 그랑프리 스타 2" },
    { "f1lap", "F1 슈퍼 랩 (세계판)" },
    { "f1lapj", "F1 슈퍼 랩 (일본판)" },
    { "f1lapt", "F1 슈퍼 랩 (세계판)" },
    { "f1superb", "F1 슈퍼 배틀" },
    { "f355", "페라리 F355 챌린지" },
    { "f355p", "페라리 F355 챌린지" },
    { "f355twin", "페라리 F355 챌린지" },
    { "f355twinp", "페라리 F355 챌린지" },
    { "f355twn2", "페라리 F355 챌린지 2" },
    { "fa", "파이터 & 어택커 (일본판)" },
    { "faceoff", "페이스 오프 (일본판 2인용)" },
    { "failgate", "페일 게이트" },
    { "falcnwld", "팔콘 와일드 - 와일드 카드 1991 (TVG)" },
    { "falcnwlda", "팔콘 와일드 - 월드 와이드 포커 (비디오 클레인,세트1)" },
    { "falcnwldb", "팔콘 와일드 - 월드 와이드 포커 (비디오 클레인,세트2)" },
    { "falcnwldd", "팔콘 와일드 - 월드 와이드 포커 (팔콘 오리지널)" },
    { "falcon", "팔콘(8085A CPU)" },
    { "falcona", "팔콘 (해적판 세트2)" },
    { "falconz", "팔콘(Z80 CPU)" },
    { "famibox", "패미콤박스" },
    { "famistat", "패미콤스테이션" },
    { "fantasia", "판타지아 (PCB,세트1)" },
    { "fantasiaa", "판타지아 (PCB)" },
    { "fantasiab", "판타지아 (PCB,세트2)" },
    { "fantasian", "판타지아 (PCB)" },
    { "fantastc", "판타스틱 (갤럭시안 하드웨어로 갤라가 변환)" },
    { "fantasy", "판타지" },
    { "fantasyg", "판타지 (독일판,세트1)" },
    { "fantasyg2", "판타지 (독일판,세트2)" },
    { "fantasyj", "판타지 (일본판)" },
    { "fantasyu", "판타지 (미국판)" },
    { "fantazia", "판타지아" },
    { "fantjour", "극상 파로디우스/ 판타스틱 저니" },
    { "fantjoura", "극상 파로디우스/ 판타스틱 저니 (버전AAA)" },
    { "fantland", "판타지 랜드 (세트1)" },
    { "fantlanda", "판타지 랜드 (세트2)" },
    { "fantlnda", "판타지 랜드 (세트2)" },
    { "fantsia2", "판타지아2 (노골적인 표현)" },
    { "fantsia2a", "판타지아2 (적은 노출)" },
    { "fantsia2n", "판타지아2 (1998)" },
    { "fantstry", "판타지 스토리" },
    { "fantstrya", "판타지 스토리 (세트2)" },
    { "fantsy95", "판타지 95" },
    { "fantzn2", "판타지 존 2 - 오파오파의 눈물" },
    { "fantzn2x", "판타지 존 2 - 오파오파의 눈물 (시스템16C)" },
    { "fantzn2xp", "판타지 존 2 - 오파오파의 눈물 (시스템16C,시험판)" },
    { "fantzn2xps2", "판타지 존 2 - 오파오파의 눈물 (시스템16C,PS2 데이터)" },
    { "fantznps2", "판타지 존 (시스템16B,PS2 데이터)" },
    { "fantznta", "판타지 존 타임어택 (시스템16B,PS2 데이터)" },
    { "fantzon1", "판타지 존 (세트1,비보호)" },
    { "fantzone", "판타지 존 (개정판A,비보호됨)" },
    { "fantzone1", "판타지 존 (비보호)" },
    { "fantzonee", "판타지 존" },
    { "fantzoneno", "판타지 존 (신형,오버씨,PS2)" },
    { "fantzonenu", "판타지 존 (신형,미국 개정판A,PS2)" },
    { "fantzonep", "판타지 존" },
    { "fantzonepr", "판타지 존 (시험판)" },
    { "fantzoneta", "판타지 존" },
    { "fantzono", "판타지 존 (구버전)" },
    { "farmer", "잇키/ 파머즈 레벨리온" },
    { "farwest", "아이언 홀스/ 머나먼 서부" },
    { "fashion", "패션 (버전2.14)" },
    { "fashiong", "패션 갬블러" },
    { "fashiong2", "패션 갬블러 (세트2)" },
    { "fastdraw", "패스트 드로우 쇼다운 v1.3" },
    { "fastdrwp", "패스트 트로우" },
    { "fastfred", "패스트 프레디" },
    { "fastlane", "패스트 레인" },
    { "fatfur1h", "아랑전설 - 숙명의 싸움 (히든 핵)" },
    { "fatfur2h", "아랑전설 2 - 새로운 싸움 (히든 핵)" },
    { "fatfur3b", "아랑전설 3 - 아득한 싸움 (보스 핵)" },
    { "fatfursa", "아랑전설 스페셜 (세트2)" },
    { "fatfursh", "아랑전설 스페셜 (히든 핵)" },
    { "fatfursp", "아랑전설 스페셜 (세트1)" },
    { "fatfurspa", "아랑전설 스페셜 (세트2)(NGM-058)(NGH-058)" },
    { "fatfurspb", "아랑전설 스페셜 (SNES 해적판 타이머)" },
    { "fatfurspbs", "아랑전설 스페셜 (히든캐릭터3rd,핵)" },
    { "fatfurwa", "아랑전설 - 와일드 앰비션" },
    { "fatfury1", "아랑전설 - 숙명의 싸움" },
    { "fatfury1bh", "아랑전설 - 숙명의 싸움 (보스핵)" },
    { "fatfury1k", "아랑전설 - 숙명의 싸움 (한글)" },
    { "fatfury2", "아랑전설 2 - 새로운 싸움" },
    { "fatfury2a", "아랑전설 2 - 새로운 싸움 (NGM-047)" },
    { "fatfury2k", "아랑전설 2 - 새로운 싸움 (한글)" },
    { "fatfury3", "아랑전설 3 - 아득한 싸움" },
    { "fatfury3a", "아랑전설 3 - 아득한 싸움 (NGM-069)(NGH-069)(대체 세트)" },
    { "fatfury3bh", "아랑전설 3 - 아득한 싸움 (고대전투부활,핵)" },
    { "fax", "팩스" },
    { "fax2", "팩스 2" },
    { "faxa", "팩스 (대체 문항)" },
    { "fb2010", "후르츠 보너스 2010" },
    { "fb2gen", "후르츠 보너스 2nd 제너레이션" },
    { "fb2genc1", "후르츠 보너스 2nd 제너레이션 (버전1.8R,세트1)" },
    { "fb2genc2", "후르츠 보너스 2nd 제너레이션 (버전1.8LT,세트1)" },
    { "fb2gend1", "후르츠 보너스 2nd 제너레이션 (버전1.8R,세트2)" },
    { "fb2gend2", "후르츠 보너스 2nd 제너레이션 (버전1.8LT,세트2)" },
    { "fb2geno", "후르츠 보너스 2nd 제너레이션 (버전1.6XT)" },
    { "fb2geno2", "후르츠 보너스 2nd 제너레이션 (버전1.5)" },
    { "fb2genv1", "후르츠 보너스 2nd 제너레이션 (버전1.8R 듀얼)" },
    { "fb2genv2", "후르츠 보너스 2nd 제너레이션 (버전1.8LT 듀얼)" },
    { "fb2nd", "후르츠 보너스 2nd 에디션" },
    { "fb2ndc2", "후르츠 보너스 2nd 에디션 (버전1.8LT,세트1)" },
    { "fb2ndd1", "후르츠 보너스 2nd 에디션 (버전1.8R,세트2)" },
    { "fb2ndd2", "후르츠 보너스 2nd 에디션 (버전1.8LT,세트2)" },
    { "fb2ndo", "후르츠 보너스 2nd 에디션 (버전1.5)" },
    { "fb2ndv1", "후르츠 보너스 2nd 에디션 (버전1.8R 듀얼)" },
    { "fb2ndv2", "후르츠 보너스 2nd 에디션 (버전1.8LT 듀얼)" },
    { "fb3g", "후르츠 보너스 3G (버전1.0.3)" },
    { "fb4", "후르츠 보너스 2004" },
    { "fb4b2", "후르츠 보너스 2004 (버전1.5LT,세트1)" },
    { "fb4c1", "후르츠 보너스 2004 (버전1.5R,세트2)" },
    { "fb4c2", "후르츠 보너스 2004 (버전1.5LT,세트2)" },
    { "fb4d1", "후르츠 보너스 2004 (버전1.5R,세트3)" },
    { "fb4d2", "후르츠 보너스 2004 (버전1.5LT,세트3)" },
    { "fb4exp", "후르츠 보너스 2005 (2004 수출 버전1.5E 듀얼)" },
    { "fb4o", "후르츠 보너스 2004 (버전1.3XT)" },
    { "fb4o2", "후르츠 보너스 2004 (버전1.2)" },
    { "fb4v1", "후르츠 보너스 2004 (버전1.5R 듀얼)" },
    { "fb4v2", "후르츠 보너스 2004 (버전1.5LT 듀얼)" },
    { "fb5", "후르츠 보너스 2005" },
    { "fb5c", "후르츠 보너스 2005 (버전1.5SH,세트2)" },
    { "fb5d", "후르츠 보너스 2005 (버전1.5SH,세트3)" },
    { "fb5v", "후르츠 보너스 2005 (버전1.5SH 듀얼)" },
    { "fb6", "후르츠 보너스 '06 - 10주년판" },
    { "fb6d1", "후르츠 보너스 '06 - 10주년판 (버전1.7R CGA,세트1)" },
    { "fb6d2", "후르츠 보너스 '06 - 10주년판 (버전1.7LT CGA,세트1)" },
    { "fb6s1", "후르츠 보너스 '06 - 10주년판 (버전1.7R CGA,세트2)" },
    { "fb6s2", "후르츠 보너스 '06 - 10주년판 (버전1.7LT CGA,세트2)" },
    { "fb6s3", "후르츠 보너스 '06 - 10주년판 (버전1.3R CGA)" },
    { "fb6se", "후르츠 보너스 2006 스페셜에디션" },
    { "fb6sed1", "후르츠 보너스 2006 스페셜에디션 (버전1.4R CGA)" },
    { "fb6sed2", "후르츠 보너스 2006 스페셜에디션 (버전1.4LT CGA)" },
    { "fb6sev", "후르츠 보너스 2006 스페셜에디션 (버전1.4E 듀얼)" },
    { "fb6sev1", "후르츠 보너스 2006 스페셜에디션 (버전1.4R 듀얼)" },
    { "fb6sev2", "후르츠 보너스 2006 스페셜에디션 (버전1.4LT 듀얼)" },
    { "fb6v", "후르츠 보너스 '06 - 10주년판 (버전1.7E 듀얼)" },
    { "fb6v1", "후르츠 보너스 '06 - 10주년판 (버전1.7R 듀얼)" },
    { "fb6v2", "후르츠 보너스 '06 - 10주년판 (버전1.7LT 듀얼)" },
    { "fbait2bc", "피셔맨스 베이트 2 - 배스 챌린지" },
    { "fbaitbc", "피셔맨스 베이트 - 배스 챌린지" },
    { "fbaitmc", "피셔맨스 베이트 - 마린 챌린지" },
    { "fbaitmca", "피셔맨스 베이트 - 마린 챌린지 (GX889 v.AA)" },
    { "fbaitmcj", "피셔맨스 베이트 - 마린 챌린지 (GX889 v.JA)" },
    { "fbaitmcu", "피셔맨스 베이트 - 마린 챌린지 (GX889 v.UA)" },
    { "fball", "파이어 볼 (FM 작동)" },
    { "fbcrazy", "풋볼 크레이지 (비디오 퀴즈)" },
    { "fbdeluxe", "후르츠 보너스 디럭스 (버전1.0.9)" },
    { "fbdeluxeo", "후르츠 보너스 디럭스 (버전1.0.7)" },
    { "fbfrenzy", "풋볼 프렌지" },
    { "fcnudge", "후르츠 카니발 너지" },
    { "fcnudgeo", "후르츠 카니발 너지 (버전2.0,세트1)" },
    { "fcnudgeo2", "후르츠 카니발 너지 (버전2.0,세트2)" },
    { "fcnudgeo3", "후르츠 카니발 너지 (버전1.7)" },
    { "fcockt_6", "후르츠 칵테일" },
    { "fcockt_6a", "후르츠 칵테일 (040216,뱅킹 주소 핵)" },
    { "fcockt_6b", "후르츠 칵테일 (040216,백도어)" },
    { "fcockt_7", "후르츠 칵테일 (050118)" },
    { "fcockt_7a", "후르츠 칵테일 (050118,백도어)" },
    { "fcockt_8", "후르츠 칵테일 (060111)" },
    { "fcombat", "필드 컴뱃" },
    { "fcrash", "파이널 크래쉬 (파이널 파이트 해적판)" },
    { "fearless", "피어리스 피노키오" },
    { "fengyunh", "풍운회" },
    { "fenix", "페닉스" },
    { "fenixn", "페닉스" },
    { "fever13", "피버 13 (일본판)" },
    { "feversoc", "피버 사커" },
    { "feversos", "탄총 피버론_피버 SOS (세계판)" },
    { "ffantasa", "파이팅 판타지 (일본판)" },
    { "ffantasy", "파이팅 판타지 (일본판 개정판3)" },
    { "ffantasya", "파이팅 판타지 (일본판)" },
    { "ffantasyb", "파이팅 판타지 (일본판 개정판?)" },
    { "ffantasybl", "파이팅 판타지" },
    { "ffantasyj", "파이팅 판타지 (일본판 개정판2)" },
    { "ffigh1v2", "파이널 파이트 (1v2,핵)" },
    { "ffight", "파이널 파이트 (세계판,세트1)" },
    { "ffight2b", "파이널 파이트 2 (SNES 해적판)" },
    { "ffight3b", "파이널 파이트 2 (SNES 해적판,세트1)" },
    { "ffight3b2", "파이널 파이트 2 (SNES 해적판,세트2)" },
    { "ffighta", "파이널 파이트 (세계판,세트2)" },
    { "ffightae", "파이널 파이트 30주년 기념판" },
    { "ffightaec2", "파이널 파이트 기념판(CPS2)" },
    { "ffightaec2ds", "파이널 파이트 기념판(데들리 스트리트,핵,CPS2)" },
    { "ffightaec2k", "파이널 파이트 기념판(CPS2,한글)" },
    { "ffightaek", "파이널 파이트 30주년 기념판 (한글)" },
    { "ffightaemgc", "파이널 파이트 30주년 기념판 (매드 기어즈 시티 핵)" },
    { "ffightbl", "파이널 파이트 (해적판 세트1,세계판)" },
    { "ffightbla", "파이널 파이트 (해적판 세트2,세계판)" },
    { "ffightblb", "파이널 파이트 (해적판 싱글 OKI)" },
    { "ffightdw", "파이널 파이트 (워리어스,핵)" },
    { "ffightfw", "파이널 파이트 (프레임워크,핵)" },
    { "ffightj", "파이널 파이트 (일본판)" },
    { "ffightj1", "파이널 파이트 (일본판)" },
    { "ffightj2", "파이널 파이트 (일본판)" },
    { "ffightj3", "파이널 파이트 (일본판)" },
    { "ffightj4", "파이널 파이트 (일본판)" },
    { "ffightjh", "파이널 파이트_스트리트 스마트 (일본판,핵)" },
    { "ffightk", "파이널 파이트 (한글)" },
    { "ffightk4", "파이널 파이트 (한글)" },
    { "ffightu", "파이널 파이트 (미국판,세트1)" },
    { "ffightu1", "파이널 파이트 (미국판,세트2)" },
    { "ffightu2", "파이널 파이트 (미국판,세트3)" },
    { "ffightua", "파이널 파이트 (미국판)" },
    { "ffightub", "파이널 파이트 (미국판)" },
    { "ffightuc", "파이널 파이트 (미국판)" },
    { "ffortune", "판타지 포춘" },
    { "ffreveng", "파이널 파이트 리벤지" },
    { "ffrevng10", "파이널 파이트 리벤지 (V1.000)" },
    { "ffurspbs", "아랑전설 스페셜 (히든캐릭터3rd,핵)" },
    { "ffurspbt", "아랑전설 스페셜 (BT 버전 PPX,핵)" },
    { "ffury1bs", "아랑전설 - 숙명의 싸움 (보스 핵)" },
    { "ffury2es", "아랑전설 2 - 새로운 싸움 (이지 스페셜 어택,핵)" },
    { "ffury3bs", "아랑전설 3 - 아득한 싸움 (고대전투부활,핵)" },
    { "ffury3eh", "아랑전설 3 - 아득한 싸움 (애드 캐릭터 - 울트라 킬 스타일 체인지드,핵)" },
    { "fghtatck", "파이터 & 어태커 (미국판)" },
    { "fghtbskt", "파이팅 바스켓볼" },
    { "fghthist", "파이터즈 히스토리 (세계판 버전43-09)" },
    { "fghthista", "파이터즈 히스토리 (세계판 버전43-07)" },
    { "fghthistb", "파이터즈 히스토리 (세계판 버전43-05)" },
    { "fghthistj", "파이터즈 히스토리 (일본판 버전41-07)" },
    { "fghthistja", "파이터즈 히스토리 (일본판 버전41-05)" },
    { "fghthistjb", "파이터즈 히스토리 (일본판 버전41-04)" },
    { "fghthistu", "파이터즈 히스토리 (미국판 버전42-09)" },
    { "fghthistua", "파이터즈 히스토리 (미국판 버전42-06)" },
    { "fghthistub", "파이터즈 히스토리 (미국판 버전42-05)" },
    { "fghthistuc", "파이터즈 히스토리 (미국판 버전42-03)" },
    { "fghthsta", "파이터즈 히스토리 (미국판 버전42-05,대체 하드웨어)" },
    { "fghthstu", "파이터즈 히스토리 (미국판 버전42-03)" },
    { "fghthstw", "파이터즈 히스토리 (세계판)" },
    { "fghtjam", "캡콤 파이팅 잼" },
    { "fghtmn", "파이팅 매니아 (QG918 VER. EAA)" },
    { "fghtmna", "파이팅 매니아 (QG918 VER. AAA)" },
    { "fghtmnk", "파이팅 매니아 (QG918 VER. KAA)" },
    { "fghtmnu", "파이팅 매니아 (QG918 VER. UAA)" },
    { "fgoal", "필드 골" },
    { "fgoala", "필드 골 (다른 버전)" },
    { "fgtlayer", "파이팅 레이어" },
    { "fgtlayerja", "파이팅 레이어 (일본판)" },
    { "fhawk", "파이팅 호크 (세계판)" },
    { "fhawkj", "파이팅 호크 (일본판)" },
    { "fhboxers", "펑키 헤드 복서" },
    { "fieldday", "필드 데이" },
    { "fightfeb", "왕중왕/ 파이트 피버 (보스 핵)" },
    { "fightfev", "왕중왕/ 파이트 피버 (세트1)" },
    { "fightfeva", "왕중왕/ 파이트 피버 (세트2)" },
    { "fightfva", "왕중왕/ 파이트 피버 (세트2)" },
    { "fightrol", "파이팅 롤러" },
    { "filetto", "필레토" },
    { "finalap2", "파이널 랩 2" },
    { "finalap2j", "파이널 랩 2 (일본판)" },
    { "finalap3", "파이널 랩 3" },
    { "finalap3a", "파이널 랩 3 (세계판,세트2)" },
    { "finalap3bl", "파이널 랩 3 (해적판)" },
    { "finalap3j", "파이널 랩 3 (일본판)" },
    { "finalap3jc", "파이널 랩 3 (일본판)" },
    { "finalapc", "파이널 랩 (개정판C)" },
    { "finalapd", "파이널 랩 (개정판D)" },
    { "finalapo", "파이널 랩 R" },
    { "finalapr", "파이널 랩 R (개정판B)" },
    { "finalapr1", "파이널 랩 R" },
    { "finalaprj", "파이널 랩 R (일본판,개정판C)" },
    { "finalaprj1", "파이널 랩 R (일본판,개정판B)" },
    { "finalapro", "파이널 랩 R" },
    { "finalb", "파이널 블로우 (세계판)" },
    { "finalbj", "파이널 블로우 (일본판)" },
    { "finalbny", "마작 파이널 바니 (일본판)" },
    { "finalbu", "파이널 블로우 (미국판)" },
    { "finalgdr", "파이널 고도리 (한국판)" },
    { "finalizb", "파이널라이저 - 슈퍼 트랜스포메이션" },
    { "finalizr", "파이널라이저 - 슈퍼 트랜스포메이션 (세트1)" },
    { "finalizra", "파이널라이저 - 슈퍼 트랜스포메이션 (세트2)" },
    { "finalizrb", "파이널라이저 - 슈퍼 트랜스포메이션" },
    { "finallap", "파이널 랩" },
    { "finallapc", "파이널 랩 (개정판C)" },
    { "finallapd", "파이널 랩 (개정판D)" },
    { "finallapjb", "파이널 랩 (일본판 - 개정판B)" },
    { "finallapjc", "파이널 랩 (일본판 - 개정판C)" },
    { "finalp2j", "파이널 랩 2 (일본판)" },
    { "finalp3a", "파이널 랩 3 (세계판)" },
    { "finalp3j", "파이널 랩 3 (일본판)" },
    { "finalttr", "파이널 테트리스" },
    { "findlove", "파인드 러브" },
    { "findout", "파인드 아웃" },
    { "findouta", "파인드 아웃 (버전4.04,세트2)" },
    { "finehour", "파이니스트 아워 (일본판)" },
    { "finfrl2j", "파이널 펄롱 2 (일본판)" },
    { "finfurl", "파이널 펄롱 2 (세계판,FF2버전A)" },
    { "finfurl2", "파이널 펄롱 2 (세계판)" },
    { "finfurl2j", "파이널 펄롱 2 (일본판)" },
    { "finger", "핑거 (스팅어 해적판)" },
    { "finlapjb", "파이널 랩 (일본판 - 개정판B)" },
    { "finlapjc", "파이널 랩 (일본판 - 개정판C)" },
    { "finlarch", "슈퍼 메이저리그/ 파이널 아치 (일본판,V1.001)" },
    { "finlflng", "파이널 펄롱" },
    { "firebarr", "에어 어썰트/ 파이어 배럴 (일본판)" },
    { "firebatl", "파이어 배틀" },
    { "firebeas", "파이어비스트 (시제품)" },
    { "firefox", "파이어 폭스" },
    { "firefoxa", "파이어 폭스 (세트2)" },
    { "firehawk", "파이어 호크 (세계판) (중국판)(가로)" },
    { "firehawkv", "파이어 호크 (세계판) (중국판)(스위쳐블)" },
    { "fireone", "파이어 원" },
    { "fireshrk", "파이어 샤크" },
    { "fireshrka", "파이어 샤크 (초기판)" },
    { "fireshrkd", "파이어 샤크 (한국판,세트1,쉬움)" },
    { "fireshrkdh", "파이어 샤크 (한국판,세트2,어려움)" },
    { "firetpbl", "파이어 트랩 (일본판 해적판)" },
    { "firetrap", "파이어 트랩 (미국판,개정판A)" },
    { "firetrapa", "파이어 트랩 (미국판)" },
    { "firetrapbl", "파이어 트랩 (일본판 해적판)" },
    { "firetrapj", "파이어 트랩 (일본판)" },
    { "firetrk", "파이어 트럭/ 스모키 조 (PROM버전)" },
    { "firetrka", "파이어 트럭/ 스모키 조 (ROM버전)" },
    { "fishfren", "피싱 프린지" },
    { "fitegol2", "파이팅 골프 (미국판)" },
    { "fitegolf", "리 트레비노의 파이팅 골프 (세계판?)" },
    { "fitegolfu", "리 트레비노의 파이팅 골프" },
    { "fitegolfua", "리 트레비노의 파이팅 골프" },
    { "fitfight", "피트 오브 파이팅" },
    { "fitter", "라운드 업/ 피터" },
    { "fitterbl", "라운드 업/ 피터 (라운드업 해적판)" },
    { "fiveside", "파이브 어 사이드 사커" },
    { "fixeighb", "픽스에이트" },
    { "fixeight", "픽스에이트 (유럽판)" },
    { "fixeighta", "픽스에이트 (동남아시판)" },
    { "fixeightat", "픽스에이트 (동남아시판,타이토 라이센스)" },
    { "fixeightb", "픽스에이트" },
    { "fixeightbl", "픽스에이트 (한국판,해적판)" },
    { "fixeighth", "픽스에이트 (홍콩판)" },
    { "fixeightht", "픽스에이트 (홍콩판,타이토 라이센스)" },
    { "fixeightj", "픽스에이트 (일본판)" },
    { "fixeightjt", "픽스에이트 (일본판,타이토 라이센스)" },
    { "fixeightk", "픽스에이트 (한국판)" },
    { "fixeightkt", "픽스에이트 (한국판,타이토 라이센스)" },
    { "fixeightt", "픽스에이트 (유럽판,타이토 라이센스)" },
    { "fixeighttw", "픽스에이트 (대만판)" },
    { "fixeighttwt", "픽스에이트 (대만판,타이토 라이센스)" },
    { "fixeightu", "픽스에이트 (미국판)" },
    { "fixeightut", "픽스에이트 (미국판,타이토 라이센스)" },
    { "fjbuster", "쇼군 워리어즈/ 후지야마 버스터 (일본판)" },
    { "fl7_2000", "플레이밍 7" },
    { "fl7_2k16", "플레이밍 7" },
    { "fl7_3121", "플레이밍 7" },
    { "fl7_50", "플레이밍 7" },
    { "fl7_500", "플레이밍 7" },
    { "fl7_tw", "플레이밍 7" },
    { "flagrall", "96 플래그 랠리" },
    { "flameguj", "프레임 거너 (일본판)" },
    { "flamegun", "프레임 거너" },
    { "flamegunj", "프레임 거너 (일본판)" },
    { "flapchck", "플래피 치킨 (HB)" },
    { "flashgal", "플래시걸 (세트1)" },
    { "flashgala", "플래시걸 (세트2)" },
    { "flashgalk", "플래시걸 (세트1,큐고 로고)" },
    { "flashgla", "플래시걸 (세트2)" },
    { "flicks1", "플릭키 (64k 버전,세트2)" },
    { "flicks2", "플릭키 (128k 버전,비암호화)" },
    { "flicky", "플릭키 (128k 버전)" },
    { "flicky2", "플릭키 (세트2)" },
    { "flickya", "플릭키 (128k 버전,고용량 롬)" },
    { "flickyb", "플릭키 (128k 버전,고용량 롬,신형)" },
    { "flickyg", "플릭키 (128k 버전,시스템2,대체 그래픽)" },
    { "flickyo", "플릭키 (64k 버전,세트1)" },
    { "flickys1", "플릭키 (64k 버전,세트2)" },
    { "flickys2", "플릭키 (128k 버전,비암호화)" },
    { "flickys2g", "플릭키 (128k 버전,시스템2,비암호화,대체 그래픽)" },
    { "flickyup", "플릭키 (64k 버전,업다운 보드세트1)" },
    { "flickyupa", "플릭키 (64k 버전,업다운 보드세트2)" },
    { "flipjack", "플리퍼 잭" },
    { "flipmaze", "플립 메이즈" },
    { "flipshot", "배틀 플립 샷" },
    { "flipshotk", "배틀 플립 샷 (한글)" },
    { "flipshtk", "배틀 플립 샷 (한글)" },
    { "flipull", "플로팅/ 플리플 (일본판)" },
    { "flkatck", "MX5000/ 플렉 어택 (일본판)" },
    { "flkatcka", "MX5000/ 플렉 어택 (일본판)" },
    { "floritas", "플로리타스 (문 크레스타 해적판)" },
    { "floritasm", "플로리타스 (스페인 해적한)" },
    { "flower", "플라워 (미국판)" },
    { "flowerbl", "플라워" },
    { "flowerj", "플라워 (일본판)" },
    { "flstory", "요정나라 이야기" },
    { "flstoryj", "요정나라 이야기 (일본판)" },
    { "flstoryo", "요정나라 이야기 (초기형)" },
    { "flyball", "플라이볼" },
    { "flyball1", "플라이볼 (개정판1)" },
    { "flyboy", "플라이 보이" },
    { "flyboyb", "플라이 보이" },
    { "flytiger", "플라잉 타이거 (세트1)" },
    { "flytigera", "플라잉 타이거 (세트2)" },
    { "fmania", "파이팅 매니아" },
    { "fmaniac2p", "낚시광 2+" },
    { "fmaniac3", "낚시광 3" },
    { "fncywld", "팬시 월드 - 어스 오브 크라이시스" },
    { "fnkyfish", "펑키 피쉬" },
    { "fnshark", "플라잉 샤크" },
    { "fntsia2a", "판타지아2 (적은 노출)" },
    { "foodf", "푸드 파이트 (개정판3)" },
    { "foodf1", "푸드 파이트 (개정판1)" },
    { "foodf2", "푸드 파이트 (개정판2)" },
    { "foodfc", "푸드 파이트 (칵테일)" },
    { "foolrace", "풋 레이스" },
    { "footbpow", "풋볼 파워" },
    { "footbpow11", "풋볼 파워 (버전1.1)" },
    { "footchmp", "해트트릭 히어로 _풋볼 챔프 (세계판)" },
    { "forcebrk", "포스 브레이크/ 강공돌파" },
    { "forcefive_aw", "포스 파이브 (미출시)" },
    { "forgottn", "포가튼 월드/ 잊혀진 세계 (세계판,신형)" },
    { "forgottna", "포가튼 월드/ 잊혀진 세계 (세계판)" },
    { "forgottnj", "포가튼 월드/ 잊혀진 세계 (일본판,영어 시험판)" },
    { "forgottnu", "포가튼 월드/ 잊혀진 세계 (미국판,개정판C)" },
    { "forgottnua", "포가튼 월드/ 잊혀진 세계 (미국판,개정판A)" },
    { "forgottnuaa", "포가튼 월드/ 잊혀진 세계 (미국판,개정판AA)" },
    { "forgottnuc", "포가튼 월드/ 잊혀진 세계 (미국판,개정판C)" },
    { "forgottnue", "포가튼 월드/ 잊혀진 세계 (미국판,개정판E)" },
    { "formatz", "포메이션 Z" },
    { "fort2b", "포트리스 2 블루 아케이드 (세계판,버전1.01)" },
    { "fort2ba", "포트리스 2 블루 아케이드 (한국판,버전1.00)" },
    { "fortecar", "포르테 카드" },
    { "fortecrd", "포르테 카드 (버전110,스페인어)" },
    { "fortecrde", "포르테 카드 (버전103,영어)" },
    { "fortune1", "포춘 I (PK485-S,드로우 포커)" },
    { "fotns", "북두의 권" },
    { "fourplay", "포 플레이" },
    { "fourtrax", "포 트랙스" },
    { "fourtraxa", "포 트랙스 (미국판)" },
    { "fourtraxj", "포 트랙스 (일본판)" },
    { "fpoint", "플래시 포인트 (세트2,일본판)" },
    { "fpoint1", "플래시 포인트 (세트1,일본판)" },
    { "fpoint1d", "플래시 포인트 (세트1,일본판,암호해제)" },
    { "fpointbj", "플래시 포인트 (일본판,해적판,세트1)" },
    { "fpointbl", "플래시 포인트 (세계판,해적판)" },
    { "fpointbla", "플래시 포인트 (일본판,해적판,세트2)" },
    { "fpointd", "플래시 포인트 (세트2,일본판,암호해제)" },
    { "franticf", "프랜틱 프레드 (발매2)" },
    { "franticfa", "프랜틱 프레드" },
    { "fredmem", "프레드 플린스톤의 메모리 매치" },
    { "fredmemc", "프레드 플린스톤의 메모리 매치 (중국판)" },
    { "fredmemj", "프레드 플린스톤의 메모리 매치 (일본판,하이스코어 버전)" },
    { "fredmemuk", "프레드 플린스톤의 메모리 매치 (영국판)" },
    { "fredmemus", "프레드 플린스톤의 메모리 매치 (미국판,하이스코어 버전)" },
    { "fredmesp", "프레드 플린스톤의 메모리 매치 (스페인어)" },
    { "freekckb", "프리 킥" },
    { "freekick", "프리 킥" },
    { "freekicka", "프리 킥" },
    { "freekickb", "프리 킥 (해적판 세트1)" },
    { "freekickb1", "프리 킥 (해적판 세트1)" },
    { "freekickb2", "프리 킥 (해적판 세트2)" },
    { "freekickb3", "프리 킥 (해적판 세트3)" },
    { "freeze", "프리즈" },
    { "freezeat", "프리즈" },
    { "freezeat2", "프리즈" },
    { "freezeat3", "프리즈" },
    { "freezeat4", "프리즈" },
    { "freezeat5", "프리즈" },
    { "freezeat6", "프리즈" },
    { "freezeatjp", "프리즈 (아타리)(시험판,일본어음성)" },
    { "frenzy", "프렌지 (개정판RA1)" },
    { "friskyt", "프리스키 톰 (세트1)" },
    { "friskyta", "프리스키 톰 (세트2)" },
    { "friskytb", "프리스키 톰 (세트3,암호화)" },
    { "frogf", "프로그" },
    { "frogg", "프로그 (갤럭시안 하드웨어,해적판)" },
    { "froggeg", "프로그 (헤르매틱,갤럭시안 하드웨어,해적판)" },
    { "frogger", "프로거" },
    { "froggeram", "프로거 (아미고? 하드웨어 해적판)" },
    { "froggereb", "프로거 - 뉴 시리즈 92 (해적판)" },
    { "froggermc", "프로거 (문 크레스타 하드웨어)" },
    { "froggers", "프로그" },
    { "froggers1", "프로거 (세가 세트1)" },
    { "froggers2", "프로거 (세가 세트2)" },
    { "froggers3", "프로거 (세가 세트3)" },
    { "froggert", "프로거 (터틀스 하드웨어)" },
    { "froggerv", "프로거 (비디오트론 하드웨어)" },
    { "froggervd", "프로그 (헤르매틱,스크램블 하드웨어,해적판)" },
    { "froggrmc", "프로거 (문 크레스타 하드웨어)" },
    { "froggrs", "프로거 (코인 뮤직,스크램블 하드웨어,해적판)" },
    { "frogs", "개구리" },
    { "frogseg1", "프로거 (세가 세트1)" },
    { "frogseg2", "프로거 (세가 세트2)" },
    { "froman2b", "아이돌 마작 - 파이널 로맨스 2 (네오 CD 변환)" },
    { "fromanc2", "대전 아이돌 마작 파이널 로맨스 2 (일본판,신형)" },
    { "fromanc2o", "대전 아이돌 마작 파이널 로맨스 2 (일본판,구형)" },
    { "fromanc4", "대전 마작 파이널 로맨스 4" },
    { "fromance", "아이돌 마작 파이널 로맨스" },
    { "fromancr", "대전 마작 파이널 로맨스 R" },
    { "frontlin", "프론트 라인 (세트1)" },
    { "frontlina", "프론트 라인 (세트2)" },
    { "fround", "파이널 라운드 (버전M)" },
    { "froundl", "파이널 라운드 (버전L)" },
    { "fruitbun", "후르츠 & 버니 (세계판)" },
    { "fruitpar", "후르츠 파라다이스" },
    { "fruitpar206us", "후르츠 파라다이스" },
    { "fruitstb", "후르츠 스타 보너스" },
    { "fruitstba", "후르츠 스타 보너스" },
    { "fruitstbb", "후르츠 스타 보너스" },
    { "fruitstbc", "후르츠 스타 보너스" },
    { "fruitstbd", "후르츠 스타 보너스" },
    { "fruitstbe", "후르츠 스타 보너스" },
    { "fruitstbf", "후르츠 스타 보너스" },
    { "fruitstbg", "후르츠 스타 보너스" },
    { "fruitstbh", "후르츠 스타 보너스" },
    { "fruitstbi", "후르츠 스타 보너스" },
    { "fruitstr", "후르츠 스타" },
    { "fshark", "플라잉 샤크 (세계판)" },
    { "fsharkb", "플라잉 샤크 (세계판,해적판)" },
    { "fsharkbt", "플라잉 샤크 (해적판)" },
    { "fsoccer", "파이팅 사커" },
    { "fsoccerb", "파이팅 사커 (조이스틱 핵 해적판)" },
    { "fsoccerba", "파이팅 사커 (조이스틱 핵 해적판,대체)" },
    { "fsoccerj", "파이팅 사커 (일본판)" },
    { "fspiderb", "프로그 & 스파이더즈 (시제품?)" },
    { "fstarfrc", "파이널 스타포스 (미국판)" },
    { "fstarfrcj", "파이널 스타포스 (일본판)" },
    { "fstarfrcja", "파이널 스타포스 (일본판)" },
    { "fstarfrcw", "파이널 스타포스 (세계판)" },
    { "fstation", "펀 스테이션" },
    { "fswords", "사무라이 쇼다운 3/ 파이터즈 소드 (한국판)" },
    { "ftimpact", "파이터즈 임팩트 (버전2.02O)" },
    { "ftimpactj", "파이터즈 임팩트 (버전2.02J)" },
    { "ftimpactu", "파이터즈 임팩트 (버전2.02A)" },
    { "ftimpcta", "파이터즈 임팩트 A" },
    { "fts2in1", "슈퍼 투 인 원" },
    { "ftsoccer", "파이팅 사커" },
    { "ftspeed", "패스터 댄 스피드" },
    { "fullthrl", "탑 스피드/ 풀 스로틀 (일본판)" },
    { "funcsino", "스테이터스 펀 카지노" },
    { "funcube", "펀큐브 (v1.5)" },
    { "funcube2", "펀큐브 2 (v1.1)" },
    { "funcube3", "펀큐브 3 (v1.1)" },
    { "funcube4", "펀큐브 4 (v1.0)" },
    { "funcube5", "펀큐브 5 (v1.0)" },
    { "funkball", "펑키 볼" },
    { "funkbeeb", "펑키 비 (해적판,어려움)" },
    { "funkybee", "펑키 비" },
    { "funkybeeb", "펑키 비 (해적판,어려움)" },
    { "funkyfig", "퍼스트 펑키 파이터" },
    { "funkyfiga", "퍼스트 펑키 파이터 (세트2)" },
    { "funkyjej", "펑키 젯 (일본판)" },
    { "funkyjet", "펑키 젯 (세계판,개정판1)" },
    { "funkyjeta", "펑키 젯 (세계판)" },
    { "funkyjeta2", "펑키 젯 (한국판,시험판?)" },
    { "funkyjetj", "펑키 젯 (일본판,개정판2)" },
    { "funlddlx", "퍼니 랜드 데 럭스" },
    { "funnymou", "슈퍼 마우스/ 퍼니 마우스 (일본판)" },
    { "funquiz", "펀 월드 퀴즈" },
    { "funriver", "펀 리버" },
    { "funriverd1", "펀 리버" },
    { "funriverv", "펀 리버" },
    { "funybubl", "퍼니 버블" },
    { "funybublc", "퍼니 버블 (코매드 버전)" },
    { "funystrp", "퍼니 스트립" },
    { "futari10", "벌레 공주님 후타리 버전1.0 (마스터 버전)" },
    { "futari15", "벌레 공주님 후타리 버전1.5 (마스터 버전1.54.)" },
    { "futari15a", "벌레 공주님 후타리 버전1.5 (마스터 버전1.54)" },
    { "futaribl", "벌레 공주님 후타리 블랙 라벨 - 어나더 버전" },
    { "futariblj", "벌레 공주님 후타리 블랙 라벨" },
    { "futflash", "퓨쳐 플래쉬" },
    { "futspy", "퓨쳐 스파이" },
    { "fuusenpn", "풍선 펜타" },
    { "fvipers", "파이팅 바이퍼즈" },
    { "fvipers2", "파이팅 바이퍼즈 2" },
    { "fvipersb", "파이팅 바이퍼즈 (개정판B)" },
    { "fx", "에프-엑스" },
};

const size_t lookup_f_count = A_SIZE(lookup_f_table);

const char *lookup_f(const char *name) {
    if (!name) return NULL;
    for (size_t i = 0; i < lookup_f_count; i++) {
        if (strcmp(lookup_f_table[i].name, name) == 0) {
            return lookup_f_table[i].value;
        }
    }
    return NULL;
}

const char *r_lookup_f(const char *value) {
    if (!value) return NULL;
    for (size_t i = 0; i < lookup_f_count; i++) {
        if (strstr(lookup_f_table[i].value, value)) {
            return lookup_f_table[i].name;
        }
    }
    return NULL;
}

void lookup_f_multi(const char *term, void (*emit)(const char *name, const char *value, void *udata), void *udata) {
    if (!term) return;
    for (size_t i = 0; i < lookup_f_count; i++) {
        if (strcasestr(lookup_f_table[i].name, term))
            emit(lookup_f_table[i].name, lookup_f_table[i].value, udata);
    }
}

void r_lookup_f_multi(const char *term, void (*emit)(const char *name, const char *value, void *udata), void *udata) {
    if (!term) return;
    for (size_t i = 0; i < lookup_f_count; i++) {
        if (strcasestr(lookup_f_table[i].value, term))
            emit(lookup_f_table[i].name, lookup_f_table[i].value, udata);
    }
}
