#include <string.h>
#include "../common/common.h"
#include "lookup.h"

const LookupName lookup_t_table[] = {
    { "tacscan", "텍/스캔" },
    { "tactcan2", "택티션 (세트2)" },
    { "tactcian", "택티션 (세트1)" },
    { "tactcian2", "택티션 (세트2)" },
    { "tagteam", "태그 팀 레슬링" },
    { "tahjong", "타작 야키토리" },
    { "taiko10", "태고의 달인 10" },
    { "taiko2", "태고의 달인 2" },
    { "taiko3", "태고의 달인 3" },
    { "taiko4", "태고의 달인 4" },
    { "taiko5", "태고의 달인 5" },
    { "taiko6", "태고의 달인 6" },
    { "taiko9", "태고의 달인 9" },
    { "tail2nos", "테일 투 노즈-그레이트 챔피언십/ 슈퍼 포뮬러" },
    { "tail2nosa", "테일 투 노즈-그레이트 챔피언십" },
    { "tailg", "테일건너" },
    { "taiwanmb", "타이완 마작" },
    { "takeoff", "테이크 오프" },
    { "takoron", "노콘 퍼즐 타쿠론 (일본판)(GDL-0042)" },
    { "talbot", "탤벗" },
    { "tangramq", "탱그램 Q" },
    { "tangtang", "탕 탕" },
    { "tank8", "탱크 8" },
    { "tank8a", "탱크 8 (세트2)" },
    { "tank8b", "탱크 8 (세트3)" },
    { "tank8c", "탱크 8 (세트4)" },
    { "tank8d", "탱크 8 (세트5)" },
    { "tankbatl", "탱크 배틀" },
    { "tankbatt", "탱크 바탈리온" },
    { "tankbattb", "탱크 바탈리온 (해적판)" },
    { "tankbust", "탱크 버스터즈" },
    { "tankfrce", "탱크 포스 (미국판,2인용)" },
    { "tankfrce4", "탱크 포스 (미국판,4인)" },
    { "tankfrcej", "탱크 포스 (일본판)" },
    { "tankfrcj", "탱크 포스 (일본판)" },
    { "tantr", "퍼즐 앤 액션 - 탄트-R (일본판)" },
    { "tantrbl", "퍼즐 앤 액션 - 탄트-R (일본판)(해적판 세트1)" },
    { "tantrbl2", "퍼즐 앤 액션 - 탄트-R (일본판)(해적판 세트2)" },
    { "tantrbl3", "퍼즐 앤 액션 - 탄트-R (일본판)(해적판 세트3)" },
    { "tantrbl4", "퍼즐 앤 액션 - 탄트-R (일본판)(해적판 세트4)" },
    { "tantrkor", "퍼즐 앤 액션 - 탄트-R (한국판)" },
    { "taotaida", "타오 체도 (세트2)" },
    { "taotaido", "타오 체도 (2 버튼 버전)" },
    { "taotaido3", "타오 체도 (2/3 버튼 버전)" },
    { "taotaidoa", "타오 체도 (6 버튼 버전)" },
    { "tapatune", "탭 어 튠" },
    { "tapper", "탭퍼 (버드와이저)" },
    { "tappera", "탭퍼" },
    { "tapperb", "탭퍼 (버드와이저)" },
    { "tapperg", "탭퍼 (버드와이저-대체 그래픽)" },
    { "targ", "타르그" },
    { "targc", "타르그 (칵테일)" },
    { "targeth", "타겟 히트 (버전1.1)" },
    { "targeth10", "타겟 히트 (버전1.0)" },
    { "targetha", "타겟 히트" },
    { "tarzan", "태산틈천관" },
    { "tarzan103m", "태산틈천관 (V103M)" },
    { "tarzan202fa", "태산틈천관 (V202FA)" },
    { "tarzana", "태산틈천관 (V107)" },
    { "tarzanb", "태산틈천관" },
    { "tarzanc", "태산틈천관" },
    { "tatacot", "타타코트" },
    { "tatsujn2", "트럭스턴 2/ 타수진 2/ 타수진왕" },
    { "tattack", "타임 어택커" },
    { "tattass", "타투 어쌔신즈 (미국판 시제품)" },
    { "tattassa", "타투 어쌔신즈 (아시아판 시험판)" },
    { "taxidriv", "택시 드라이버" },
    { "taxidrvr", "택시 드라이버" },
    { "tazmani2", "태즈매니아 (세트2)" },
    { "tazmani3", "태즈매니아 (아르픽/롬다 해적판)" },
    { "tazmania", "태즈매니아 (세트1)" },
    { "tazmaniet", "태즈매니아 - 엘 트롬파" },
    { "tazzmang", "태즈매니아" },
    { "tazzmang2", "태즈매니아" },
    { "tbeastw2", "트랜스포머 비스트 워즈 II" },
    { "tblkkuzu", "블록 깨기" },
    { "tbonusal", "트레져 보너스" },
    { "tbowl", "테크모 보울 (세계판,세트1)" },
    { "tbowla", "테크모 보울 (세계판,세트2)" },
    { "tbowlj", "테크모 보울 (일본판)" },
    { "tbowlp", "테크모 보울 (세계판,시험판)" },
    { "tbyahhoo", "트윈비 야호!" },
    { "tceptor", "썬더 셉터" },
    { "tceptor2", "썬더 셉터 2" },
    { "tcl", "타이완 체스 레전드" },
    { "tcobra2", "트윈 코브라 2 (버전2.1O)" },
    { "tcobra2u", "트윈 코브라 2 (버전2.1A)" },
    { "tdfever", "터치다운 피버" },
    { "tdfever2", "터치다운 피버 2" },
    { "tdfever2b", "터치다운 피버 2" },
    { "tdfeverj", "터치다운 피버 (일본판)" },
    { "tdoboon", "대포로 도봉" },
    { "tdpgal", "트리플 드로우 포커" },
    { "tdragon", "썬더 드래곤 (비보호됨)" },
    { "tdragon1", "썬더 드래곤" },
    { "tdragon2", "썬더 드래곤 2" },
    { "tdragon2a", "썬더 드래곤 2" },
    { "tdragon3h", "썬더 드래곤 3 (뇌룡 2 해적판)" },
    { "tdragonb", "썬더 드래곤" },
    { "tdragonb3", "썬더 드래곤 (해적판,비보호됨)" },
    { "tduno", "터치 데 우노!/ 우노 노력 체크 머신 (일본판)" },
    { "tduno2", "터치 데 우노! 2 (일본판)" },
    { "te0144", "퍼즐 보블/ 버스트 어 무브" },
    { "teamht", "팀 해트 트릭" },
    { "teamqb", "존 얼웨이의 팀 쿼터백" },
    { "teamqb2", "존 얼웨이의 팀 쿼터백 (세트2)" },
    { "techbowl", "테크니컬 볼링" },
    { "technodr", "테크로 드라이브" },
    { "techromn", "초강전기 키카이오/ 테크 로맨서" },
    { "techromna", "초강전기 키카이오/ 테크 로맨서 (아시아판)" },
    { "techromnu", "초강전기 키카이오/ 테크 로맨서 (미국판)" },
    { "techromu", "초강전기 키카이오/ 테크 로맨서 (미국판)" },
    { "tecmowcm", "테크모 월드컵 밀레니엄" },
    { "teddybb", "테디보이 블루스 (신버전)" },
    { "teddybbo", "테디보이 블루스 (구버전)" },
    { "teddybboa", "테디보이 블루스 (구버전,해적판)" },
    { "teddybbobl", "테디보이 블루스" },
    { "teedoff", "티드 오프" },
    { "teedoffj", "티드 오프 (일본판)" },
    { "teetert", "티터 토쳐" },
    { "tehkanwc", "테칸 월드컵" },
    { "tehkanwcb", "테칸 월드컵 (세트2,해적판?)" },
    { "tehkanwcc", "테칸 월드컵 (세트3,해적판)" },
    { "tehkanwcd", "테칸 월드컵 (세트4,해적판)" },
    { "tehkanwch", "테칸 월드컵 (1986년 핵)" },
    { "tekipaki", "테키 파키" },
    { "tekipakit", "테키 파키 (로케 테스트)" },
    { "tekken", "철권" },
    { "tekken2", "철권 2 버전B" },
    { "tekken2a", "철권 2 (세계판,TES2/버전A)" },
    { "tekken2b", "철권 2 버전B (세계판,TES2/버전B)" },
    { "tekken2jb", "철권 2 버전B (일본판,TES1/버전B)" },
    { "tekken2jc", "철권 2 버전B (일본판,TES1/버전C)" },
    { "tekken2ua", "철권 2 (미국판,TES3/버전A)" },
    { "tekken2ub", "철권 2 버전B (미국판,TES3/버전B)" },
    { "tekken2ud", "철권 2 버전B (미국판,TES3/버전D)" },
    { "tekken3", "철권 3" },
    { "tekken3a", "철권 3 (세계판,TET2/버전B)" },
    { "tekken3b", "철권 3 (세계판,TET2/버전C)" },
    { "tekken3c", "철권 3 (세계판,TES2/버전C)" },
    { "tekken3d", "철권 3 (세계판,TET2/버전D)" },
    { "tekken3ja", "철권 (일본판,TET1/버전A)" },
    { "tekken3je1", "철권 (일본판,TET1/버전E1)" },
    { "tekken3ua", "철권 (미국판,TET3/버전A)" },
    { "tekken3ud", "철권 (미국판,TET3/버전D)" },
    { "tekken4", "철권 4" },
    { "tekken4a", "철권 4 (TEF2 v.A)" },
    { "tekken4b", "철권 4 (TEF1 v.A)" },
    { "tekken51", "철권 5.1" },
    { "tekkena", "철권 (TE2/버전B)" },
    { "tekkenac", "철권 (아시아판,TE4/버전C)" },
    { "tekkenb", "철권 (세계판,TE2/버전B)" },
    { "tekkenbs", "철권 배틀 스크래치" },
    { "tekkenc", "철권 (일본판,TE1/버전B)" },
    { "tekkencw", "철권 카드 월드" },
    { "tekkenjb", "철권 (일본판,TE1/버전B)" },
    { "tekkentt", "철권 태그 토너먼트" },
    { "tektagt", "철권 태그 토너먼트" },
    { "tektagta", "철권 태그 토너먼트 (TEG3/버전B)" },
    { "tektagtb", "철권 태그 토너먼트 (일본판,TEG1/v.B)" },
    { "tektagtc", "철권 태그 토너먼트 (일본판,TEG1/v.A3)" },
    { "tektagtc1a", "철권 태그 토너먼트" },
    { "tektagtjc1", "철권 태그 토너먼트" },
    { "tektagtub", "철권 태그 토너먼트" },
    { "tektagtuc1", "철권 태그 토너먼트" },
    { "teljan", "텔 쟝" },
    { "telmahjn", "텔레폰 마작" },
    { "telpacfl", "텔레파치 피버 라이온" },
    { "tempall", "템페스트 올 레벨즈" },
    { "temped", "템페스트/ TempEd" },
    { "tempest", "템페스트 (개정판3,리바이스드 하드웨어)" },
    { "tempest1", "템페스트 (개정판1)" },
    { "tempest1r", "템페스트 (개정판1,개정 하드웨어)" },
    { "tempest2", "템페스트 (개정판2)" },
    { "tempest3", "템페스트 (개정판3)" },
    { "temptube", "템페스트 튜브" },
    { "temptwst", "템페스트 트위스티드" },
    { "tenballs", "텐 볼즈 (버전1.05)" },
    { "tengai", "전국 블레이드-전국 에이스 2/ 텐가이 (세계판)" },
    { "tengaij", "전국 블레이드-전국 에이스 2/ 텐가이 (일본판)" },
    { "tengaik", "전국 블레이드-전국 에이스 2/ 텐가이 (한글)" },
    { "tenkai", "마작 전개원" },
    { "tenkai2b", "마작 전개원 2" },
    { "tenkaibb", "마작 전개원 (해적판 b)" },
    { "tenkaicb", "마작 전개원 (해적판 c)" },
    { "tenkaid", "마작 전개원 (세트1)" },
    { "tenkaie", "마작 전개원 (세트2)" },
    { "tenkomoj", "텐코모리 슈팅 (TKM1/버전A1)" },
    { "tenkomor", "텐코모리 슈팅" },
    { "tenkomorj", "텐코모리 슈팅 (일본판,TKM1/v.A1)" },
    { "tenkomorja1", "텐코모리 슈팅 (일본판)" },
    { "tenpindx", "텐 핀 딜럭스" },
    { "tenspot", "텐 스포츠" },
    { "tenthdeg", "텐스 디그리" },
    { "tenup", "텐 업" },
    { "tenup3", "텐 업 (요약 3)" },
    { "teot", "극초호권 (HB,베타7)" },
    { "teplus2j", "테트리스 플러스 2 (일본판)" },
    { "terabrst", "테라버스트" },
    { "terabrsta", "테라버스트 (버전HEL)" },
    { "terabrstj", "테라버스트 (버전JEL)" },
    { "term2", "터미네이터 2 - 심판의 날 (개정판LA4)" },
    { "term2la1", "터미네이터 2 - 심판의 날 (개정판LA1)" },
    { "term2la2", "터미네이터 2 - 심판의 날 (개정판LA2)" },
    { "term2la3", "터미네이터 2 - 심판의 날 (개정판LA3)" },
    { "term2lg1", "터미네이터 2 - 심판의 날 (독일판,개정판LG1)" },
    { "term2pa2", "터미네이터 2 - 심판의 날 (시험판,개정판PA2)" },
    { "terracra", "테라 크레스타/ 독수리 오형제 (YM2203)" },
    { "terracrb", "테라 크레스타/ 독수리 오형제 (YM3526 세트2)" },
    { "terracre", "테라 크레스타/ 독수리 오형제 (YM3526 세트1)" },
    { "terracrea", "테라 크레스타/ 독수리 오형제 (YM3526 세트3)" },
    { "terracren", "테라 크레스타/ 독수리 오형제 (YM2203)" },
    { "terracreo", "테라 크레스타/ 독수리 오형제 (YM3526 세트2)" },
    { "terraf", "테라 포스" },
    { "terrafa", "테라 포스 (세트2)" },
    { "terrafb", "테라 포스 (일본판,해적판 세트2)" },
    { "terrafj", "테라 포스 (일본판)" },
    { "terrafjb", "테라 포스 (일본판,해적판)" },
    { "terrafu", "테라 포스 (미국판)" },
    { "terrafua", "테라 포스 (미국판,대체사운드)" },
    { "test240p", "240p 테스트 스위트" },
    { "tetfight", "테트리스 파이터즈" },
    { "tetkiwam", "테트리스 극도 (일본판)(GDL-0020)" },
    { "tetrbx", "테트리스/ 블럭시드" },
    { "tetris", "테트리스 (세트4,일본판,시스템16A)" },
    { "tetris1", "테트리스 (세트1,일본판,시스템16B)" },
    { "tetris1d", "테트리스 (세트1,일본판,시스템16B,암호해제)" },
    { "tetris2", "테트리스 (세트2,일본판,시스템16B)" },
    { "tetris2d", "테트리스 (세트2,일본판,시스템16B,암호해제)" },
    { "tetris3", "테트리스 (세트3,일본판,시스템16A)" },
    { "tetris3d", "테트리스 (세트3,일본판,시스템16A,암호해제)" },
    { "tetrisa", "테트리스 (세가 세트2)" },
    { "tetrisbl", "테트리스" },
    { "tetrisd", "테트리스 (세트4,일본판,시스템16A,암호해제)" },
    { "tetriskr", "테트리스" },
    { "tetrisp", "테트리스 플러스 (버전1.0)" },
    { "tetrisp2", "테트리스 플러스 2" },
    { "tetrisp2a", "테트리스 플러스 2" },
    { "tetrisp2j", "테트리스 플러스 2 (일본판,V2.2)" },
    { "tetrisp2ja", "테트리스 플러스 2 (일본판,v2.1)" },
    { "tetrisse", "테트리스 (일본판,E-시스템)" },
    { "tetrist", "테트리스 (일본판,B-시스템,YM2610)" },
    { "tetrista", "테트리스 (일본판,B-시스템,YM2203)" },
    { "tetristh", "테트리스 (일본판,타이토 H-시스템)" },
    { "tetrsark", "테트리스" },
    { "tetrsark2", "테트리스" },
    { "tfrceac", "썬더포스 AC" },
    { "tfrceacb", "썬더포스 AC" },
    { "tfrceacj", "썬더포스 AC (일본판)" },
    { "tfrceacjpb", "썬더포스 AC (일본판,시험판,해적판)" },
    { "tgm2", "테트리스 더 앱솔룻 그랜드 마스터 2" },
    { "tgm2p", "테트리스 더 앱솔룻 그랜드 마스터 2 플러스" },
    { "tgmj", "테트리스 그랜드 마스터" },
    { "tgtbal96", "타겟 볼 96" },
    { "tgtball", "타겟 볼" },
    { "tgtballa", "타겟 볼" },
    { "tgtballn", "타겟 볼 (누드)" },
    { "tgtpanic", "타겟 패닉" },
    { "tharierj", "태스크 포스 해리어 (일본판)" },
    { "tharrier", "태스크 포스 해리어" },
    { "tharrierb", "태스크 포스 해리어 (레터링 해적판)" },
    { "tharrierj", "태스크 포스 해리어 (일본판)" },
    { "tharrieru", "태스크 포스 해리어 (미국판)" },
    { "thayers", "테이어의 퀘스트" },
    { "thayersa", "테이어의 퀘스트 (세트2)" },
    { "the26thz", "26번째 Z" },
    { "theboat", "더 보트" },
    { "thedealr", "더 딜러" },
    { "thedeep", "더 딥 (일본판)" },
    { "theend", "디 엔드" },
    { "theends", "디 엔드 (스턴)" },
    { "theendss", "디 엔드 (세가/ 소닉)" },
    { "theglad", "신검의 풍운/ 글라디에이터 (V101)" },
    { "theglad100", "신검의 풍운/ 글라디에이터 (V100,대만판)" },
    { "theglad101", "신검의 풍운/ 글라디에이터 (V100)" },
    { "theglad104", "신검의 풍운/ 글라디에이터 (V104)" },
    { "theglada", "글라디에이터 (버전101)" },
    { "thegladpcb", "신검의 풍운/ 글라디에이터" },
    { "thegladpcba", "신검의 풍운/ 글라디에이터 (V100,일본판,싱글 PCB 버전)" },
    { "theglob", "글로브" },
    { "theglob2", "글로브 (초기판)" },
    { "theglob3", "글로브 (세트3)" },
    { "theglobme", "글로브 (팩맨 하드웨어)" },
    { "theglobp", "글로브 (팩맨 하드웨어)" },
    { "theglobpa", "글로브 (팩맨 하드웨어,세트2)" },
    { "theglobpb", "글로브 (팩맨 하드웨어,해적판)" },
    { "thegrid", "그리드" },
    { "thegrida", "그리드 (버전1.1)" },
    { "thehand", "핸드" },
    { "thehole", "홀" },
    { "thehustj", "허슬러 (일본판 버전J)" },
    { "thehustl", "허슬러 (일본판,프로그램 코드 M)" },
    { "thehustlj", "허슬러 (일본판,프로그램 코드 J)" },
    { "themj", "마작" },
    { "themj2", "마작 (일본판,세트2)" },
    { "thepit", "피트" },
    { "thepitb", "피트" },
    { "thepitc", "피트 (센추리)" },
    { "thepitj", "피트 (일본판)" },
    { "thepitm", "피트" },
    { "thepitu1", "피트 (미국판 세트1)" },
    { "thepitu2", "피트 (미국판 세트2)" },
    { "thepitu3", "피트 (미국판 세트3)" },
    { "theportr", "포터 (포트맨 해적판)" },
    { "theroes", "벽력영웅/ 썬더 히어로즈" },
    { "theroesa", "벽력영웅/ 썬더 히어로즈 (세트2)" },
    { "thetogyu", "불파이트/ 투우 (일본판)" },
    { "thief", "씨프" },
    { "thndblst", "리썰 썬더/ 썬더 블래스터 (일본판)" },
    { "thnderxa", "썬더 크로스 (세트2)" },
    { "thnderxb", "썬더 크로스 (세트3)" },
    { "thnderxj", "썬더 크로스 (일본판)" },
    { "thndfoxj", "썬더 폭스 (일본판)" },
    { "thndfoxu", "썬더 폭스 (미국판)" },
    { "thndrbd1", "썬더 블레이드 (디럭스 입석,비보호)" },
    { "thndrbdj", "썬더 블레이드 (일본판)" },
    { "thndrbld", "썬더 블레이드 (수직형)" },
    { "thndrbld1", "썬더 블레이드 (디럭스 입석,비보호)" },
    { "thndrbldd", "썬더 블레이드 (업라이트,암호해제)" },
    { "thndrx2", "썬더 크로스 2 (세계판)" },
    { "thndrx2a", "썬더 크로스 2 (아시아판)" },
    { "thndrx2j", "썬더 크로스 2 (일본판)" },
    { "thndzone", "썬더 존 (세계판,개정판1)" },
    { "thndzone4", "썬더 존 (세계판 4인용)" },
    { "thndzonea", "썬더 존 (세계판)" },
    { "thndzonej", "썬더 존 (일본판)" },
    { "thoop", "썬더 후프 (버전1)" },
    { "thoop2", "TH 스트라이크 백" },
    { "thoop2a", "TH 스트라이크 백" },
    { "threeds", "쓰리 Ds - 쓰리 딜러스 카지노 하우스" },
    { "threedsa", "쓰리 Ds - 쓰리 딜러스 카지노 하우스 (세트2)" },
    { "thrild2", "스릴 드라이브 2" },
    { "thrild2a", "스릴 드라이브 2 (버전AAA)" },
    { "thrild2c", "스릴 드라이브 2 (버전EAA)" },
    { "thrilld", "스릴 드라이브" },
    { "thrillda", "스릴 드라이브" },
    { "thrilldab", "스릴 드라이브" },
    { "thrilldb", "스릴 드라이브 (JAB)" },
    { "thrilldba", "스릴 드라이브" },
    { "thrilldbab", "스릴 드라이브" },
    { "thrilldbe", "스릴 드라이브" },
    { "thrilldbj", "스릴 드라이브" },
    { "thrilldbja", "스릴 드라이브" },
    { "thrillde", "스릴 드라이브" },
    { "thrilldgej", "스릴 드라이브" },
    { "thrilldgeu", "스릴 드라이브" },
    { "thrilldgke", "스릴 드라이브" },
    { "thrilldgkee", "스릴 드라이브" },
    { "thrilldgkk", "스릴 드라이브" },
    { "thrilldgmj", "스릴 드라이브" },
    { "thrilldgnj", "스릴 드라이브" },
    { "thrilldgpj", "스릴 드라이브" },
    { "thrilldj", "스릴 드라이브" },
    { "thrilldja", "스릴 드라이브" },
    { "thunderh", "오퍼레이션 썬더 허리케인" },
    { "thunderhu", "오퍼레이션 썬더 허리케인 (버전UAA)" },
    { "thunderj", "썬더죠스 (개정판3)" },
    { "thunderja", "썬더죠스 (개정판2)" },
    { "thunderl", "썬더 & 라이트닝" },
    { "thunderla", "썬더 & 라이트닝 (세트2)" },
    { "thunderlbl", "썬더 & 라이트닝 (해적판 테트리스 사운드.세트1)" },
    { "thunderlbl2", "썬더 & 라이트닝 (해적판 테트리스 사운드.세트2)" },
    { "thunderx", "썬더 크로스 (세트1)" },
    { "thunderxa", "썬더 크로스 (세트2)" },
    { "thunderxb", "썬더 크로스 (세트3)" },
    { "thunderxj", "썬더 크로스 (일본판)" },
    { "thundfox", "썬더 폭스 (세계판)" },
    { "thundfoxj", "썬더 폭스 (일본판)" },
    { "thundfoxu", "썬더 폭스 (미국판)" },
    { "thunt", "퍼즐 앤 액션 - 트레져 헌트 (V2.00E)" },
    { "thuntk", "퍼즐 앤 액션 - 보물을 찾아라 (V2.00K)" },
    { "tickee", "티키 티캐츠" },
    { "tictac", "틱 택 트리비아" },
    { "tictaca", "틱 택 트리비아" },
    { "tictacv", "틱 택 트리비아" },
    { "tigerh", "타이거 헬리 (미국판)" },
    { "tigerh2", "타이거 헬리 (일본판 세트1)" },
    { "tigerhb1", "타이거 헬리 (해적판 세트1)" },
    { "tigerhb2", "타이거 헬리 (해적판 세트2)" },
    { "tigerhb3", "타이거 헬리 (해적판 세트3)" },
    { "tigerhj", "타이거 헬리 (일본판)" },
    { "tigeroad", "타이거 로드 (미국판)" },
    { "tigeroadb", "타이거 로드 (미국판 해적판,세트1)" },
    { "tigeroadb2", "타이거 로드 (미국판 해적판,세트2)" },
    { "tigeroadu", "타이거 로드 (미국판,롬스타 라이센스)" },
    { "tigerodb", "타이거 로드 (미국판 해적판)" },
    { "tighook", "타이거 후크" },
    { "tighookc1", "타이거 후크 (버전2.1R,세트1)" },
    { "tighookc2", "타이거 후크 (버전2.0LT,세트1)" },
    { "tighookd1", "타이거 후크 (버전2.1R,세트2)" },
    { "tighookd2", "타이거 후크 (버전2.0LT,세트2)" },
    { "tighooko", "타이거 후크 (버전1.7XT)" },
    { "tighooko2", "타이거 후크 (버전1.7)" },
    { "tighookv1", "타이거 후크 (버전2.1R 듀얼)" },
    { "tighookv2", "타이거 후크 (버전2.0LT 듀얼)" },
    { "timber", "팀버" },
    { "timecris", "타임 크라이시스" },
    { "timecrisa", "타임 크라이시스 (개정판TS2 버전A)" },
    { "timecrs2", "타임 크라이시스 2" },
    { "timecrs2b", "타임 크라이시스 2" },
    { "timecrs2c", "타임 크라이시스 2" },
    { "timecrs2v1b", "타임 크라이시스 2" },
    { "timecrs2v2b", "타임 크라이시스 2" },
    { "timecrs2v4a", "타임 크라이시스 2" },
    { "timecrs2v5a", "타임 크라이시스 2" },
    { "timecrs3", "타임 크라이시스 3" },
    { "timecrsa", "타임 크라이시스 (개정판TS2 버전A)" },
    { "timefgtr", "타임 파이터 (갤럭시안 하드웨어의 타임 파일럿 변환)" },
    { "timek131", "타임 킬러즈 (v1.31)" },
    { "timekill", "타임 킬러즈 (v1.32)" },
    { "timekill100", "타임 킬러즈 (v1.00)" },
    { "timekill120", "타임 킬러즈 (v1.20)" },
    { "timekill121", "타임 킬러즈 (v1.21)" },
    { "timekill121a", "타임 킬러즈 (v1.21,대체 롬보드)" },
    { "timekill131", "타임 킬러즈 (v1.31)" },
    { "timekill132i", "타임 킬러즈 (v1.32I)" },
    { "timelimt", "타임 리미트" },
    { "timemchn", "타임 머신" },
    { "timeplt", "타임 파일럿" },
    { "timeplta", "타임 파일럿 (아타리)" },
    { "timepltc", "타임 파일럿 (센추리)" },
    { "timesca1", "타임 스캐너 (세트1,시스템16A)" },
    { "timescan", "타임 스캐너 (세트2,시스템16B)" },
    { "timescan1", "타임 스캐너 (세트1,시스템16A)" },
    { "timescan3", "타임 스캐너 (세트3,일본판,시스템16B)" },
    { "timesol1", "타임 솔져 (미국판 개정판1)" },
    { "timesold", "타임 솔져 (미국판 개정판3)" },
    { "timesold1", "타임 솔져 (미국판 개정판1)" },
    { "timesup", "타임 업 (HB)" },
    { "timesupd", "타임 업 (HB,데모)" },
    { "timetrv", "타임 트레블러" },
    { "timetrv2", "타임 트레블러 (일본판)" },
    { "timetunl", "타임 터널" },
    { "timscanr", "타임 스캐너" },
    { "tinklpit", "틴클 핏 (일본판)" },
    { "tinstar", "틴 스타 (A10,4 PCB 버전)" },
    { "tinstar2", "틴 스타 (세트2)" },
    { "tinstara", "틴 스타" },
    { "tinv2650", "인베이더스" },
    { "tiptop", "팁 탑" },
    { "tisland", "보물섬" },
    { "tisub", "보물섬" },
    { "tisuba", "보물섬 (세트2)" },
    { "titanpac", "타이탄 (팩맨 해킹)" },
    { "titlef", "타이틀 파이트 (세계판)" },
    { "titlefj", "타이틀 파이트 (일본판)" },
    { "titlefu", "타이틀 파이트 (미국판)" },
    { "tjsb", "마작 천강신병" },
    { "tjumpman", "뛰어라! 점프맨" },
    { "tkdensha", "투희전승 - 엔젤 아이즈" },
    { "tkdensho", "투희전승 - 엔젤 아이즈" },
    { "tkdenshoa", "투희전승 - 엔젤 아이즈" },
    { "tkmmpzdm", "두근두근 메모리얼 대전 퍼즐" },
    { "tknight", "와일드 팡/ 테크모 나이트" },
    { "tkoboxng", "TKO 복싱" },
    { "tm", "터치마스터" },
    { "tm2k", "터치마스터 2000" },
    { "tm2ka", "터치마스터 2000 (v4.00 표준)" },
    { "tm2kb", "터치마스터 2000 (v4.00 표준)" },
    { "tm2kspeval", "터치마스터 2000 (v4.XX3 스페인 평가)" },
    { "tm3k", "터치마스터 3000" },
    { "tm3ka", "터치마스터 3000 (v5.01 표준)" },
    { "tm3keval", "터치마스터 3000" },
    { "tm3ksp", "터치마스터 3000" },
    { "tm4k", "터치마스터 4000" },
    { "tm4ka", "터치마스터 4000 (v6.02 표준)" },
    { "tm4kb", "터치마스터 4000" },
    { "tm4kca", "터치마스터 4000" },
    { "tm4kmn", "터치마스터 4000" },
    { "tm4knj", "터치마스터 4000" },
    { "tm4kuk", "터치마스터 4000" },
    { "tm5k", "터치마스터 5000" },
    { "tm5ka", "터치마스터 5000 (v7.01 표준)" },
    { "tm5kca", "터치마스터 5000 (v7.10 캘리포니아)" },
    { "tm5kmn", "터치마스터 5000" },
    { "tm5kuk", "터치마스터 5000" },
    { "tm7k", "터치마스터 7000" },
    { "tm7ka", "터치마스터 7000 (v8.00 표준)" },
    { "tm7kde", "터치마스터 7000" },
    { "tm7keval", "터치마스터 7000 (v8.1X 에볼루션)" },
    { "tm7kmn", "터치마스터 7000" },
    { "tm7kmna", "터치마스터 7000" },
    { "tm7knj", "터치마스터 7000" },
    { "tm8k", "터치마스터 8000" },
    { "tm8k902", "터치마스터 8000 (v9.02 표준)" },
    { "tmdo", "터치마스터 (v2.2-01 표준)" },
    { "tmek", "티 멕" },
    { "tmek20", "티 멕 (v2.0,시험판)" },
    { "tmek44", "티 멕 (v4.4)" },
    { "tmek45", "티 멕 (v4.5)" },
    { "tmek51p", "티 멕 (v5.1,시험판)" },
    { "tmekprot", "티 멕 (시험판)" },
    { "tmht", "돌연변이 닌자거북이 (영국판 4인,버전F)" },
    { "tmht22pe", "돌연변이 닌자거북이-시간 속의 거북이 (2인용 EBA)" },
    { "tmht24pe", "돌연변이 닌자거북이-시간 속의 거북이 (4인용 EAA)" },
    { "tmht2p", "돌연변이 닌자거북이 (영국판 2인,버전U)" },
    { "tmht2pa", "돌연변이 닌자거북이 (영국판 2인,버전?)" },
    { "tmhta", "돌연변이 닌자거북이 (영국판 4인,버전S)" },
    { "tmhtb", "돌연변이 닌자거북이 (영국판 4인,버전?)" },
    { "tmmjprd", "두근두근 마작 파라다이스 - 디어 마이 러브" },
    { "tmnt", "돌연변이 닌자거북이 (세계판 4인용,버전X)" },
    { "tmnt2", "돌연변이 닌자거북이-시간 속의 거북이 (4인용 버전UAA)" },
    { "tmnt22p", "돌연변이 닌자거북이-시간 속의 거북이 (2인용 UDA)" },
    { "tmnt22pu", "돌연변이 닌자거북이-시간 속의 거북이 (2인용 UDA)" },
    { "tmnt24pu", "돌연변이 닌자거북이-시간 속의 거북이" },
    { "tmnt2a", "돌연변이 닌자거북이-시간 속의 거북이 (4인용 ADA)" },
    { "tmnt2o", "돌연변이 닌자거북이-시간 속의 거북이 (4인용 OAA)" },
    { "tmnt2pj", "돌연변이 닌자거북이 (일본판 2인,버전1)" },
    { "tmnt2po", "돌연변이 닌자거북이 (오세아이나 2인,버전)" },
    { "tmnta", "돌연변이 닌자거북이 (아시아판 4인,버전?)" },
    { "tmnti", "돌연변이 닌자거북이" },
    { "tmntia", "돌연변이 닌자거북이 (데모,대체)" },
    { "tmntj", "돌연변이 닌자거북이 (일본판 4인,버전2)" },
    { "tmntmwb", "돌연변이 닌자거북이 - 뮤턴트 워리어즈 (SNES 해적판)" },
    { "tmntu", "돌연변이 닌자거북이 (미국판 4인,버전R)" },
    { "tmntua", "돌연변이 닌자거북이" },
    { "tmntub", "돌연변이 닌자거북이 (미국판 4인,버전J)" },
    { "tmntuc", "돌연변이 닌자거북이 (미국판 4인용,버전H)" },
    { "tmntucbl", "돌연변이 닌자거북이 (해적판,미국판 4인용,버전H)" },
    { "tmosh", "두근두근 메모리얼 알려줘 너의 마음" },
    { "tmoshs", "두근두근 메모리얼 알려줘 너의 마음 실 버전" },
    { "tmoshsp", "두근두근 메모리얼 알려줘 너의 마음 실 버전 플러스" },
    { "tmoshspa", "두근두근 메모리얼 알려줘 너의 마음 실 버전 플러스" },
    { "tmpdoki", "두근두근 마작 파라다이스 - 두근두근 편" },
    { "tndrcade", "특수부대 U.A.G./ 썬더케이드/ 트윈 포메이션" },
    { "tndrcadej", "특수부대 U.A.G. (일본판)" },
    { "tndrcadj", "특수부대 U.A.G. (일본판)" },
    { "tnexspce", "넥스트 스페이스" },
    { "tnextspc", "넥스트 스페이스 (세트1)" },
    { "tnextspc2", "넥스트 스페이스 (세트2)" },
    { "tnextspcj", "넥스트 스페이스 (일본판)" },
    { "tnk3", "T.N.K. 3 (미국판)" },
    { "tnk3b", "T.A.N.K." },
    { "tnk3j", "T.A.N.K. (일본판)" },
    { "tnzs", "뉴질랜드 스토리 (세계판,신형)" },
    { "tnzs2", "뉴질랜드 스토리 2 (세계판)" },
    { "tnzsb", "뉴질랜드 스토리 (세계판,해적판)" },
    { "tnzsj", "뉴질랜드 스토리 (일본판,신버전,신형 PCB)" },
    { "tnzsjo", "뉴질랜드 스토리 (일본판,구버전)(구형 PCB)" },
    { "tnzso", "뉴질랜드 스토리 (세계판,구버전)(구형 PCB)" },
    { "tnzsoa", "뉴질랜드 스토리 (세계판,미확인 버전)(구형 PCB)" },
    { "tnzsop", "뉴질랜드 스토리 (세계판,시험판)(구형 PCB)" },
    { "tnzsuo", "뉴질랜드 스토리 (미국판,구버전)(구형 PCB)" },
    { "todruaga", "드루아가의 탑 (신버전)" },
    { "todruagao", "드루아가의 탑 (구버전)" },
    { "todruagas", "드루아가의 탑 (시담)" },
    { "todruagb", "드루아가의 탑 (세트2)" },
    { "todruago", "드루아가의 탑 (구버전)" },
    { "toffy", "토피" },
    { "togenkyo", "도원향" },
    { "toggle", "토글" },
    { "toki", "주주전설/ 토키 (세계판,세트1)" },
    { "toki2", "주주전설/ 토키 (세트2)" },
    { "toki3", "주주전설/ 토키 (세트3)" },
    { "tokia", "주주전설/ 토키 (세계판,세트2)" },
    { "tokib", "주주전설/ 토키" },
    { "tokibr", "주주전설/ 토키" },
    { "tokij", "주주 전설 (일본판)" },
    { "tokimbsj", "두근두근 미소녀 (일본판)" },
    { "tokimosh", "두근두군 메모리얼 알려줘 너의 하트" },
    { "tokimosp", "두근두군 메모리얼 알려줘 너의 하트 실 버전플러스" },
    { "tokims", "주주전설/ 토키 (모듈라 시스템)" },
    { "tokio", "토키오/ 스크램블 포메이션 (신형)" },
    { "tokiob", "토키오/ 스크램블 포메이션" },
    { "tokioo", "토키오/ 스크램블 포메이션 (구형)" },
    { "tokiou", "토키오/ 스크램블 포메이션 (미국판)" },
    { "tokip", "주주전설/ 토키 (미국판,시험판?)" },
    { "tokisens", "시간의 전사 - 크로노 솔져" },
    { "tokisensa", "시간의 전사 - 크로노 솔져 (시험판)" },
    { "tokiu", "주주전설/ 토키 (미국판,세트1)" },
    { "tokiua", "주주전설/ 토키 (미국판,세트2)" },
    { "tokkae", "대전 번갈아 구슬" },
    { "tokyobus", "도쿄 버스 가이드 (일본판,개정판A)" },
    { "tokyocop", "도쿄 캅" },
    { "tokyogal", "도쿄 걸 도감" },
    { "tokyowar", "도쿄 워즈" },
    { "tokyowarj", "도쿄 워즈 (일본판)" },
    { "tomagic", "톰톰 매직" },
    { "tomahaw5", "토마호크 777 (개정판5)" },
    { "tomahawk", "토마호크 777" },
    { "tomahawk1", "토마호크 777 (개정판1)" },
    { "tomcat", "톰캣" },
    { "tomcatsw", "톰캣 (시험판)" },
    { "tondemo", "돈데모 크라이시스" },
    { "tonton", "두근 두근 동물랜드 톤톤" },
    { "tontonb", "톤톤" },
    { "tonypok", "포커 마스터" },
    { "toobin", "투빈 (개정판3)" },
    { "toobin1", "투빈 (개정판1)" },
    { "toobin2", "투빈 (개정판2)" },
    { "toobin2e", "투빈 (유럽판,개정판2)" },
    { "toobine", "투빈 (유럽판,개정판3)" },
    { "toobing", "투빈 (독일판,개정판3)" },
    { "toobinp", "투빈 (시험판)" },
    { "topbladv", "탑 블레이드 V" },
    { "topdrive", "탑 드라이빙" },
    { "topgear", "탑 기어" },
    { "topgun", "탑 건" },
    { "topgunbl", "탑 거너 (해적판,로터리 조이스틱)" },
    { "topgunnr", "탑 거너" },
    { "topgunr", "탑 거너 (미국판,8방향 조이스틱)" },
    { "tophunta", "탑 헌터 - 로디 & 케시 (세트2)" },
    { "tophuntr", "탑 헌터 - 로디 & 케시" },
    { "tophuntrh", "탑 헌터 - 로디 & 케시 (NGH-046)" },
    { "tophuntrk", "탑 헌터 - 로디 & 케시 (한글)" },
    { "topland", "탑 랜딩" },
    { "toplandj", "탑 랜딩 (일본판)" },
    { "toppyrap", "토피 & 래피" },
    { "topracer", "탑 레이서" },
    { "topracera", "탑 레이서" },
    { "topracern", "탑 레이서" },
    { "topracra", "탑 레이서 (세트2)" },
    { "topracrb", "탑 레이서 (세트3)" },
    { "toprollr", "탑 롤러" },
    { "topsecex", "탑 시크릿" },
    { "topsecrt", "탑 시크릿" },
    { "topsecrt2", "탑 시크릿 (일본판,개정판B)" },
    { "topshoot", "탑 슈터" },
    { "topskatr", "탑 스케이터" },
    { "topskatru", "탑 스케이터 (미국판)" },
    { "topspedu", "탑 스피드 (미국판)" },
    { "topspeed", "탑 스피드 (세계판)" },
    { "topspeedu", "탑 스피드 (미국판)" },
    { "toramich", "타이거 로드/ 호랑이의 길 (일본판)" },
    { "toratora", "토라 토라" },
    { "toratorab", "토라 토라 (세트2)" },
    { "torid2gg", "토리데 2 아다우치 외전 (독일판)" },
    { "toride2g", "토리데 2 아다우치 외전" },
    { "toride2gg", "토리데 2 아다우치 외전 (독일판)" },
    { "toride2gk", "토리데 2 복수외전 아다우치 외전 (한국판)" },
    { "toride2j", "토리데 2 (일본판)" },
    { "toride2ji", "토리데 2 (일본판,개정판I)" },
    { "tornado1", "토네이도" },
    { "tornado2", "토네이도 (해적판 세트2)" },
    { "tornbase", "토네이도 베이스볼" },
    { "tortufam", "토투가 패밀리" },
    { "torus", "토루스" },
    { "toryumon", "등용문" },
    { "toryumondx", "등용문 DX" },
    { "totc", "케러비안의 보물" },
    { "totcarn", "토탈 카니지 (개정판LA1)" },
    { "totcarnp", "토탈 카니지 (시험판,개정판1.0)" },
    { "totcarnp1", "토탈 카니지 (시험판,v1.0)" },
    { "totcarnp2", "토탈 카니지 (시험판,v2.0)" },
    { "totd", "타이핑 오브 데드 (개정판A)" },
    { "totdo", "타이핑 오브 데드" },
    { "totlvice", "토탈 바이스" },
    { "totlvicj", "토탈 바이스 (버전JAD)" },
    { "totmejan", "도테모 이 종" },
    { "toto", "컴 백 토토" },
    { "toucheme", "터치 미" },
    { "touchemea", "터치 미 (세트2)" },
    { "touchgo", "터치 & 고 (세계판)" },
    { "touchgoe", "터치 & 고 (초기 개정판)" },
    { "touchgok", "터치 & 고 (한국판,비보호)" },
    { "touchgon", "터치 & 고 (북미 제외)" },
    { "toukon3", "신일본 프로레슬링 투혼 열전 3 아케이드 에디션" },
    { "toukon4", "신일본 프로레슬링 투혼열전 4 아케이드 에디션 (일본판)" },
    { "tour4000", "투어 4000" },
    { "tour4010", "투어 4010" },
    { "tourpgum", "불명의 볼링 테마 포커 게임" },
    { "toursol", "토너먼트 솔리테어" },
    { "toursol1", "토너먼트 솔리테어 (V1.04)" },
    { "tourtab2", "토너먼트 테이블 (세트2)" },
    { "tourtabl", "토너먼트 테이블" },
    { "touryuu", "등용문 (V11.1)?" },
    { "toutrun", "터보 아웃런 (아웃런 업그레이드)" },
    { "toutrun1", "터보 아웃런 (디럭스 콕핏)" },
    { "toutrun2", "터보 아웃런 (콕핏,미확인)" },
    { "toutrun2d", "터보 아웃런 (해적판)" },
    { "toutrun3", "터보 아웃런 (콕핏)" },
    { "toutrun3d", "터보 아웃런 (콕핏,암호해제)" },
    { "toutruna", "터보 아웃런 (세트2)" },
    { "toutrund", "터보 아웃런 (암호해제)" },
    { "toutrunj", "터보 아웃런 (일본판,아웃런 업그레이드)" },
    { "toutrunj1", "터보 아웃런 (일본판)" },
    { "toutrunj1d", "터보 아웃런 (일본판,암호해제)" },
    { "toutrunjd", "터보 아웃런 (일본판,암호해제)" },
    { "toutrunu", "터보 아웃런 (아웃런 업그레이드)" },
    { "toyfight", "토이 파이터" },
    { "toyland", "토이 랜드 어드벤쳐" },
    { "toypop", "토이팝" },
    { "tp2m32", "테트리스 플러스 2 (메가시스템32 버전)" },
    { "tp84", "타임 파일럿 84 (세트1)" },
    { "tp84a", "타임 파일럿 84 (세트2)" },
    { "tp84b", "타임 파일럿 84 (세트3)" },
    { "tpgolf", "탑 플레이어의 골프" },
    { "tpoker2", "터보 포커 2" },
    { "tqst", "트레져 퀘스트" },
    { "tqstp", "트레져 퀘스트 (시험판)" },
    { "trackflc", "트랙 앤 필드/ 하이퍼 올림픽 (센추리)" },
    { "trackfld", "트랙 앤 필드/ 하이퍼 올림픽" },
    { "trackfldc", "트랙 앤 필드/ 하이퍼 올림픽 (센추리)" },
    { "trackfldnz", "트랙 앤 필드/ 하이퍼 올림픽 (NZ 해적판)" },
    { "trackfldu", "트랙 앤 필드/ 하이퍼 올림픽 (센추리,비암호화)" },
    { "trailblz", "트레일 블레이저" },
    { "trally", "트래쉬 랠리" },
    { "tranqgun", "트랜퀄라이저 건" },
    { "transfrm", "트랜스포머" },
    { "travrusa", "트래버스 USA/ 지피 레이스" },
    { "travrusab", "트래버스 USA" },
    { "travrusab2", "트래버스 USA" },
    { "trckydca", "트리키 닥 (세트2)" },
    { "trckydoc", "트리키 닥 (세트1)" },
    { "trckydoca", "트리키 닥 (세트2)" },
    { "treacity", "트레져 시티" },
    { "treacity202", "트레져 시티 (V202)" },
    { "treahunt", "트레져 헌트" },
    { "treamary", "트레져 매리" },
    { "trebltop", "트레블 탑" },
    { "trgheart", "트리거 하트 엑셀리카 버전A (일본판)(GDL-0036A)" },
    { "trghearto", "트리거 하트 엑셀리카 (일본판)(GDL-0036)" },
    { "tricktrp", "트릭 트랩 (세계판?)" },
    { "trigon", "라이트닝 파이터즈/ 트라이곤 (일본판)" },
    { "trikitri", "트리키 트리키 (러버보이 해적판)" },
    { "triothej", "트리오 더 펀치 - 나를 잊지 마세요... (일본판)" },
    { "triothep", "트리오 더 펀치 - 나를 잊지 마세요... (세계판)" },
    { "triothepj", "트리오 더 펀치 - 나를 잊지 마세요... (일본판)" },
    { "tripdraw", "트리플 드로우" },
    { "tripfev", "트리플 피버" },
    { "tripfev105us", "트리플 피버 (V105)" },
    { "tripfev107us", "트리플 피버 (V107)" },
    { "triplep", "트리플 펀치 (세트1)" },
    { "triplepa", "트리플 펀치 (세트2)" },
    { "triplew1", "마작 트리플 워즈" },
    { "triplew2", "마작 트리플 워즈 2" },
    { "triplfun", "트리플 펀" },
    { "triplfunk", "숨어있는 덩달이를 찾아라" },
    { "triplhnt", "트리플 헌트" },
    { "tripool", "트라이풀 (카지노 테크)" },
    { "tripoola", "트라이풀 (코스탈 게임즈)" },
    { "tripslot", "트리플 슬롯" },
    { "trisport", "트라이 스포츠" },
    { "trivia12", "트리비얼 퍼슈트" },
    { "triviabb", "트리비얼 퍼슈트" },
    { "triviaes", "트리비얼 퍼슈트" },
    { "triviaes2", "트리비얼 퍼슈트" },
    { "triviag1", "트리비얼 퍼슈트" },
    { "triviag1a", "트리비얼 퍼슈트" },
    { "triviag2", "트리비얼 퍼슈트" },
    { "trivialp", "트리비얼 퍼슈트" },
    { "trivialpd", "트리비얼 퍼슈트" },
    { "trivialpo", "트리비얼 퍼슈트" },
    { "triviaqz", "프로페서 트리비아 (세트1)" },
    { "triviaqz2", "프로페서 트리비아 (세트2)" },
    { "triviasp", "트리비얼 퍼슈트" },
    { "triviayp", "트리비얼 퍼슈트" },
    { "trivquiz", "트리브 퀴즈" },
    { "trivrus", "트리비아 R US" },
    { "trizeal", "트라이질 (일본판)(GDL-0026)" },
    { "troangel", "트로피컬 엔젤" },
    { "trog", "트로그 (개정판LA5)" },
    { "trog3", "트로그 (개정판LA3)" },
    { "trog3a", "트로그 (개정판LA3)" },
    { "trog4", "트로그 (개정판LA4)" },
    { "trogp", "트로그 (시험판,개정판4.00)" },
    { "trogpa4", "트로그 (시험판,개정판4.00)" },
    { "trogpa5", "트로그 (시험판,개정판PA5-PAC)" },
    { "trogpa6", "트로그 (시험판,개정판PA6-PAC)" },
    { "trojan", "투쟁의 만가/ 트로젠 (미국판 세트1)" },
    { "trojana", "투쟁의 만가/ 트로젠 (미국판 세트2)" },
    { "trojanb", "투쟁의 만가/ 트로젠 (해적판)" },
    { "trojanj", "투쟁의 만가 (일본판)" },
    { "trojanjo", "투쟁의 만가 (일본판,구형)" },
    { "trojanlt", "투쟁의 만가/ 트로젠 (로케이션 테스트)" },
    { "trojanr", "투쟁의 만가/ 트로젠 (롬스타)" },
    { "trojanra", "투쟁의 만가/ 트로젠 (롬스타,세트2)" },
    { "tron", "트론 (8/9)" },
    { "tron2", "트론 (6/25)" },
    { "tron3", "트론 (6/17)" },
    { "tron4", "트론 (6/15)" },
    { "tron5", "트론" },
    { "tronfp", "트론 (프리플레이)" },
    { "tronger", "트론 (독일판)" },
    { "troopy", "트루피" },
    { "tropfrt", "트로피컬 후르츠" },
    { "trophyh", "트로피 사냥 - 곰 & 사슴 V1.00" },
    { "trophyht", "트로피 사냥 - 곰 & 사슴 V1.00 (로케이션 테스트)" },
    { "trstar", "탑 랭킹 스타 (버전2.1O,신버전)" },
    { "trstar2k", "트리플 스타 2000" },
    { "trstarj", "탑 랭킹 스타 (버전2.1J,신버전)" },
    { "trstaro", "탑 랭킹 스타 (버전2.1O,구버전)" },
    { "trstaroj", "탑 랭킹 스타 (버전2.1J,구버전)" },
    { "truckk", "트럭 광주곡" },
    { "truco", "트루코 트론" },
    { "trucocl", "트루코 클레멘트" },
    { "truxton", "트럭스턴/ 타수진" },
    { "truxton2", "트럭스턴 2/ 타수진 2/ 타수진왕" },
    { "trvchlng", "트리비아 챌린지" },
    { "trvgns", "트리비아 지니어스" },
    { "trvhang", "트리비아 행업" },
    { "trvhanga", "트리비아 행업" },
    { "trvmadns", "트리비아 매드니스 - 시리즈 A 문항 세트" },
    { "trvmadnsa", "트리비아 매드니스 - 시리즈 B 문항 세트" },
    { "trvmstr", "트리비아 마스터 (세트1)" },
    { "trvmstra", "트리비아 마스터 (세트2)" },
    { "trvmstrb", "트리비아 마스터 (세트3)" },
    { "trvmstrc", "트리비아 마스터 (세트4)" },
    { "trvmstrd", "트리비아 마스터 (세트5)" },
    { "trvquest", "트리비아 퀘스트" },
    { "trvwhiz", "트리비아 위즈" },
    { "trvwhzha", "트리비아 위즈 (가로 - 문항 세트2)" },
    { "trvwhzho", "트리비아 위즈" },
    { "trvwhzii", "트리비아 위즈" },
    { "trvwhziv", "트리비아 위즈" },
    { "trvwhzva", "트리비아 위즈 (수직 - 세트2)" },
    { "trvwhzve", "트리비아 위즈" },
    { "trvwz", "트리비아 위즈" },
    { "trvwz2", "트리비아 위즈 에디션 2" },
    { "trvwz2a", "트리비아 위즈 에디션 2" },
    { "trvwz3", "트리비아 위즈 에디션 3" },
    { "trvwz3a", "트리비아 위즈 에디션 3" },
    { "trvwz3b", "트리비아 위즈 에디션 3" },
    { "trvwz3h", "트리비아 위즈" },
    { "trvwz3ha", "트리비아 위즈 (가로) (세트2)" },
    { "trvwz3v", "트리비아 위즈 에디션 3" },
    { "trvwz4", "트리비아 위즈 에디션 4" },
    { "trvwz4a", "트리비아 위즈 (세트4)(문항 세트2)" },
    { "trvwz4v", "트리비아 위즈 에디션 4" },
    { "trvwz4va", "트리비아 위즈 에디션 4" },
    { "trvwza", "트리비아 위즈" },
    { "trvwzb", "트리비아 위즈" },
    { "trvwzh", "트리비아 위즈" },
    { "trvwzha", "트리비아 위즈 (가로)(문항 세트2)" },
    { "trvwzhb", "트리비아 위즈 (가로)(문항 세트3)" },
    { "trvwzv", "트리비아 위즈 (수직)(문항 세트1)" },
    { "trvwzva", "트리비아 위즈 (수직)(문항 세트2)" },
    { "tryout", "프로 베이스볼 스킬 트라이아웃" },
    { "ts2", "배틀 아레나 투신전 2" },
    { "ts2j", "배틀 아레나 투신전 2 (일본판)" },
    { "ts2ja", "배틀 아레나 투신전 2 (일본판)" },
    { "ts2u", "배틀 아레나 투신전 2 (미국판)" },
    { "ts2ua", "배틀 아레나 투신전 2 (미국판)" },
    { "tsamura2", "사무라이 일본 제일 (세트2)" },
    { "tsamurai", "사무라이 일본 제일 (세트1)" },
    { "tsamurai2", "사무라이 일본 제일 (세트2)" },
    { "tsamuraia", "사무라이 일본 제일" },
    { "tsamuraih", "사무라이 일본 제일 (해적판,어려움)" },
    { "tsclass", "트랩 슛 클래식" },
    { "tshingen", "다케다 신겐" },
    { "tshingena", "다케다 신겐 (일본판,일본어)" },
    { "tshingna", "다케다 신겐 (일본판,영어 버전)" },
    { "tshoot", "터키 슛" },
    { "tstrike", "썬더 스트라이크" },
    { "tstrikea", "썬더 스트라이크 (구형)" },
    { "tsukande", "츠칸데 토루 치치" },
    { "tsupenta", "츄리코 펜타" },
    { "tsurugi", "츠루기/ 검성" },
    { "tsurugij", "츠루기/ 검성 (버전JAC)" },
    { "ttchamp", "테이블 테니스 챔피언쉽" },
    { "ttchampa", "테이블 테니스 챔피언쉽 (팔렌시아 일렉트로닉 라이선스)" },
    { "ttfitter", "T.T 핏터 (일본판)" },
    { "ttmahjng", "T.T 마작" },
    { "tturf", "터프 터프 (세트2,일본판)" },
    { "tturfbl", "터프 터프" },
    { "tturfu", "터프 터프 (세트1,US)" },
    { "tubeit", "튜브 잇" },
    { "tubep", "튜브 패닉" },
    { "tubepb", "튜브 패닉" },
    { "tugboat", "터그보트" },
    { "tumbleb", "텀블 팝 (해적판 세트1)" },
    { "tumbleb2", "텀블 팝 (해적판 세트2)" },
    { "tumblep", "텀블 팝 (세계판)" },
    { "tumblep2", "텀블 팝 (해적판 세트2)" },
    { "tumblepb", "텀블 팝 (해적판 세트1)" },
    { "tumblepba", "텀블 팝 (플레이마크 해적판)" },
    { "tumblepj", "텀블 팝 (일본판)" },
    { "tunhunt", "터널 헌트" },
    { "tunhuntc", "터널 헌트 (센추리)" },
    { "turbo", "터보" },
    { "turboa", "터보" },
    { "turbob", "터보" },
    { "turbobl", "인디아나폴리스" },
    { "turboc", "터보" },
    { "turbod", "터보 (암호화,개정판A)" },
    { "turboe", "터보 (암호화)" },
    { "turbofrc", "터보 포스 (세계판,세트1)" },
    { "turbofrco", "터보 포스 (세계판,세트2)" },
    { "turbofrcu", "터보 포스 (미국판)" },
    { "turbofrcua", "터보 포스 (미국판,세트2)" },
    { "turbosub", "터보 서브" },
    { "turbosub6", "터보 서브 (시험판 개정판TSC6)" },
    { "turbosub7", "터보 서브 (시험판 개정판TSC7)" },
    { "turbosubb8", "터보 서브" },
    { "turbosubc5", "터보 서브" },
    { "turbosubc5s", "터보 서브" },
    { "turbosubc6", "터보 서브" },
    { "turbosubc7", "터보 서브" },
    { "turbosubc8", "터보 서브" },
    { "turbotag", "터보 태그" },
    { "turfmast", "네오 터프 마스터즈/ 빅 토너먼트 골프" },
    { "turkhunt", "터키 헌팅 USA" },
    { "turnover", "턴오버" },
    { "turpin", "터핀" },
    { "turpins", "터핀" },
    { "turrett", "터렛 타워" },
    { "turtles", "터틀즈" },
    { "turtshik", "거북선 (한국판)" },
    { "turtship", "거북선 (미국판)" },
    { "turtshipj", "거북선 (일본판)" },
    { "turtshipk", "거북선 (한국판)" },
    { "turtshipkn", "거북선 (한국판,88/9)" },
    { "turtshipko", "거북선 (한국판,구형)" },
    { "tutankhm", "투탕카멘" },
    { "tutankhms", "투탕카멘 (스턴)" },
    { "tutankst", "투탕카멘 (스턴)" },
    { "tutstomb", "텃의 무덤" },
    { "twcup90", "테크모 월드컵 90 (세계판,세트1)" },
    { "twcup90a", "테크모 월드컵 90 (유럽판 세트1)" },
    { "twcup90b", "테크모 월드컵 90 (유럽판 세트2)" },
    { "twcup90b1", "유로 리그 (이탈리아판 해적판)" },
    { "twcup90b2", "테크모 월드컵 90 (해적판,세트1)" },
    { "twcup90b3", "테크모 월드컵 90 (해적판,세트2)" },
    { "twcup90b4", "테크모 월드컵 90 (해적판,세트3)" },
    { "twcup90ba", "유로 리그 (이탈리아판 해적판)" },
    { "twcup90bb", "테크모 월드컵 90 (유럽 해적판)" },
    { "twcup90c", "테크모 월드컵 90" },
    { "twcup90t", "테크모 월드컵 90 (트랙볼)" },
    { "twcup94", "테크모 월드컵 94" },
    { "twcup94a", "테크모 월드컵 94 (세트2)" },
    { "twcup94b", "테크모 월드컵 94 (세트3)" },
    { "twcup98", "테크모 월드컵 98" },
    { "twcupmil", "테크모 월드컵 밀레니엄" },
    { "twinactn", "트윈 액션" },
    { "twinadv", "트윈 어드벤처 (세계판)" },
    { "twinadvk", "트윈 어드벤쳐 (한국판)" },
    { "twinbee", "트윈비 (롬 버전)" },
    { "twinbeeb", "트윈비 (버블 시스템)" },
    { "twinbrat", "트윈 브라츠 (세트1)" },
    { "twinbrata", "트윈 브라츠 (세트2)" },
    { "twinbratb", "트윈 브라츠 (세트3)" },
    { "twincobr", "트윈 코브라 (세계판)" },
    { "twincobru", "트윈 코브라 (미국판)" },
    { "twincobu", "트윈 코브라 (미국판)" },
    { "twineag2", "트윈 이글 2 - 레스큐 미션" },
    { "twineagl", "트윈 이글 - 리벤지 조스 브라더" },
    { "twinfalc", "트윈 팔콘" },
    { "twinhawk", "트윈 호크/ 대선풍 (세계판)" },
    { "twinhawku", "트윈 호크 (미국판)" },
    { "twinhwku", "트윈 호크 (미국판)" },
    { "twinkle", "트윙클" },
    { "twinklea", "트윙클 (세트2)" },
    { "twinqix", "트윈 퀵스 (버전1.0A,시제품)" },
    { "twinqixjh", "트윈 퀵스 (버전1.0A,핵)" },
    { "twins", "트윈스" },
    { "twinsa", "트윈스 (세트2)" },
    { "twinsed1", "트윈스" },
    { "twinsed2", "트윈스" },
    { "twinsprh", "트윙클 스타 스프라이트 (히든 핵)" },
    { "twinspri", "트윙클 스타 스프라이트" },
    { "twinsqua", "트윈 스쿼시" },
    { "twocrude", "투 크루드 (미국판 FT 개정판1)" },
    { "twocrudea", "투 크루드 (미국판 FT 버전)" },
    { "twotiger", "투 타이거즈 (헌정됨)" },
    { "twotigerc", "투 타이거즈 (트론 컨버젼)" },
    { "twotigra", "투 타이거즈" },
    { "twotigrc", "투 타이거즈 (트론 컨버젼)" },
    { "twrdc94a", "테크모 월드컵 94 (세트2)" },
    { "twrldc94", "테크모 월드컵 94" },
    { "twrldc94a", "테크모 월드컵 94 (세트2)" },
    { "twrshaft", "타워 & 샤프트" },
    { "tws96", "테크모 월드 축구 96" },
    { "twsoc96", "테크모 월드 축구 96" },
    { "twsoc98", "티엑스 원" },
    { "tx1", "티엑스 원" },
    { "tx1a", "티엑스 원 (아타리/남코/타이토 라이센스)" },
    { "tx1jb", "티엑스 원" },
    { "tx1jc", "티엑스 원" },
    { "tygn", "특이공능" },
    { "tylz", "틸즈" },
    { "typhoon", "타이푼" },
};

const size_t lookup_t_count = A_SIZE(lookup_t_table);

const char *lookup_t(const char *name) {
    if (!name) return NULL;
    for (size_t i = 0; i < lookup_t_count; i++) {
        if (strcmp(lookup_t_table[i].name, name) == 0) {
            return lookup_t_table[i].value;
        }
    }
    return NULL;
}

const char *r_lookup_t(const char *value) {
    if (!value) return NULL;
    for (size_t i = 0; i < lookup_t_count; i++) {
        if (strstr(lookup_t_table[i].value, value)) {
            return lookup_t_table[i].name;
        }
    }
    return NULL;
}

void lookup_t_multi(const char *term, void (*emit)(const char *name, const char *value, void *udata), void *udata) {
    if (!term) return;
    for (size_t i = 0; i < lookup_t_count; i++) {
        if (strcasestr(lookup_t_table[i].name, term))
            emit(lookup_t_table[i].name, lookup_t_table[i].value, udata);
    }
}

void r_lookup_t_multi(const char *term, void (*emit)(const char *name, const char *value, void *udata), void *udata) {
    if (!term) return;
    for (size_t i = 0; i < lookup_t_count; i++) {
        if (strcasestr(lookup_t_table[i].value, term))
            emit(lookup_t_table[i].name, lookup_t_table[i].value, udata);
    }
}
