#include <string.h>
#include "../common/common.h"
#include "lookup.h"

const LookupName lookup_g_table[] = {
    { "g13jnr", "고르고 13 총성의 진혼곡" },
    { "g13knd", "고르고 13 기적의 탄도" },
    { "ga2", "골든 엑스 - 데스 애더의 복수 (세계판,개정판B)" },
    { "ga2j", "골든 엑스 - 데스 애더의 복수 (일본판)" },
    { "ga2u", "골든 엑스 - 데스 애더의 복수 (미국판)" },
    { "gahaha", "GAHAHA 일발당 (세계판)" },
    { "gahaha2", "GAHAHA 일발당2 (일본판)" },
    { "gaia", "가이아 크루세이더" },
    { "gaialast", "가이아 - 라스트 초이스 오브 어스" },
    { "gaiapolj", "가이아폴리스 (버전JAF)" },
    { "gaiapols", "가이아폴리스 (버전EAF)" },
    { "gaiapolsj", "가이아폴리스 (버전JAF)" },
    { "gaiapolsu", "가이아폴리스 (버전UAF)" },
    { "gaiapolu", "가이아폴리스 (버전UAF)" },
    { "gaiden", "닌자 용검전/ 닌자 가이덴 (미국판)" },
    { "gakupara", "퀴즈 학원 파라다이스" },
    { "gakupara102", "퀴즈 학원 파라다이스 (일본판,버전10.2)" },
    { "gakusai", "마작 학원제" },
    { "gakusai2", "마작 학원제 2" },
    { "gakusaia", "마작 학원제 (일본판,세트2)" },
    { "gal10ren", "마작 걸 10연발" },
    { "gal3", "갤럭시안 3" },
    { "galactic", "갤럭티카 - 우주전투" },
    { "galactica2", "갤럭티카-2 (문 에일리언 파트2 해적판)" },
    { "galag88b", "갤러그 88 (세트2)" },
    { "galag88j", "갤러그 88 (일본판)" },
    { "galaga", "갤러그 (남코 개정판B)" },
    { "galaga3", "갤러그 3 (GP3 개정판D)" },
    { "galaga3a", "갤러그 3 (GP3 개정판C)" },
    { "galaga3b", "갤러그 3 (GP3)" },
    { "galaga3c", "갤러그 3 (세트4)" },
    { "galaga3m", "갤러그 3 (세트5)" },
    { "galaga84", "갤러그 84" },
    { "galaga88", "갤러그 88" },
    { "galaga88a", "갤러그 88" },
    { "galaga88j", "갤러그 88 (일본판)" },
    { "galagab2", "갤러그" },
    { "galagads", "갤러그 (속사)" },
    { "galagamf", "갤러그 (연사 핵)" },
    { "galagamk", "갤러그 (미드웨이 세트2)" },
    { "galagamw", "갤러그 (미드웨이 세트1)" },
    { "galagao", "갤러그 (남코)" },
    { "galagap", "갤러그 (패치드)" },
    { "galagawm", "갤러그 웨이브 믹서 (핵)" },
    { "galaktron", "갤라크트론" },
    { "galap1", "스페이스 인베이더 갤럭티카 (핵)" },
    { "galap2", "GX 파트 2 (갤럭시안 핵)" },
    { "galap4", "갤럭시안 파트 4 (핵)" },
    { "galapx", "갤럭시안 파트 X (핵)" },
    { "galartic", "갤럭시안 (아크틱 시스템 해적판)" },
    { "galastrm", "갤럭틱 스톰 (일본판)" },
    { "galaxb", "갤럭시안" },
    { "galaxbsf", "갤럭시안 (해적판,세트1)" },
    { "galaxbsf2", "갤럭시안 (해적판,세트3)" },
    { "galaxcirsa", "갤럭시안" },
    { "galaxi", "갤럭시" },
    { "galaxia", "갤럭시아" },
    { "galaxiaa", "갤럭시아 (세트2)" },
    { "galaxiab", "갤럭시아 (세트3)" },
    { "galaxiac", "갤럭시아 (세트4)" },
    { "galaxiaj", "갤럭시안 (남코 세트2)" },
    { "galaxiamv", "즐겨요 갤럭시아 (멀티비디오, 갤럭시안의 스페인어 해적판)" },
    { "galaxian", "갤럭시안 (남코 세트1)" },
    { "galaxiana", "갤럭시안 (남코 세트2)" },
    { "galaxianbl", "갤럭시안 (해적판,세트2)" },
    { "galaxianbl2", "갤럭시안 (해적판,세트4)" },
    { "galaxianbl3", "갤럭시안" },
    { "galaxianem", "갤럭시안 (Electromar 스페인 해적판)" },
    { "galaxiani", "갤럭시안 (아이렘)" },
    { "galaxianiii", "갤럭시안 III (갤럭시안 해적판)" },
    { "galaxianm", "갤럭시안 (미드웨이 세트1)" },
    { "galaxianmo", "갤럭시안 (미드웨이 세트2)" },
    { "galaxianrp", "갤럭시안" },
    { "galaxiant", "갤럭시안 (타이토)" },
    { "galaxrcgg", "갤럭시안 그로윙 갤럭십 (리크레이티보스 코바동가 스페인어 해적판)" },
    { "galaxrf", "갤럭시안 (스페인어 해적판)" },
    { "galaxrfgg", "갤럭시안 그로윙 갤럭십 (스페인어 해적판)" },
    { "galaxyfg", "갤럭시 파이트 - 유니버셜 워리어즈" },
    { "galaxyfh", "갤럭시 파이트 - 유니버셜 워리어즈 (히든 핵)" },
    { "galaxygn", "갤럭시 건너즈" },
    { "galaxygnh", "갤럭시 건너즈 (1990 핵)" },
    { "galaxyr", "갤럭시 레인져" },
    { "galaxyrp", "갤럭시 레인져 (파이어니어 LDV1000)" },
    { "galaxyx", "갤럭시 X (갤럭시안 해적판)" },
    { "galds", "갈스 Ds - 쓰리 딜러스 카지노 하우스 (해적판?)" },
    { "galemp", "갤럭시 엠파이어 (해적판?)" },
    { "galeone", "갈리온" },
    { "galgame", "갤럭시 게임" },
    { "galgame2", "갤럭시 게임즈 스타팩 2" },
    { "galgame3", "갤럭시 게임즈 스타팩 3" },
    { "galgame4", "갤럭시 게임즈 스타팩 4" },
    { "galgame4p", "갤럭시 게임즈 스타팩 4 (시험판)" },
    { "galhustl", "걸스 허슬러" },
    { "galivan", "우주형사 가리반" },
    { "galivan2", "우주형사 가리반 (12/16/1985)" },
    { "galivan3", "우주형사 가리반 (12/11/1985)" },
    { "galkaika", "마작 소녀의 개화" },
    { "galkamika", "카미카제" },
    { "galkoku", "마작 소녀의 고백" },
    { "gallag", "갤라그" },
    { "gallag50", "갤라그 비디오 게임/ 나비" },
    { "gallgall", "갤러거스 갤러리 v2.2" },
    { "gallop", "코스믹 캅/ 갤럽 - 암드 폴리스 유닛 (일본판,M72 PCB 버전)" },
    { "gallopm72", "코스믹 캅/ 갤럽 - 암드 폴리스 유닛 (일본판,M84 PCB 버전)" },
    { "galmedes", "갈메데스 (일본판)" },
    { "galmidw", "갤럭시안 (미드웨이)" },
    { "galmidwo", "갤럭시안 (미드웨이,구형 개정판)" },
    { "galmonst", "갤럭시 몬스터즈" },
    { "galpandx", "갈스 패닉 DX (아시아판)" },
    { "galpani2", "갈스 패닉 2 (아시아판)" },
    { "galpani2e", "갈스 패닉 2 (영어)" },
    { "galpani2e2", "갈스 패닉 2 (영어,2PCB버전)" },
    { "galpani2g", "갈스 패닉 2 (독일판)" },
    { "galpani2gs", "갈스 패닉 2 (독일판,싱글PCB)" },
    { "galpani2i", "갈스 패닉 2 (이탈리아판,싱글PCB)" },
    { "galpani2i2", "갈스 패닉 2 (이탈리아판,2PCB버전)" },
    { "galpani2j", "갈스 패닉 2 (일본판)" },
    { "galpani2k", "갈스 패닉 2 (한국판,싱글PCB)" },
    { "galpani2t", "갈스 패닉 2 (대만판)" },
    { "galpani3", "갈스 패닉 3 (유럽판)" },
    { "galpani3hk", "갈스 패닉 3 (홍콩판)" },
    { "galpani3j", "갈스 패닉 3 (일본판)" },
    { "galpani3k", "갈스 패닉 3 (한국판)" },
    { "galpani4", "갈스 패닉 4 (유럽판)" },
    { "galpani4j", "갈스 패닉 4 (일본판)" },
    { "galpani4k", "갈스 패닉 4 (한국판)" },
    { "galpania", "갈스 패닉 (MCU 보호)" },
    { "galpanib", "갈스 패닉 (세트2)" },
    { "galpanic", "갈스 패닉 (비보호됨,버전2)" },
    { "galpanica", "갈스 패닉 (비보호됨)" },
    { "galpanicb", "갈스 패닉 (ULA보호됨,세트1)" },
    { "galpanicc", "갈스 패닉 (ULA보호됨,세트2)" },
    { "galpanicms", "뉴 퀴즈 (갈스 패닉의 모듈라 시스템 해적판)" },
    { "galpanidx", "갈스 패닉 DX (아시아판)" },
    { "galpaniex", "갈스 패닉 EX (한국판)" },
    { "galpanis", "갈스 패닉 S - 엑스트라 에디션 (유럽판,개정판1)" },
    { "galpanisa", "갈스 패닉 S - 엑스트라 에디션 (아시아판)" },
    { "galpanise", "갈스 패닉 S - 엑스트라 에디션 (유럽판,세트2)" },
    { "galpanisj", "갈스 패닉 S - 엑스트라 에디션 (일본판)" },
    { "galpanisk", "갈스 패닉 S - 엑스트라 에디션 (한국판)" },
    { "galpaniska", "갈스 패닉 S - 엑스트라 에디션 (한국판)" },
    { "galpanisu", "갈스 패닉 SU (한국판,갈스 패닉 4 재발매)" },
    { "galpans2", "갈스 패닉 S2 (유럽판,버전3)" },
    { "galpans2a", "갈스 패닉 S2 (아시아판,버전1.1)" },
    { "galpans2j", "갈스 패닉 S2 (일본판)" },
    { "galpans3", "갈스 패닉 S3 (일본판)" },
    { "galpansu", "갈스 패닉 SU (한국판,개정판5)" },
    { "galpansua", "갈스 패닉 SU (한국판)" },
    { "galsnew", "갈스 패닉 (수출판,EXPRO-02 PCB)" },
    { "galsnewa", "갈스 패닉 (수출판,EXPRO-02 PCB)" },
    { "galsnewj", "갈스 패닉 (일본판,EXPRO-02 PCB)" },
    { "galsnewk", "갈스 패닉 (한국판,EXPRO-02 PCB)" },
    { "galsnewt", "갈스 패닉 (대만판,EXPRO-02 PCB)" },
    { "galsnewu", "갈스 패닉 (미국판,EXPRO-02 PCB)" },
    { "galspnbl", "갈스 핀볼" },
    { "galturbo", "갤럭시안 터보 (핵)" },
    { "galwars2", "갤럭시 워즈 2" },
    { "galxwar2", "갤럭시 워즈 (유니버셜 세트2)" },
    { "galxwars", "갤럭시 워즈" },
    { "galxwars2", "갤럭시 워즈 (유니버셜 세트2)" },
    { "galxwarst", "갤럭시 워즈 (타이토)" },
    { "galxwarst2", "갤럭시 워즈 (타이토)" },
    { "galxwart", "갤럭시 워즈 (타이토)" },
    { "gamecst2", "게임 크리스탈 (버전2.613)" },
    { "gamecstl", "게임 크리스탈" },
    { "gametngk", "게임 천국 - 게임 파라다이스 (버전1.0)" },
    { "gamshara", "겜스하라" },
    { "gamsharao", "겜스하라" },
    { "ganbare", "힘내라! 마린 군 (일본판)" },
    { "gangonta", "힘내라 곤타 2/ 파티 타임 (일본판 발매)" },
    { "gangwarb", "갱 워즈 (해적판)" },
    { "gangwars", "갱 워즈" },
    { "gangwarsb", "갱 워즈 (해적판)" },
    { "gangwarsj", "갱 워즈 (일본판)" },
    { "gangwarsu", "갱 워즈 (미국판)" },
    { "ganjaja", "힘내라 자자마루 사이쇼하 구" },
    { "ganryu", "간류/무사시 간류키" },
    { "ganryun", "간류/무사시 간류키(해독됨 C)" },
    { "ganryund", "간류/무사시 간류키(완전해독됨)" },
    { "gaplus", "갤러그 3_가플러스 (GP2 개정판B)" },
    { "gaplusa", "갤러그 3_가플러스 (GP2)" },
    { "gaplusd", "갤러그 3_가플러스 (GP2 개정판D,대체 하드웨어)" },
    { "gapluse", "갤러그 3_가플러스 (GP7)" },
    { "gapluso", "갤러그 3_가플러스 (개정판B)" },
    { "gaplust", "갤러그 3_가플러스 (테크프라이 PCB)" },
    { "garage_4", "게라지" },
    { "garage_4a", "게라지 (백도어)" },
    { "garage_4b", "게라지 (버전텍스트 변경)" },
    { "garage_5", "게라지" },
    { "garage_5a", "게라지 (백도어)" },
    { "gardia", "가르디아" },
    { "gardiab", "가르디아" },
    { "gardiaj", "가르디아" },
    { "garogun", "가로군 세로양 (한국판)" },
    { "garou", "아랑/가로우-늑대의 증표" },
    { "garoub", "아랑/가로우-늑대의 증표 (히든핵)" },
    { "garoubl", "아랑/가로우-늑대의 증표 (해적판)" },
    { "garoubs", "아랑/가로우-늑대의 증표 (히든 캐릭터 가능,핵)" },
    { "garouh", "아랑/가로우-늑대의 증표 (NGM-2530)(NGH-2530)" },
    { "garouha", "아랑/가로우-늑대의 증표 (NGH-2530)" },
    { "garoujq", "아랑/가로우-늑대의 증표 (강화,핵)" },
    { "garoun", "아랑/가로우-늑대의 증표 (해독됨 C)" },
    { "garound", "아랑/가로우-늑대의 증표 (완전해독됨)" },
    { "garouo", "아랑/가로우-늑대의 증표 (세트2)" },
    { "garoup", "아랑/가로우-늑대의 증표 (시험판)" },
    { "garuka", "약탈자/ 가루카 (일본판 버전W)" },
    { "garyoret", "와룡열전 (일본판)" },
    { "gatedom1", "게이트 오브 둠 (미국판 개정판1)" },
    { "gatedoom", "게이트 오브 둠 (미국판 개정판4)" },
    { "gatedoom1", "게이트 오브 둠 (미국판 개정판1)" },
    { "gatsbee", "가츠비" },
    { "gaun22p1", "건틀렛 2 (2인용,개정판1)" },
    { "gaun22pg", "건틀렛 2 (2인용,독일판)" },
    { "gaun2pg1", "건틀렛 (2인용,독일판,개정판1)" },
    { "gaun2pj2", "건틀렛 (2인용,일본판,개정판2)" },
    { "gaun2pr3", "건틀렛 (2인용,개정판3)" },
    { "gaunt2", "건틀렛 2" },
    { "gaunt22p", "건틀렛 2 (2인용,개정판2)" },
    { "gaunt22p1", "건틀렛 2 (2인용,개정판1)" },
    { "gaunt22pg", "건틀렛 2 (2인용,독일판)" },
    { "gaunt2g", "건틀렛 2 (독일판)" },
    { "gaunt2p", "건틀렛 (2인용,개정판6)" },
    { "gaunt2pg", "건틀렛 (2인용,독일판,개정판4)" },
    { "gaunt2pj", "건틀렛 (2인용,일본판,개정판5)" },
    { "gauntd24", "건틀렛 다크 레거시 (버전DL 2.4)" },
    { "gauntdl", "건틀렛 다크 레거시" },
    { "gauntdl24", "건틀렛 다크 레거시 (버전DL 2.4)" },
    { "gauntg", "건틀렛 (독일판,개정판10)" },
    { "gauntgr3", "건틀렛 (독일판,개정판3)" },
    { "gauntgr6", "건틀렛 (독일판,개정판6)" },
    { "gauntgr8", "건틀렛 (독일판,개정판8)" },
    { "gauntir1", "건틀렛 (중간 배포 1)" },
    { "gauntir2", "건틀렛 (중간 배포 2)" },
    { "gauntj", "건틀렛 (일본판,개정판13)" },
    { "gauntj12", "건틀렛 (일본판,개정판12)" },
    { "gauntl12", "건틀렛 레전드 (버전1.2)" },
    { "gauntleg", "건틀렛 레전드" },
    { "gauntleg12", "건틀렛 레전드 (버전1.2)" },
    { "gauntlet", "건틀렛 (개정판14)" },
    { "gauntlet2p", "건틀렛 (2인용,개정판6)" },
    { "gauntlet2pg", "건틀렛 (2인용,독일판,개정판4)" },
    { "gauntlet2pg1", "건틀렛 (2인용,독일판,개정판1)" },
    { "gauntlet2pj", "건틀렛 (2인용,일본판,개정판5)" },
    { "gauntlet2pj2", "건틀렛 (2인용,일본판 개정판2)" },
    { "gauntlet2pr3", "건틀렛 (2인용,개정판3)" },
    { "gauntletg", "건틀렛 (독일판,개정판10)" },
    { "gauntletgr3", "건틀렛 (독일판,개정판3)" },
    { "gauntletgr6", "건틀렛 (독일판,개정판6)" },
    { "gauntletgr8", "건틀렛 (독일판,개정판8)" },
    { "gauntletj", "건틀렛 (일본판,개정판13)" },
    { "gauntletj12", "건틀렛 (일본판,개정판12)" },
    { "gauntletr1", "건틀렛 (개정판1)" },
    { "gauntletr2", "건틀렛 (개정판2)" },
    { "gauntletr4", "건틀렛 (개정판4)" },
    { "gauntletr5", "건틀렛 (개정판5)" },
    { "gauntletr7", "건틀렛 (개정판7)" },
    { "gauntletr9", "건틀렛 (개정판9)" },
    { "gauntlets", "건틀렛 (스페인어,개정판15)" },
    { "gauntr1", "건틀렛 (개정판1)" },
    { "gauntr2", "건틀렛 (개정판2)" },
    { "gauntr4", "건틀렛 (개정판4)" },
    { "gauntr5", "건틀렛 (개정판5)" },
    { "gauntr7", "건틀렛 (개정판7)" },
    { "gauntr9", "건틀렛 (개정판9)" },
    { "gaunts", "건틀렛 (스페인어,개정판15)" },
    { "gaxeduel", "골든 엑스-더 듀얼" },
    { "gbbchmp", "그레이트 비시 바시 챔프" },
    { "gberet", "그린베레" },
    { "gberetb", "그린베레" },
    { "gblchmp", "글로벌 챔피언 (버전2.1A)" },
    { "gbusters", "갱 버스터즈/ 크레이지 캅 (세트1)" },
    { "gbustersa", "갱 버스터즈/ 크레이지 캅 (세트2)" },
    { "gcastle", "황금성 (시험판?)" },
    { "gchgchmp", "가챠가 챔프" },
    { "gcpinbal", "그랜드 크로스" },
    { "gdarius", "G-다리우스 (버전2.02O)" },
    { "gdarius2", "G-다리우스 (버전2.03J)" },
    { "gdariusb", "G-다리우스 (버전2.02A)" },
    { "gdariusj", "G-다리우스 (버전2.01J)" },
    { "gdariusu", "G-다리우스 (버전2.02A)" },
    { "gderby", "그랜 더비 (쟈키 클럽의 스페인어 해적판)" },
    { "gdfs", "기동전사 건담 파이널 슈팅 (일본판)" },
    { "geebee", "기비 (일본판)" },
    { "geebeea", "기비 (영국판)" },
    { "geebeeb", "기비 (유럽판)" },
    { "geebeeg", "기비 (미국판)" },
    { "gegege", "게게게의 기타로 요괴슬롯" },
    { "geimulti", "GEI 멀티 게임" },
    { "geishanz", "게이샤" },
    { "gekiretu", "퀴즈 격렬 스크램블" },
    { "gekiretup", "퀴즈 격렬 스크램블 (일본판,시험판)" },
    { "gekiridn", "역린탄 (버전2.3O)" },
    { "gekiridnj", "역린탄 (버전2.3J)" },
    { "gekirido", "역린탄" },
    { "gekisha", "마작 격사" },
    { "gekishap2", "마작 격사 파트 II" },
    { "gekisou", "격주" },
    { "gekitsui", "격추왕 (일본판)" },
    { "gekpurya", "격투 프로야구 미지즈마 신지 올스타 vs 프로 야구" },
    { "gemcrush", "젬크러쉬" },
    { "gemini", "제미니 윙 (세계판)" },
    { "geminib", "제미니 윙 (세계판,해적판)" },
    { "geminij", "제미니 윙 (일본판)" },
    { "genie", "지니" },
    { "geniea", "지니 (ICP-1,세트2)" },
    { "genius6", "지니어스 6 (V110F)" },
    { "genius6a", "지니어스 6 (V133F)" },
    { "genius6b", "지니어스 6 (V132F)" },
    { "genix", "제닉스 패밀리" },
    { "genpeitd", "원평 토마전" },
    { "gensitou", "원시도 1930 (일본판)" },
    { "geostorm", "건포스 2/ 지오스톰 (일본판)" },
    { "geostorma", "건포스 2/ 지오스톰 (일본판)" },
    { "gepoker", "포커" },
    { "gepoker1", "포커 (버전50.02 ICB,세트2)" },
    { "gepoker2", "포커 (버전50.02 ICB,세트3)" },
    { "gepoker3", "포커 (버전50.02 ICB 세트3)" },
    { "getaway", "겟 어 웨이 (입식)" },
    { "getbass", "겟 베스" },
    { "getbassur", "겟 베스: 세가 베스 피싱 업라잇 (일본판)" },
    { "getrich", "겟 리치" },
    { "getstar", "가디언" },
    { "getstarb", "겟 스타 (해적판,세트1)" },
    { "getstarb1", "겟 스타 (해적판 세트1)" },
    { "getstarb2", "겟 스타 (해적판 세트2)" },
    { "getstarj", "겟 스타 (일본판)" },
    { "gfire2", "골든 파이어 2" },
    { "gforce2", "갤럭시 포스 2" },
    { "gforce2j", "갤럭시 포스 2 (일본판)" },
    { "gforce2ja", "갤럭시 포스 2 (일본판,개정판A)" },
    { "gforce2sd", "갤럭시 포스 2 (슈퍼 디럭스 유닛)" },
    { "ggconnie", "고!고! 코니 짱 자카자카잔칸" },
    { "gghost", "골리 고스트" },
    { "ggisuka", "길티 기어 이스카" },
    { "ggoemon", "힘내라 고에몽" },
    { "ggram2", "자이언트 그램: 전일본 프로 레슬링 2 (일본판)" },
    { "ggreats2", "골핑 그레이트 2 (버전JAC)" },
    { "gground", "게인 그라운드 (세계판,3인용)" },
    { "ggroundj", "게인 그라운드 (일본판,2인용)" },
    { "ggx", "길티 기어 X" },
    { "ggx15", "길티 기어 X 버전 1.5" },
    { "ggxx", "길티 기어 XX (GDL-0011)" },
    { "ggxxac", "길티 기어 XX 액센트 코어 (일본판)(GDL-0041)" },
    { "ggxxrl", "길티 기어 XX 리로드 (일본판,개정판A)(GDL-0019A)" },
    { "ggxxrlo", "길티 기어 XX 리로드 (일본판)(GDL-0019)" },
    { "ggxxsla", "길티 기어 XX 슬래시 (일본판,개정판A)(GDL-0033A)" },
    { "ghlpanic", "구울 패닉" },
    { "ghoshunt", "고스트 헌터" },
    { "ghostb", "리얼 고스트버스터스 (미국판 2인용,개정판2)" },
    { "ghostb2a", "리얼 고스트버스터스 (미국판 2인용)" },
    { "ghostb3", "리얼 고스트버스터스" },
    { "ghostbi", "고스트 버스터즈 (FMV 데모)" },
    { "ghostlop", "고스트럽 (시제품)" },
    { "ghostmun", "고스트 먼처" },
    { "ghostsqu", "고스트 스쿼드" },
    { "ghouls", "대마계촌/ 구울 앤 고스트 (세계판)" },
    { "ghoulsj", "대마계촌 (일본판)" },
    { "ghoulsu", "대마계촌/ 구울 앤 고스트 (미국판)" },
    { "ghox", "곡스 (스피너)" },
    { "ghoxj", "곡스 (조이스틱)" },
    { "ghoxjo", "곡스 (조이스틱,구형)" },
    { "ghunter", "데드 앵글/ 갱 헌터" },
    { "ghunters", "데드 앵글/ 갱 헌터 (스페인판)" },
    { "gigaman2", "기가맨 2 - 파워 파이터즈(MCU 덤프안됨)" },
    { "gigamn2", "자이언트 맨 2 - 파워 파이터즈" },
    { "gigandes", "기간데스" },
    { "gigandesa", "기간데스 (초기판)" },
    { "gigandesj", "기간데스 (일본판)" },
    { "gigandsj", "기간데스 (일본판)" },
    { "gigas", "기가스" },
    { "gigasb", "기가스" },
    { "gigasm2", "기가스 마크 2" },
    { "gigasm2b", "기가스 마크 2" },
    { "gigawing", "기가 윙 (미국판)" },
    { "gigawinga", "기가 윙 (아시아판)" },
    { "gigawingb", "기가 윙 (브라질판)" },
    { "gigawingd", "기가 윙 (미국판,피닉스에디션)" },
    { "gigawingh", "기가 윙 (히스패닉판)" },
    { "gigawingj", "기가 윙 (일본판)" },
    { "gigawingjd", "기가 윙 (일본판,피닉스에디션)" },
    { "gijoe", "GI 죠 (세계판,EAB,세트1)" },
    { "gijoea", "GI 죠 (아시아판,AA)" },
    { "gijoeea", "GI 죠 (세계판,EB8,시험판)" },
    { "gijoej", "GI 죠 (일본판,JAA)" },
    { "gijoeu", "GI 죠 (미국판,UAB)" },
    { "gijoeua", "GI 죠" },
    { "gimeabrk", "김미 어 브레이크" },
    { "gingania", "은하 임협전 (세트2)" },
    { "ginganin", "은하 임협전 (세트1)" },
    { "ginganina", "은하 임협전 (세트2)" },
    { "ginganink", "은하 임협전 (한글)" },
    { "ginkun", "힘내라 긴군" },
    { "gionbana", "기원화" },
    { "girotutt", "지로투토" },
    { "gjspace", "참새 스페이스" },
    { "gladiatr", "황금성/ 글래디에이터 (미국판)" },
    { "gladmort", "글레드모트 (HB)" },
    { "glass", "글래스 (버전1.1,브레이크 에디션)" },
    { "glass10", "글래스 (버전1.0,브레이크 에디션)(세트1)" },
    { "glass10a", "글래스 (버전1.0,브레이크 에디션)(세트2)" },
    { "glassbrk", "글래스 (버전1.0,브레이크 에디션)" },
    { "glasskr", "글래스 (버전1.1,브레이크 에디션)(삭제판,비보호)" },
    { "gldarrow", "골든 애로우" },
    { "gldncrwn", "골든 크라운" },
    { "glfgreat", "골핑 그레이트 (세계판,버전L)" },
    { "glfgreatj", "골핑 그레이트 (일본판,버전J)" },
    { "glfgreatu", "골핑 그레이트 (미국판,버전K)" },
    { "glfgretj", "골핑 그레이트 (일본판)" },
    { "gloc", "G-LOC 에어 배틀 (세계판)" },
    { "glocr360", "G-LOC R360 (세계판)" },
    { "glocr360j", "G-LOC R360 (일본판)" },
    { "glocu", "G-LOC 에어 배틀 (미국판)" },
    { "glprac2j", "갤럽 레이서 2 (일본판)" },
    { "glprac2l", "갤럽 레이서 2 (일본판)" },
    { "glpracr", "갤럽 레이서" },
    { "glpracr2", "갤럽 레이서 2" },
    { "glpracr2j", "갤럽 레이서 2 (일본판)" },
    { "glpracr2l", "갤럽 레이서 2 (일본판)" },
    { "glpracr3", "갤럽 레이서 3" },
    { "glpracr3j", "갤럽 레이서 3 (일본판)" },
    { "glpracrj", "갤럽 레이서 (일본어 버전)" },
    { "gluck2", "굿 룩 II" },
    { "gmahou", "그레이트 마법 대작전 (일본판)" },
    { "gmgalax", "고스트멍커 갤럭시안 (복제품)" },
    { "gmissile", "미사일 X/ 유도 미사일" },
    { "gnbarich", "건바리치" },
    { "gng", "마계촌/ 고스트 앤 고블린" },
    { "gnga", "마계촌/ 고스트 앤 고블린 (세계판,세트2)" },
    { "gngbl", "마계촌/ 고스트 앤 고블린 (해적판)" },
    { "gngbla", "마계촌/ 고스트 앤 고블린 (해적판,어려움)" },
    { "gngblita", "마계촌/ 고스트 앤 고블린 (이탈리아판 해적판,어려움)" },
    { "gngc", "마계촌/ 고스트 앤 고블린 (세계판,세트3)" },
    { "gngprot", "마계촌/ 고스트 앤 고블린 (시험판)" },
    { "gngt", "마계촌/ 고스트 앤 고블린 (미국판)" },
    { "go2000", "고 2000" },
    { "goal92", "골! 92" },
    { "goaltogo", "골 투 고" },
    { "goalx3", "골! 골! 골!" },
    { "gobyrc", "고 바이 알씨" },
    { "gocowboy", "고 고 카우보이" },
    { "godzilla", "고질라 (일본판)" },
    { "gogold", "레코드브레이커/ 금메달을 향해 (일본판)" },
    { "gogomile", "나아가라! 마일 스마일 (신형)" },
    { "gogomilej", "나아가라! 마일 스마일 (일본판)" },
    { "gogomileo", "나아가라! 마일 스마일 (구형)" },
    { "gogomilj", "나아가라! 마일 스마일 (일본판)" },
    { "goindol", "고인돌 (세계판)" },
    { "goindolj", "고인돌 (일본판)" },
    { "goindolk", "고인돌 (한국판)" },
    { "goindolu", "고인돌 (미국판)" },
    { "gokuparo", "극상 파로디우스 (버전JAD)" },
    { "goldbug", "골드 버그" },
    { "goldenc", "골든 카나리아" },
    { "goldfrui", "골드 후루츠" },
    { "goldmeda", "금메달리스트 (대체)" },
    { "goldmedb", "금메달리스트" },
    { "goldmedl", "금메달리스트 (세트1)" },
    { "goldmedla", "금메달리스트 (세트2)" },
    { "goldmedlb", "금메달리스트" },
    { "goldnabl", "골든 엑스" },
    { "goldnax1", "골든 엑스 (세트1,세계판)" },
    { "goldnax2", "골든 엑스 (세트2,미국판)" },
    { "goldnax3", "골든 엑스 (세트3,세계판)" },
    { "goldnaxa", "골든 엑스 (버전2)" },
    { "goldnaxb", "골든 엑스 (버전2)" },
    { "goldnaxc", "골든 엑스 (버전2)" },
    { "goldnaxe", "골든 엑스 (세트6,미국판)" },
    { "goldnaxe1", "골든 엑스 (세트1,세계판)" },
    { "goldnaxe1d", "골든 엑스 (세트1,세계판,암호해제)" },
    { "goldnaxe2", "골든 엑스 (세트2,미국판)" },
    { "goldnaxe3", "골든 엑스 (세트3,세계판)" },
    { "goldnaxe3d", "골든 엑스 (세트3,세계판,암호해제)" },
    { "goldnaxeb1", "골든 엑스 (암호화 해적판)" },
    { "goldnaxeb2", "골든 엑스" },
    { "goldnaxej", "골든 엑스 (세트4,일본판)" },
    { "goldnaxejd", "골든 엑스 (세트4,일본판,암호해제)" },
    { "goldnaxeng", "골든 엑스 네오지오 (HB)" },
    { "goldnaxeu", "골든 엑스 (세트5,미국판)" },
    { "goldnaxeud", "골든 엑스 (세트5,미국판,암호해제)" },
    { "goldnaxj", "골든 엑스 (세트4,일본판)" },
    { "goldnaxu", "골든 엑스 (세트5,미국판)" },
    { "goldnjkr", "골든 조커" },
    { "goldnjkra", "골든 조커" },
    { "goldnpkb", "골든 포커 더블 업 (미니 보이)" },
    { "goldnpkc", "골든 포커 더블 업 (해적판,세트1)" },
    { "goldnpke", "골든 포커 더블 업 (해적판,세트3)" },
    { "goldnpkf", "골든 포커 더블 업 (해적판,세트4)" },
    { "goldnpkg", "골든 포커 더블 업 (해적판,세트5)" },
    { "goldnpkr", "골든 포커 더블 업 (빅 보이)" },
    { "goldprmd", "골든 피라미드" },
    { "goldstar", "골든 스타" },
    { "goldstbl", "골든 스타 (블루 버전)" },
    { "golgo13", "고르고 13" },
    { "gollygho", "골리! 고스트!" },
    { "gomoku", "오목 두는 돌" },
    { "gondo", "마경전사/ 곤도매니아 (세계판)" },
    { "gondou", "마경전사/ 곤도매니아 (미국판)" },
    { "good", "굿" },
    { "goodejan", "굿 E 작 - 토너먼트 마작 상금왕" },
    { "goodejana", "굿 E 작 - 토너먼트 마작 상금왕 (세트2)" },
    { "goodluck", "굿럭" },
    { "goonies", "Vs 구니스" },
    { "goori", "구리구리" },
    { "gorf", "고프" },
    { "gorfirec", "고프 (스페인판,이렉사 라이센스)" },
    { "gorfpgm1", "고프 (프로그램 1)" },
    { "gorfpgm1f", "고프 (프로그램 1,프랑스어 롬)" },
    { "gorfpgm1g", "고프 (프로그램 1,독일어 롬)" },
    { "gorkans", "고칸스" },
    { "gorodki", "요롯키" },
    { "gostop", "한국 화투 고스톱" },
    { "gotcha", "빠샤빠샤 챔프_갓챠 미니게임 페스티발" },
    { "gotya", "더 핸드/ 갓야 (시험판)" },
    { "gowcaiet", "볼티지 파이터-고우카이저 (이터널,핵)" },
    { "gowcaizb", "볼티지 파이터-고우카이저 (보스 핵)" },
    { "gowcaizr", "볼티지 파이터-고우카이저" },
    { "gp2quiz", "갈스 패닉 2 - 퀴즈버전" },
    { "gp2se", "갈스 패닉 2 - 특별판 (일본판)" },
    { "gp500", "GP500" },
    { "gp98", "그랑프리 98" },
    { "gp98a", "그랑프리 98" },
    { "gpan2qiz", "갈스 패닉 2 - 퀴즈버전 (일본판)" },
    { "gpgolf", "골든 파 골프" },
    { "gpgolfa", "골든 파 골프" },
    { "gpilots", "고스트 파일럿" },
    { "gpilotsh", "고스트 파일럿 (미국판)" },
    { "gpilotsp", "고스트 파일럿 (시험판)" },
    { "gprider", "GP 라이더 (세계판,트윈 셋업)" },
    { "gprider1", "GP 라이더 (세트1,US)" },
    { "gpriderj", "GP 라이더 (일본판)(트윈 셋업)" },
    { "gpriderjs", "GP 라이더 (일본판)" },
    { "gpriders", "GP 라이더 (세계판)" },
    { "gprideru", "GP 라이더 (미국판)(트윈 셋업)" },
    { "gpriderus", "GP 라이더 (미국판)" },
    { "gpworld", "GP 월드" },
    { "gradius", "그라디우스 (일본판,ROM 버전)" },
    { "gradius2", "그라디우스 2 - 고퍼의 야망 (일본판 신버전)" },
    { "gradius2a", "그라디우스 2 - 고퍼의 야망 (일본판 구버전)" },
    { "gradius2b", "그라디우스 2 - 고퍼의 야망 (일본판 구버전)" },
    { "gradius3", "그라디우스 3 (세계판,버전R)" },
    { "gradius3a", "그라디우스 3 (아시아판)" },
    { "gradius3e", "그라디우스 3 (세계판)" },
    { "gradius3j", "그라디우스 3 (일본판,버전3,신형)" },
    { "gradius3ja", "그라디우스 3 (일본판,버전S)" },
    { "gradius3jas", "그라디우스 3 (일본판,버전S,스플릿)" },
    { "gradius3js", "그라디우스 3 (일본판,프로그램 코드 S,분할)" },
    { "gradius4", "그라디우스 4 - 부활" },
    { "gradius4a", "그라디우스 4 (버전AAC)" },
    { "gradius4aa", "그라디우스 4 (버전AAA)" },
    { "gradius4ja", "그라디우스 4 - 부활 (버전JAA)" },
    { "gradius4u", "그라디우스 4 (버전UAC)" },
    { "gradius4ua", "그라디우스 4 (버전UAA)" },
    { "gradiusb", "그라디우스 (버블 시스템)" },
    { "grainbow", "SD건담 삼국지 레인보우 대륙전기 (일본판)" },
    { "grainbowk", "SD건담 삼국지 레인보우 대륙전기 (한국판)" },
    { "grally", "그랜 랠리 (폴 포지션 2의 스페인어 해적판)" },
    { "gram2000", "자이언트 그램 2000" },
    { "grancapi", "그란 캡틴 (버전3)" },
    { "grandprx", "그랑프리" },
    { "granny", "그래니 앤 더 게이터스" },
    { "grasspin", "그래스핀" },
    { "gratia", "그라시아 - 세컨드 어스 (버전1.0)" },
    { "gratiaa", "그라시아 - 세컨드 어스" },
    { "gravitar", "그라비타 (버전3)" },
    { "gravitar1", "그라비타 (버전1)" },
    { "gravitar2", "그라비타 (버전2)" },
    { "gravitr2", "그라비타 (버전2)" },
    { "gravp", "그라비타 (시험판)" },
    { "grchamp", "그랜드 챔피언" },
    { "grchampb", "그랜드 챔피언 (세트3)" },
    { "grdforce", "가디언 포스" },
    { "grdian", "가디언 (미국판)" },
    { "grdiands", "전신마괴 2/가디언즈 (프로,핵)" },
    { "grdianke", "전신마괴 2/가디언즈 (리베리,핵)" },
    { "grdianls", "전신마괴 2/가디언즈 (LBS슈퍼,핵)" },
    { "grdians", "전신마괴 2/가디언즈" },
    { "grdiansa", "전신마괴 2/가디언즈 (P0-113A PCB)" },
    { "grdiansbl", "전신마괴 2/가디언즈 (해적판)" },
    { "grdianshs", "전신마괴 2/가디언즈 (핵시리즈)" },
    { "grdianske", "전신마괴 2/가디언즈 (케론 에디션,핵)" },
    { "grdiansl", "전신마괴 2/가디언즈 (LBS,핵)" },
    { "grdianslbs", "전신마괴 2/가디언즈 (LBS 에디션,핵)" },
    { "grdianslbss", "전신마괴 2/가디언즈 (필드 에디션,핵)" },
    { "grdiansp", "전신마괴 2/가디언즈 (플러스,핵)" },
    { "grdianssy", "전신마괴 2/가디언즈 (Shen Yue 에디션,핵)" },
    { "grdiansy", "전신마괴 2/가디언즈 (에빌,핵)" },
    { "grdius2a", "그라디우스 2 - 고퍼의 야망 (일본판 구버전)" },
    { "grdius2b", "그라디우스 2 - 고퍼의 야망 (일본판 구버전)" },
    { "grdius3a", "그라디우스 3 (아시아판)" },
    { "grdius3e", "그라디우스 3 (세계판)" },
    { "grdnstrm", "전신 - 가디언 스톰 (가로형,암호화 안됨)" },
    { "grdnstrmau", "전신 - 가디언 스톰" },
    { "grdnstrmg", "전신 - 가디언 스톰 (독일판)" },
    { "grdnstrmj", "전신 - 가디언 스톰 (일본판)" },
    { "grdnstrmk", "전신 - 가디언 스톰 (한국판)" },
    { "grdnstrmv", "전신 - 가디언 스톰 (수직)" },
    { "greatgun", "그레이트 건즈" },
    { "greatgur", "황금성 (해적판?)" },
    { "greenber", "그린베레" },
    { "grescue", "갤럭시 레스큐" },
    { "gridiron", "그리다이언 파이트" },
    { "gridlee", "그리들리" },
    { "griffon", "그리폰" },
    { "grindsta", "그라인드 스토머 (구형 세트)" },
    { "grindstm", "그라인드 스토머" },
    { "grindstma", "그라인드 스토머 (구형 세트)" },
    { "grmatch", "그루지 매치" },
    { "grndtour", "그랜드 투어" },
    { "grobda", "그로브다 (신버전)" },
    { "grobda2", "그로브다 (구버전세트1)" },
    { "grobda3", "그로브다 (구버전세트2)" },
    { "groovef", "호혈사 일족 3/ 파워 인스팅트 3 - 그루브 온 파이.." },
    { "groundfx", "그라운드 이펙트 (일본판)" },
    { "growl", "그라울 (세계판,개정판1)" },
    { "growla", "그라울 (세계판)" },
    { "growlp", "그라울 (세계판,시험판)" },
    { "growlu", "그라울 (미국판)" },
    { "grtesoro", "그란 테소로/ 플레이 2000" },
    { "grtwall", "만리장성 (V638C)" },
    { "grudge", "그루지 매치" },
    { "grudgei", "그루지 매치 (v00.90,이탈리아,로케이션테스트?)" },
    { "grudgep", "그루지 매치 (v00.80,시험판)" },
    { "gryzor", "그리저 (세트1)" },
    { "gryzor1", "그리저 (세트2)" },
    { "gryzora", "그리저 (세트2)" },
    { "gs4002", "셀렉션" },
    { "gs4002a", "셀렉션 (세트2)" },
    { "gseeker", "그리드 시커 - 프로젝트 스톰 해머 (버전1.3O)" },
    { "gseekerj", "그리드 시커 - 프로젝트 스톰 해머 (버전1.3J)" },
    { "gseekeru", "그리드 시커 - 프로젝트 스톰 해머 (버전1.3A)" },
    { "gslgr94j", "그레이트 슬러거 94 (일본판)" },
    { "gslgr94u", "그레이트 슬러거 94" },
    { "gslugrsj", "그레이트 슬러거 (일본판)" },
    { "gstream", "G 스트림 G2020" },
    { "gstrik2", "그랜드 스트라이커 2" },
    { "gstrik2j", "그랜드 스트라이커 2 (일본판)" },
    { "gstriker", "그랜드 스트라이커" },
    { "gstrikera", "그랜드 스트라이커 (아메리카스)" },
    { "gstrikerj", "그랜드 스트라이커 (일본판)" },
    { "gsword", "그레이트 소드맨" },
    { "gsword2", "그레이트 소드맨 (일본판)" },
    { "gt102b", "트리비아 (버전 1.02b)" },
    { "gt102c", "트리비아 (버전 1.02c)" },
    { "gt102c1", "트리비아 (버전1.02C 대체 문항 1)" },
    { "gt102c2", "트리비아 (버전1.02C 대체 문항 2)" },
    { "gt102c3", "트리비아 (버전1.02C 대체 문항 3)" },
    { "gt103", "트리비아 (버전 1.03)" },
    { "gt103a", "트리비아 (버전 1.03a)" },
    { "gt103a1", "트리비아 (버전1.03a)(대체1)" },
    { "gt103a2", "트리비아 (버전1.03a)(대체 2)" },
    { "gt103a3", "트리비아 (버전1.03a)(대체 3)" },
    { "gt103aa", "트리비아 (버전1.03a 대체 문항)" },
    { "gt103ab", "트리비아 (버전1.03a 대체 문항 2)" },
    { "gt103asx", "트리비아 (버전1.03a 섹스 문항)" },
    { "gt103asxa", "트리비아 (버전1.03a 섹스 문항,대체 개정 문항)" },
    { "gt2k", "골든 티 2K (v1.00)" },
    { "gt2kp100", "골든 티 2K (v1.00)(대체 프로텍션)" },
    { "gt2ks100", "골든 티 2K (v1.00S)" },
    { "gt2kt500", "골든 티 2K 토너먼트 (v5.00)" },
    { "gt3d", "골든 티 3D 골프 (v1.93N)" },
    { "gt3dl19", "골든 티 3D 골프 (v1.9L)" },
    { "gt3dl191", "골든 티 3D 골프 (v1.91L)" },
    { "gt3dl192", "골든 티 3D 골프 (v1.92L)" },
    { "gt3ds192", "골든 티 3D 골프 (v1.92S)" },
    { "gt3dt211", "골든 티 3D 골프 토너먼트 (v2.11)" },
    { "gt3dt231", "골든 티 3D 골프 토너먼트 (v2.31)" },
    { "gt3dv14", "골든 티 3D 골프 (v1.4)" },
    { "gt3dv15", "골든 티 3D 골프 (v1.5)" },
    { "gt3dv16", "골든 티 3D 골프 (v1.6)" },
    { "gt3dv17", "골든 티 3D 골프 (v1.7)" },
    { "gt3dv18", "골든 티 3D 골프 (v1.8)" },
    { "gt5", "트리비아 (버전 5.06)" },
    { "gt507uk", "트리비아 (UK 버전 5.07)" },
    { "gt97", "골든 티 97 (v1.30)" },
    { "gt97s121", "골든 티 97 (v1.21S)" },
    { "gt97t240", "골든 티 97 토너먼트 (v2.40)" },
    { "gt97t243", "골든 티 97 토너먼트 (v2.43)" },
    { "gt97v120", "골든 티 97 (v1.20)" },
    { "gt97v121", "골든 티 97 (v1.21)" },
    { "gt97v122", "골든 티 97 (v1.22)" },
    { "gt98", "골든 티 98 (v1.10)" },
    { "gt98c100", "골든 티 98 (v1.10C)" },
    { "gt98s100", "골든 티 98 (v1.00S)" },
    { "gt98t302", "골든 티 98 토너먼트 (v3.02)" },
    { "gt98t303", "골든 티 98 토너먼트 (v3.03)" },
    { "gt98v100", "골든 티 98 (v1.00)" },
    { "gt99", "골든 티 99 (v1.00)" },
    { "gt99s100", "골든 티 99 (v1.00S)" },
    { "gt99t400", "골든 티 99 토너먼트 (v4.00)" },
    { "gtclassc", "골든 티 클래식 (v1.00)" },
    { "gtclasscp", "골든 티 클래식 (v1.00)(대체 프로텍션)" },
    { "gtclasscs", "골든 티 클래식 (v1.00S)" },
    { "gtclassp", "골든 티 클래식 (v1.00) 대체" },
    { "gtcls100", "골든 티 클래식 (v1.00S)" },
    { "gtdiamond", "골든 티 다이아몬드 에디션 토너먼트 (v3.05T ELC)" },
    { "gteikob2", "은하제국의 역습 (해적판 세트2)" },
    { "gteikokb", "은하제국의 역습 (해적판 세트1)" },
    { "gteikoku", "은하제국의 역습" },
    { "gteikokub", "은하제국의 역습 (해적판 세트1)" },
    { "gteikokub2", "은하제국의 역습 (해적판 세트2)" },
    { "gteikokub3", "은하제국의 역습 (해적판 세트3)" },
    { "gtfore01", "골든 티 포레!" },
    { "gtfore02", "골든 티 포레! 2002" },
    { "gtfore03", "골든 티 포레! 2003" },
    { "gtfore03a", "골든 티 포레! 2003" },
    { "gtfore04", "골든 티 포레! 2004 엑스트라" },
    { "gtfore04a", "골든 티 포레! 2004 엑스트라" },
    { "gtfore05", "골든 티 포레! 2005 엑스트라" },
    { "gtfore05a", "골든 티 포레! 2005 엑스트라" },
    { "gtfore05b", "골든 티 포레! 2005 엑스트라" },
    { "gtfore05c", "골든 티 포레! 2005 엑스트라" },
    { "gtfore06", "골든 티 포레! 2006 컴플리트" },
    { "gtfrk10m", "기타 프릭스 10th 믹스" },
    { "gtfrk10ma", "기타 프릭스 10th 믹스" },
    { "gtfrk11m", "기타 프릭스 11th 믹스" },
    { "gtfrk3ma", "기타 프릭스 3rd 믹스 (GE949 v.JAB)" },
    { "gtfrk3mb", "기타 프릭스 3rd 믹스 - 보안 카세트 버전업" },
    { "gtg", "골든 티 골프" },
    { "gtg2", "골든 티 골프 2" },
    { "gtg2j", "골든 티 골프 2 (조이스틱,V1.0)" },
    { "gtg2t", "골든 티 골프 2 (트랙볼,V1.1)" },
    { "gtgj31", "골든 티 골프 (조이스틱,v3.1)" },
    { "gtgt", "골든 티 골프 (트랙볼,v1.0)" },
    { "gtgt10", "골든 티 골프 (트랙볼,V1.0)" },
    { "gtgt20", "골든 티 골프 (트랙볼,V2.0)" },
    { "gtgt21", "골든 티 골프 (트랙볼,V2.1)" },
    { "gticlub", "GTI 클럽" },
    { "gticlub2", "GTI 클럽 2" },
    { "gticlub2ea", "GTI 클럽 2 (버전EAA)" },
    { "gticluba", "GTI 클럽 (버전AAA)" },
    { "gticlubj", "GTI 클럽 (버전JAA)" },
    { "gticlubu", "GTI 클럽 (버전UAA)" },
    { "gtipoker", "GTI 포커" },
    { "gtmr", "1000 미글리아:그레이트 1000마일 랠리 (대만판)" },
    { "gtmr2", "마일 미글리아 2: 그레이트 1000마일 랠리" },
    { "gtmr2a", "마일 미글리아 2: 그레이트 1000마일 랠리" },
    { "gtmr2u", "그레이트 1000마일 랠리 2 USA" },
    { "gtmr2ua", "그레이트 1000마일 랠리 2 USA" },
    { "gtmra", "1000 미글리아:그레이트 1000마일 랠리" },
    { "gtmrb", "1000 미글리아:그레이트 1000마일 랠리" },
    { "gtmre", "그레이트 1000마일 랠리: 이볼루션 모델!!!" },
    { "gtmro", "1000 미글리아:그레이트 1000마일 랠리" },
    { "gtmrusa", "그레이트 1000마일 랠리 (미국판)" },
    { "gtrfrk2m", "기타 프릭스 2nd 믹스 버전1.01" },
    { "gtrfrk2ma", "기타 프릭스 2nd 믹스" },
    { "gtrfrk2maa", "기타 프릭스 2nd 믹스" },
    { "gtrfrk2mja", "기타 프릭스 2nd 믹스" },
    { "gtrfrk2mka", "기타 프릭스 2nd 믹스" },
    { "gtrfrk2ml1", "기타 프릭스 2nd 믹스 링크 킷1" },
    { "gtrfrk2ml2", "기타 프릭스 2nd 믹스 링크 킷2" },
    { "gtrfrk2mua", "기타 프릭스 2nd 믹스" },
    { "gtrfrk3m", "기타 프릭스 3rd 믹스" },
    { "gtrfrk4m", "기타 프릭스 4th 믹스" },
    { "gtrfrk5m", "기타 프릭스 5th 믹스" },
    { "gtrfrk6m", "기타 프릭스 6th 믹스" },
    { "gtrfrk7m", "기타 프릭스 7th 믹스" },
    { "gtrfrks", "기타 프릭스 버전1.01" },
    { "gtrfrksa", "기타 프릭스 버전1.01(GQ886 v.AAC)" },
    { "gtrfrksaa", "기타 프릭스 (GQ886 버전AAA)" },
    { "gtrfrksac", "기타 프릭스 (GQ886 버전AAC)" },
    { "gtrfrksc", "기타 프릭스 (GQ886 버전EAC)" },
    { "gtrfrksea", "기타 프릭스 (GQ886 버전EAA)" },
    { "gtrfrksj", "기타 프릭스 버전1.01(GQ886 v.JAC)" },
    { "gtrfrksja", "기타 프릭스 (GQ886 버전JAA)" },
    { "gtrfrksjc", "기타 프릭스 (GQ886 버전JAC)" },
    { "gtrfrksu", "기타 프릭스 버전1.01(GQ886 v.UAC)" },
    { "gtrfrksua", "기타 프릭스 (GQ886 버전UAA)" },
    { "gtrfrksuc", "기타 프릭스 (GQ886 버전UAC)" },
    { "gtroyal", "골든 티 로얄 에디션 토너먼트 (v4.02T EDM)" },
    { "gtsers1", "트리비아 (질문시리즈1)" },
    { "gtsers10", "트리비아 (질문 시리즈 10)" },
    { "gtsers11", "트리비아 (질문 시리즈 11)" },
    { "gtsers11a", "트리비아 (질문 시리즈 11)" },
    { "gtsers11b", "트리비아 (질문 시리즈 11)" },
    { "gtsers12", "트리비아 (질문 시리즈 12)" },
    { "gtsers12a", "트리비아 (질문 시리즈 12)" },
    { "gtsers14", "트리비아 (질문 시리즈 14)" },
    { "gtsers14a", "트리비아 (질문 시리즈 14)" },
    { "gtsers15", "트리비아 (질문 시리즈 15)" },
    { "gtsers18", "트리비아 (질문 시리즈 18)" },
    { "gtsers2", "트리비아 (질문 시리즈 2)" },
    { "gtsers3", "트리비아 (질문 시리즈 3)" },
    { "gtsers4", "트리비아 (질문 시리즈 4)" },
    { "gtsers5", "트리비아 (질문 시리즈 5)" },
    { "gtsers7", "트리비아 (질문 시리즈 7)" },
    { "gtsers7a", "트리비아 (질문 시리즈 7)" },
    { "gtsers8", "트리비아 (질문 시리즈 8)" },
    { "gtsers8a", "트리비아 (질문 시리즈 8)" },
    { "gtsers9", "트리비아 (질문 시리즈 9)" },
    { "gtsersa", "트리비아 (대체 개정판질문 세트1)" },
    { "gtsersb", "트리비아 (대체 개정판질문 세트2)" },
    { "gtstarb1", "겟 스타 (해적판 세트1)" },
    { "gtstarb2", "겟 스타 (해적판 세트2)" },
    { "gtstarba", "겟 스타 (해적판,세트2)" },
    { "gtsuprem", "골든 티 슈프림 에디션 토너먼트 (v5.10)" },
    { "gtsupreme", "골든 티 슈프림 에디션 토너먼트 (v5.10T ELC S)" },
    { "guab", "기브 어스 어 브레이크" },
    { "guab21", "기브 어스 어 브레이크 (21st 에디션)" },
    { "guab3a", "기브 어스 어 브레이크 (3rd 에디션 대체)" },
    { "guab4", "기브 어스 어 브레이크 (4th 에디션)" },
    { "guab43", "기브 어스 어 브레이크 (43rd 에디션)" },
    { "guab6", "기브 어스 어 브레이크 (6th 에디션)" },
    { "guab6a", "기브 어스 어 브레이크 (6th 에디션 대체)" },
    { "guab7", "기브 어스 어 브레이크 (7th 에디션)" },
    { "guardian", "가디언스 오브 더 후드" },
    { "guchokip", "구, 초키, 파" },
    { "guiness", "힘과 기술/ 기네스 (일본판)" },
    { "gulfstr2", "걸프 스톰 (미디어 쇼지)" },
    { "gulfstrm", "걸프 스톰 (세트1)" },
    { "gulfstrma", "걸프 스톰 (세트2)" },
    { "gulfstrmb", "걸프 스톰 (세트3)" },
    { "gulfstrmk", "걸프 스톰 (한국판)" },
    { "gulfstrmm", "걸프 스톰 (미디어 쇼지)" },
    { "gulfwar2", "걸프 워 2 (세트1)" },
    { "gulfwar2a", "걸프 워 2 (세트2)" },
    { "gulunpa", "구룬파!" },
    { "gumbo", "검보" },
    { "gunbalina", "건바닐라" },
    { "gunball", "니트로 볼/건 볼 (일본판)" },
    { "gunbarl", "건발 (일본판,GNB4/버전A)" },
    { "gunbarla", "건발 (일본판,GNB1/버전A)" },
    { "gunbird", "건버드 (세계판)" },
    { "gunbird2", "건버드 2 (세트1)" },
    { "gunbird2a", "건버드 2 (세트2)" },
    { "gunbirdj", "건버드 (일본판)" },
    { "gunbirdk", "건버드 (한국판)" },
    { "gunbirdka", "건버드 (한글)" },
    { "gunblade", "건블레이드 NY" },
    { "gunbulet", "포인트 블랭크/ 건 불릿 (일본판)" },
    { "gunbuletj", "포인트 블랭크/ 건 불릿 (일본판,GN1)" },
    { "gunbuletw", "포인트 블랭크/ 건 불릿 (세계판,GN3 개정판B)" },
    { "gunbustr", "건버스터 (세계판)" },
    { "gunbustrj", "건버스터 (일본판)" },
    { "gunbustru", "건버스터 (미국판)" },
    { "gunchamp", "건 챔프" },
    { "gunchamps", "건 챔프 (신형,슈퍼샷 하드웨어)" },
    { "gundamex", "기동전사 건담 EX 리뷰" },
    { "gundamos", "건담 배틀 오퍼레이팅 시뮬레이터" },
    { "gundeala", "건 딜러 (세트2)" },
    { "gundealr", "건 딜러" },
    { "gundealra", "건 딜러 (대체 카드 세트)" },
    { "gundealrbl", "건 딜러 (얌!얌!?하드웨어,세트1)" },
    { "gundealrbl2", "건 딜러 (얌!얌!?하드웨어,세트1)" },
    { "gundealrt", "건 딜러 (한국판)" },
    { "gundealt", "건 딜러 (테크모)" },
    { "gundhara", "건드하라" },
    { "gundharac", "건드하라 (중국 해적판)" },
    { "gundl94", "건 딜러 94" },
    { "gundmct", "기동전사 건담: 연방 대 지온" },
    { "gundmgd", "기동전사 건담: 연방 대 지온 (GDL-0001)" },
    { "gundmxgd", "기동전사 건담: 연방 대 지온 DX (GDL-0006)" },
    { "gunfight", "건 파이트" },
    { "gunfighto", "건 파이트 (세트2)" },
    { "gunforc2", "건포스 2 (미국판)" },
    { "gunforce", "건포스 (세계판)" },
    { "gunforcej", "건포스 (일본판)" },
    { "gunforceu", "건포스 (미국판)" },
    { "gunforcj", "건포스 (일본판)" },
    { "gunforcu", "건포스 (미국판)" },
    { "gunfronj", "건 프론티어 (일본판)" },
    { "gunfront", "건 프론티어 (세계판)" },
    { "gunfrontj", "건 프론티어 (일본판)" },
    { "gunhohki", "미스틱 라이더스/ 마법경비대 건 호키 (일본판)" },
    { "gunkids", "하야우치 건 키즈" },
    { "gunlock", "건락/ 래이 포스 (버전2.3O)" },
    { "gunlocko", "건락/ 래이 포스 (버전2.0O)" },
    { "gunmast", "건 마스터" },
    { "gunnail", "건네일" },
    { "gunnailb", "건네일 (해적판)" },
    { "gunnailp", "건네일 (로케이션 테스트)" },
    { "gunpey", "건피" },
    { "gunsmoka", "건 스모크 (미국판 세트2)" },
    { "gunsmoke", "건 스모크 (세계판)" },
    { "gunsmokeb", "건 스모크 (세계판)(해적판)" },
    { "gunsmokeg", "건 스모크 (독일판)" },
    { "gunsmokej", "건 스모크 (일본판)" },
    { "gunsmokeu", "건 스모크 (미국,캐나다)" },
    { "gunsmokeua", "건 스모크 (미국,캐나다)" },
    { "gunsmokeub", "건 스모크 (미국,캐나다,세트1)" },
    { "gunsmokeuc", "건 스모크 (미국,캐나다,세트2)" },
    { "gunsmokj", "건 스모크 (일본판)" },
    { "gunsmoku", "건 스모크 (미국판 세트1)" },
    { "gunsmrom", "건 스모크 (미국판 세트1)" },
    { "gunsur2", "건 서바이버 2 바이오 하자드 코드 베로니카 (세계판)" },
    { "gunsur2j", "건 서바이버 2 바이오 하자드 코드 베로니카 (일본판)" },
    { "gunwars", "건맨 워즈" },
    { "gururin", "구루링" },
    { "gussun", "리스키 챌린지/ 굿슨 오요요 (일본판)" },
    { "gutangtn", "로코 모션/ 구땅 가땅" },
    { "gutangtns", "로코 모션/ 구땅 가땅 (세가 라이선스)" },
    { "guts", "것츠 앤 글로리" },
    { "gutsn", "거츠앤 (일본판)" },
    { "guttangt", "로코 모션/ 구땅 가땅 (갤럭시안 하드웨어 해적판)" },
    { "guttangts3", "로코 모션/ 구땅 가땅 (갤럭시안 하드웨어 Sede 3 해적판)" },
    { "guwange", "구완게 (일본판,마스터 버전)" },
    { "guwanges", "구완게 (일본판,특별판)" },
    { "guzzler", "거즐러" },
    { "guzzlers", "거즐러 (스위머 컨버전)" },
    { "gwar", "게릴라 워 (미국판)" },
    { "gwara", "게릴라 워 (버전1)" },
    { "gwarab", "게릴라 워" },
    { "gwarb", "게릴라 워 (조이스틱 핵 해적판)" },
    { "gwarj", "게릴라 워/ 게바라 (일본판)" },
    { "gwarrior", "갤럭틱 워리어즈" },
    { "gwing2", "기가 윙 2" },
    { "gwinga", "기가 윙 (아시아판)" },
    { "gwingj", "기가 윙 (일본판)" },
    { "gwingjd", "기가 윙 (일본판,피닉스에디션)" },
    { "gypsyjug", "집시 저글러" },
    { "gyrodinc", "자이로다인 (크럭스)" },
    { "gyrodine", "자이로다인" },
    { "gyrodinet", "자이로다인 (타이토 라이센스)" },
    { "gyruss", "자이러스 (코나미)" },
    { "gyrussb", "자이러스" },
    { "gyrussce", "자이러스 (센추리)" },
};

const size_t lookup_g_count = A_SIZE(lookup_g_table);

const char *lookup_g(const char *name) {
    if (!name) return NULL;
    for (size_t i = 0; i < lookup_g_count; i++) {
        if (strcmp(lookup_g_table[i].name, name) == 0) {
            return lookup_g_table[i].value;
        }
    }
    return NULL;
}

const char *r_lookup_g(const char *value) {
    if (!value) return NULL;
    for (size_t i = 0; i < lookup_g_count; i++) {
        if (strstr(lookup_g_table[i].value, value)) {
            return lookup_g_table[i].name;
        }
    }
    return NULL;
}

void lookup_g_multi(const char *term, void (*emit)(const char *name, const char *value, void *udata), void *udata) {
    if (!term) return;
    for (size_t i = 0; i < lookup_g_count; i++) {
        if (strcasestr(lookup_g_table[i].name, term))
            emit(lookup_g_table[i].name, lookup_g_table[i].value, udata);
    }
}

void r_lookup_g_multi(const char *term, void (*emit)(const char *name, const char *value, void *udata), void *udata) {
    if (!term) return;
    for (size_t i = 0; i < lookup_g_count; i++) {
        if (strcasestr(lookup_g_table[i].value, term))
            emit(lookup_g_table[i].name, lookup_g_table[i].value, udata);
    }
}
