#include <string.h>
#include "../common/common.h"
#include "lookup.h"

const LookupName lookup_n_table[] = {
    { "nagano98", "나가노 동계 올림픽 98" },
    { "naganoj", "하이퍼 올림픽 인 나가노" },
    { "nam1975", "남-1975" },
    { "namenayo", "무시하지마" },
    { "nametune", "네임 댓 튠" },
    { "nametune2", "네임 댓 튠 (3-23-86)" },
    { "nametunea", "네임 댓 튠" },
    { "naname", "나나메 데 매직" },
    { "narc", "나크 (개정판7.00)" },
    { "narc1", "나크 (개정판1.80)" },
    { "narc2", "나크 (개정판2.00)" },
    { "narc3", "나크 (개정판3.20)" },
    { "narc4", "나크 (개정판4.00)" },
    { "narc6", "나크 (개정판6.00)" },
    { "nastar", "라스탄 사가 2/ 네스타 (세계판)" },
    { "nastarw", "네스타 워리어 (미국판)" },
    { "natodef", "나토 디펜스" },
    { "natodefa", "나토 디펜스 (대체 미로)" },
    { "natsuiro", "여름빛 마작 (일본판)" },
    { "naughtya", "너티 보이" },
    { "naughtyb", "너티 보이" },
    { "naughtyba", "너티 보이 (해적판,세트1)" },
    { "naughtybb", "너티 보이 (해적판,세트2)" },
    { "naughtybc", "너티 보이 (시네마트로닉스)" },
    { "naughtyc", "너티 보이 (시네마트로닉스)" },
    { "navalone", "나바론" },
    { "navarone", "나바론" },
    { "nbaatw", "NBA 올 더 웨이" },
    { "nbaatwa", "NBA 올 더 웨이 (버전EAA)" },
    { "nbagold", "스포츠스테이션: NBA 쇼타임 NBA온 NBC 골드에디션/ NFL 블리츠 2000 골드에디션" },
    { "nbahangt", "NBA 행타임 (개정판L1.3)" },
    { "nbahangtl11", "NBA 행타임 (개정판L1.1)" },
    { "nbahangtl12", "NBA 행타임 (개정판L1.2)" },
    { "nbahangtm11", "NBA 행타임 (개정판M1.1)" },
    { "nbahangtm12", "NBA 행타임 (개정판M1.2)" },
    { "nbahangtm13", "NBA 행타임 (개정판M1.3)" },
    { "nbajam", "NBA 잼 (개정판3.01)" },
    { "nbajamex", "NBA 잼 익스트림" },
    { "nbajamexa", "NBA 잼 익스트림 (v1.04)" },
    { "nbajamp1", "NBA 잼 (시험 v1.01)" },
    { "nbajamp2", "NBA 잼 (시험 v2.00)" },
    { "nbajamr1", "NBA 잼 (개정판1.00)" },
    { "nbajamr2", "NBA 잼 (개정판2.00)" },
    { "nbajamre", "NBA 잼 리와인드 (핵,v1.1)" },
    { "nbajamt1", "NBA 잼 TE (개정판1.0)" },
    { "nbajamt2", "NBA 잼 TE (개정판2.0)" },
    { "nbajamt3", "NBA 잼 TE (개정판3.0)" },
    { "nbajamte", "NBA 잼 TE (개정판4.0)" },
    { "nbajamte1", "NBA 잼 TE (개정판1.0)" },
    { "nbajamte2", "NBA 잼 TE (개정판2.1)" },
    { "nbajamte2a", "NBA 잼 TE (개정판2.0)" },
    { "nbajamte3", "NBA 잼 TE (개정판3.0)" },
    { "nbajamte3a", "NBA 잼 TE (개정판3.0)" },
    { "nbajamte4", "NBA 잼 TE (개정판4.0)" },
    { "nbajamten", "NBA 잼 TE (Nani에디션,개정판5.2,시험판)" },
    { "nbajamtep2", "NBA 잼 TE (시험 2.00)" },
    { "nbajamtr", "NBA 잼 TE 리와인드 버전1.1" },
    { "nbamaxht", "NBA 맥시멈 행타임" },
    { "nbamht", "NBA 맥시멈 행타임 (버전L1.03)" },
    { "nbamht1", "NBA 맥시멈 행타임 (개정판1.0)" },
    { "nbamhtl10", "NBA 맥시멈 행타임 (버전L1.0)" },
    { "nbamhtm10", "NBA 맥시멈 행타임 (버전M1.0)" },
    { "nbamhtp", "NBA 맥시멈 행타임 (버전L0.9)" },
    { "nbanfl", "NFL 블릿츠 2000" },
    { "nbapbp", "NBA 플레이 바이 플레이" },
    { "nbapbpa", "NBA 플레이 바이 플레이 (버전AAB)" },
    { "nbapbpaa", "NBA 플레이 바이 플레이 (버전AAA)" },
    { "nbapbpj", "NBA 플레이 바이 플레이 (버전JAB)" },
    { "nbapbpja", "NBA 플레이 바이 플레이 (버전JAA)" },
    { "nbapbpua", "NBA 플레이 바이 플레이 (버전UAA)" },
    { "nbashowt", "NBA쇼타임" },
    { "nbbat1v2", "닌자 베이스볼 배트맨 (1v2,핵)" },
    { "nbbat1v4", "닌자 베이스볼 배트맨 (1v4,핵)" },
    { "nbbat1v8", "닌자 베이스볼 배트맨 (1v8,핵)" },
    { "nbbatman", "닌자 베이스볼 배트맨 (세계판)" },
    { "nbbatmano", "닌자 베이스볼 배트맨 (원키판,핵)" },
    { "nbbatmanu", "닌자 베이스볼 배트맨 (미국판)" },
    { "nbbatmbh", "닌자 베이스볼 배트맨 (트랜스폼,핵)" },
    { "nbbatmx2", "닌자 베이스볼 배트맨 (X2,핵)" },
    { "nblktiger", "네오 블랙 타이거 (HB,데모)" },
    { "nc96", "뉴 체리 96 스페셜 (v3.63)" },
    { "nc96a", "뉴 체리 96 스페셜 (v3.62)" },
    { "nc96b", "뉴 체리 96 스페셜 (v3.61)" },
    { "nc96c", "뉴 체리 96 스페셜 (v3.54)" },
    { "nc96d", "뉴 체리 96 스페셜 (v3.53)" },
    { "nc96e", "뉴 체리 96 스페셜 (v3.40)" },
    { "nc96f", "뉴 체리 96 스페셜 (v3.62)" },
    { "nc96g", "뉴 체리 96 (v3.1)" },
    { "nc96h", "뉴 체리 96 (v3.1C)" },
    { "nc96i", "뉴 체리 96 스페셜 (v3.55)" },
    { "nc96j", "뉴 체리 96 스페셜 (v3.61)" },
    { "nc96k", "뉴 체리 96 스페셜 (v3.51)" },
    { "nc96l", "뉴 체리 96 (v3.0)" },
    { "nc96txt", "뉴 체리 96 스페셜 (v1.32 Texas XT)" },
    { "ncb3", "체리 보너스 3" },
    { "nclubv3", "네임 클럽 ver. 3" },
    { "ncombat", "닌자 컴뱃" },
    { "ncombata", "닌자 컴뱃 (세트2)" },
    { "ncombath", "닌자 컴뱃" },
    { "ncommand", "닌자 코만도" },
    { "ncommandk", "닌자 코만도 (한글)" },
    { "ncv1", "남코 클래식 콜렉션 Vol.1" },
    { "ncv1j", "남코 클래식 콜렉션 Vol.1 (일본판,v1.00)" },
    { "ncv1j2", "남코 클래식 콜렉션 Vol.1 (일본판,v1.03)" },
    { "ncv2", "남코 클래식 콜렉션 Vol.2" },
    { "ncv2j", "남코 클래식 콜렉션 Vol.2 (일본판)" },
    { "ndxron10", "로얄 온 텐" },
    { "nebulbee", "네뷸러스 비" },
    { "nebulray", "네뷸러스 레이 (세계판,NR2)" },
    { "nebulrayj", "네뷸러스 레이 (일본판,NR1)" },
    { "nebulrayp", "네뷸러스 레이 (시험판)" },
    { "nebulryj", "네뷸러스 레이 (일본판)" },
    { "neckneck", "넥 앤 넥" },
    { "nekkyoku", "열도 종단 열국 마작사 - 동일본편" },
    { "nemesis", "그라디우스/ 네메시스 (롬 버전)" },
    { "nemesisuk", "그라디우스/ 네메시스 (세계판,ROM 버전)" },
    { "nemesuk", "그라디우스/ 네메시스 (세계판)" },
    { "nemo", "네모 (세계판)" },
    { "nemoj", "네모 (일본판)" },
    { "nemoja", "네모 (일본판)" },
    { "nemor1", "네모 (세계판)" },
    { "neo2048", "네오 2048 (HB)" },
    { "neo2500", "네오 2500 데모" },
    { "neo3ddmo", "네오지오 3D (HB,데모)" },
    { "neobattl", "SD건담 네오 배틀링 (일본판)" },
    { "neobombe", "네오 봄버맨" },
    { "neocstlv", "네오 캐슬배니아 (HB,데모)" },
    { "neocu98k", "네오지오컵 98-승리로 향하는 길 (한글)" },
    { "neocup98", "네오지오컵 98-승리로 향하는 길" },
    { "neocup98k", "네오지오컵 98-승리로 향하는 길 (한글)" },
    { "neodemo", "카오스 데모 (네오지오)" },
    { "neodrift", "네오 드리프트 아웃 - 뉴 테크놀러지" },
    { "neogalag", "갤러그 데모 (HB)" },
    { "neogalaga", "갤러그 데모 (HB,세트2)" },
    { "neomrdo", "네오 미스터 도!" },
    { "neonopon", "네오 노 파네퐁 (HB,베타)" },
    { "neopang", "네오 팡 (HB)" },
    { "neopong", "네오 퐁 (HB)" },
    { "neoponga", "네오 퐁 (HB,버전1.0)" },
    { "neoprimo", "프리모 (HB,데모)" },
    { "neotet", "네오지오 2인용 테트리스 (HB)" },
    { "neothndr", "네오 썬더 (HB)" },
    { "neotris", "네오트리스 (HB,프리베타2)" },
    { "neoww2", "WW2 아케이드 개발 프로젝트 (HB,데모)" },
    { "neptunp2", "넵튠스 펄 2" },
    { "neraidou", "네라이둘라" },
    { "neruton", "마작 네루톤 하이쿠지라단" },
    { "nerutona", "마작 네루톤 하이쿠지라단" },
    { "netchu02", "열츄 프로야구 2002" },
    { "nettoqc", "열답 퀴즈 챔피언" },
    { "netwars", "넷 워즈" },
    { "new2001", "뉴 2001" },
    { "newapunk", "뉴 아토믹 펑크 - 글로벌 퀘스트 (미국판)" },
    { "newfant", "뉴 판타지아 (1995 저작권)" },
    { "newfanta", "뉴 판타지아 (1994)" },
    { "newmcard", "뉴 매직 카드" },
    { "newpuc2", "뉴퍽2" },
    { "newpuc2b", "뉴퍽2" },
    { "newpuckx", "뉴 퍽 X" },
    { "news", "뉴스 (세트1)" },
    { "newsa", "뉴스 (세트2)" },
    { "newsin7", "뉴 신밧드 7" },
    { "newsin7a", "뉴 신밧드 7" },
    { "newtangl", "트로피컬 앤젤, 뉴" },
    { "newxpang", "뉴 크로스 팡" },
    { "newxpanga", "뉴 크로스 팡" },
    { "nextfase", "넥스트 페이즈" },
    { "nfb96", "뉴 후르츠 보너스 96 스페셜 에디션" },
    { "nfb96a", "뉴 후르츠 보너스 96 스페셜 에디션 (세트2)" },
    { "nfb96b", "뉴 후르츠 보너스 96 스페셜 에디션 (세트3)" },
    { "nfb96c", "뉴 후르츠 보너스 96 스페셜 에디션 (세트4)" },
    { "nfb96d", "뉴 후르츠 보너스 96" },
    { "nfb96e", "뉴 후르츠 보너스 96 스페셜 에디션" },
    { "nfb96f", "뉴 후르츠 보너스 96 스페셜 에디션" },
    { "nfb96g", "뉴 후르츠 보너스 96 스페셜 에디션" },
    { "nfb96h", "뉴 후르츠 보너스 96 스페셜 에디션" },
    { "nfb96i", "뉴 후르츠 보너스 96 스페셜 에디션" },
    { "nfb96j", "뉴 후르츠 보너스 96 스페셜 에디션" },
    { "nfb96k", "뉴 후르츠 보너스 96 스페셜 에디션" },
    { "nfb96l", "뉴 후르츠 보너스 96" },
    { "nfb96m", "뉴 후르츠 보너스 96" },
    { "nfb96se", "뉴 후르츠 보너스 96 스페셜 에디션 (해적판,세트1)" },
    { "nfb96sea", "뉴 후르츠 보너스 96 스페셜 에디션 (해적판,세트2)" },
    { "nfb96seb", "뉴 후르츠 보너스 96 스페셜 에디션 (해적판,세트3)" },
    { "nfb96sec", "뉴 후르츠 보너스 96 스페셜 에디션" },
    { "nfb96txt", "뉴 후르츠 보너스 96 스페셜 에디션 (세트5,Texas XT)" },
    { "nflclsfb", "NFL 클래식 풋볼" },
    { "nflfoot", "NFL 풋볼" },
    { "nfm", "뉴 후르츠 머신" },
    { "ngalsumr", "나이트 갈 섬머" },
    { "ngbc", "네오지오 배틀 콜리세움" },
    { "ngbcj", "네오지오 배틀 콜리세움 (일본판)" },
    { "ngcdtdd0", "네오지오CD 점프 앤 런 테크데모 데즈 2020 (HB)" },
    { "ngem2k", "NGEM2K (HB)" },
    { "ngfrog", "네오 프로그 피스트 (HB)" },
    { "ngftdemo", "NGF 투명도 데모 (HB)" },
    { "nghtstrj", "나이트 스트라이커 (일본판)" },
    { "nghtstru", "나이트 스트라이커 (미국판)" },
    { "ngmontst", "모니터 테스트 패턴 툴 (HB)" },
    { "ngold", "잭 포튼의 포커" },
    { "ngolda", "잭 포튼의 포커" },
    { "ngoldb", "잭 포튼의 포커" },
    { "ngpgal", "열혈 그랑프리 걸" },
    { "ngtbunny", "나이트 버니" },
    { "nhidctch", "틀린그림 찾기,뉴" },
    { "nhomerun", "불타라 프로야구 홈런" },
    { "nibbler", "니블러 (개정판9)" },
    { "nibbler6", "니블러 (개정판6)" },
    { "nibbler7", "니블러 (개정판7)" },
    { "nibbler8", "니블러 (개정판8)" },
    { "nibblera", "니블러 (개정판9,대체판 세트)" },
    { "nibblerb", "니블러 (세트3)" },
    { "nibblero", "니블러 (올림피아 - 개정판8)" },
    { "nibblerp", "니블러 (파이어니어 벌룬 컨버전- 개정판6)" },
    { "nicetsuk", "츠코미 요세이 기브스 나이스 츠코미" },
    { "nightgal", "나이트 갈" },
    { "nightlov", "나이트 러브" },
    { "nightmare", "나이트 매어" },
    { "nightrai", "나이트 래이드" },
    { "nightstr", "나이트 스트라이커 (세계판)" },
    { "nightstrj", "나이트 스트라이커 (일본판)" },
    { "nightstru", "나이트 스트라이커 (미국판)" },
    { "ninclown", "닌자 크라운스" },
    { "ninja", "닌자 (315-5102)" },
    { "ninjak", "닌자 키즈 (세계판)" },
    { "ninjak2a", "닌자 키드 2 (세트2)" },
    { "ninjak2b", "닌자 키드 2 (세트3)" },
    { "ninjakd2", "닌자 키드 2/ 닌자군 아수라의 장 (세트1)" },
    { "ninjakd2a", "닌자 키드 2/ 닌자군 아수라의 장 (세트2,해적판?)" },
    { "ninjakd2b", "닌자 키드 2/ 닌자군 아수라의 장 (세트3,해적판)" },
    { "ninjakd2c", "닌자 키드 2/ 닌자군 아수라의 장 (세트4)" },
    { "ninjakj", "닌자 키즈 (일본판)" },
    { "ninjaku", "닌자 키즈 (미국판)" },
    { "ninjakun", "닌자군 마성의 모험" },
    { "ninjamab", "닌자 마스터즈 - 패왕인법첩 (보스 핵)" },
    { "ninjamas", "닌자 마스터즈 - 패왕인법첩" },
    { "ninjamasha", "닌자 마스터즈 - 패왕인법첩 (플러스)" },
    { "ninjaslt", "닌자 어썰트 (세계판)" },
    { "ninjaslta", "닌자 어썰트 (아시아판)" },
    { "ninjasltj", "닌자 어썰트 (일본판)" },
    { "ninjasltu", "닌자 어썰트 (미국판)" },
    { "ninjaw", "닌자 워리어즈 (세계판,이후 버전)" },
    { "ninjaw1", "닌자 워리어즈 (세계판,초기 버전)" },
    { "ninjawj", "닌자 워리어즈 (일본판)" },
    { "ninjawu", "닌자 워리어즈 (미국판,롬스타 라이센스)" },
    { "ninjemak", "닌자회권/ 요마인법첩 (미국판)" },
    { "nitd", "나이트메어 인 더 다크" },
    { "nitdbl", "나이트메어 인 더 다크" },
    { "nitdn", "나이트메어 인 더 다크 (해독됨 C)" },
    { "nitdnd", "나이트메어 인 더 다크 (완전해독됨)" },
    { "nitedrvr", "나이트 드라이버" },
    { "nitrobal", "니트로 볼 (세계판,세트1)" },
    { "nitrobala", "니트로 볼 (세계판,세트2)" },
    { "nitrobalb", "니트로 볼 (세계판,세트3)" },
    { "niyanpai", "니얀페이" },
    { "njp60in1", "NJ 포켓 60합 핸드헬드 X 제로" },
    { "nkdodge", "열혈고교 피구부 (일본판)" },
    { "nkdodgeb", "열혈고교 피구부 (일본판,해적판)" },
    { "nkishusp", "마작 염력 SP" },
    { "nmaster", "메타모케스터/ 오니-닌자 마스터 (일본판)" },
    { "nmasterk", "메타모케스터/ 오니-닌자 마스터 (한글)" },
    { "nmg5", "멀티 5/ 뉴 멀티게임 5 (세트1)" },
    { "nmg5a", "멀티 5/ 뉴 멀티게임 5 (세트2)" },
    { "nmg5e", "멀티 5/ 뉴 멀티게임 5 (세트3,초기)" },
    { "nmouse", "너티 마우스 (세트1)" },
    { "nmouseb", "너티 마우스 (세트2)" },
    { "nmsengen", "열혈 마작 선언! 애프터 5" },
    { "nndmseal", "무엇이든 씰 위원회" },
    { "nndmseal11", "무엇이든 씰 위원회" },
    { "nndmseala", "무엇이든 씰 위원회" },
    { "nndmsealb", "무엇이든 씰 위원회" },
    { "nndmsealc", "무엇이든 씰 위원회" },
    { "noahsark", "노아의 방주" },
    { "nob", "노보랑카" },
    { "nobb", "노보랑카 (일본판,해적판)" },
    { "noboranb", "노보랑카" },
    { "nomnlnd", "노 맨즈 랜드" },
    { "nomnlndg", "노 맨즈 랜드 (고티브)" },
    { "noraut3a", "노라웃 조커 포커" },
    { "noraut3b", "노라웃 조커 포커" },
    { "norautdx", "노라웃 디럭스 포커" },
    { "norautjo", "노라웃 조커 포커" },
    { "norautjp", "노라웃 조커 포커 (대체)" },
    { "norautp", "노라웃 포커" },
    { "norautpl", "노라웃 조커 포커" },
    { "norautpn", "노라웃 디럭스 포커" },
    { "norautra", "노라웃 레드 핫 조커 포커" },
    { "norautrh", "노라웃 레드 핫 조커 포커" },
    { "norautu", "노라웃 포커" },
    { "norautua", "노라웃 미확인 세트1" },
    { "norautub", "노라웃 미확인 세트2" },
    { "nost", "노스트라다무스" },
    { "nostj", "노스트라다무스 (일본판)" },
    { "nostk", "노스트라다무스 (한국판)" },
    { "nostromo", "노스트로모" },
    { "nouryoku", "두뇌능력 향상 위원회" },
    { "nouryokup", "두뇌능력 향상 위원회 (시험판)" },
    { "nov2001u", "노바 2001 (미국판)" },
    { "nova2001", "노바 2001 (일본판)" },
    { "nova2001h", "노바 2001 (일본판,핵)" },
    { "nova2001u", "노바 2001 (미국판)" },
    { "npacmod", "퍽맨 (어려움)" },
    { "nprinces", "세가 닌자/ 닌자 공주 (64k 버전해적판)" },
    { "nprincesb", "세가 닌자/ 닌자 공주 (128k 버전해적판)" },
    { "nprinceso", "세가 닌자/ 닌자 공주 (128k 버전)" },
    { "nprincesu", "세가 닌자/ 닌자 공주 (64k 버전비암호화)" },
    { "nprincsb", "세가 닌자/ 닌자 공주 (128k 버전해적판)" },
    { "nprincso", "세가 닌자/ 닌자 공주 (128k 버전)" },
    { "nprincsu", "세가 닌자/ 닌자 공주 (64k 버전비암호화)" },
    { "nprobowl", "뉴 프로 볼링" },
    { "nrallyv", "뉴 랠리 X" },
    { "nrallyx", "뉴 랠리 X" },
    { "nrallyxb", "뉴 랠리 X" },
    { "nratechu", "노려라 츄" },
    { "ns8lines", "뉴 럭키 8 라인즈/ 뉴 슈퍼 8 라인즈" },
    { "ns8linesa", "뉴 럭키 8 라인즈/ 뉴 슈퍼 8 라인즈" },
    { "ns8linew", "뉴 럭키 8 라인즈/ 뉴 슈퍼 8 라인즈" },
    { "ns8linewa", "뉴 럭키 8 라인즈/ 뉴 슈퍼 8 라인즈" },
    { "nslashej", "나이트 슬래셔 (일본판 개정판1.2)" },
    { "nslasher", "나이트 슬래셔 (한국판 개정판1.3)" },
    { "nslasherj", "나이트 슬래셔 (일본판 개정판1.2)" },
    { "nslashers", "나이트 슬래셔 (해외판 개정판1.2)" },
    { "nslasheru", "나이트 슬래셔 (미국판 개정판1.2)" },
    { "nslashes", "나이트 슬래셔 (개정판1.2)" },
    { "nsmb", "네오 슈퍼 마리오 브로스 (HB,데모)" },
    { "nspirit", "닌자 스피리츠 (세계판)" },
    { "nspiritj", "닌자 스리피츠/ 최후의 인도 (일본판)" },
    { "nss_actr", "액트 라이저" },
    { "nss_adam", "아담스 패밀리" },
    { "nss_aten", "데이비드 크레인의 놀라운 테니스" },
    { "nss_con3", "혼두라 3 - 에일리언 워즈" },
    { "nss_fzer", "F-제로" },
    { "nss_lwep", "리썰 웨폰" },
    { "nss_ncaa", "NCAA 농구" },
    { "nss_rob3", "로보캅 3" },
    { "nss_skin", "스킨즈 게임" },
    { "nss_smw", "슈퍼 마리오 월드" },
    { "nss_ssoc", "슈퍼 사커" },
    { "nss_sten", "슈퍼 테니스" },
    { "nstocker", "나이트 스토커" },
    { "nstocker2", "나이트 스토커" },
    { "nstockera", "나이트 스토커" },
    { "nsub", "N서브" },
    { "ntcash", "엔티캐시" },
    { "ntopstar", "마작 노려라! 톱스타" },
    { "numanath", "뉴먼 애슬레틱스 (세계판)" },
    { "numanathj", "뉴먼 애슬레틱스 (일본판)" },
    { "numanatj", "뉴먼 애슬레틱스 (일본판)" },
    { "number1", "넘버 원" },
    { "number10", "넘버 10" },
    { "numbr10l", "넘버 10 (라틴)" },
    { "numcrash", "넘버 크래쉬" },
    { "nunchaku", "눈챠크군" },
    { "nvs_machrider", "Vs 마하 라이더" },
    { "nvs_machridera", "Vs 마하 라이더" },
    { "nvs_mightybj", "Vs 마이티 봄 잭" },
    { "nvs_platoon", "Vs 플래툰" },
    { "nwarr", "뱀파이어 헌터/ 나이트 워리어즈 - 다크스토커의 복수 (유럽판)" },
    { "nwarra", "뱀파이어 헌터/ 나이트 워리어즈 - 다크스토커의 복수 (아시아판)" },
    { "nwarrb", "뱀파이어 헌터/ 나이트 워리어즈 - 다크스토커의 복수 (브라질판)" },
    { "nwarrh", "뱀파이어 헌터/ 나이트 워리어즈 - 다크스토커의 복수 (히스패닉판)" },
    { "nwarru", "뱀파이어 헌터/ 나이트 워리어즈 - 다크스토커의 복수 (미국판)" },
    { "nwarrud", "뱀파이어 헌터/ 나이트 워리어즈 - 다크스토커의 복수 (미국판,피닉스에디션)" },
    { "nyanpani", "냥 냥 패닉 (일본판)" },
    { "nycaptor", "N.Y. 캡터" },
    { "nyjoker", "뉴욕 조커" },
    { "nyny", "뉴욕 뉴욕" },
    { "nynyg", "뉴욕 뉴욕 (고티브)" },
    { "nzerotea", "뉴 제로팀" },
    { "nzeroteam", "뉴 제로팀 (V33 type_B)" },
    { "nzeroteama", "뉴 제로팀 (V33 type_B,중국판)" },
    { "nzeroteamb", "뉴 제로팀 (V33 type_B,중국판)" },
    { "nzteamp", "뉴 제로팀 (플러스,핵)" },
};

const size_t lookup_n_count = A_SIZE(lookup_n_table);

const char *lookup_n(const char *name) {
    if (!name) return NULL;
    for (size_t i = 0; i < lookup_n_count; i++) {
        if (strcmp(lookup_n_table[i].name, name) == 0) {
            return lookup_n_table[i].value;
        }
    }
    return NULL;
}

const char *r_lookup_n(const char *value) {
    if (!value) return NULL;
    for (size_t i = 0; i < lookup_n_count; i++) {
        if (strstr(lookup_n_table[i].value, value)) {
            return lookup_n_table[i].name;
        }
    }
    return NULL;
}

void lookup_n_multi(const char *term, void (*emit)(const char *name, const char *value, void *udata), void *udata) {
    if (!term) return;
    for (size_t i = 0; i < lookup_n_count; i++) {
        if (strcasestr(lookup_n_table[i].name, term))
            emit(lookup_n_table[i].name, lookup_n_table[i].value, udata);
    }
}

void r_lookup_n_multi(const char *term, void (*emit)(const char *name, const char *value, void *udata), void *udata) {
    if (!term) return;
    for (size_t i = 0; i < lookup_n_count; i++) {
        if (strcasestr(lookup_n_table[i].value, term))
            emit(lookup_n_table[i].name, lookup_n_table[i].value, udata);
    }
}
