#include <string.h>
#include "../common/common.h"
#include "lookup.h"

const LookupName lookup_v_table[] = {
    { "v4dealem", "딜럼" },
    { "valkyrie", "발키리의 전설 (일본판)" },
    { "valtric", "발트릭" },
    { "vamphalf", "뱀프 x 1/2 (유럽판,버전1.1)" },
    { "vamphalfk", "뱀프 x 1/2 (한국판,버전1.1)" },
    { "vamphalfr1", "뱀프 x 1/2 (유럽판,버전1.0)" },
    { "vampire", "뱀파이어" },
    { "vampj", "뱀파이어/ 다크스토커즈 - 나이트 워리어즈 (일본판)" },
    { "vampja", "뱀파이어/ 다크스토커즈 - 나이트 워리어즈 (일본판,대체)" },
    { "vampjbh", "뱀파이어/ 다크 스토커즈 - 나이트 워리어즈 (히든 캐릭터, 핵)" },
    { "vampjh", "뱀파이어/ 다크스토커즈 - 나이트 워리어즈 (일본판,히든 핵)" },
    { "vampjr1", "뱀파이어/ 다크스토커즈 - 나이트 워리어즈 (일본판)" },
    { "vandyja2", "반다이크 (세트1)" },
    { "vandyjal", "반다이크 (세트1)" },
    { "vandyke", "반다이크 (일본판)" },
    { "vandykeb", "반다이크" },
    { "vandykejal", "반다이크 (세트1)" },
    { "vandykejal2", "반다이크 (세트1)" },
    { "vangrd2", "뱅가드 2" },
    { "vangrdce", "뱅가드 (센추리)" },
    { "vanguard", "뱅가드 (SNK)" },
    { "vanguardc", "뱅가드 (센추리)" },
    { "vanguardg", "뱅가드 (독일판)" },
    { "vanguardj", "뱅가드 (일본판)" },
    { "vanguarj", "뱅가드 (일본판)" },
    { "vanilla", "마작 바닐라 신드롬" },
    { "vanvan", "반반 카" },
    { "vanvanb", "반반 카 (세트3)" },
    { "vanvank", "반반 카 (카라테코)" },
    { "vanvans", "반반 카 (산리츠)" },
    { "vaportra", "공아/ 베이퍼 트레일-하이퍼 오펜스 포메이션 (세계판 개정판1)" },
    { "vaportra3", "공아/ 베이퍼 트레일-하이퍼 오펜스 포메이션 (세계판 개정판3)" },
    { "vaportrau", "공아/ 베이퍼 트레일-하이퍼 오펜스 포메이션 (미국판)" },
    { "vaportrp", "베이퍼 TRX (시험판)" },
    { "vaportru", "공아/ 베이퍼 트레일-하이퍼 오펜스 포메이션 (미국판)" },
    { "vaportrx", "베이퍼 TRX" },
    { "vaportrxp", "베이퍼 TRX (시험판)" },
    { "varth", "바스 - 오퍼레이션 썬더스톰 (기타)" },
    { "varthb", "바스 - 오퍼레이션 썬더스톰 (해적판,기타)" },
    { "varthb2", "바스 - 오퍼레이션 썬더스톰 (해적판,기타)" },
    { "varthj", "바스 - 오퍼레이션 썬더스톰 (일본판)" },
    { "varthjr", "바스 - 오퍼레이션 썬더스톰 (일본판,재판)" },
    { "varthr1", "바스 - 오퍼레이션 썬더스톰 (기타)" },
    { "varthu", "바스 - 오퍼레이션 썬더스톰 (미국판)" },
    { "vasara", "바사라" },
    { "vasara2", "바사라 2 (세트1)" },
    { "vasara2a", "바사라 2 (세트2)" },
    { "vastar", "바스타 (세트1)" },
    { "vastar2", "바스타 (세트2)" },
    { "vastar3", "바스타 (세트3)" },
    { "vastar4", "바스타 (세트4)" },
    { "vathlete", "버추어 애슬래틱스 (GDS-0019)" },
    { "vathletep", "버추어 애슬래틱스 (시험판)" },
    { "vautour", "보투어 (8085A CPU)" },
    { "vautour2", "보투어 (세트2)" },
    { "vautourz", "보투어 (Z80 CPU)" },
    { "vautourza", "보투어 (Z80 CPU,싱글 PROM)" },
    { "vball", "U.S. 챔피언쉽 비치발리볼 (미국판)" },
    { "vball2pj", "U.S. 챔피언쉽 비치발리볼 (일본판)" },
    { "vball2pjb", "U.S. 챔피언쉽 비치발리볼 (일본판 세트 해적판)" },
    { "vballb", "U.S. 챔피언쉽 비치발리볼 (미국판 세트 해적판)" },
    { "vblokbrk", "VS 블럭 브레이커 (유럽판)" },
    { "vblokbrka", "VS 블럭 브레이커 (아시아판)" },
    { "vbowl", "버추어 볼링" },
    { "vbowlhk", "버추어 볼링" },
    { "vbowlj", "버추어 볼링 (일본판,V100JCM)" },
    { "vbrakout", "벡터 브레이크아웃" },
    { "vcarn", "비디오 카니발 1999/ 슈퍼 로얄 카드" },
    { "vcircle", "비셔스 서클" },
    { "vcombat", "버추얼 컴뱃" },
    { "vcop", "버추어 캅" },
    { "vcop2", "버추어 캅 2" },
    { "vcop3", "버추어 캅 3" },
    { "vcopa", "버추어 캅" },
    { "vega", "베가" },
    { "vegasfst", "로얄 베가스 조커 카드 (빠른 딜)" },
    { "vegasfte", "로얄 베가스 조커 카드 (빠른 딜,영어)" },
    { "vegasmil", "로얄 베가스 조커 카드 (빠른 딜,마일)" },
    { "vegasslw", "로얄 베가스 조커 카드" },
    { "vendet2p", "벤데타 (세계판 2인용 W)" },
    { "vendetao", "벤데타 (세계판 4인용 R)" },
    { "vendetas", "벤데타 (아시아판 2인용 U)" },
    { "vendett2", "벤데타 (아시아판 세트2)" },
    { "vendetta", "벤데타 (세계판,4인용 버전T)" },
    { "vendetta2p", "벤데타 (세계판 2인용 W)" },
    { "vendetta2pd", "벤데타 (아시아판,2인용 D)" },
    { "vendetta2peba", "벤데타 (세계판,2인용 EB-A)" },
    { "vendetta2pp", "벤데타/ 크라임 파이터즈 2 (일본판,2인용 P)" },
    { "vendetta2pu", "벤데타 (아시아판,2인용 U)" },
    { "vendetta2pun", "벤데타 (세계판,2인 버전?)" },
    { "vendetta2pw", "벤데타 (세계판,2인용 W)" },
    { "vendettaj", "벤데타/ 크라임 파이터즈 2 (일본판 2인용 P)" },
    { "vendettan", "벤데타/ 크라임 파이터즈 2 (일본판,4인용 버전. N)" },
    { "vendettar", "벤데타 (미국판,4인용 R)" },
    { "vendettaun", "벤데타" },
    { "vendettaz", "벤데타 (아시아판,4인용 Z)" },
    { "vendettj", "벤데타/ 크라임 파이터즈 2 (일본판 2인용 P)" },
    { "vendtaso", "벤데타 (아시아판 2인용 D)" },
    { "venom", "베놈 & 스파이더맨" },
    { "venture", "벤처" },
    { "venture2", "벤처 (버전5 세트2)" },
    { "venture4", "벤처 (버전4)" },
    { "venture5a", "벤처" },
    { "venture5b", "벤처" },
    { "venus", "비너스" },
    { "verbena", "버베나" },
    { "version4", "버전4" },
    { "vf", "버추어 파이터" },
    { "vf2", "버추어 파이터 2" },
    { "vf2a", "버추어 파이터 2 (개정판A)" },
    { "vf2b", "버추어 파이터 2 (개정판B)" },
    { "vf2o", "버추어 파이터 2" },
    { "vf3", "버추어 파이터 3" },
    { "vf3a", "버추어 파이터 3 (개정판A)" },
    { "vf3tb", "버추어 파이터 3 팀 배틀" },
    { "vf4", "버추어 파이터 4" },
    { "vf4b", "버추어 파이터 4 (개정판B)(GDS-0012B)" },
    { "vf4c", "버추어 파이터 4 (개정판C)(GDS-0012C)" },
    { "vf4cart", "버추어 파이터 4 (세계판)" },
    { "vf4evo", "버추어 파이터 4 에볼루션" },
    { "vf4evoa", "버추어 파이터 4 에볼루션 (개정판A)(GDS-0024A)" },
    { "vf4evob", "버추어 파이터 4 에볼루션 (일본판)(GDS-0024B)" },
    { "vf4evoct", "버추어 파이터 4 에볼루션 (세계판)" },
    { "vf4o", "버추어 파이터 4 (GDS-0012)" },
    { "vf4tuned", "버추어 파이터 4 파이널 튠 (버전B)(GDS-0036F)" },
    { "vf4tuneda", "버추어 파이터 4 파이널 튠 (개정판A)(GDS-0036A)" },
    { "vf4tunedd", "버추어 파이터 4 파이널 튠 (버전A)(GDS-0036D)" },
    { "vfive", "그라인드 스토머/ V파이브 (일본판)" },
    { "vfkids", "버추어 파이터 키즈" },
    { "vformula", "버추어 포뮬러" },
    { "vfremix", "버추어 파이터 리믹스" },
    { "vfurlong", "넷 셀렉트 경마: 빅토리 퍼롱" },
    { "vgoalsca", "V 골 사커 (세트2)" },
    { "vgoalsoc", "V 골 사커" },
    { "vgoalsoca", "V 골 사커" },
    { "vgpoker", "베가스 포커" },
    { "vhunt2", "뱀파이어 헌터 2 - 다크스토커의 복수 (970929 일본판)" },
    { "vhunt2d", "뱀파이어 헌터 2 - 다크스토커의 복수 (일본판,피닉스에디션)" },
    { "vhunt2r1", "뱀파이어 헌터 2 - 다크스토커의 복수 (일본판)" },
    { "vhuntj", "뱀파이어 헌터 - 다크스토커의 복수 (일본판)" },
    { "vhuntjr1", "뱀파이어 헌터 - 다크스토커의 복수 (일본판)" },
    { "vhuntjr1s", "뱀파이어 헌터 - 다크스토커의 복수 (일본판 스톱버전)" },
    { "vhuntjr2", "뱀파이어 헌터 - 다크스토커의 복수 (일본판)" },
    { "victlap", "에이스 드라이버 - 빅토리 랩 (세계판,ADV2 버전B)" },
    { "victlapa", "에이스 드라이버 - 빅토리 랩 (세계판,ADV2)" },
    { "victlapj", "에이스 드라이버 - 빅토리 랩 (일본판,ADV1 버전C)" },
    { "victlapw", "에이스 드라이버 - 빅토리 랩 (세계판,ADV2)" },
    { "victnine", "빅토리우스 나인" },
    { "victor21", "빅터 21" },
    { "victor5", "G.E.A" },
    { "victorba", "빅터 바나나" },
    { "victory", "빅토리" },
    { "victoryc", "빅토리 (컴소프트)" },
    { "victorycb", "빅토리" },
    { "victroad", "빅토리 로드" },
    { "videight", "비디오 에이트" },
    { "video21", "비디오 21" },
    { "videocba", "비디오 코도바" },
    { "videodad", "비디오 다도" },
    { "videomat", "비디오매트 (폴란드 해적판)" },
    { "videopin", "비디오 핀볼" },
    { "videopina", "비디오 핀볼" },
    { "videopkr", "비디오 포커" },
    { "videtrna", "비디오트론 포커 (노말 컨트롤)" },
    { "videtron", "비디오트론 포커" },
    { "videtron2", "비디오트론 포커 (세트2)" },
    { "vidvince", "비디오 빈스와 게임 공장" },
    { "viewpoin", "뷰포인트" },
    { "viewpoinp", "뷰포인트 (시험판)" },
    { "vigilant", "비질란테 (세계판,개정판E)" },
    { "vigilanta", "비질란테 (세계판,개정판A)" },
    { "vigilantb", "비질란테 (미국판,개정판B)" },
    { "vigilantbl", "비질란테" },
    { "vigilantc", "비질란테 (세계판,개정판C)" },
    { "vigilantd", "비질란테 (일본판,개정판D)" },
    { "vigilantg", "비질란테 (미국판,개정판G)" },
    { "vigilantj", "비질란테 (일본판)" },
    { "vigilanto", "비질란테 (미국판)" },
    { "vigilantu", "비질란테 (미국판)" },
    { "vigilntj", "비질란테 (일본판)" },
    { "vigilntu", "비질란테 (미국판)" },
    { "vimana", "비마나 (세계판,세트1)" },
    { "vimana1", "비마나 (일본판)" },
    { "vimana2", "비마나 (세트2)" },
    { "vimanaj", "비마나 (일본판)" },
    { "vimanan", "비마나 (세계판,세트2)" },
    { "vindc2r1", "빈디케이터 파트 2 (개정판1)" },
    { "vindc2r2", "빈디케이터 파트 2 (개정판2)" },
    { "vindctr2", "빈디케이터 파트 2 (개정판3)" },
    { "vindctr2r1", "빈디케이터 파트 2 (개정판1)" },
    { "vindctr2r2", "빈디케이터 파트 2 (개정판2)" },
    { "vindice3", "빈디케이터 (유럽판,개정판3)" },
    { "vindice4", "빈디케이터 (유럽판,개정판4)" },
    { "vindict1", "빈디케이터 (개정판1)" },
    { "vindict2", "빈디케이터 (개정판2)" },
    { "vindict4", "빈디케이터 (개정판4)" },
    { "vindicte", "빈디케이터 (유럽판,개정판5)" },
    { "vindictg", "빈디케이터 (독일판,개정판1)" },
    { "vindictr", "빈디케이터 (개정판5)" },
    { "vindictr1", "빈디케이터 (개정판1)" },
    { "vindictr2", "빈디케이터 (개정판2)" },
    { "vindictr4", "빈디케이터 (개정판4)" },
    { "vindictre", "빈디케이터 (유럽판,개정판5)" },
    { "vindictre3", "빈디케이터 (유럽판,개정판3)" },
    { "vindictre4", "빈디케이터 (유럽판,개정판4)" },
    { "vindictrg", "빈디케이터 (독일판,개정판1)" },
    { "viofight", "바이올런스 파이트 (세계판)" },
    { "viofightj", "바이올런스 파이트 (일본판)" },
    { "viofightu", "바이올런스 파이트 (미국판)" },
    { "viofighu", "바이올런스 파이트 (미국판)" },
    { "viostorm", "바이올렌트 스톰 (버전EAC)" },
    { "viostorma", "바이올렌트 스톰 (버전AAC)" },
    { "viostormab", "바이올렌트 스톰 (버전AAB)" },
    { "viostormabbl", "바이올렌트 스톰 (버전AAB)" },
    { "viostormeb", "바이올렌트 스톰 (버전EAB)" },
    { "viostormj", "바이올렌트 스톰 (버전JAC)" },
    { "viostormu", "바이올렌트 스톰 (버전UAC)" },
    { "viostormub", "바이올렌트 스톰 (버전UAB)" },
    { "viostormubbl", "바이올렌트 스톰 (버전UAB)" },
    { "viostrma", "바이올렌트 스톰 (버전AAC)" },
    { "viostrmj", "바이올렌트 스톰 (버전JAC)" },
    { "viostrmu", "바이올렌트 스톰 (버전UAB)" },
    { "vipclub", "VIP 클럽 - 비밀 일발 개방 (일본판)" },
    { "viper", "바이퍼" },
    { "viprp1", "바이퍼 페이즈 1 (신버전,세계판)" },
    { "viprp1h", "바이퍼 페이즈 1 (신버전,폴란드판)" },
    { "viprp1hk", "바이퍼 페이즈 1 (홍콩판)" },
    { "viprp1j", "바이퍼 페이즈 1 (신버전,일본판)" },
    { "viprp1k", "바이퍼 페이즈 1 (신버전,한국판)" },
    { "viprp1o", "바이퍼 페이즈 1 (일본판)" },
    { "viprp1oj", "바이퍼 페이즈 1 (일본판)" },
    { "viprp1ot", "바이퍼 페이즈 1 (독일판)" },
    { "viprp1pt", "바이퍼 페이즈 1 (신버전,포르투갈판)" },
    { "viprp1s", "바이퍼 페이즈 1 (스위스판,신버전)" },
    { "viprp1t", "바이퍼 페이즈 1 (신버전,독일판)" },
    { "viprp1u", "바이퍼 페이즈 1 (미국판,신버전)" },
    { "viprp1ua", "바이퍼 페이즈 1 (미국판,세트2)" },
    { "virnba", "버추어 NBA (미국판)" },
    { "virnbao", "버추어 NBA" },
    { "virnbap", "버추어 NBA (시험판)" },
    { "virnbapa", "버추어 NBA (시험판,15.11)" },
    { "virtpool", "버추얼 풀" },
    { "vitaminc", "마작 비타민 C" },
    { "vivdolls", "비비드 돌" },
    { "vliner", "V라이너" },
    { "vliner53", "V라이너 (v0.53)" },
    { "vliner54", "V라이너 (v0.54)" },
    { "vliner6e", "V라이너 (v0.6e)" },
    { "vliner7e", "V라이너 (v0.7e)" },
    { "vlinero", "V라이너 (세트2)" },
    { "vmahjong", "버추얼 마작" },
    { "vmetal", "바리아 메탈" },
    { "vmetaln", "바리아 메탈 (뉴웨이 트레이딩)" },
    { "volfied", "볼피드 - 땅따먹기 (세계판,개정판1)" },
    { "volfiedj", "볼피드 - 땅따먹기 (일본판,개정판1)" },
    { "volfiedjo", "볼피드 - 땅따먹기 (일본판)" },
    { "volfiedo", "볼피드 - 땅따먹기 (세계판)" },
    { "volfiedu", "볼피드 - 땅따먹기 (미국판,개정판1)" },
    { "volfieduo", "볼피드 - 땅따먹기 (미국판)" },
    { "von", "전뇌전기 버추얼 온 - 트윈" },
    { "von2", "전뇌전기 버추얼 온 2 - 오라토리오 텅그램" },
    { "von254g", "전뇌전기 버추얼 온 2 - 오라토리오 텅그램 (버전5.4g)" },
    { "von2a", "전뇌전기 버추얼 온 2 - 오라토리오 텅그램" },
    { "von2o", "전뇌전기 버추얼 온 2 - 오라토리오 텅그램" },
    { "vonj", "전뇌전기 버추얼 온 - 트윈 (일본판,개정판B)" },
    { "vonot", "버추얼 온 오라토리오 탱그램" },
    { "vonu", "전뇌전기 버추얼 온 - 트윈 (미국판,개정판B)" },
    { "vonusa", "전뇌전기 버추얼 온 (미국판)" },
    { "vortex", "볼텍스" },
    { "vp906iii", "906III 비디오 포커" },
    { "vpoker", "비디오트로닉스 포커" },
    { "vpool", "비디오 풀 (문 크레스타 하드웨어 해적판)" },
    { "vr", "버추어 레이싱" },
    { "vroulet", "베가스 룰렛" },
    { "vs10yard", "VS. 10 야드 파이트 (세계판)" },
    { "vs10yardj", "VS. 10 야드 파이트 (미국판,타이토 라이센스)" },
    { "vs2", "버추어 스트라이커 2" },
    { "vs2002ex", "버추어 스트라이커 2002" },
    { "vs2002j", "버추어 스트라이커 2002" },
    { "vs215", "버추어 스트라이커 2 (스텝 1.5)" },
    { "vs215o", "버추어 스트라이커 2 (스텝 1.5)" },
    { "vs298", "버추어 스트라이커 2 98" },
    { "vs29815", "버추어 스트라이커 2 98 (스텝 1.5)" },
    { "vs299", "버추어 스트라이커 2 99" },
    { "vs299a", "버추어 스트라이커 2 99 (개정판A)" },
    { "vs299b", "버추어 스트라이커 2 99 (개정판B)" },
    { "vs2_2k", "버추어 스트라이커 2 버전2000 (개정판C)" },
    { "vs2_2ko", "버추어 스트라이커 2 버전2000" },
    { "vs2v991", "버추어 스트라이커 2 99.1" },
    { "vs4", "버추어 스트라이커 4" },
    { "vs42006", "버처어 스트라이커 4 ver. 2006" },
    { "vs4j", "버추어 스트라이커 4" },
    { "vsav", "뱀파이어 세이비어 - 뱀파이어의 제왕 (유럽판)" },
    { "vsav2", "뱀파이어 세이비어 2 - 뱀파이어의 제왕 (일본판)" },
    { "vsav2d", "뱀파이어 세이비어 2 - 뱀파이어의 제왕 (일본판,피닉스에디션)" },
    { "vsava", "뱀파이어 세이비어 - 뱀파이어의 제왕 (아시아판)" },
    { "vsavb", "뱀파이어 세이비어 - 뱀파이어의 제왕 (브라질판)" },
    { "vsavd", "뱀파이어 세이비어 - 뱀파이어의 제왕 (유럽판,피닉스에디션)" },
    { "vsavdt", "뱀파이어 세이비어 - 뱀파이어의 제왕 (유럽판 피닉스 에디션,트레이닝 핵)" },
    { "vsavh", "뱀파이어 세이비어 - 뱀파이어의 제왕 (히스패닉판)" },
    { "vsavj", "뱀파이어 세이비어 - 뱀파이어의 제왕 (일본판)" },
    { "vsavu", "뱀파이어 세이비어 - 뱀파이어의 제왕 (미국판)" },
    { "vsbattlecity", "VS. 배틀 시티" },
    { "vsbbalja", "베이스볼 (일본판 세트2)" },
    { "vsbbaljb", "베이스볼 (일본판 세트3)" },
    { "vsbball", "베이스볼" },
    { "vsbballj", "베이스볼 (일본판 세트1)" },
    { "vsbballja", "베이스볼 (일본판 세트2)" },
    { "vsbballjb", "베이스볼 (일본판 세트3)" },
    { "vscaptfl", "Vs. 슈퍼 캡틴 플래그" },
    { "vscastlevania", "VS. 캐슬베니아" },
    { "vsclucluland", "VS. 클루 클루 랜드" },
    { "vscompmj", "VS 컴퓨터 마작" },
    { "vsdrmario", "VS. 닥터 마리오" },
    { "vsduckhunt", "VS. 덕헌트" },
    { "vsexcitebike", "VS. 익사이트 바이크" },
    { "vsfdf", "VS. 프리덤 포스" },
    { "vsfreedomforce", "VS. 프리덤 포스" },
    { "vsfrombelow", "VS. 프롬 빌로우 (HB)" },
    { "vsgongf", "VS 공 파이트" },
    { "vsgoonies", "VS. 구니스" },
    { "vsgradius", "VS. 그라디우스" },
    { "vsgradus", "VS. 그라디우스" },
    { "vsgshoe", "VS. 검슈" },
    { "vsgumshoe", "VS. 검슈" },
    { "vshogansalley", "VS. 호간 앨리" },
    { "vshoot", "J리그 사커 V슛 (일본판)" },
    { "vsiceclimber", "VS. 아이스 클라이머" },
    { "vsmachrider", "VS. 마하 라이더" },
    { "vsmahjng", "VS. 마작" },
    { "vsmightybomjack", "VS. 마이티 봄잭" },
    { "vsmjtria", "VS 마작 트라이앵글" },
    { "vsnetscj", "버서스 넷 사커 (버전JAB)" },
    { "vsnetscr", "버서스 넷 사커" },
    { "vsnetscra", "버서스 넷 사커 (버전AAA)" },
    { "vsnetscreb", "버서스 넷 사커 (버전EAB)" },
    { "vsnetscrj", "버서스 넷 사커 (버전JAB)" },
    { "vsnetscru", "버서스 넷 사커 (버전UAB)" },
    { "vsninjajkun", "VS. 닌자 자자마루군" },
    { "vspinbal", "VS. 핀볼" },
    { "vspinbalj", "VS. 핀볼 (일본판)" },
    { "vspinball", "VS. 핀볼" },
    { "vspinblj", "VS. 핀볼 (일본판)" },
    { "vsplatoon", "VS. 플래툰" },
    { "vsraidbbay", "VS. 레이드 온 벙글링 베이" },
    { "vsrbibbal", "VS. 아타리 RBI 야구" },
    { "vsskykid", "VS. 슈퍼 스카이키드" },
    { "vsslalom", "VS. 슬라럼" },
    { "vssmb", "VS. 슈퍼 마리오 브로스" },
    { "vssmgolf", "VS. 스트로크 & 매치 골프" },
    { "vssmgolfla", "VS. 스트로크 & 매치 골프 레이디스" },
    { "vssoccer", "VS. 사커" },
    { "vssoccera", "VS. 사커" },
    { "vssoccerj", "VS. 사커 (일본판)" },
    { "vsstarluster", "VS. 스타 러스터" },
    { "vssuperskykid", "VS. 슈퍼 스카이 키드" },
    { "vssuperxevious", "VS. 슈퍼 제비우스 - 검프의 수수께끼" },
    { "vstars", "비디오 스타즈" },
    { "vstennij", "VS. 테니스 (일본판)" },
    { "vstennis", "VS. 테니스" },
    { "vstennisa", "VS. 테니스" },
    { "vstennisb", "VS. 테니스" },
    { "vstennisj", "VS. 테니스 (일본판)" },
    { "vstetris", "VS. 테트리스" },
    { "vstkoboxing", "VS. TKO 복싱" },
    { "vstopgun", "VS. 탑건" },
    { "vstrik3", "버추어 스트라이커 3 (GDS-0006)" },
    { "vstrik3c", "버추어 스트라이커 3" },
    { "vstrik3co", "버추어 스트라이커 3 (세계판)" },
    { "vstriker", "버추어 스트라이커" },
    { "vstrikero", "버추어 스트라이커" },
    { "vstrikra", "버추어 스트라이커 (개정판A)" },
    { "vsurbanchamp", "VS. 어반 챔피언" },
    { "vsyard", "VS. 10 야드 파이트 (세계판)" },
    { "vsyard2", "VS. 10 야드 파이트 (일본판,세트2)" },
    { "vtenis2c", "버추어 테니스 2/ 파워 스매시 2 (개정판A)" },
    { "vtennis", "버추어 테니스/ 파워 스매시" },
    { "vtennis2", "버추어 테니스 2/ 파워 스매시 2 (개정판A)(GDS-0015A)" },
    { "vtennisg", "버추어 테니스/ 파워 스매시 (GDS-0011)" },
    { "vueloesp", "부엘로 이스파시알" },
    { "vulcan", "그라디우스 2/ 불칸 벤처 (신형)" },
    { "vulcana", "그라디우스 2/ 불칸 벤처 (구형)" },
    { "vulcanb", "그라디우스 2/ 불칸 벤처 (최종)" },
    { "vulgus", "벌거스 (세트1)" },
    { "vulgus2", "발가스 (세트2)" },
    { "vulgusa", "벌거스 (세트2)" },
    { "vulgusj", "벌거스 (일본판?)" },
};

const size_t lookup_v_count = A_SIZE(lookup_v_table);

const char *lookup_v(const char *name) {
    if (!name) return NULL;
    for (size_t i = 0; i < lookup_v_count; i++) {
        if (strcmp(lookup_v_table[i].name, name) == 0) {
            return lookup_v_table[i].value;
        }
    }
    return NULL;
}

const char *r_lookup_v(const char *value) {
    if (!value) return NULL;
    for (size_t i = 0; i < lookup_v_count; i++) {
        if (strstr(lookup_v_table[i].value, value)) {
            return lookup_v_table[i].name;
        }
    }
    return NULL;
}

void lookup_v_multi(const char *term, void (*emit)(const char *name, const char *value, void *udata), void *udata) {
    if (!term) return;
    for (size_t i = 0; i < lookup_v_count; i++) {
        if (strcasestr(lookup_v_table[i].name, term))
            emit(lookup_v_table[i].name, lookup_v_table[i].value, udata);
    }
}

void r_lookup_v_multi(const char *term, void (*emit)(const char *name, const char *value, void *udata), void *udata) {
    if (!term) return;
    for (size_t i = 0; i < lookup_v_count; i++) {
        if (strcasestr(lookup_v_table[i].value, term))
            emit(lookup_v_table[i].name, lookup_v_table[i].value, udata);
    }
}
