#include <string.h>
#include "../common/common.h"
#include "lookup.h"

const LookupName lookup_j_table[] = {
    { "jack", "잭과 콩나무 (세트1)" },
    { "jack2", "잭과 콩나무 (세트2)" },
    { "jack3", "잭과 콩나무 (세트3)" },
    { "jackal", "특수부대 자칼/ 자칼 (세계판,8방향 조이스틱)" },
    { "jackalbl", "특수부대 자칼/ 자칼 (해적판,로터리 조이스틱)" },
    { "jackalj", "특수부대 자칼/ 자칼 (일본판,8방향 조이스틱)" },
    { "jackalr", "특수부대 자칼/ 자칼 (세계판,로터리 조이스틱)" },
    { "jackhous", "잭 하우스" },
    { "jackie", "해피 재키" },
    { "jackler", "재클러" },
    { "jackpool", "잭팟 카드/ 잭팟 풀" },
    { "jackrab2", "잭 래빗 (세트2)" },
    { "jackrabs", "잭 래빗 (특별판)" },
    { "jackrabt", "잭 래빗" },
    { "jackrabt2", "잭 래빗 (세트2)" },
    { "jackrabts", "잭 래빗 (특별판)" },
    { "jailbrek", "탈옥" },
    { "jailbrekb", "탈옥" },
    { "jajamaru", "VS. 닌자 자자마루군" },
    { "jambo", "잠보! 사파리" },
    { "janbari", "마작 쟝쟝 팍팍" },
    { "jangou", "장고" },
    { "jangtaku", "장 타쿠" },
    { "janjans1", "러블리 팝 마작 장장 합시다 (일본판)" },
    { "janjans2", "러블리 팝 마작 장장 합시다 2 (일본판)" },
    { "janoh", "작 오" },
    { "janoha", "작 오 (세트2)" },
    { "janptr96", "잔퓨터 96" },
    { "janptrsp", "잔퓨터 스페셜" },
    { "janputer", "뉴 더블 벳 마작" },
    { "janputera", "뉴 더블 벳 마작 (세트2)" },
    { "janshi", "마작사" },
    { "janshin", "작신전설 - 마작 마스터의 모험" },
    { "janshinp", "마작 작신 플러스 (일본판)" },
    { "jansou", "작장" },
    { "jansoua", "작장 (세트2)" },
    { "jantotsu", "4인 마작 잔토스" },
    { "jantouki", "작투기" },
    { "janyoup2", "잔유 파트 2 (버전7.03)" },
    { "janyoup2a", "잔유 파트 2 (버전7.03,노 타이틀스크린)" },
    { "janyuki", "작유기 (일본판)" },
    { "jbell", "징글벨" },
    { "jbell133i", "징글벨" },
    { "jbell141ue", "징글벨" },
    { "jbell153ue", "징글벨" },
    { "jbell155ue", "징글벨" },
    { "jbell157us", "징글벨" },
    { "jchan", "재키 챈 - 쿵푸 마스터 (개정판4?)" },
    { "jchan2", "재키 챈 - 성룡전설" },
    { "jchana", "재키 챈 - 쿵푸 마스터" },
    { "jclub2", "쟈키 클럽 II" },
    { "jclub2bl", "쟈키 클럽 II" },
    { "jclub2o", "쟈키 클럽 II (구형 하드웨어)" },
    { "jclub2v100", "쟈키 클럽 II" },
    { "jclub2v101", "쟈키 클럽 II" },
    { "jclub2v110", "쟈키 클럽 II" },
    { "jclub2v112", "쟈키 클럽 II" },
    { "jclub2v200", "쟈키 클럽 II" },
    { "jclub2v201", "쟈키 클럽 II" },
    { "jclub2v203", "쟈키 클럽 II" },
    { "jclub2v204", "쟈키 클럽 II" },
    { "jclub2v205", "쟈키 클럽 II" },
    { "jclub2v220", "쟈키 클럽 II" },
    { "jcross", "점핑 크로스 (세트1)" },
    { "jcrossa", "점핑 크로스 (세트2)" },
    { "jdredd", "저지 드레드" },
    { "jdreddb", "저지 드레드 (개정판B)" },
    { "jdreddp", "저지 드레드 (개정판TA1,로케이션 테스트)" },
    { "jedi", "스타 워즈 - 제다이의 귀환" },
    { "jetwave", "제트 웨이브" },
    { "jetwavej", "제트 웨이브 (일본판)" },
    { "jgakuen", "사립 저스티스 학원 (일본판)" },
    { "jgakuen1", "사립 저스티스 학원 (일본판)" },
    { "jigkmgri", "본즈 어드벤처/ 지옥순례 (일본판)" },
    { "jigkmgria", "본즈 어드벤처/ 지옥순례 (일본판,핵)" },
    { "jin", "진" },
    { "jingbell", "징글벨" },
    { "jingling", "징글링 지아주 지니 2000" },
    { "jingystm", "진기 스톰 - 아케이드 (일본판)(GDL-0037)" },
    { "jitsupro", "실력!! 프로야구 (일본판)" },
    { "jituroku", "실록 멀티 마작" },
    { "jjack", "점핑 잭" },
    { "jjparad2", "작 작 파라다이스 2" },
    { "jjparads", "작 작 파라다이스" },
    { "jjpoker", "잭팟 조커 포커" },
    { "jjpokerb", "잭팟 조커 포커 (세트2)" },
    { "jjsquawk", "J. J. 스쿼커즈" },
    { "jjsquawkb", "J. J. 스쿼커즈" },
    { "jjsquawkb2", "J. J. 스쿼커즈 (해적판,블란디아 컨버젼)" },
    { "jjsquawko", "J. J. 스쿼커즈 (구형)" },
    { "jking02", "정글 킹 2002" },
    { "jking103a", "정글 킹 (V103A)" },
    { "jking200pr", "정글 킹 (V200PR)" },
    { "jkrbonus", "조커 보너스" },
    { "jkrmast", "조커 마스터" },
    { "jleague", "슈퍼 비주얼 풋볼/ J리그 1994 (일본판,개정판A)" },
    { "jleagueo", "슈퍼 비주얼 풋볼/ J리그 1994 (일본판)" },
    { "jmpbreak", "점핑 브레이크 (세트1)" },
    { "jmpbreaka", "점핑 브레이크 (세트2)" },
    { "jnero", "조니 니로 액션 히어로" },
    { "jngolady", "장고 레이디" },
    { "jockeyc", "조키 클럽" },
    { "jockeygp", "조키 그랑프리 (세트1)" },
    { "jockeygpa", "조키 그랑프리 (세트2)" },
    { "joemac", "원시인 닌자/ 싸워라 원시인 죠 & 맥 (일본판 버전1)" },
    { "joemacr", "죠 & 맥 리턴즈 (세계판,버전1.1)" },
    { "joemacra", "죠 & 맥 리턴즈 (세계판,버전1.0)" },
    { "joemacrj", "죠 & 맥 리턴즈 (일본판,버전1.2)" },
    { "jogakuen", "마작 여학원" },
    { "joinem", "조인엠" },
    { "jojo", "죠죠의 모험 (유럽판)" },
    { "jojoa", "죠죠의 모험 (일본판)" },
    { "jojoaltn", "죠죠의 기묘한 모험 (아시아판,NO CD)" },
    { "jojoan", "죠죠의 기묘한 모험 (아시아판,NO CD)" },
    { "jojoar1", "죠죠의 모험 (아시아판)" },
    { "jojoar2", "죠죠의 모험 (아시아판)" },
    { "jojoba", "죠죠의 기묘한 모험 - 미래로의 유산 (유럽판)" },
    { "jojobaa", "죠죠의 기묘한 모험 - 미래로의 유산 (대체)" },
    { "jojobaj", "죠죠의 기묘한 모험 - 미래로의 유산 (일본판)" },
    { "jojobajr1", "죠죠의 기묘한 모험 - 미래로의 유산 (일본판)" },
    { "jojobajr2", "죠죠의 기묘한 모험 - 미래로의 유산 (일본판)" },
    { "jojoban", "죠죠의 기묘한 모험 - 미래로의 유산 (일본판,NO CD)" },
    { "jojobane", "죠죠의 기묘한 모험 - 미래로의 유산 (유럽판,NO CD)" },
    { "jojobaner1", "죠죠의 기묘한 모험 - 미래로의 유산 (유럽판,NO CD)" },
    { "jojobaner2", "죠죠의 기묘한 모험 - 미래로의 유산 (유럽판,NO CD)" },
    { "jojobanr1", "죠죠의 기묘한 모험 - 미래로의 유산 (일본판,NO CD)" },
    { "jojobanr2", "죠죠의 기묘한 모험 - 미래로의 유산 (일본판,NO CD)" },
    { "jojobanrb", "죠죠의 기묘한 모험 - 미래로의 유산 (레인보우 에디션 v1.0.1)" },
    { "jojobar1", "죠죠의 기묘한 모험 - 미래로의 유산 (유럽판)" },
    { "jojobar2", "죠죠의 기묘한 모험 - 미래로의 유산 (유럽판)" },
    { "jojoj", "죠죠의 기묘한 모험 (일본판)" },
    { "jojojr1", "죠죠의 기묘한 모험 (일본판)" },
    { "jojojr2", "죠죠의 기묘한 모험 (일본판)" },
    { "jojon", "죠죠의 모험 (아시아판,NO CD)" },
    { "jojonr1", "죠죠의 모험 (아시아판,NO CD)" },
    { "jojonr2", "죠죠의 모험 (아시아판,NO CD)" },
    { "jojor1", "죠죠의 모험 (유럽판)" },
    { "jojor2", "죠죠의 모험 (유럽판)" },
    { "jojou", "죠죠의 모험 (미국판)" },
    { "jojour1", "죠죠의 모험 (미국판)" },
    { "jojour2", "죠죠의 모험 (미국판)" },
    { "jokercar", "조커 카드" },
    { "jokercrd", "조커 카드" },
    { "jokpoker", "조커 포커" },
    { "jokpokera", "조커 포커 (버전16.03BI)" },
    { "jokpokerb", "조커 포커 (버전16.04BI,조커 포커)" },
    { "jokpokerc", "조커 포커 (버전16.03BI,포커 노 레이즈)" },
    { "jokrwild", "조커스 와일드" },
    { "jollycrd", "졸리 카드" },
    { "jollyjgr", "졸리 조거" },
    { "jolyc3x3", "졸리 카드 (3x3 딜)" },
    { "jolyc980", "졸리 카드 프로페셔널 2.0 (스패일 소프트)" },
    { "jolyccra", "졸리 카드 (세트1)" },
    { "jolyccrb", "졸리 카드 (세트2)" },
    { "jolycdab", "졸리 카드 (호주판,펀월드 해적판)" },
    { "jolycdat", "졸리 카드 (호주판,펀월드)" },
    { "jolycdcr", "졸리 카드 (크로아티아)" },
    { "jolycdev", "졸리 카드 (이노바 일렉트로닉)" },
    { "jolycdib", "졸리 카드 (이탈리아,암호화 해적판)" },
    { "jolycdit", "졸리 카드 (이탈리아,블루탭 보드,암호화)" },
    { "jolycmzs", "졸리 카드 프로페셔널 2.0 (MZS 테크)" },
    { "jolyjokr", "졸리 조커" },
    { "jolyjokra", "졸리 조커 (98bet,세트2)" },
    { "jolyjokrb", "졸리 조커 (40bet,핵)" },
    { "jongbou", "마작 블럭 작봉" },
    { "jongbou2", "마작 블럭 작봉 2" },
    { "jongkyo", "작광" },
    { "jongpute", "정푸터" },
    { "jongshin", "종 신" },
    { "jongtei", "마작 종테" },
    { "jongteia", "마작 종테" },
    { "josvolly", "조시 발리볼" },
    { "journey", "저니" },
    { "joust", "자우스트 (흰색/초록색 라벨)" },
    { "joust2", "자우스트 2" },
    { "joust2r1", "자우스트 2 (개정판1)" },
    { "joustr", "자우스트 (레드 라벨)" },
    { "joustwr", "자우스트 (흰색/빨간색 라벨)" },
    { "jousty", "자우스트 (옐로우 라벨)" },
    { "joyfulr", "조이풀 로드 (일본판)" },
    { "joyjoy", "퍼즐드/ 조이조이 키드" },
    { "joyman", "조이맨" },
    { "joystand", "조이 스탠드 프라이빗" },
    { "jpark", "쥬라기 공원 (세계판,개정판A)" },
    { "jpark3", "쥬라기 공원 3" },
    { "jpark3u", "쥬라기 공원 3 (버전UBC)" },
    { "jparkj", "쥬라기 공원 (일본판,개정판A,디럭스)" },
    { "jparkja", "쥬라기 공원 (일본판,컨버전)" },
    { "jparkjc", "쥬라기 공원 (일본판,개정판A,컨버전)" },
    { "jparkmb", "쥬라기 공원 (메가드리이브 버전 해적판)" },
    { "jpcoin", "조커 포커" },
    { "jpcoin2", "조커 포커 (코인마스터, 어뮤즈먼트 오운리)" },
    { "jpjcoin", "잭팟 조커 포커" },
    { "jpopnics", "점핑 팝 (닉스,한국판 플럼프 팝의 복제품)" },
    { "jppyex98", "실황 파워풀 프로야구 EX 98" },
    { "jrking", "쥬니어 킹" },
    { "jrpacman", "쥬니어 팩맨 (11/9/83)" },
    { "jrpacmanf", "쥬니어 팩맨 (속도업 핵)" },
    { "jrpacmbl", "쥬니어 팩맨 (펭고 하드웨어)" },
    { "jrpacmnf", "쥬니어 팩맨 (스피드업 핵)" },
    { "jsk", "여류 장기 교실" },
    { "jspecter", "재트리 스펙터 (세트1)" },
    { "jspecter2", "재트리 스펙터 (세트2)" },
    { "jspectr2", "재트리 스펙터 (세트2)" },
    { "jt104", "닌자 키드 2/ 닌자군 아수라의 장" },
    { "jubileep", "더블-업 포커" },
    { "juju", "주주 전설 (일본판)" },
    { "jujub", "주주 전설 (플레이마크 해적판)" },
    { "jujuba", "주주 전설 (일본판,해적판)" },
    { "jumbogod", "점보 고질라" },
    { "jumpbug", "점프 버그" },
    { "jumpbugb", "점프 버그 (해적판,세트1)" },
    { "jumpbugbc", "점프 버그 (해적판,세트3)" },
    { "jumpbugbrf", "점프 버그 (해적판,세트2)" },
    { "jumpcoas", "점프 코스터 (세계판)" },
    { "jumpcoasa", "점프 코스터" },
    { "jumpcoast", "점프 코스터 (타이토)" },
    { "jumpcoat", "점프 코스터 (타이토)" },
    { "jumping", "점핑 (세트1)" },
    { "jumpinga", "점핑 (세트2)" },
    { "jumpingi", "점핑 (세트3,해적판)" },
    { "jumpjump", "점프 점프" },
    { "jumpkids", "점프 키즈" },
    { "jumpkun", "점프 군 (시제품)" },
    { "jumppop", "점핑 팝 (세트1)" },
    { "jumppope", "점핑 팝 (세트2)" },
    { "jumpshot", "점프 샷" },
    { "jumpshotp", "점프 샷 엔지니어링 샘플" },
    { "jumpshtp", "점프 샷 엔지니어링 샘플" },
    { "jungleby", "정글 보이" },
    { "jungleh", "정글 킹-정글 헌트 (미국판)" },
    { "junglehbr", "정글 킹-정글 헌트 (브라질판)" },
    { "junglek", "정글 킹 (일본판)" },
    { "junglekas", "정글 킹 (대체 사운드)" },
    { "junglekj2", "정글 킹 (일본판,초기)" },
    { "junglekj2a", "정글 킹 (일본판,초기,대체)" },
    { "jungler", "정글러" },
    { "junglero", "정글러 (올림피아)" },
    { "junglers", "정글러 (스턴)" },
    { "junglhbr", "정글 킹-정글 헌트 (브라질판)" },
    { "junglkj2", "정글 킹 (일본판,초기)" },
    { "jungsub", "정글러 (서브일렉트로,스크램블 하드웨어 해적판)" },
    { "junofrst", "주노 퍼스트" },
    { "junofrstg", "주노 퍼스트 (고티브)" },
    { "junofstg", "주노 퍼스트 (고티브)" },
    { "jurassic99", "쥬라기 99" },
    { "jwildb52", "조커스 와일드" },
    { "jwildb52a", "조커스 와일드 (B52 시스템,세트2)" },
    { "jwildb52h", "조커스 와일드 (B52 시스템)" },
    { "jyangoku", "작국지 - 패왕의 채패 (일본판)" },
    { "jyuohki", "수왕기 (일본판)" },
    { "jzth", "결전 천황" },
};

const size_t lookup_j_count = A_SIZE(lookup_j_table);

const char *lookup_j(const char *name) {
    if (!name) return NULL;
    for (size_t i = 0; i < lookup_j_count; i++) {
        if (strcmp(lookup_j_table[i].name, name) == 0) {
            return lookup_j_table[i].value;
        }
    }
    return NULL;
}

const char *r_lookup_j(const char *value) {
    if (!value) return NULL;
    for (size_t i = 0; i < lookup_j_count; i++) {
        if (strstr(lookup_j_table[i].value, value)) {
            return lookup_j_table[i].name;
        }
    }
    return NULL;
}

void lookup_j_multi(const char *term, void (*emit)(const char *name, const char *value, void *udata), void *udata) {
    if (!term) return;
    for (size_t i = 0; i < lookup_j_count; i++) {
        if (strcasestr(lookup_j_table[i].name, term))
            emit(lookup_j_table[i].name, lookup_j_table[i].value, udata);
    }
}

void r_lookup_j_multi(const char *term, void (*emit)(const char *name, const char *value, void *udata), void *udata) {
    if (!term) return;
    for (size_t i = 0; i < lookup_j_count; i++) {
        if (strcasestr(lookup_j_table[i].value, term))
            emit(lookup_j_table[i].name, lookup_j_table[i].value, udata);
    }
}
