#include <string.h>
#include "../common/common.h"
#include "lookup.h"

const LookupName lookup_o_table[] = {
    { "oceanhun", "오션 헌터" },
    { "oceanhuna", "오션 헌터" },
    { "oceanpar", "오션 파라다이스" },
    { "oceanpar101us", "오션 파라다이스" },
    { "oedfight", "블러드 워리어/ 오에도 파이트 (일본판 블러드섀드 버전)" },
    { "oedfighta", "블러드 워리어/ 오에도 파이트 (일본판 블러드리스 버전)" },
    { "offensiv", "오펜시브 (스크램블 스페인어 해적판)" },
    { "officeye", "오피스 여인천하" },
    { "offroad", "철인 이반 스튜어트의 슈퍼 오프로드" },
    { "offroad3", "철인 이반 스튜어트의 슈퍼 오프로드" },
    { "offroadc", "오프 로드 챌린지" },
    { "offroadc0", "오프 로드 챌린지 (v1.00)" },
    { "offroadc1", "오프 로드 챌린지 (v1.10)" },
    { "offroadc3", "오프 로드 챌린지 (v1.30)" },
    { "offroadc4", "오프 로드 챌린지 (v1.40)" },
    { "offroadc5", "오프 로드 챌린지 (v1.50)" },
    { "offroadt", "철인 이반 스튜어트의 슈퍼 오프로드 트랙팩" },
    { "offroadt2p", "철인 이반 스튜어트의 슈퍼 오프로드 트랙팩 (2인용)" },
    { "offtwalc", "오프 더 월 (2인용 칵테일)" },
    { "offtwall", "오프 더 월 (2-3인용 업라이트)" },
    { "offtwallc", "오프 더 월 (2인용 칵테일)" },
    { "ogonsiro", "황금성 (일본판)" },
    { "ohbakyuun", "오! 바큔" },
    { "ohmygod", "오 마이 갓! (일본판)" },
    { "ohpaipee", "오!파이피" },
    { "oigas", "오이가스" },
    { "oinori", "오이노리-다이묘진 축제" },
    { "oisipuzl", "맛있는 퍼즐은 필요없습니까" },
    { "ojanko2", "오장코 저택 2번관" },
    { "ojankoc", "오장코 클럽" },
    { "ojankoca", "오장코 클럽" },
    { "ojankocb", "오장코 클럽" },
    { "ojankohs", "오장코 하이 스쿨" },
    { "ojankoy", "오장코 저택" },
    { "ojousan", "아가씨" },
    { "ojousanm", "아가씨 (일본판 870108)" },
    { "olds", "오리엔탈 레전드 슈퍼 (V101,한국보드)" },
    { "olds100", "오리엔탈 레전드 스페셜-서유석액전 슈퍼 (버전100,세트1)" },
    { "olds100a", "오리엔탈 레전드 스페셜-서유석액전 슈퍼 (버전100,세트2)" },
    { "olds103t", "오리엔탈 레전드 스페셜-서유석액전 슈퍼 (버전103,중국판,텐센트,비보호)" },
    { "oldsdsgl", "오리엔탈 레전드 스페셜-대성귀래 (핵)" },
    { "oldsmx", "오리엔탈 레전드 스페셜-몽심령산 (핵)" },
    { "oldsplus", "오리엔탈 레전드 2/ 서유석액전 군마난무 (버전205)" },
    { "oldsplus203", "오리엔탈 레전드 2/ 서유석액전 군마난무 (버전203)" },
    { "oldsplusnr", "오리엔탈 레전드 2/ 서유석액전 군마난무 (핵)" },
    { "oldsplusok", "오리엔탈 레전드 2 (원 키 에디션,핵)" },
    { "olibochu", "올리 부 츄" },
    { "olibug", "올리 버그 (점프 버그 해적판)" },
    { "ollie", "올리에 킹" },
    { "olmandingc", "올리브만딩고" },
    { "olmandingo", "올리브만딩고" },
    { "olym65bj", "블랙 잭" },
    { "olysoc92", "올림픽 축구 92" },
    { "omega", "오메가" },
    { "omegaa", "오메가 (초기판)" },
    { "omegab", "디 엔드/ 오메가" },
    { "omegaf", "오메가 파이터" },
    { "omegafs", "오메가 파이터 스페셜" },
    { "omegrace", "오메가 레이스 (세트1)" },
    { "omegrace2", "오메가 레이스 (세트2)" },
    { "omegrace3", "오메가 레이스 (세트3)" },
    { "omni", "옴니" },
    { "omotesnd", "표삼도" },
    { "oneshot", "원 샷 원 킬" },
    { "onetwo", "원 + 투" },
    { "onetwoe", "원 + 투 (초기판)" },
    { "onna34ra", "여자 산시로 - 타이푼 갈 (세트2)" },
    { "onna34ro", "여자 산시로 - 타이푼 갈" },
    { "onna34roa", "여자 산시로 - 타이푼 갈 (해적판)" },
    { "ooparts", "오파츠 (시제품,조이스틱 핵)" },
    { "opaopa", "오파 오파" },
    { "opaopan", "오파 오파 (개정판A,비보호)" },
    { "opengol2", "코나미의 오픈 골프 챔피언쉽 (버전EAD)" },
    { "opengolf", "코나미의 오픈 골프 챔피언쉽" },
    { "opengolf2", "코나미의 오픈 골프 챔피언쉽 (버전EAD)" },
    { "openice", "2대2 오픈 아이스 챌린지 (개정판1.21)" },
    { "openicea", "2대2 오픈 아이스 챌린지 (개정판1.2A)" },
    { "openmj", "오픈 마작 (일본판)" },
    { "optiger", "오퍼레이션 타이거" },
    { "optigera", "오퍼레이션 타이거 (버전2.10 O)" },
    { "optigerj", "오퍼레이션 타이거 (버전2.09 J)" },
    { "optigersm", "오퍼레이션 타이거 세컨드 미션 (버전2.02 J)" },
    { "opwolf", "오퍼레이션 울프 (세계판,세트1)" },
    { "opwolf3", "오퍼레이션 울프 3 (세계판)" },
    { "opwolf3j", "오퍼레이션 울프 3 (일본판)" },
    { "opwolf3u", "오퍼레이션 울프 3 (미국판)" },
    { "opwolfa", "오퍼레이션 울프 (세계판,세트2)" },
    { "opwolfb", "오퍼레이션 베어" },
    { "opwolfj", "오퍼레이션 울프 (일본판)" },
    { "opwolfjsc", "오퍼레이션 울프 (일본판,SC)" },
    { "opwolfp", "오퍼레이션 울프 (일본판,시험판)" },
    { "opwolfu", "오퍼레이션 울프 (미국판)" },
    { "orangec", "오렌지 클럽 - 비밀 과외수업" },
    { "orangeci", "오렌지 클럽 - 비밀 과외수업 (일본판)" },
    { "orbit", "오빗" },
    { "orbite", "오비트 (시험판)" },
    { "orbitron", "오비트론" },
    { "orbs", "오브 (시제품?)" },
    { "ordyne", "오딘 (세계판)" },
    { "ordynej", "오딘 (일본판)" },
    { "ordyneje", "오딘 (일본판,영어 버전)" },
    { "orius", "오리우스 (버전UAA)" },
    { "orld105k", "오리엔탈 레전드/ 서유석액전 (버전105,한국보드)" },
    { "orld111c", "오리엔탈 레전드/ 서유석액전 (버전111,중국보드)" },
    { "orleg2", "오리엔탈 레전드 2 (V104,해외판)" },
    { "orleg2_101", "오리엔탈 레전드 2 (V101,해외판)" },
    { "orleg2_101cn", "오리엔탈 레전드 2/ 서유석액전 2 (V101,중국판)" },
    { "orleg2_101jp", "오리엔탈 레전드 2/ 서유석액전 2 (V101,일본판)" },
    { "orleg2_103", "오리엔탈 레전드 2 (V103,중국판)" },
    { "orleg2_103cn", "오리엔탈 레전드 2/ 서유석액전 2 (V103,중국판)" },
    { "orleg2_103jp", "오리엔탈 레전드 2/ 서유석액전 2 (V103,일본판)" },
    { "orleg2_104cn", "오리엔탈 레전드 2/ 서유석액전 2 (V104,중국판)" },
    { "orleg2_104jp", "오리엔탈 레전드 2/ 서유석액전 2 (V104,일본판)" },
    { "orlegend", "오리엔탈 레전드/ 서유석액전 (버전126)" },
    { "orlegend105k", "오리엔탈 레전드/ 서유석액전 (버전105,한국보드)" },
    { "orlegend105t", "오리엔탈 레전드/ 서유석액전 (버전105,대만보드)" },
    { "orlegend111c", "오리엔탈 레전드/ 서유석액전 (버전111,중국보드)" },
    { "orlegend111k", "오리엔탈 레전드/ 서유석액전 (버전111,한국보드)" },
    { "orlegend111t", "오리엔탈 레전드/ 서유석액전 (버전111,대만보드)" },
    { "orlegendc", "오리엔탈 레전드/ 서유석액전 (버전112,중국보드)" },
    { "orlegendca", "오리엔탈 레전드/ 서유석액전 (버전???,중국보드)" },
    { "orlegende", "오리엔탈 레전드/ 서유석액전 (버전112)" },
    { "orlegendea", "오리엔탈 레전드/ 서유석액전 (버전112,세트2)" },
    { "orlegndc", "오리엔탈 레전드/ 서유석액전 (버전112,중국보드)" },
    { "orlegnde", "오리엔탈 레전드/ 서유석액전 (버전112)" },
    { "orunners", "아웃러너즈 (세계판)" },
    { "orunnersj", "아웃러너즈 (일본판)" },
    { "orunnersu", "아웃러너즈 (미국판)" },
    { "orunneru", "아웃러너즈 (미국판)" },
    { "oscar", "사이코닉스 오스카 (세계판 개정판0)" },
    { "oscarbl", "사이코닉스 오스카 (세계판 개정판0,해적판)" },
    { "oscarj", "사이코닉스 오스카 (일본판 개정판2)" },
    { "oscarj0", "사이코닉스 오스카 (일본판 개정판0)" },
    { "oscarj1", "사이코닉스 오스카 (일본판 개정판1)" },
    { "oscarj2", "사이코닉스 오스카 (일본판 개정판2)" },
    { "oscaru", "사이코닉스 오스카 (미국판)" },
    { "osman", "오스만/ 캐논 댄서 (세계판)" },
    { "otatidai", "디스코 마작 선반의 법칙" },
    { "otenamhf", "솜씨가 어떤지 좀 봅시다 파이널" },
    { "otenamih", "솜씨가 어떤지 좀 봅시다" },
    { "otenki", "오텐키 코로린" },
    { "othello", "오델로" },
    { "othellos", "오델로 하자" },
    { "othldrby", "오델로 더비" },
    { "othunder", "오퍼레이션 썬더볼트 (세계판,개정판1)" },
    { "othunderj", "오퍼레이션 썬더볼트 (일본판)" },
    { "othunderjsc", "오퍼레이션 썬더볼트 (일본판,SC)" },
    { "othundero", "오퍼레이션 썬더볼트 (세계판)" },
    { "othunderu", "오퍼레이션 썬더볼트 (미국판,개정판1)" },
    { "othunderua", "오퍼레이션 썬더볼트 (미국판)" },
    { "othunderuo", "오퍼레이션 썬더볼트 (미국판)" },
    { "othundrj", "오퍼레이션 썬더볼트 (일본판)" },
    { "othundu", "오퍼레이션 썬더볼트 (미국판)" },
    { "othunduo", "오퍼레이션 썬더볼트 (미국판,구형)" },
    { "otonano", "성인 마작" },
    { "otrigger", "아웃트리거" },
    { "ottopz", "오토 프로젝트 PZ (핵)" },
    { "otwalls", "오프 더 월 (센테)" },
    { "ougonhai", "마작 황금의 패" },
    { "ougonhaib1", "마작 황금의 패 (일본해적판 세트1,메달)" },
    { "ougonhaib2", "마작 황금의 패 (일본해적판 세트2,메달)" },
    { "outfxesj", "아웃폭시즈 (일본판)" },
    { "outfxies", "아웃폭시즈 (세계판,OU2)" },
    { "outfxiesa", "아웃폭시즈 (한국판?)" },
    { "outfxiesj", "아웃폭시즈 (일본판,OU1)" },
    { "outfxiesja", "아웃폭시즈 (일본판,OU1,대체GFX롬)" },
    { "outline", "아웃라인" },
    { "outr2", "아웃런 2" },
    { "outrun", "아웃런 (좌석/수직형,개정판B)" },
    { "outrun1", "아웃런 (세트1)" },
    { "outrun2", "아웃런 (세트2)" },
    { "outruna", "아웃런 (세트2)" },
    { "outrunb", "아웃런" },
    { "outrundx", "아웃런 (디럭스 좌석)" },
    { "outrundxa", "아웃런 (초기 버전)" },
    { "outrundxeh", "아웃런 (디럭스 좌석,강화 에디션 v2.0.3)" },
    { "outrundxeha", "아웃런 (디럭스 좌석,강화 에디션 v1.0.3)" },
    { "outrundxj", "아웃런 (일본판,디럭스 좌석)" },
    { "outruneh", "아웃런 (업라이트,개정판B)(개선판 v2.0.3)" },
    { "outruneha", "아웃런 (업라이트,개정판B)(개선판 v1.1.0)" },
    { "outrunehb", "아웃런 (업라이트,개정판B)(개선판 v2.0.2)" },
    { "outruno", "아웃런 (좌식/입식)" },
    { "outrunra", "아웃런 (업라이트,개정판A)" },
    { "outzone", "아웃 존" },
    { "outzonea", "아웃 존 (구형 세트)" },
    { "outzoneb", "아웃 존 (구형 세트)" },
    { "outzonec", "아웃 존 (최종 세트)" },
    { "outzonecv", "아웃 존 (제로윙 TP-015 PCB 컨버전)" },
    { "outzoned", "아웃 존 (세트5)" },
    { "outzoneh", "아웃 존 (어려움)" },
    { "outzonep", "아웃 존" },
    { "overdriv", "오버 드라이브" },
    { "overdriva", "오버 드라이브 (세트2)" },
    { "overdrivb", "오버 드라이브 (세트3)" },
    { "overrev", "오버 레브" },
    { "overrevb", "오버 레브 (모델2B,개정판B)" },
    { "overrevba", "오버 레브 (모델2B,개정판A)" },
    { "overtop", "오버 탑" },
    { "ozmawar2", "오즈마 워즈 (세트2)" },
    { "ozmawars", "오즈마 워즈 (세트1)" },
    { "ozmawars2", "오즈마 워즈 (세트2)" },
    { "ozmawarsmr", "오즈마 워즈 (모델 레이싱 해적판)" },
    { "ozon1", "오존 I" },
};

const size_t lookup_o_count = A_SIZE(lookup_o_table);

const char *lookup_o(const char *name) {
    if (!name) return NULL;
    for (size_t i = 0; i < lookup_o_count; i++) {
        if (strcmp(lookup_o_table[i].name, name) == 0) {
            return lookup_o_table[i].value;
        }
    }
    return NULL;
}

const char *r_lookup_o(const char *value) {
    if (!value) return NULL;
    for (size_t i = 0; i < lookup_o_count; i++) {
        if (strstr(lookup_o_table[i].value, value)) {
            return lookup_o_table[i].name;
        }
    }
    return NULL;
}

void lookup_o_multi(const char *term, void (*emit)(const char *name, const char *value, void *udata), void *udata) {
    if (!term) return;
    for (size_t i = 0; i < lookup_o_count; i++) {
        if (strcasestr(lookup_o_table[i].name, term))
            emit(lookup_o_table[i].name, lookup_o_table[i].value, udata);
    }
}

void r_lookup_o_multi(const char *term, void (*emit)(const char *name, const char *value, void *udata), void *udata) {
    if (!term) return;
    for (size_t i = 0; i < lookup_o_count; i++) {
        if (strcasestr(lookup_o_table[i].value, term))
            emit(lookup_o_table[i].name, lookup_o_table[i].value, udata);
    }
}
