#include <string.h>
#include "../common/common.h"
#include "lookup.h"

const LookupName lookup_w_table[] = {
    { "wacko", "와코" },
    { "waidrive", "왁자지껄 드라이브" },
    { "wakuw7jq", "와쿠와쿠 7 (강화,핵)" },
    { "wakuwa7h", "와쿠와쿠 7 (히든핵)" },
    { "wakuwak7", "와쿠와쿠 7" },
    { "wakuwak7bh", "와쿠와쿠 7 (보스 핵)" },
    { "wakuwak7k", "와쿠와쿠 7 (한글)" },
    { "wallc", "월 크래시 (세트1)" },
    { "wallca", "월 크래시 (세트2)" },
    { "wallst", "월 스트리트" },
    { "wangmid", "완간 미드나이트 맥시멈 튠" },
    { "wangmid2", "완간 미드나이트 맥시멈 튠 2" },
    { "wanted", "원티드" },
    { "wantouch", "완터쳐블" },
    { "wantsega", "원티드" },
    { "warahana", "웃음의 화천사" },
    { "warcadia", "내 청춘의 아르카디아" },
    { "wardner", "와드너/ 와드너의 숲 (세계판)" },
    { "wardnerb", "와드너/ 와드너의 숲 (세계판,해적판)" },
    { "wardnerj", "와드너/ 와드너의 숲 (일본판)" },
    { "wardnerjb", "와드너/ 와드너의 숲 (일본판,해적판)" },
    { "warfa", "워 - 파이널 어썰트" },
    { "warfaa", "워 - 파이널 어썰트" },
    { "warfab", "워 - 파이널 어썰트" },
    { "warfac", "워 - 파이널 어썰트" },
    { "wargods", "워 갓즈" },
    { "wargodsa", "워 갓즈" },
    { "wargodsb", "워 갓즈" },
    { "warlord", "워로드" },
    { "warlords", "워로드" },
    { "warofbug", "벌래들의 전쟁 - 버섯미로 속의 괴물같은 움직임" },
    { "warofbugg", "벌래들의 전쟁 - 버섯미로 속의 괴물같은 움직임 (독일판)" },
    { "warofbugu", "벌래들의 전쟁 - 버섯미로 속의 괴물같은 움직임 (미국판)" },
    { "warp1", "워프 1" },
    { "warp1bl", "워프 1" },
    { "warp1t", "워프 1" },
    { "warpsped", "와프 스피드" },
    { "warpwar2", "워프 워프 (세트2)" },
    { "warpwarp", "와프 & 와프" },
    { "warpwarpr", "워프 워프 (세트1)" },
    { "warpwarpr2", "워프 워프 (세트2)" },
    { "warpwarr", "워프 워프 (세트1)" },
    { "warrior", "워리어" },
    { "warriorb", "라스탄 사가 Ep.3/ 워리어 블레이드 (일본판)" },
    { "warzard", "레드 어스/ 워자드 (일본판)" },
    { "warzardr1", "레드 어스/ 워자드 (일본판)" },
    { "wasafari", "개구쟁이 사파리" },
    { "waterski", "수상스키" },
    { "watrball", "워터 볼" },
    { "waverunr", "웨이브 러너" },
    { "waveshrk", "웨이브 샤크" },
    { "wavybug", "레이지 버그/ 웨이비 버그" },
    { "wb3", "원더 보이 3 - 몬스터 레어" },
    { "wb31", "원더 보이 3 - 몬스터 레어 (세트1,일본판,시스템16A)" },
    { "wb31d", "원더 보이 3 - 몬스터 레어 (세트1,일본판,시스템16A,암호해제)" },
    { "wb32", "원더 보이 3 - 몬스터 레어 (세트2,일본판,시스템16B)" },
    { "wb32d", "원더 보이 3 - 몬스터 레어 (세트2,일본판,시스템16B,암호해제)" },
    { "wb33", "원더 보이 3 - 몬스터 레어 (세트3,세계판,시스템16B)" },
    { "wb33d", "원더 보이 3 - 몬스터 레어 (세트3,세계판,시스템16B,암호해제)" },
    { "wb34", "원더 보이 3 - 몬스터 레어 (세트4,일본판,시스템16B)" },
    { "wb34d", "원더 보이 3 - 몬스터 레어 (세트4,일본판,시스템16B,암호해제)" },
    { "wb35", "원더 보이 3 - 몬스터 레어 (세트5,일본판,시스템16A)" },
    { "wb35a", "원더 보이 3 - 몬스터 레어 (세트6,시스템16A)" },
    { "wb35d", "원더 보이 3 - 몬스터 레어 (세트5,일본판,시스템16A,암호해제)" },
    { "wb3a", "원더 보이 3 - 몬스터 레어 (세트2)" },
    { "wb3bbl", "원더 보이 3 - 몬스터 레어 (해적판)" },
    { "wb3bl", "원더 보이 3 - 몬스터 레어 (해적판)" },
    { "wbbc97", "비치 페스티벌 월드 챔피언십 1997" },
    { "wbdeluxe", "원더 보이 디럭스" },
    { "wbeachv2", "월드 비치 발리볼 (세트2)" },
    { "wbeachvl", "월드 비치 발리볼" },
    { "wbeachvl2", "월드 비치 발리볼 (세트2)" },
    { "wbeachvl3", "월드 비치 발리볼 (세트3)" },
    { "wbeachvla", "월드 비치 발리볼" },
    { "wbml", "원더 보이 인 몬스터 랜드 (일본 신버전)" },
    { "wbmlb", "원더 보이 인 몬스터 랜드 (영어 해적판 세트1)" },
    { "wbmlb2", "원더 보이 인 몬스터 랜드 (영어 해적판 세트4)" },
    { "wbmlbg", "원더 보이 인 몬스터 랜드 (영어 해적판 세트2)" },
    { "wbmlbge", "원더 보이 인 몬스터 랜드 (영어 해적판 세트3)" },
    { "wbmld", "원더 보이 인 몬스터 랜드 (일본 신버전의 해독된 해적판)" },
    { "wbmldk", "원더 보이 인 몬스터 랜드 (한글,신형)" },
    { "wbmlh", "원더 보이 인 몬스터 랜드 (영어,난이도핵)" },
    { "wbmlj", "원더 보이 인 몬스터 랜드 (일본판 세트1)" },
    { "wbmlj2", "원더 보이 인 몬스터 랜드 (일본판 세트2)" },
    { "wbmljb", "원더 보이 인 몬스터 랜드 (일본 해적판)" },
    { "wbmljo", "원더 보이 인 몬스터 랜드 (일본 구버전)" },
    { "wbmljod", "원더 보이 인 몬스터 랜드 (일본 구버전의 해독된 해적판)" },
    { "wbmlju", "원더 보이 인 몬스터 랜드 (일본판 비암호화)" },
    { "wbmlkb", "원더 보이 인 몬스터 랜드 (한글)" },
    { "wbmlkod", "원더 보이 인 몬스터 랜드 (한글,구형)" },
    { "wbmlvc", "원더 보이 인 몬스터 랜드 (영어,버추얼 콘솔)" },
    { "wbmlvcd", "원더 보이 인 몬스터 랜드 (해독된 영어 해적판,버추얼 콘솔 릴리스)" },
    { "wboy", "원더 보이" },
    { "wboy2", "원더 보이 (세트2)" },
    { "wboy2u", "원더 보이 (세트2,비암호화)" },
    { "wboy3", "원더 보이 (세트3)" },
    { "wboy4", "원더 보이 (세트4)" },
    { "wboy4u", "원더 보이 (세트4 비암호화)" },
    { "wboy5", "원더 보이 (세트5,해적판)" },
    { "wboy6", "원더 보이 (세트6)" },
    { "wboyblt", "원더 보이 (테크프라이 해적판)" },
    { "wboyo", "원더 보이 (세트1)" },
    { "wboysys2", "원더 보이 (시스템2)" },
    { "wboysys2a", "원더 보이 (시스템2)" },
    { "wboyu", "원더 보이 (비암호화)" },
    { "wboyub", "원더 보이 (미국 해적판)" },
    { "wc90", "테크모 월드컵" },
    { "wc90a", "테크모 월드컵 (유럽판 세트1)" },
    { "wc90b", "테크모 월드컵 (유럽판 세트2)" },
    { "wc90b1", "유로 리그" },
    { "wc90b2", "월드컵 90" },
    { "wc90t", "테크모 월드컵" },
    { "wcat3", "와일드 캣 3" },
    { "wcatcher", "마작 와쿠와쿠 캐쳐" },
    { "wcbowl", "월드 클래스 볼링 (v1.66)" },
    { "wcbowl10", "월드 클래스 볼링 (v1.0)" },
    { "wcbowl11", "월드 클래스 볼링 (v1.1)" },
    { "wcbowl12", "월드 클래스 볼링 (v1.2)" },
    { "wcbowl13", "월드 클래스 볼링 (v1.3)" },
    { "wcbowl130", "월드 클래스 볼링 토너먼트 (v1.30)" },
    { "wcbowl13j", "월드 클래스 볼링 (v1.3J,일본판)" },
    { "wcbowl14", "월드 클래스 볼링 (v1.4)" },
    { "wcbowl140", "월드 클래스 볼링 토너먼트 (v1.40)" },
    { "wcbowl15", "월드 클래스 볼링 (v1.5)" },
    { "wcbowl16", "월드 클래스 볼링 (v1.6)" },
    { "wcbowl161", "월드 클래스 볼링 (v1.61)" },
    { "wcbowl165", "월드 클래스 볼링 (v1.65)" },
    { "wcbowldx", "월드 클래스 볼링 디럭스 (v2.00)" },
    { "wcbwl12", "월드 클래스 볼링 (v1.2)" },
    { "wcbwl140", "월드 클래스 볼링 토너먼트 (v1.40)" },
    { "wcbwl161", "월드 클래스 볼링 (v1.61)" },
    { "wcbwl165", "월드 클래스 볼링 (v1.65)" },
    { "wccf116", "월드 클럽 챔피언 풋볼 시리즈 A 2001-2002 v2 (일본판)" },
    { "wccf212e", "월드 클럽 챔피언 풋볼 시리즈 A 2002-2003 v2.12 (이탈리아판)" },
    { "wccf234j", "월드 클럽 챔피언 풋볼 시리즈 A 2002-2003 v2.34 (일본판)" },
    { "wccf310j", "월드 클럽 챔피언 풋볼 유러피언 클럽 2004-2005 (아시아판)" },
    { "wccf322e", "월드 클럽 챔피언 풋볼 유러피언 클럽 2004-2005 v3.22 (수출판)" },
    { "wccf331e", "월드 클럽 챔피언 풋볼 유러피언 클럽 2004-2005 v1.1 (수출판)" },
    { "wccf331j", "월드 클럽 챔피언 풋볼 유러피언 클럽 2004-2005 v1.1 (일본판)" },
    { "wccf341j", "월드 클럽 챔피언 풋볼 유러피언 클럽 2004-2005 v1.2 (일본판)" },
    { "wccf400j", "월드 클럽 챔피언 풋볼 유러피언 클럽 2005-2006 (일본판)" },
    { "wccf420e", "월드 클럽 챔피언 풋볼 유러피언 클럽 2005-2006 (수출판)" },
    { "wcombat", "월드 컴뱃" },
    { "wcombatj", "월드 컴뱃" },
    { "wcombatk", "월드 컴뱃" },
    { "wcvol95", "월드컵 발리볼 95 (아시아판 v1.0)" },
    { "wcvol95j", "월드컵 발리볼 95 (일본판 v1.0)" },
    { "wcvol95x", "월드컵 발리볼 95 엑스트라 버전(아시아판 v2.0B)" },
    { "wecleman", "WEC 르망 24 (v2.01)" },
    { "weclemana", "WEC 르망 24 (v2.00)" },
    { "weclemanb", "WEC 르망 24" },
    { "weclemanc", "WEC 르망 24" },
    { "weddingr", "웨딩 랩소디" },
    { "welltrij", "웰트리스 (일본판,2인용)" },
    { "welltris", "웰트리스 (세계판?,2인용)" },
    { "welltrisj", "웰트리스 (일본판,2인용)" },
    { "westgun2", "웨스턴 건 파트2" },
    { "weststry", "카발2/ 서부 이야기" },
    { "weststrya", "카발2/ 서부 이야기" },
    { "wexpresb", "익스프레스 레이더/ 웨스턴 익스프레스 (해적판 세트1)" },
    { "wexpresc", "익스프레스 레이더/ 웨스턴 익스프레스 (해적판 세트2)" },
    { "wexpress", "익스프레스 레이더/ 웨스턴 익스프레스 (일본판,개정판4)" },
    { "wexpressb", "익스프레스 레이더/ 웨스턴 익스프레스 (해적판 세트1)" },
    { "wexpressb1", "익스프레스 레이더/ 웨스턴 익스프레스 (해적판 세트1)" },
    { "wexpressb2", "익스프레스 레이더/ 웨스턴 익스프레스 (해적판 세트2)" },
    { "wexpressb3", "익스프레스 레이더/ 웨스턴 익스프레스 (해적판 세트3)" },
    { "wfishing", "개구쟁이 피싱" },
    { "wfortuna", "휠 오브 포츈 (대체)" },
    { "wfortune", "휠 오브 포츈" },
    { "wfortunea", "휠 오브 포츈 (대체)" },
    { "wg3dh", "웨인 그레츠키 3D 하키" },
    { "wg3dhfe", "웨인 그레츠키 3D 하키" },
    { "wgp", "월드 그랑프리" },
    { "wgp2", "월드 그랑프리 2 (일본판)" },
    { "wgpj", "월드 그랑프리 (일본판)" },
    { "wgpjoy", "월드 그랑프리 (조이스틱 버전)(일본판,세트1)" },
    { "wgpjoya", "월드 그랑프리 (조이스틱 버전)(일본판,세트2)" },
    { "wgpu", "월드 그랑프리 (미국판)" },
    { "wh1", "월드 히어로즈" },
    { "wh1b", "월드 히어로즈 (보스 핵)" },
    { "wh1h", "월드 히어로즈 (ALH-005)" },
    { "wh1ha", "월드 히어로즈 (세트3)" },
    { "wh1k", "월드 히어로즈 (한글)" },
    { "wh2", "월드 히어로즈 2" },
    { "wh2b", "월드 히어로즈 2 (보스 핵)" },
    { "wh2es", "월드 히어로즈 2 (핵)" },
    { "wh2h", "월드 히어로즈 2 (ALH-006)" },
    { "wh2j", "월드 히어로즈 2 제트" },
    { "wh2ja", "월드 히어로즈 2 제트 (ADM-007)" },
    { "wh2jb", "월드 히어로즈 2 제트 (보스 핵)" },
    { "wh2jes", "월드 히어로즈 2 제트 (핵)" },
    { "wh2jh", "월드 히어로즈 2 제트 (세트2)" },
    { "wheelfir", "휠즈 앤 파이어" },
    { "wheelrun", "휠즈 러너" },
    { "whizquiz", "휘즈 퀴즈" },
    { "whizz", "휘즈" },
    { "whodunit", "후 듀닛" },
    { "whodunit8", "후 듀닛 (버전8.0)" },
    { "whoopee", "피피 & 비비스/ 후피!! (테키 파키 하드웨어)" },
    { "whp", "월드 히어로즈 퍼팩트" },
    { "whpb", "월드 히어로즈 퍼팩트 (보스 핵)" },
    { "whpjq", "월드 히어로즈 퍼팩트 (강화,핵)" },
    { "wiggie", "위기 웨기" },
    { "wildfang", "와일드 팡/ 테크모 나이트" },
    { "wildfangh", "와일드 팡" },
    { "wildfangs", "와일드 팡" },
    { "wildplt", "와일드 파일럿" },
    { "willow", "윌로우 (세계판)" },
    { "willowbr", "윌로우" },
    { "willowj", "윌로우 (일본판,일본어)" },
    { "willowje", "윌로우 (일본판,영어 버전)" },
    { "willowu", "윌로우 (미국판)" },
    { "willowuo", "윌로우 (미국판 구버전)" },
    { "wilytowr", "윌리 타워" },
    { "winbingo", "윈 윈 빙고" },
    { "winbingoa", "윈 윈 빙고" },
    { "windheat", "윈딩 히트" },
    { "windheata", "윈딩 히트" },
    { "windheatj", "윈딩 히트 (JAA,일본판 v2.11)" },
    { "windheatu", "윈딩 히트 (UBC,미국판 v2.22)" },
    { "wingforc", "윙 포스 (일본판,시제품)" },
    { "wingwar", "윙 워" },
    { "wingwar360", "윙 워" },
    { "wingwara", "윙 워" },
    { "wingwarj", "윙 워 (일본판)" },
    { "wingwaru", "윙 워 (미국판)" },
    { "wink", "윙크" },
    { "winka", "윙크 (세트2)" },
    { "winner81", "위너 서클" },
    { "winner81b", "위너 서클" },
    { "winner82", "위너 서클" },
    { "winrun", "위닝런 스즈카 그랑프리" },
    { "winrun91", "위닝 런 91" },
    { "winrungp", "위닝 런 수즈카 그랑프리" },
    { "winspike", "위닝 스파이크" },
    { "winspikea", "위닝 스파이크" },
    { "winspikej", "위닝 스파이크 (버전JAA)" },
    { "winspikj", "위닝 스파이크 (버전JAA)" },
    { "wintbob", "윈터 보블" },
    { "winterht", "윈터 히트" },
    { "wiping", "위핑" },
    { "wiseguy", "와이즈 가이" },
    { "witch", "위치" },
    { "witchcda", "위치 카드 (스페인어,세트1)" },
    { "witchcdb", "위치 카드 (스페인어,세트2)" },
    { "witchcdc", "위치 카드 (영어)" },
    { "witchcdd", "위치 카드 (독일판,세트1)" },
    { "witchcde", "위치 카드 (독일판,세트2)" },
    { "witchcdf", "위치 카드 (영어)" },
    { "witchcrd", "위치 카드" },
    { "witchcrda", "위치 카드" },
    { "witchcrdb", "위치 카드" },
    { "witchcrdc", "위치 카드" },
    { "witchcrdd", "위치 카드" },
    { "witchcrde", "위치 카드" },
    { "witchcrdf", "위치 카드" },
    { "witchcrdg", "위치 카드" },
    { "witchcrdh", "위치 카드" },
    { "witchcrdi", "위치 카드" },
    { "witchcrdj", "위치 카드" },
    { "witchgme", "마녀 게임" },
    { "witchjol", "졸리 위치" },
    { "witchstar", "위치 스타" },
    { "wits", "윗츠 (일본판)" },
    { "wivernwg", "와이번 윙즈" },
    { "wiz", "위즈" },
    { "wizard", "위저드" },
    { "wizdfire", "위저드 파이어 (해외판 v2.1)" },
    { "wizdfireu", "위저드 파이어 (미국판 v1.1)" },
    { "wizt", "위즈 (타이토,세트1)" },
    { "wizta", "위즈 (타이토,세트2)" },
    { "wizwarz", "위즈 워즈" },
    { "wizzquiz", "위즈 퀴즈" },
    { "wizzquiza", "위즈 퀴즈 (버전4)" },
    { "wizzquza", "위즈 퀴즈 (버전4)" },
    { "wjammerk", "윈드잼머스/ 플라잉 파워 디스크 (한글)" },
    { "wjammers", "윈드잼머스/ 플라잉 파워 디스크" },
    { "wjammersk", "윈드잼머스/ 플라잉 파워 디스크 (한글)" },
    { "wlcc", "만리장성 (중국판,V638C)" },
    { "wldarrow", "와일드 애로우" },
    { "wldcourt", "월드 코트 (일본판)" },
    { "wldgunsb", "와일드 건즈" },
    { "wldkicks", "월드 킥스 (세계판)" },
    { "wldkicksj", "월드 킥스" },
    { "wldkickspj", "월드 킥스 PCB" },
    { "wldkickspw", "월드 킥스 PCB" },
    { "wldkicksu", "월드 킥스" },
    { "wldrider", "와일드 라이더즈" },
    { "wldwitch", "와일드 위치" },
    { "wldwitcha", "와일드 위치" },
    { "wldwitchc", "와일드 위치" },
    { "wldwitchd", "와일드 위치" },
    { "wldwitchf", "와일드 위치" },
    { "wldwitchg", "와일드 위치" },
    { "wldwitchh", "와일드 위치" },
    { "wldwitchi", "와일드 위치" },
    { "wldwitchj", "와일드 위치" },
    { "wldwitchk", "와일드 위치" },
    { "wldwitchl", "와일드 위치" },
    { "wldwitchm", "와일드 위치" },
    { "wldwitchn", "와일드 위치" },
    { "wldwitcho", "와일드 위치" },
    { "wldwitchp", "와일드 위치" },
    { "wldwitchq", "와일드 위치" },
    { "wldwitchr", "와일드 위치" },
    { "wldwitchs", "와일드 위치" },
    { "wldwitcht", "와일드 위치" },
    { "wldwitchu", "와일드 위치" },
    { "wldwitchv", "와일드 위치" },
    { "wlstar", "원더리그 스타 - 속 매직볼 파이팅 (한국판)" },
    { "wmatch", "워터 매치" },
    { "wmg", "윌리엄 멀티게임" },
    { "wndrmomo", "원더 모모" },
    { "wndrplnt", "원더 플래닛 (일본판)" },
    { "wof", "천지를 먹다 2_워리어즈 오브 페이트 (세계판)" },
    { "wof1v3", "천지를 먹다 2 적벽의 전투 (1v3,핵)" },
    { "wof1v3p", "천지를 먹다 2 적벽의 전투 (1v3플러스,핵)" },
    { "wof3js", "천지를 먹다 2 삼검성 (중국 해적판 세트1)" },
    { "wof3jsa", "천지를 먹다 2 삼검성 (중국 해적판 세트2)" },
    { "wof3sj", "천지를 먹다 2 삼성검 (중국 해적판 세트1)" },
    { "wof3sja", "천지를 먹다 2 삼성검 (중국 해적판 세트2)" },
    { "wofa", "천지를 먹다 2 (아시아판)" },
    { "wofabl", "천지를 먹다 2 (해적판)" },
    { "wofabla", "천지를 먹다 2 (아시아판,해적판,세트2)" },
    { "wofah", "천지를 먹다 2 (핵 세트1,아시아판)" },
    { "wofaha", "천지를 먹다 2 (핵 세트2,아시아판)" },
    { "wofahb", "천지를 먹다 2 (핵 세트3,아시아판)" },
    { "wofc", "천지를 먹다 2 (T-Chi)" },
    { "wofch", "천지를 먹다 2 적벽의 전투 (CPS 체인저,일본판)" },
    { "wofch3p", "천지를 먹다 2 적벽의 전투 (CPS 체인저 3P,일본판,우라모드해제)" },
    { "wofchdx", "삼국지 III 외전: 하후은의 복수 DX (핵)" },
    { "wofchk", "천지를 먹다 2 적벽의 전투 (CPS 체인저,한글)" },
    { "wofchku", "천지를 먹다 2 적벽의 전투 (CPS 체인저,한글,우라모드해제)" },
    { "wofchp", "천지를 먹다 2" },
    { "wofchu", "천지를 먹다 2 적벽의 전투 (CPS 체인저,일본판,우라모드해제)" },
    { "wofdr", "천지를 먹다 2 적벽의 전투 (마스터,핵)" },
    { "wofdr20", "천지를 먹다 2 적벽의 전투 (마스터2020,핵)" },
    { "wofdr2020", "천지를 먹다 2 적벽의 전투 (마스터 2020,핵)" },
    { "wofh", "천지를 먹다 2 삼국영웅전 (중국 해적판 세트1,아시아판)" },
    { "wofha", "천지를 먹다 2 삼국영웅전 (중국 해적판 세트2,아시아판)" },
    { "wofhfb", "화봉황 (중국판 해적판)" },
    { "wofhfh", "천지를 먹다 2 화봉황 (중국 해적판,아시아판)" },
    { "wofj", "천지를 먹다 2 적벽의 전투 (일본판)" },
    { "wofj103", "천지를 먹다 2 메이 자매의 역습 (일본판,핵)" },
    { "wofjdr", "천지를 먹다 2 적벽의 전투 (마스터 에디션,핵)" },
    { "wofjh", "천지를 먹다 2 (핵,일본판)" },
    { "wofk", "천지를 먹다 2 적벽의 전투 (한글)" },
    { "wofk103", "천지를 먹다 2 메이 자매의 역습 (한글)" },
    { "wofkm3", "천지를 먹다 2 적벽의 전투 (서브젝트3,핵)" },
    { "wofmws", "천지를 먹다 2 적벽의 전투 (3M워리어즈,핵)" },
    { "wofmz1v3", "천지를 먹다 2 적벽의 전투 (카발리1v3,핵)" },
    { "wofpic", "천지를 먹다 2 (해적판 PIC16C57)" },
    { "wofr1", "천지를 먹다 2 (세계판)" },
    { "wofr1bl", "천지를 먹다 2 (세계판,해적판)" },
    { "wofsc", "천지를 먹다 2 적벽의 전투 (스위쳐블 캐릭터,핵)" },
    { "wofsgzb", "천지를 먹다 2 삼국쟁패 (중국 해적판)" },
    { "wofsj", "천지를 먹다 2 생건삼국 (중국 해적판 세트1,아시아판)" },
    { "wofsja", "천지를 먹다 2 생건삼국 (중국 해적판 세트2,아시아판)" },
    { "wofsjb", "천지를 먹다 2 생건삼국 (중국 해적판 세트3,아시아판)" },
    { "wofsjc", "천지를 먹다 2 생건삼국 (중국 해적판 세트4,아시아판)" },
    { "wofsm", "천지를 먹다 2 적벽의 전투 (3M,핵)" },
    { "wofu", "천지를 먹다 2 (미국판)" },
    { "wofwjq", "천지를 먹다 2 적벽의 전투 (워리어즈 강화,핵)" },
    { "wofwp", "천지를 먹다 2 적벽의 전투 (워리어즈 플러스,핵)" },
    { "wofzl", "천지를 먹다 2 적벽의 전투 (울프 워리어즈,핵)" },
    { "wolffang", "공아 2001-울프 팡 (일본판)" },
    { "wolfpack", "울프 팩" },
    { "wonder3", "쓰리 원더스/ 원더 3 (일본판)" },
    { "wonder3k", "쓰리 원더스/ 원더 3 (한글)" },
    { "wondl96", "원더리그 96 (한국판)" },
    { "wondstck", "원더 스틱 (세트1)" },
    { "wondstcka", "원더 스틱 (세트2,검열)" },
    { "woodpeca", "딱따구리 (세트2)" },
    { "woodpeck", "딱따구리 (세트1)" },
    { "woodpek", "딱따구리 (세트1)" },
    { "woodpeka", "딱따구리 (세트2)" },
    { "worldadv", "월드 어드벤쳐" },
    { "worldc94", "테크모 월드컵 94" },
    { "worldwar", "월드 워즈 (세계판?)" },
    { "wotw", "워 오브 더 월드" },
    { "wotwc", "워 오브 더 월드 (컬러)" },
    { "wow", "위저드 오브 워" },
    { "wowg", "위저드 오브 워 (독일어 롬)" },
    { "wownfant", "와우 뉴 판타지아" },
    { "wownfanta", "와우 뉴 판타지아" },
    { "wpksoc", "월드 피케이 싸커" },
    { "wpksocv2", "월드 피케이 싸커 V2 (버전1.1)" },
    { "wrally", "월드 랠리" },
    { "wrally2", "월드 랠리 2 - 트윈 레이싱 (마스크 롬 버전)" },
    { "wrally2a", "월드 랠리 2 - 트윈 레이싱 (EPROM 버전)" },
    { "wrallya", "월드 랠리 (버전1.0,체크섬 3873)" },
    { "wrallyat", "월드 랠리 (미국판)" },
    { "wrallyata", "월드 랠리 (미국판)" },
    { "wrallyb", "월드 랠리 (버전1.0,체크섬 8AA2)" },
    { "wrallyc", "월드 랠리 (버전1.0,체크섬 E586)" },
    { "wrecking", "레킹 크루" },
    { "wrestwa1", "레슬 워 (세트1,일본판)" },
    { "wrestwa2", "레슬 워 (세트2,세계판)" },
    { "wrestwar", "레슬 워 (세트3,세계판)" },
    { "wrestwar1", "레슬 워 (세트1,일본판)" },
    { "wrestwar1d", "레슬 워 (세트1,일본판,암호해제)" },
    { "wrestwar2", "레슬 워 (세트2,세계판)" },
    { "wrestwar2d", "레슬 워 (세트2,세계판,암호해제)" },
    { "wrofaero", "워 오브 에어로 - 프로젝트 MEIOU" },
    { "wrungp", "웨이브 러너 GP" },
    { "wrungpo", "웨이브 러너 GP" },
    { "ws", "프로 야구 월드 스타디움 (일본판)" },
    { "ws89", "프로 야구 월드 스타디움 89 (일본판)" },
    { "ws90", "프로 야구 월드 스타디움 90 (일본판)" },
    { "wsbbgd", "월드 시리즈 베이스볼/ 슈퍼 메이져 리그 (GDS-0010)" },
    { "wschamp", "윙 슈팅 선수권대회 V2.00" },
    { "wschampa", "윙 슈팅 선수권대회 V1.01" },
    { "wschampb", "윙 슈팅 선수권대회 V1.00" },
    { "wseries", "월드 시리즈" },
    { "wseries0", "월드 시리즈" },
    { "wsf", "월드 사커 파이널" },
    { "wsf3", "월드 사커 파이널" },
    { "wsjr", "누가 조니 락을 쏘았나 v1.6" },
    { "wsjr15", "누가 조니 락을 쏘았나 v1.5" },
    { "wstrike", "위치 스트라이크" },
    { "wstrikea", "위치 스트라이크" },
    { "wtchjack", "위치 잭" },
    { "wtchjacka", "위치 잭" },
    { "wtchjackb", "위치 잭" },
    { "wtchjackc", "위치 잭" },
    { "wtchjackd", "위치 잭" },
    { "wtchjacke", "위치 잭" },
    { "wtchjackf", "위치 잭" },
    { "wtchjackg", "위치 잭" },
    { "wtchjacki", "위치 잭" },
    { "wtchjackj", "위치 잭팟" },
    { "wtennis", "월드 테니스" },
    { "wtigernz", "화이트 타이거" },
    { "wtrnymph", "워터 님프" },
    { "wulybuly", "울리 불리" },
    { "wupndown", "위치 업 앤 다운" },
    { "wupndowna", "위치 업 앤 다운" },
    { "wupndownb", "위치 업 앤 다운" },
    { "wupndownc", "위치 업 앤 다운" },
    { "wupndownd", "위치 업 앤 다운" },
    { "ww3", "WW 3" },
    { "wwally", "월리는 어디에?" },
    { "wwally1", "월리는 어디에?" },
    { "wwallyj", "월리를 찾아라! (개정판B,일본판)" },
    { "wwallyja", "월리를 찾아라! (개정판A,일본판)" },
    { "wwallyja3p", "월리를 찾아라! (개정판A,일본판,3인용)" },
    { "wwallyjad", "월리를 찾아라! (개정판A,일본판,암호해제)" },
    { "wwallyjd", "월리를 찾아라! (개정판B,일본판,암호해제)" },
    { "wwanpanm", "두근 두근 호빵맨" },
    { "wwanpanmo", "두근 두근 호빵맨" },
    { "wwester1", "와일드 웨스턴 (세트2)" },
    { "wwestern", "와일드 웨스턴 (세트1)" },
    { "wwestern1", "와일드 웨스턴 (세트2)" },
    { "wwfmanac", "WWF - 레슬매니아 (애시드클라운SP2)" },
    { "wwfmania", "WWF - 레슬매니아 (개정판1.30)" },
    { "wwfmaniab", "WWF - 레슬매니아 (개정판1.20)" },
    { "wwfmaniac", "WWF - 레슬매니아 (개정판1.07)" },
    { "wwfmaniap", "WWF - 레슬매니아 (시험판 2.01)" },
    { "wwfroyal", "WWF 로얄 럼블" },
    { "wwfsstaa", "WWF 슈퍼스타즈 (미국판,신형)" },
    { "wwfsstaj", "WWF 슈퍼스타즈 (일본판)" },
    { "wwfsstar", "WWF 슈퍼스타즈 (유럽판)" },
    { "wwfsstara", "WWF 슈퍼스타즈 (미국판,신형)" },
    { "wwfsstarb", "WWF 슈퍼스타즈" },
    { "wwfsstarb2", "WWF 슈퍼스타즈 (해적판)" },
    { "wwfsstarc", "WWF 슈퍼스타즈 (캐나다판)" },
    { "wwfsstarj", "WWF 슈퍼스타즈 (일본판)" },
    { "wwfsstaru", "WWF 슈퍼스타즈 (미국판)" },
    { "wwfsstaru4", "WWF 슈퍼스타즈 (미국판 개정판4)" },
    { "wwfsstaru6", "WWF 슈퍼스타즈 (미국판 개정판6)" },
    { "wwfsstaru7", "WWF 슈퍼스타즈 (미국판 개정판7)" },
    { "wwfsstau", "WWF 슈퍼스타즈 (미국판)" },
    { "wwfwfest", "WWF 레슬페스트 (세계판)" },
    { "wwfwfesta", "WWF 레슬페스트 (미국판)" },
    { "wwfwfestb", "WWF 레슬페스트 (미국판 해적판)" },
    { "wwfwfestj", "WWF 레슬페스트 (일본판)" },
    { "wwfwfestk", "WWF 레슬페스트 (한국판)" },
    { "wwfwfestu", "WWF 레슬페스트" },
    { "wwfwfestu1", "WWF 레슬페스트 (미국판)" },
    { "wwfwfestub", "WWF 레슬페스트 (미국판 해적판)" },
    { "wwfwfsta", "WWF 레슬페스트 (미국판)" },
    { "wwfwfstb", "WWF 레슬페스트 (미국판 해적판)" },
    { "wwfwfstj", "WWF 레슬페스트 (일본판)" },
    { "wwjgtin", "와이 와이 자키 게이트 인" },
    { "wwmarine", "두근 두근 마린" },
    { "wyvernf0", "와이번 F-0 (개정판1)" },
    { "wyvernf0a", "와이번 F-0" },
    { "wyvernwg", "와이번 윙즈" },
    { "wyvernwga", "와이번 윙즈 (세트2)" },
};

const size_t lookup_w_count = A_SIZE(lookup_w_table);

const char *lookup_w(const char *name) {
    if (!name) return NULL;
    for (size_t i = 0; i < lookup_w_count; i++) {
        if (strcmp(lookup_w_table[i].name, name) == 0) {
            return lookup_w_table[i].value;
        }
    }
    return NULL;
}

const char *r_lookup_w(const char *value) {
    if (!value) return NULL;
    for (size_t i = 0; i < lookup_w_count; i++) {
        if (strstr(lookup_w_table[i].value, value)) {
            return lookup_w_table[i].name;
        }
    }
    return NULL;
}

void lookup_w_multi(const char *term, void (*emit)(const char *name, const char *value, void *udata), void *udata) {
    if (!term) return;
    for (size_t i = 0; i < lookup_w_count; i++) {
        if (strcasestr(lookup_w_table[i].name, term))
            emit(lookup_w_table[i].name, lookup_w_table[i].value, udata);
    }
}

void r_lookup_w_multi(const char *term, void (*emit)(const char *name, const char *value, void *udata), void *udata) {
    if (!term) return;
    for (size_t i = 0; i < lookup_w_count; i++) {
        if (strcasestr(lookup_w_table[i].value, term))
            emit(lookup_w_table[i].name, lookup_w_table[i].value, udata);
    }
}
