#include <string.h>
#include "../common/common.h"
#include "lookup.h"

const LookupName lookup_l_table[] = {
    { "labyrunk", "트릭 트랩/ 라비린스 러너 (세계판 버전K)" },
    { "labyrunr", "트릭 트랩/ 라비린스 러너 (일본판)" },
    { "labyrunrf", "트릭 트랩/ 라비린스 러너 (세계판 버전F)" },
    { "labyrunrk", "트릭 트랩/ 라비린스 러너 (세계판 버전K)" },
    { "lacrazyc", "렛츠 어택 크레이지 크로스" },
    { "ladybgb2", "무당벌레 (해적판 세트2)" },
    { "ladybug", "무당벌레" },
    { "ladybugb", "무당벌레 (해적판 세트1)" },
    { "ladybugb2", "코시넬 (무당벌레 해적판,세트2)" },
    { "ladybugg", "무당벌레" },
    { "ladyfrog", "레이디 프로그" },
    { "ladygolf", "스트로크 & 매치 골프 (여자 버전)" },
    { "ladygolfe", "스트로크 & 매치 골프 (여자 버전)" },
    { "ladygum", "레이디 검" },
    { "ladykill", "불타라 곤타/ 레이디 킬러" },
    { "ladylinr", "레이디 라이너" },
    { "ladylinra", "레이디 라이너 (세트2)" },
    { "ladylinrb", "레이디 라이너 (암호화,세트1)" },
    { "ladylinrc", "레이디 라이너 (암호화,세트2)" },
    { "ladylinrd", "레이디 라이너 (암호화,세트3)" },
    { "ladylinre", "레이디 라이너 (암호화,세트4)" },
    { "ladymakr", "레이디 메이커" },
    { "ladymstr", "레이디 마스터 오브 쿵푸 (세트1,신형)" },
    { "ladymstr2", "레이디 마스터 오브 쿵후 (세트2,구형)" },
    { "ladymstra", "레이디 마스터 오브 쿵푸" },
    { "lagirl", "LA 걸" },
    { "lagunar", "라구나 레이서" },
    { "lamachin", "LA 머신건" },
    { "landbrk", "랜드 브레이커 (PCB 버전3.02)" },
    { "landbrka", "랜드 브레이커 (PCB 버전3.03)" },
    { "landbrkb", "랜드 브레이커 (PCB 버전1.0)" },
    { "landgear", "랜딩 기어" },
    { "landgeara", "랜딩 기어" },
    { "landgearj", "랜딩 기어" },
    { "landgearja", "랜딩 기어" },
    { "landhigh", "랜딩 하이 재팬" },
    { "landmakr", "랜드 메이커 (버전2.02O)" },
    { "landmakrhe", "랜드 메이커 (영어 번역 핵)" },
    { "landmakrj", "랜드 메이커 (버전2.01J)" },
    { "landmakrp", "랜드 메이커 (버전2.02O)(시험판)" },
    { "landmkrp", "랜드 메이커 (버전2.02O)(시험판)" },
    { "lans2004", "랜스퀴넷 2004" },
    { "laperla", "검은 진주" },
    { "laperlag", "검은 진주 골드" },
    { "laser", "아스트로 레이져" },
    { "laser2k1", "레이저 2001" },
    { "laserbas", "레이저 베이스" },
    { "laserbasa", "레이저 베이스 (세트2)" },
    { "laserbat", "레이저 배틀" },
    { "laserbsa", "레이저 베이스 (세트2)" },
    { "lasso", "올가미" },
    { "lasstixx", "레이저 스트릭스 2" },
    { "lastapos", "영계도사 (영문수출)" },
    { "lastbank", "라스트 뱅크" },
    { "lastbd2b", "월화의 검사 2/ 라스트 블레이드 2 (이네이블 히든 캐릭터 V4)" },
    { "lastbd2e", "월화의 검사 2/ 라스트 블레이드 2 (강화,핵)" },
    { "lastbd2i", "월화의 검사 2/ 라스트 블레이드 2 (무한에너지,핵)" },
    { "lastbd2p", "월화의 검사 2/ 라스트 블레이드 2 (플러스,핵)" },
    { "lastbd2t", "월화의 검사 2/ 라스트 블레이드 2 (팀 에디션 핵)" },
    { "lastbh", "라스트 바운티 헌터" },
    { "lastbl2f", "월화의 검사 2/ 라스트 블레이드 2 (시스템 버그수정)" },
    { "lastbl2h", "월화의 검사 2/ 라스트 블레이드 2 (히든 핵)" },
    { "lastblad", "월화의 검사 /라스트 블레이드" },
    { "lastblada", "월화의 검사 /라스트 블레이드 (NGM-2340,대체)" },
    { "lastbladb", "월화의 검사 /라스트 블레이드 (히든 핵)" },
    { "lastbladh", "월화의 검사 /라스트 블레이드 (NGH-2340)" },
    { "lastbladsp", "월화의 검사 /라스트 블레이드 (스페셜 2017,핵)" },
    { "lastbld2", "월화의 검사 2/ 라스트 블레이드 2" },
    { "lastbld2eh", "월화의 검사 2/ 라스트 블레이드 2 (강화 핵)" },
    { "lastbld2te", "월화의 검사 2/ 라스트 블레이드 2 (팀 에디션 핵)" },
    { "lastbld2uh", "월화의 검사 2/ 라스트 블레이드 2 (AES 미검열 핵)" },
    { "lastblda", "월화의 검사 /라스트 블레이드 (세트2)" },
    { "lastbldh", "월화의 검사 /라스트 블레이드 (NGH-2340)" },
    { "lastbldi", "월화의 검사 /라스트 블레이드 (무한에너지,핵)" },
    { "lastbldp", "월화의 검사 /라스트 블레이드 (플러스,핵)" },
    { "lastblsp", "월화의 검사 /라스트 블레이드 (스페셜 2017,핵)" },
    { "lastbrnj", "라스트 브롱크스 (일본판,개정판A)" },
    { "lastbrnx", "라스트 브롱크스" },
    { "lastbrnxj", "라스트 브롱크스 (일본판,개정판A)" },
    { "lastday", "라스트 데이 (세트1)" },
    { "lastdaya", "라스트 데이 (세트2)" },
    { "lastduel", "라스트 듀얼 (미국판 신버전)" },
    { "lastduelb", "라스트 듀얼" },
    { "lastduelj", "라스트 듀얼 (일본판)" },
    { "lastduelo", "라스트 듀얼 (미국판 구버전)" },
    { "lastfero", "토리데 - 라스트 포트리스 (성인)" },
    { "lastfght", "라스트 파이팅" },
    { "lastforg", "토리데 - 라스트 포트리스 (독일판)" },
    { "lastfort", "토리데 - 라스트 포트리스 (일본판,VG420 PCB)" },
    { "lastforte", "토리데 - 라스트 포트리스 (성인,개정판C)" },
    { "lastfortea", "토리데 - 라스트 포트리스 (성인,개정판A)" },
    { "lastfortg", "토리데 - 라스트 포트리스 (독일판)" },
    { "lastfortj", "토리데 - 라스트 포트리스" },
    { "lastfortk", "토리데 - 라스트 포트리스 (한국판)" },
    { "lastfour", "라스트 포" },
    { "lasthope", "라스트 호프" },
    { "lastkm", "라스트 KM (버전1.0.0275)" },
    { "lastmisn", "라스트 미션 (세계판 개정판8)" },
    { "lastmisnj", "라스트 미션 (일본판)" },
    { "lastmisno", "라스트 미션 (미국판 개정판5)" },
    { "lastmisnu5", "라스트 미션 (미국판 개정판5)" },
    { "lastmisnu6", "라스트 미션 (미국판 개정판6)" },
    { "lastmiss", "라스트 미션" },
    { "lastmsnj", "라스트 미션 (일본판)" },
    { "lastmsno", "라스트 미션 (미국판 개정판5)" },
    { "lastmss2", "라스트 미션 (미국판 개정판5)" },
    { "lastsold", "월화의 검사 /라스트 솔져 (한국판)" },
    { "laststar", "라스트 스타파이터" },
    { "lastsurv", "라스트 서바이버" },
    { "lastsurvd", "라스트 서바이버 (암호해제)" },
    { "lasvegas", "라스베가스 너바다" },
    { "lazarian", "라자리안" },
    { "lazercmd", "레이저 커맨드" },
    { "lazybug", "레이지 버그" },
    { "lb2b", "월화의 검사 2/ 라스트 블레이드 2 (히든핵V4)" },
    { "lbeach", "롱 비치" },
    { "lbgrande", "리베로 그랑데" },
    { "lbowling", "리그 볼링" },
    { "lckywldj", "럭키 & 와일드 (일본판)" },
    { "ldrun", "로드 러너 (세트1)" },
    { "ldrun2", "로드 러너 2 - 번질링 스트라이크 백" },
    { "ldrun3", "로드 러너 3 - 황금 미로/ 마신의 부활" },
    { "ldrun3j", "로드 러너 3 - 황금 미로/ 마신의 부활 (일본판)" },
    { "ldrun3jc", "로드 러너 3 - 황금 미로/ 마신의 부활 (일본판,개정판C)" },
    { "ldrun3jp", "로드 러너 3 - 황금 미로/ 마신의 부활" },
    { "ldrun4", "로드 러너 4 - 제국으로부터의 탈출" },
    { "ldruna", "로드 러너 (세트2)" },
    { "le2", "리썰 인포서스 2 - 건 파이터즈" },
    { "le2j", "리썰 인포서스 2 - 웨스턴 (버전JAA)" },
    { "le2u", "리썰 인포서스 2 - 건 파이터즈 (버전UAA)" },
    { "leadang", "데드 앵글/ 리드 앵글 (일본판)" },
    { "leader", "리더" },
    { "leadera", "리더" },
    { "leaguemk", "야구 격투 리그맨 (한글)" },
    { "leaguemn", "야구 격투 리그맨 (일본판)" },
    { "leaguemna", "야구 격투 리그맨 (일본판,세트2)" },
    { "leds2011", "레드 스톰 랠리 2011 (세계판)" },
    { "leds2011p", "레드 스톰 랠리 2011 (미국판,시험판12)" },
    { "leds2011u", "레드 스톰 랠리 2011 (미국판)" },
    { "ledstorm", "레드 스톰 (미국판)" },
    { "ledstorm2", "레드 스톰 랠리 2011 (미국판)" },
    { "ledstrm2", "레드 스톰 랠리 2011 (미국판)" },
    { "legend", "레전드" },
    { "legendb", "레전드/ 레지온 (해적판)" },
    { "legendoh", "레전드 오브 히어로즈" },
    { "legendos", "내일의 죠 전설" },
    { "legendsb", "레전드 (SNES 해적판)" },
    { "legion", "초시미공 레지온/ 레지온 -스피너-87 (세계판 버전2.03)" },
    { "legionj", "초시미공 레지온 (일본판 버전1.05)" },
    { "legionj2", "초시미공 레지온 (일본판 버전1.05)" },
    { "legionjb", "초시미공 레지온 (일본판 버전1.05,해적판 세트1)" },
    { "legionjb2", "초시미공 레지온 (일본판 버전1.05,해적판 세트2)" },
    { "legionna", "리전에어 (세계판)" },
    { "legionnaj", "리전에어 (일본판)" },
    { "legionnau", "리전에어 (미국판)" },
    { "legionnu", "리전에어 (미국판)" },
    { "legiono", "초시미공 레지온 (버전1.05)" },
    { "legofair", "초퍼 I/ 항공 기병 이야기 - 리젼드 오브 에어 카발리 (일본판)" },
    { "legrandc", "르 그랑샹" },
    { "lemans24", "르망 24" },
    { "lemmings", "레밍즈 (미국판 시제품)" },
    { "lemnangl", "마작 레몬 엔젤" },
    { "lependu", "르 팡듀" },
    { "leprechn", "레프리콘" },
    { "leprechna", "레프리콘 (세트2)" },
    { "leprechp", "레프리콘 (퍼시픽)" },
    { "lespendu", "르 시페 팡듀 (V1,세계판 세트#1)" },
    { "lespenduj", "르 시페 팡듀 (V1,세계판 세트#2)" },
    { "lethalej", "리썰 인포서스 (버전JAD)" },
    { "lethalen", "리썰 인포서스 (버전UAE)" },
    { "lethaleneaa", "리썰 인포서스 (버전EAA)" },
    { "lethaleneab", "리썰 인포서스 (버전EAB)" },
    { "lethalenead", "리썰 인포서스 (버전EAD)" },
    { "lethaleneae", "리썰 인포서스 (버전EAE)" },
    { "lethalenj", "리썰 인포서스 (버전JAD)" },
    { "lethalenua", "리썰 인포서스 (버전UAA)" },
    { "lethalenub", "리썰 인포서스 (버전UAB)" },
    { "lethalenux", "리썰 인포서스 (버전불명,US,핵/시험판)" },
    { "lethalj", "리썰 저스티스" },
    { "lethalth", "리썰 썬더 (세계판)" },
    { "letsdnce", "레츠 댄스" },
    { "levers", "레버즈" },
    { "lghost", "레이저 고스트 (세계판)" },
    { "lghostd", "레이저 고스트" },
    { "lghostj", "레이저 고스트 (일본판)" },
    { "lghostu", "레이저 고스트" },
    { "lghostud", "레이저 고스트" },
    { "lgp", "레이저 그랑프리" },
    { "lgtnfght", "라이트닝 파이터즈 (세계판)" },
    { "lgtnfghta", "라이트닝 파이터즈 (아시아판)" },
    { "lgtnfghtu", "라이트닝 파이터즈 (미국판)" },
    { "lgtnfghu", "라이트닝 파이터즈 (미국판)" },
    { "lhaunt_4", "럭키 헌터" },
    { "lhaunt_4a", "럭키 헌터 (백도어)" },
    { "lhaunt_5", "럭키 헌터" },
    { "lhaunt_5a", "럭키 헌터 (백도어)" },
    { "lhaunt_6", "럭키 헌터" },
    { "lhaunt_6a", "럭키 헌터 (백도어)" },
    { "lhb", "용호방" },
    { "lhb2", "용호방 2" },
    { "lhbv33c", "용호방 (중국판,V033C)" },
    { "lhcdb", "라스트 호프 CD베타" },
    { "lhdmg", "용호대만관" },
    { "lhdmgp", "용호대만관 대전가강판" },
    { "lhzb", "용호쟁패" },
    { "lhzb2", "용호쟁패 2" },
    { "lhzb2a", "용호쟁패 2 (세트2)" },
    { "lhzb3", "용호쟁패 3" },
    { "lhzb3106c5m", "용호쟁패 3" },
    { "lhzb3sjb", "용호쟁패 3 승급판" },
    { "lhzb4", "용호쟁패 4" },
    { "lhzb4dhb", "용호쟁패 4 대화판" },
    { "lhzba", "용호쟁패 (세트2)" },
    { "liberat2", "리버레이터 (세트2)" },
    { "liberatb", "리버레이션" },
    { "liberate", "리버레이션" },
    { "liberateb", "리버레이션" },
    { "liberatr", "리버레이터" },
    { "liberatr2", "리버레이터 (세트2)" },
    { "liberatrp", "리버레이터 (시험판)" },
    { "liblrabl", "리블 라블" },
    { "lifefrce", "사라만다/ 라이프포스 (미국판)" },
    { "lifefrcej", "사라만다/ 라이프포스 (일본판)" },
    { "lifefrcj", "사라만다/ 라이프포스 (일본판)" },
    { "lightbr", "라이트 브링어 (버전2.2O)" },
    { "lightbrj", "라이트 브링어 (버전2.1J)" },
    { "link", "링크 (아타리 테트리스 한국 해적판)" },
    { "linkypip", "링키 파이프" },
    { "liquidk", "리퀴드 키즈 (세계판)" },
    { "liquidku", "리퀴드 키즈 (미국판)" },
    { "lithero", "리틀 히어로" },
    { "littlerb", "리틀 로빈" },
    { "livegal", "라이브 걸" },
    { "livequiz", "라이브 퀴즈 쇼" },
    { "lizwiz", "리자드 위자드" },
    { "lkage", "영의 전설 (개정판2)" },
    { "lkagea", "영의 전설 (개정판1)" },
    { "lkageb", "영의 전설" },
    { "lkageb2", "영의 전설 (해적판 세트2)" },
    { "lkageb3", "영의 전설 (해적판 세트3)" },
    { "lkageb4", "영의 전설 (해적판 세트4)" },
    { "lkagebl1", "영의 전설 (해적판 세트1)" },
    { "lkagebl2", "영의 전설 (해적판 세트2)" },
    { "lkagebl3", "영의 전설 (해적판 세트3)" },
    { "lkagebl4", "영의 전설 (해적판 세트4)" },
    { "lkagem", "영의 전설 (개정판2,MSM5232사운드)" },
    { "lkageo", "영의 전설 (구형)" },
    { "lkageoo", "영의 전설 (최종)" },
    { "llander", "루나 랜더 (개정판2)" },
    { "llander1", "루나 랜더 (개정판1)" },
    { "llandert", "루나 랜더 (스크린 테스트)" },
    { "lluck3x3", "럭키 레이디 (3x3 딜)" },
    { "lluck4x1", "럭키 레이디 (4x1 에이스)" },
    { "lnc", "락 앤 체이스" },
    { "lockload", "락드 앤 로디드" },
    { "lockloadu", "락드 앤 로디드 (미국판)" },
    { "lockon", "락 온 (개정판E)" },
    { "lockonc", "락 온 (개정판C)" },
    { "lockonph", "락 온 (필코)" },
    { "locoboot", "로코 모션/ 구땅 가땅" },
    { "locomotn", "로코 모션/ 구땅 가땅" },
    { "loderdfa", "로드 러너 - 디그 파이트 (버전A)" },
    { "loderndf", "로드 러너 - 디그 파이트 (버전B)" },
    { "loderndfa", "로드 러너 - 디그 파이트 (버전A)" },
    { "loffire", "라인 오브 파이어/ 폭탄녀석 (세계판)" },
    { "loffired", "라인 오브 파이어/ 폭탄녀석 (세계판 암호해제)" },
    { "loffirej", "라인 오브 파이어/ 폭탄녀석 (일본판)" },
    { "loffirejd", "라인 오브 파이어/ 폭탄녀석 (일본판 암호해제)" },
    { "loffireu", "라인 오브 파이어/ 폭탄녀석 (미국판)" },
    { "loffireud", "라인 오브 파이어/ 폭탄녀석 (미국판,암호해제)" },
    { "logger", "로거" },
    { "loggerr2", "로거 (개정판2)" },
    { "logicpr2", "로직프로 2 (일본판)" },
    { "logicpro", "로직프로 (일본판)" },
    { "loht", "영웅 톤마의 전설" },
    { "loht_ms", "영웅 톤마의 전설 (자레코 해적판)" },
    { "lohtb", "영웅 톤마의 전설 (해적판,세트1)" },
    { "lohtb2", "영웅 톤마의 전설 (해적판,세트2)" },
    { "lohtb3", "영웅 톤마의 전설 (세계판,해적판)" },
    { "lohtj", "영웅 톤마의 전설 (일본판)" },
    { "lomakai", "마계전설 (세계판)" },
    { "looper", "루퍼" },
    { "looping", "루핑" },
    { "loopinga", "루핑 (세트2)" },
    { "loopingv", "루핑 (세트1)" },
    { "loopingva", "루핑 (세트2)" },
    { "looptris", "룹트리스 (HB)" },
    { "looptrsp", "룹트리스 플러스 (HB)" },
    { "lordgun", "로드 오브 건" },
    { "lordgunu", "로드 오브 건 (미국판)" },
    { "lordofk", "로드 오브 킹 (일본판)" },
    { "lordofkb", "로드 오브 킹 (해적판,비보호)" },
    { "lordofkbp", "로드 오브 킹 (해적판,보호)" },
    { "losttmbh", "잃어버린 무덤 (어려움)" },
    { "losttomb", "잃어버린 무덤 (쉬움)" },
    { "losttombh", "잃어버린 무덤 (어려움)" },
    { "lostwrld", "포가튼 월드/ 로스트 월드 (일본판)" },
    { "lostwrldo", "포가튼 월드/ 로스트 월드 (일본판 구버전)" },
    { "lostwsga", "잃어버린 세계" },
    { "lotlot", "랏 랏" },
    { "lottof2", "로또 펀 2" },
    { "lottofun", "로또 펀" },
    { "lovehous", "마작 러브 하우스 (일본판)" },
    { "loverboy", "러버보이" },
    { "lpadv", "로직프로 어드벤쳐" },
    { "lrescue", "루나 레스큐" },
    { "lrescueabl", "루나 레스큐 (아크틱 해적판)" },
    { "lrescuem", "루나 레스큐 (모델레이싱 해적판,세트1)" },
    { "lrescuem2", "루나 레스큐 (모델레이싱 해적판,세트2)" },
    { "lresort", "라스트 리조트" },
    { "lresortp", "라스트 리조트 (시험판)" },
    { "lsasquad", "랜드 씨 에어 스쿼드/ 육해공 최전선" },
    { "lsrquiz", "레이저 퀴즈 이탈리아" },
    { "lsrquiz2", "레이저 퀴즈 2 이탈리아" },
    { "lsrquiz2i", "레이저 퀴즈 이탈리아 2" },
    { "lstduela", "라스트 듀얼 (미국판 세트2)" },
    { "lstduelb", "라스트 듀얼 (해적판)" },
    { "ltcasin2", "리틀 카지노 2" },
    { "ltcasin2a", "리틀 카지노 2 (v18.1)" },
    { "ltcasin2b", "리틀 카지노 2 (v17.0)" },
    { "ltcasinn", "리틀 카지노" },
    { "ltcasino", "리틀 카지노" },
    { "ltcasinoa", "리틀 카지노 (세트2)" },
    { "lthyp", "용등호요 대전강화판" },
    { "ltorb", "조나스 인디애나와 RA의 잃어버린 신전 (HB)" },
    { "ltswords", "라이트닝 소드" },
    { "luckboom", "럭키 붐" },
    { "luckboomh", "럭키 붐" },
    { "luckgrln", "럭키 걸" },
    { "lucky74", "럭키 74" },
    { "lucky74a", "럭키 74 (해적판,세트2)" },
    { "lucky8", "뉴 럭키 8 라인즈 (세트1)" },
    { "lucky8a", "뉴 럭키 8 라인즈 (세트2)" },
    { "lucky8b", "뉴 럭키 8 라인즈 (세트3)" },
    { "lucky8c", "뉴 럭키 8 라인즈 (세트4)" },
    { "lucky8d", "뉴 럭키 8 라인즈 (세트5)" },
    { "lucky8e", "뉴 럭키 8 라인즈 (세트6)" },
    { "lucky8f", "뉴 럭키 8 라인즈 (세트7)" },
    { "lucky8g", "뉴 럭키 8 라인즈 (세트8)" },
    { "lucky8h", "뉴 럭키 8 라인즈 슈퍼 터보 (핵)" },
    { "lucky8i", "뉴 럭키 8 라인즈 (세트9)" },
    { "lucky8k", "뉴 럭키 8 라인즈 (세트10)" },
    { "lucky8l", "뉴 럭키 8 라인즈 (세트11)" },
    { "lucky8m", "뉴 럭키 8 라인즈 (세트12)" },
    { "luckycoin", "럭키 코인" },
    { "luckygrl", "럭키 걸" },
    { "luckypkr", "럭키 포커" },
    { "luckyrlt", "럭키 룰렛 플러스" },
    { "luckywld", "럭키 & 와일드" },
    { "luckywldj", "럭키 & 와일드 (일본판)" },
    { "luctoday", "운수 좋은 날" },
    { "lufykzku", "보물 받기 루피 해적단" },
    { "lunarba1", "루나 배틀" },
    { "lunarbat", "루나 배틀" },
    { "lupin3", "루팡 3세" },
    { "lupin3a", "루팡 3세 (세트2)" },
    { "lupinsho", "루팡 3세 - 슈팅 (개정판A)(GDS-0018A)" },
    { "lupinshoo", "루팡 3세 - 슈팅 (GDS-0018)" },
    { "luplup", "러프러프 퍼즐/ 장장 퍼즐 (버전3.0)" },
    { "luplup10", "러프러프 퍼즐/ 장장 퍼즐" },
    { "luplup29", "러프러프 퍼즐/ 장장 퍼즐 (버전2.9)" },
    { "luptype", "루팡 3세 - 타이핑 (개정판A)(GDS-0021A)" },
    { "lvcards", "러블리 카드" },
    { "lvcardsa", "러블리 카드 (암호화)" },
    { "lvgirl94", "라스베가스 걸 (걸 '94)" },
    { "lvpoker", "러블리 포커" },
    { "lwings", "아레스의 날개_레전더리 윙스 (미국판 세트1)" },
    { "lwings2", "아레스의 날개_레전더리 윙스 (미국판 세트2)" },
    { "lwingsa", "아레스의 날개_레전더리 윙스 (미국판)" },
    { "lwingsb", "아레스의 날개_레전더리 윙스" },
    { "lwingsj", "아레스의 날개 (일본판)" },
    { "lwingsja", "아레스의 날개 (일본판,개정판. A)" },
    { "lwingsjp", "아레스의 날개 (일본판)" },
    { "lxts3", "토이 스토리 3" },
};

const size_t lookup_l_count = A_SIZE(lookup_l_table);

const char *lookup_l(const char *name) {
    if (!name) return NULL;
    for (size_t i = 0; i < lookup_l_count; i++) {
        if (strcmp(lookup_l_table[i].name, name) == 0) {
            return lookup_l_table[i].value;
        }
    }
    return NULL;
}

const char *r_lookup_l(const char *value) {
    if (!value) return NULL;
    for (size_t i = 0; i < lookup_l_count; i++) {
        if (strstr(lookup_l_table[i].value, value)) {
            return lookup_l_table[i].name;
        }
    }
    return NULL;
}

void lookup_l_multi(const char *term, void (*emit)(const char *name, const char *value, void *udata), void *udata) {
    if (!term) return;
    for (size_t i = 0; i < lookup_l_count; i++) {
        if (strcasestr(lookup_l_table[i].name, term))
            emit(lookup_l_table[i].name, lookup_l_table[i].value, udata);
    }
}

void r_lookup_l_multi(const char *term, void (*emit)(const char *name, const char *value, void *udata), void *udata) {
    if (!term) return;
    for (size_t i = 0; i < lookup_l_count; i++) {
        if (strcasestr(lookup_l_table[i].value, term))
            emit(lookup_l_table[i].name, lookup_l_table[i].value, udata);
    }
}
