#include <string.h>
#include "../common/common.h"
#include "lookup.h"

const LookupName lookup_a_table[] = {
    { "a51mxr3k", "에어리어 51/ 맥시멈 포스 듀오 (R3000)" },
    { "a51mxr3ka", "에어리어 51/ 맥시멈 포스 듀오 (R3000)" },
    { "a51site4", "에어리어 51 - 사이트 4" },
    { "aa", "에일리언 아르마다" },
    { "aafb", "올 아메리칸 풋볼" },
    { "aafbb", "올 아메리칸 풋볼 (개정판B)" },
    { "aafbc", "올 아메리칸 풋볼 (개정판C)" },
    { "aafbd2p", "올 아메리칸 풋볼 (개정판D,2인용)" },
    { "abacus", "아바쿠스" },
    { "abaseb", "아타리 베이스볼" },
    { "abaseb2", "아타리 베이스볼 (세트2)" },
    { "abattle", "아스트로 배틀 (세트1)" },
    { "abattle2", "아스트로 배틀 (세트2)" },
    { "abcheck", "어브노말 체크" },
    { "abcop", "A.B. 캅 (세계판)" },
    { "abcopd", "A.B. 캅 (세계판,암호해제)" },
    { "abcopj", "A.B. 캅 (일본판)" },
    { "abcopjd", "A.B. 캅 (일본판,암호해제)" },
    { "ablast", "펭귄 브라더스/ 굉천뢰 (A 블라스트) (일본판)" },
    { "abnudge", "애니멀 보너스 너지" },
    { "abnudgeb", "애니멀 보너스 너지 (버전2.0,세트1)" },
    { "abnudged", "애니멀 보너스 너지 (버전2.0,세트2)" },
    { "abnudgeo", "애니멀 보너스 너지 (버전1.7)" },
    { "abscam", "압스캠" },
    { "abunai", "위험한 방과후 - 이젠 기다리지 않아" },
    { "aburner", "애프터 버너" },
    { "aburner2", "애프터 버너 2" },
    { "aburner2g", "애프터 버너 2 (독일판)" },
    { "abyssali", "심연의 유아들 (HB)" },
    { "acchi", "가위바위보 게임 저기를 봐 호이!" },
    { "ace", "에이스" },
    { "aceattaa", "에이스 어택커 (일본판,시스템16A)" },
    { "aceattac", "에이스 어택커" },
    { "aceattaca", "에이스 어택커 (일본판,시스템16A)" },
    { "acedrive", "에이스 드라이버 - 레이싱 에볼루션" },
    { "acedrvrw", "에이스 드라이버 - 레이싱 에볼루션" },
    { "acefruit", "실루엣" },
    { "acitya", "아틀랜틱 시티 액션" },
    { "acombat", "아스트로 컴뱃 (신형)" },
    { "acombat3", "아스트로 컴뱃 (신형)" },
    { "acombat4", "아스트로 컴뱃 (신형)" },
    { "acombato", "아스트로 컴뱃 (구형,PZ)" },
    { "acommand", "에일리언 커맨드" },
    { "acrobatm", "아크로뱃 미션" },
    { "acrobatmbl", "아크로뱃 미션" },
    { "act2000", "액션 2000" },
    { "act2000b1", "액션 2000 (버전3.5R,세트2)" },
    { "act2000bx", "액션 2000 (버전3.30XT,세트2)" },
    { "act2000d1", "액션 2000 (버전3.5R,세트1)" },
    { "act2000dx", "액션 2000 (버전3.30XT,세트1)" },
    { "act2000o", "액션 2000 (버전3.3)" },
    { "act2000o2", "액션 2000 (버전3.10XT)" },
    { "act2000o3", "액션 2000 (버전1.2)" },
    { "act2000v1", "액션 2000 (버전3.5R 듀얼)" },
    { "act2000vx", "액션 2000 (버전3.30XT 듀얼)" },
    { "actfanc1", "액트팬서 사이버네틱 하이퍼 웨폰 (세계판 개정판1)" },
    { "actfancj", "액트팬서 사이버네틱 하이퍼 웨폰 (일본판 개정판1)" },
    { "actfancr", "액트팬서 사이버네틱 하이퍼 웨폰 (세계판 개정판3)" },
    { "actfancr1", "액트팬서 사이버네틱 하이퍼 웨폰 (세계판 개정판1)" },
    { "actfancr2", "액트팬서 사이버네틱 하이퍼 웨폰 (세계판 개정판2)" },
    { "actfancrj", "액트팬서 사이버네틱 하이퍼 웨폰 (일본판 개정판1)" },
    { "actionhw", "액션 헐리우드" },
    { "ad2083", "서기 2083" },
    { "adders", "애더 앤 래더" },
    { "adillor", "아마딜로 레이싱 (세계판, AM2 버전A)" },
    { "adillorj", "아마딜로 레이싱 (일본판, AM1 버전A)" },
    { "adonis", "아도니스" },
    { "adpoker", "암스타 드로우 포커" },
    { "aerfboo2", "에어로 파이터즈 (해적판 세트2)" },
    { "aerfboot", "에어로 파이터즈 (해적판 세트1)" },
    { "aeroboto", "에어로보토" },
    { "aerofgt", "에어로 파이터즈/ 소닉 윙즈" },
    { "aerofgtb", "에어로 파이터즈/ 소닉 윙즈 (터보 포스 하드웨어 세트1)" },
    { "aerofgtc", "에어로 파이터즈/ 소닉 윙즈 (터보 포스 하드웨어 세트2)" },
    { "aerofgts", "에어로 파이터즈 스페셜" },
    { "aerofgtst", "에어로 파이터즈 스페셜" },
    { "aerolitol", "에어로리토스" },
    { "aerolitos", "에어로리토스" },
    { "afighter", "액션 파이터" },
    { "afightera", "액션 파이터 (비보호)" },
    { "afighterb", "액션 파이터 (비보호,아날로그 컨트롤)" },
    { "afighterc", "액션 파이터" },
    { "afighterd", "액션 파이터 (아날로그)" },
    { "afightere", "액션 파이터 (System 16B,비암호화,아날로그)" },
    { "afighterf", "액션 파이터 (System 16B,아날로그)" },
    { "afighterg", "액션 파이터 (System 16B)" },
    { "afighterh", "액션 파이터 (System 16B)" },
    { "afire", "아스트로 파이어" },
    { "agallet", "에어 갈렛" },
    { "agalleta", "에어 갈렛 (구형,유럽판)" },
    { "agalletah", "에어 갈렛 (구형,홍콩판)" },
    { "agalletaj", "에어 갈렛/ 아쿠 갈렛 (구형,일본판)" },
    { "agalletak", "에어 갈렛 (구형,한국판)" },
    { "agalletat", "에어 갈렛 (구형,대만판)" },
    { "agalletau", "에어 갈렛 (구형,미국판)" },
    { "agalleth", "에어 갈렛 (홍콩판)" },
    { "agalletj", "에어 갈렛/ 아쿠 갈렛 (일본판)" },
    { "agalletk", "에어 갈렛 (한국판)" },
    { "agallett", "에어 갈렛 (대만판)" },
    { "agalletu", "에어 갈렛 (미국판)" },
    { "agentx1", "클락 & 대거/ 에이전트 X (시험판,개정판1)" },
    { "agentx2", "클락 & 대거/ 에이전트 X (시험판,개정판2)" },
    { "agentx3", "클락 & 대거/ 에이전트 X (시험판,개정판3)" },
    { "agentx4", "클락 & 대거/ 에이전트 X (시험판,개정판4)" },
    { "agress", "어그레스" },
    { "agressb", "어그레스" },
    { "ainferno", "에어 인페르노" },
    { "ainfernoj", "에어 인페르노" },
    { "ainfernou", "에어 인페르노" },
    { "airass", "에어 어썰트 (세계판)" },
    { "airattck", "공습-에어 어택 (세트1)" },
    { "airattcka", "공습-에어 어택 (세트2)" },
    { "airbustj", "에어 버스터 - 트러블 스페셜티 레이드 유닛 (일본판)" },
    { "airbustr", "에어 버스터 - 트러블 스페셜티 레이드 유닛 (세계판)" },
    { "airbustrb", "에어 버스터 - 트러블 스페셜티 레이드 유닛" },
    { "airbustrj", "에어 버스터 - 트러블 스페셜티 레이드 유닛 (일본판)" },
    { "airco22b", "에어 컴뱃 22" },
    { "aircomb", "에어 컴뱃" },
    { "aircombj", "에어 컴뱃 (일본판)" },
    { "aircombu", "에어 컴뱃 (미국판)" },
    { "airduel", "에어 듀얼 (세계판,M82 하드웨어)" },
    { "airdueljm72", "에어 듀얼 (일본판,M72 하드웨어)" },
    { "airduelm72", "에어 듀얼 (세계판,M72 하드웨어)" },
    { "airduelu", "에어 듀얼 (US 로케이션 테스트,M82 하드웨어)" },
    { "airrace", "에어 레이스" },
    { "airraid", "에어 레이드 (암호화)" },
    { "airtrix", "에어 트릭스" },
    { "airwlkrs", "에어 워커즈" },
    { "airwolf", "에어울프" },
    { "airwolfa", "에어울프 (미국판)" },
    { "ajax", "아약스" },
    { "ajaxj", "아약스 (일본판)" },
    { "akamaru", "패널 앤 버라이어티 아카마루 Q 상승 돈트 알" },
    { "akamj", "아카 마작 (더블베트, 버전 1 16)" },
    { "akatana", "아카이 카타나 (마스터 버전)" },
    { "akazukin", "빨간 망토 (일본판)" },
    { "akiss", "마작 엔젤 키스" },
    { "akkaarrh", "아카 아아 (시제품)" },
    { "akkanvdr", "스페이스 인베이더 95/ 아칸베더 (버전2.5J)" },
    { "akumajou", "악마성 드라큘라 (일본판 버전P)" },
    { "akumajoun", "악마성 드라큘라 (일본판 버전N)" },
    { "aladbl", "알라딘" },
    { "aladmdb", "알라딘 (메가드라이브판)" },
    { "alantin", "알라틴 - 알라딘의 요술 램프" },
    { "alcon", "슬랩 파이트/ 알콘 (미국판)" },
    { "alexkid1", "알렉스 키드 - 잃어버린 별 (세트1,불명)" },
    { "alexkida", "알렉스 키드 - 잃어버린 별 (세트2)" },
    { "alexkidd", "알렉스 키드 - 잃어버린 별 (세트2,비보호됨)" },
    { "alexkidd1", "알렉스 키드 - 잃어버린 별 (세트1,불명)" },
    { "alibaba", "알리바바와 40인의 도둑" },
    { "alibabab", "알리바바와 40인의 도둑" },
    { "alien3", "에일리언 3: 더 건 (세계판)" },
    { "alien3j", "에일리언 3: 더 건 (일본판)" },
    { "alien3u", "에일리언 3: 더 건 (미국판)" },
    { "alienar", "에일리언 아레나" },
    { "alienaru", "에일리언 아레나 (스타게이트 업그레이드)" },
    { "aliencha", "에일리언 챌린지 (세계판)" },
    { "alienchac", "에일리언 챌린지 (중국판)" },
    { "aliencr", "에일리언 크러쉬" },
    { "alienfnt", "에일리언 프론트 (개정판T)" },
    { "alienfnta", "에일리언 프론트 (개정판A)" },
    { "alieninv", "에일리언 인베이더" },
    { "alieninvp2", "스페이스 인베이더 파트2" },
    { "alienres", "에일리언 레스큐 (홈브류,테스트 빌드)" },
    { "aliens", "에일리언즈 (세계판 세트1)" },
    { "aliens2", "에일리언즈 (세계판 세트2)" },
    { "aliens3", "에일리언즈 (세계판 세트3)" },
    { "aliens4", "에일리언즈 (세계판 세트4)" },
    { "aliensa", "에일리언즈 (아시아판)" },
    { "aliensec", "바라듀크 (에일리언 섹터)" },
    { "aliensj", "에일리언즈 (일본판 세트1)" },
    { "aliensj2", "에일리언즈 (일본판 세트2)" },
    { "aliensu", "에일리언즈 (미국판 세트1)" },
    { "aliensu2", "에일리언즈 (미국판 세트2)" },
    { "aliensy1", "에일리언 신드롬 (세트1,시스템16A)" },
    { "aliensy2", "에일리언 신드롬 (세트2,시스템16A)" },
    { "aliensy3", "에일리언 신드롬 (세트3,시스템16B)" },
    { "aliensy5", "에일리언 신드롬 (세트5,시스템16A)" },
    { "aliensya", "에일리언 신드롬 (세트2)" },
    { "aliensyb", "에일리언 신드롬 (세트3)" },
    { "aliensyj", "에일리언 신드롬 (일본판)" },
    { "aliensyn", "에일리언 신드롬 (세트4,시스템16B,비보호됨)" },
    { "aliensyn2", "에일리언 신드롬 (세트2,시스템16A)" },
    { "aliensyn3", "에일리언 신드롬 (세트3,시스템16B)" },
    { "aliensyn5", "에일리언 신드롬 (세트5,시스템16A)" },
    { "aliensyn7", "에일리언 신드롬 (세트7,시스템16B)" },
    { "aliensynj", "에일리언 신드롬 (세트6,일본판,신형,시스템16B)" },
    { "aliensynjo", "에일리언 신드롬 (세트1,일본판,구형,시스템16A)" },
    { "aligator", "엘리게이터 헌트 (세계판,보호됨)" },
    { "aligators", "엘리게이터 헌트 (스페인판,보호)" },
    { "aligatorun", "엘리게이터 헌트 (비보호,세트1)" },
    { "aligatoruna", "엘리게이터 헌트 (비보호,세트2)" },
    { "aligatun", "엘리게이터 헌트 (비보호)" },
    { "alinvade", "에일리언 인베이더" },
    { "alleymas", "앨리 마스터" },
    { "alpha1v", "알파 원" },
    { "alphaho", "알파 파이터/ 헤드 온" },
    { "alphahob", "미사일 / 서킷" },
    { "alpham2", "ASO II 라스트 가디언_알파 미션 2" },
    { "alpham2p", "ASO II 라스트 가디언_알파 미션 2 (시험판)" },
    { "alphamc07", "알파엠씨07" },
    { "alphamis", "ASO /알파 미션" },
    { "alphaona", "알파 원 (시험판,5 생명)" },
    { "alphaone", "알파 원" },
    { "alphaonea", "알파 원" },
    { "alphaxz", "알팩스 Z (일본판)" },
    { "alpilot", "에어라인 파일럿 (세계판,개정판B)" },
    { "alpilota", "에어라인 파일럿 (개정판A)" },
    { "alpilotj", "에어라인 파일럿 (세계판,개정판A)" },
    { "alpiltdx", "에어라인 파일럿 (딜럭스,개정판B)" },
    { "alpine", "알파인 스키 (세트1)" },
    { "alpinea", "알파인 스키 (세트2)" },
    { "alpinerc", "알파인 레이서 (개정판AR2 버전C)" },
    { "alpinerd", "알파인 레이서" },
    { "alpinerjc", "알파인 레이서" },
    { "alpines", "알파인 서퍼" },
    { "alpinesa", "알파인 서퍼" },
    { "alpinr2a", "알파인 레이서 2 (개정판ARS2 v.A)" },
    { "alpinr2b", "알파인 레이서 2" },
    { "altair", "알테어" },
    { "altair2", "알테어 2" },
    { "altbeaj1", "수왕기 (세트1,일본판)" },
    { "altbeaj3", "수왕기 (세트3,일본판)" },
    { "altbeas2", "수왕기 (세트2)" },
    { "altbeas4", "수왕기 (세트4)" },
    { "altbeas5", "수왕기 (세트5)" },
    { "altbeasj", "수왕기 (세트6)" },
    { "altbeast", "수왕기 (세트8)" },
    { "altbeast2", "수왕기 (세트2)" },
    { "altbeast4", "수왕기 (세트4)" },
    { "altbeast5", "수왕기 (세트5)" },
    { "altbeast5d", "수왕기 (세트5,암호해제)" },
    { "altbeast6", "수왕기 (세트6)" },
    { "altbeastbl", "수왕기 (해적판)" },
    { "altbeastbl2", "수왕기 (해적판)" },
    { "altbeastj", "수왕기 (세트7,일본판)" },
    { "altbeastj1", "수왕기 (세트1,일본판)" },
    { "altbeastj2", "수왕기 (세트5,일본판)" },
    { "altbeastj3", "수왕기 (세트3,일본판)" },
    { "altbeastj3d", "수왕기 (세트3,일본판,암호해제)" },
    { "am_mg24", "멀티 게임 1" },
    { "am_mg3", "멀티 게임 3" },
    { "am_uslot", "아마틱 슬롯 게임" },
    { "amatelas", "솔저 걸 아마존/ 성전사 아마테라스" },
    { "amazon", "솔져 걸 아마존" },
    { "amazoneo", "솔져 걸 아마존 네오 (HB)" },
    { "amazont", "솔져 걸 아마존 (테크프라이 라이센스)" },
    { "ambush", "앰버쉬" },
    { "ambushh", "앰버쉬 (핵)" },
    { "ambushj", "앰버쉬 (일본판)" },
    { "ambusht", "앰버쉬 (테크프라이)" },
    { "ambushv", "앰버쉬 (볼트 일렉)" },
    { "amerdar2", "아메리다트 (세트2)" },
    { "amerdart", "아메리다트" },
    { "amerdart2", "아메리다트 (세트2)" },
    { "amerdart3", "아메리다트 (세트3)" },
    { "americna", "아메리카나" },
    { "americnaa", "아메리카나" },
    { "amerug", "아메러그" },
    { "amidar", "아미다" },
    { "amidar1", "아미다 (구형)" },
    { "amidarb", "아미다 (해적판,세트1)" },
    { "amidarb2", "아미다 (해적판,세트2)" },
    { "amidaro", "아미다 (올림피아)" },
    { "amidars", "아미다 (스크램블 하드웨어)" },
    { "amidaru", "아미다 (스턴)" },
    { "amigo", "아미고" },
    { "amigo2", "아미고" },
    { "ampkr228", "아메리칸 포커 2" },
    { "ampkr2b1", "아메리칸 포커 2 (해적판,세트1)" },
    { "ampkr2b2", "아메리칸 포커 2 (해적판,세트2)" },
    { "ampkr2b3", "아메리칸 포커 2 (해적판,세트3)" },
    { "ampkr2b4", "아메리칸 포커 2 (해적판,세트4)" },
    { "ampkr95", "아메리칸 포커 95" },
    { "ampoker2", "아메리칸 포커 2" },
    { "ampokr2a", "아메리칸 포커 2 (세트2)" },
    { "ampokr2b", "아메리칸 포커 2 (세트3)" },
    { "ampokr2c", "아메리칸 포커 2 (세트4)" },
    { "amspdwy", "아메리칸 스피드웨이 (세트1)" },
    { "amspdwya", "아메리칸 스피드웨이 (세트2)" },
    { "amusco", "아메리칸 뮤직 포커" },
    { "amuse", "어뮤즈" },
    { "amuse1", "어뮤즈 (버전30.08 IBA)" },
    { "amuse1a", "어뮤즈 (버전30.08A)" },
    { "androdun", "안드로 듀노스" },
    { "androidp", "안드로이드 (시제품,이후 빌드)" },
    { "androidpo", "안드로이드 (시험판,초기 빌드)" },
    { "andromed", "안드로메다" },
    { "angelkds", "엔젤 키즈 (일본판)" },
    { "anibonus", "애니멀 보너스 (버전1.8E 듀얼)" },
    { "anibonusb1", "애니멀 보너스 (버전1.7R,세트1)" },
    { "anibonusb2", "애니멀 보너스 (버전1.7LT,세트1)" },
    { "anibonusd1", "애니멀 보너스 (버전1.7R,세트2)" },
    { "anibonusd2", "애니멀 보너스 (버전1.7LT,세트2)" },
    { "anibonuso", "애니멀 보너스 (버전1.5)" },
    { "anibonuso2", "애니멀 보너스 (버전1.4,세트1)" },
    { "anibonuso3", "애니멀 보너스 (버전1.4,세트2)" },
    { "anibonusv1", "애니멀 보너스 (버전1.8R 듀얼)" },
    { "anibonusv2", "애니멀 보너스 (버전1.8LT 듀얼)" },
    { "anibonusxo", "애니멀 보너스 (버전1.50XT)" },
    { "anibonusxo2", "애니멀 보너스 (버전1.40XT,세트1)" },
    { "anibonusxo3", "애니멀 보너스 (버전1.40XT,세트2)" },
    { "animalc", "애니멀 캐치" },
    { "animalhjb", "애니멀 하우스" },
    { "animalhs", "애니멀 하우스" },
    { "animalhsb", "애니멀 하우스" },
    { "animalhsc", "애니멀 하우스" },
    { "animaljr", "익사이팅 애니멀 랜드 주니어" },
    { "animaljrj", "와이와이 애니멀 랜드 주니어 (일본판)" },
    { "animaljrs", "애니멀랜디아 쥬니어 (스페인어)" },
    { "animechmp", "애니메 챔프" },
    { "animpkr", "불명의 로켓/애니멀-테마 포커" },
    { "anithunt", "애니멀 트레져 헌트" },
    { "anithuntd1", "애니멀 트레져 헌트 (버전1.9R,세트2)" },
    { "anithunto", "애니멀 트레져 헌트 (버전1.7)" },
    { "anithunto2", "애니멀 트레져 헌트 (버전1.5)" },
    { "anithuntv1", "애니멀 트레져 헌트 (버전1.9R 듀얼)" },
    { "anmlbskt", "허슬 공넣기 경쟁" },
    { "anmlbskta", "허슬 공넣기 경쟁 (19 Jan 2005)" },
    { "anpanman", "그래! 호빵맨 팝콘 공장 (개정판B)" },
    { "anpanmana", "그래! 호빵맨 팝콘 공장 (개정판A)" },
    { "anteater", "앤트이터" },
    { "anteaterg", "아마이센바엘 (독일판)" },
    { "anteatergg", "아마이센바엘 (독일 해적판 갤럭시안 하드웨어)" },
    { "anteateruk", "앤트이터 (영국판)" },
    { "anteatg", "아마이센바엘 (독일판)" },
    { "anteatgb", "앤트이터 (영국판)" },
    { "aodk", "통쾌 간간 행진곡" },
    { "aof", "용호의 권 (K,H)" },
    { "aof2", "용호의 권 2" },
    { "aof2a", "용호의 권 2 (NGH-056)" },
    { "aof2b", "용호의 권 2 (보스 핵)" },
    { "aof2bh", "용호의 권 2 (히든캐릭터v2)" },
    { "aof2bhs", "용호의 권 2 (보스 심플 공격판,핵)" },
    { "aof3", "용호의 권 3 - 전사의 길" },
    { "aof3b", "용호의 권 3 - 전사의 길 (보스 핵)" },
    { "aof3bh", "용호의 권 3 - 전사의 길 (히든캐릭터v2)" },
    { "aof3k", "용호의 권 3 - 전사의 길 (한국판)" },
    { "aof3uh", "용호의 권 3 - 전사의 길" },
    { "aofb", "용호의 권 (보스핵)" },
    { "aofbr", "용호의 권 (포르투갈판, 핵)" },
    { "aofk", "용호의 권 (한글,보스 핵)" },
    { "aoh", "실크로드 2 - 에이지 오브 히어로즈 (v0.63)" },
    { "apache3", "아파치 3" },
    { "apache3a", "아파치 3 (개정판E)" },
    { "apache3b", "아파치 3 (카나 라이센스)" },
    { "apb", "올 포인트 뷰레틴 (개정판7)" },
    { "apb1", "올 포인트 뷰레틴 (개정판1)" },
    { "apb2", "올 포인트 뷰레틴 (개정판2)" },
    { "apb3", "올 포인트 뷰레틴 (개정판3)" },
    { "apb4", "올 포인트 뷰레틴 (개정판4)" },
    { "apb5", "올 포인트 뷰레틴 (개정판5)" },
    { "apb6", "올 포인트 뷰레틴 (개정판6)" },
    { "apbf", "올 포인트 뷰레틴 (프랑스판)" },
    { "apbg", "올 포인트 뷰레틴 (독일판)" },
    { "aplarail", "어택 플라 레일 (일본판,AP1/버전A)" },
    { "aplatoon", "플래툰 V" },
    { "aponow", "아포칼립스 나우" },
    { "apparel", "어패럴 나이트" },
    { "apple10", "애플 10" },
    { "appoooh", "압뿌우" },
    { "aquajack", "아쿠아잭 (세계판)" },
    { "aquajackj", "아쿠아 잭 (일본판)" },
    { "aquajacku", "아쿠아 잭 (미국판)" },
    { "aquajckj", "아쿠아 잭 (일본판)" },
    { "aquajet", "아쿠아 젯" },
    { "aquario", "클락워크 아쿠아리오 (시험판)" },
    { "aquarium", "아쿠아리움 (미국판)" },
    { "aquariumj", "아쿠아리움 (일본판)" },
    { "aquarush", "아쿠아 러쉬" },
    { "ar_airh", "스포트타임 테이블 하키" },
    { "ar_airh2", "스포트타임 테이블 하키" },
    { "ar_argh", "Aaargh! (아카디아)" },
    { "ar_blast", "블래스터볼" },
    { "ar_bowl", "스포트타임 볼링" },
    { "ar_dart", "월드 다트" },
    { "ar_dart2", "월드 다트 (아카디아,세트2)" },
    { "ar_dlta", "델타 커맨드 (아카디아)" },
    { "ar_fast", "매직 존슨의 패스트 브레이크" },
    { "ar_fasta", "매직 존슨의 패스트 브레이크 (아카디아,V 2.7)" },
    { "ar_ldrb", "리더 보드 골프 (아카디아,세트1,V 2.5)" },
    { "ar_ldrba", "리더 보드 골프 (아카디아,세트2,V 245)" },
    { "ar_ldrbb", "리더 보드 골프 (아카디아,세트3)" },
    { "ar_ninj", "닌자 미션" },
    { "ar_ninj2", "닌자 미션 (아카디아,세트2)" },
    { "ar_pm", "파라오스 매치 (아카디아)" },
    { "ar_rdwr", "로드워즈" },
    { "ar_sdwr", "사이드와인더" },
    { "ar_sdwr2", "사이드와인더 (아카디아,세트2)" },
    { "ar_socc", "월드 트로피 사커" },
    { "ar_spot", "스팟" },
    { "ar_sprg", "스페이스 레인져" },
    { "ar_xeon", "제논" },
    { "arabfgt", "아라비안 파이트 (세계판)" },
    { "arabfgtj", "아라비안 파이트 (일본판)" },
    { "arabfgtu", "아라비안 파이트 (미국판)" },
    { "arabiamj", "아라비안 매직 (버전1.0J)" },
    { "arabiamu", "아라비안 매직 (버전1.0A)" },
    { "arabian", "아라비안" },
    { "arabiana", "아라비안 (아타리)" },
    { "arabianm", "아라비안 매직 (버전1.0O)" },
    { "arabianmj", "아라비안 매직 (버전1.0J)" },
    { "arabianmu", "아라비안 매직 (버전1.0A)" },
    { "aracnis", "아라크니스" },
    { "arbalest", "아바레스터" },
    { "arcadecl", "아케이드 클래식 (시제품)" },
    { "arcadia", "내 청춘의 아르카디아" },
    { "arcadian", "아르카디아 (NMK)" },
    { "archriv2", "아치 라이벌스 (개정판2.0)" },
    { "archrivl", "아치 라이벌스" },
    { "archrivl2", "아치 라이벌스 (개정판2.0)" },
    { "archrivla", "아치 라이벌스 (개정판2.0)" },
    { "archrivlb", "아치 라이벌스 (개정판2.0, 8-웨이 조이스틱)" },
    { "area51", "에어리어 51" },
    { "area51a", "에어리어 51 (아타리)" },
    { "area51mx", "에어리어 51/ 맥시멈 포스 듀오 v2.0" },
    { "area51t", "에어리어 51 (워너 라이센스)" },
    { "area51ta", "에어리어 51" },
    { "area88", "에어리어 88 (일본판)" },
    { "area88k", "에어리어 88 (한글)" },
    { "area88ka", "에어리어 88 (한글,A형)" },
    { "area88kb", "에어리어 88 (한글,B형)" },
    { "area88r", "에어리어 88 (일본판 재판매)" },
    { "arescue", "에어 레스큐 (세계판)" },
    { "arescuej", "에어 레스큐 (일본판)" },
    { "arescueu", "에어 레스큐 (미국판)" },
    { "argus", "아르고스" },
    { "argusg", "아르고스 (고틀리프, 시험판)" },
    { "arian", "ASO /아리언 미션" },
    { "ark1ball", "알카노이드" },
    { "ark1balla", "알카노이드" },
    { "ark2jp", "알카노이드 - DOH의 복수 (일본판)" },
    { "ark2us", "알카노이드 - DOH의 복수 (미국판)" },
    { "arkaboot", "알카노이드 (해적판,일본판,구형)" },
    { "arkangc", "알카노이드 (해적판,세트1)" },
    { "arkangc2", "알카노이드 (해적판,세트2)" },
    { "arkanoi2", "알카노이드 - DOH의 복수" },
    { "arkanoid", "알카노이드 (세계판,가장 오래된 개정판)" },
    { "arkanoidj", "알카노이드 (일본판)" },
    { "arkanoidja", "알카노이드 (일본판,구형 개정판)" },
    { "arkanoidjb", "알카노이드 (일본판,최종 개정판)" },
    { "arkanoidjbl", "알카노이드" },
    { "arkanoidjbl2", "알카노이드" },
    { "arkanoidjbla", "알카노이드" },
    { "arkanoidpe", "알카노이드" },
    { "arkanoidu", "알카노이드 (미국판)" },
    { "arkanoiduo", "알카노이드 (미국판,최종 개정판)" },
    { "arkarea", "아크 에어리어" },
    { "arkatayt", "알카노이드" },
    { "arkatour", "토너먼트 알카노이드 (미국판)" },
    { "arkatour2", "토너먼트 알카노이드 (미국판,신형)" },
    { "arkbl2", "알카노이드 (일본판 해적판 세트2)" },
    { "arkbl3", "알카노이드 (일본판 해적판 세트3)" },
    { "arkbloc2", "블럭 (해적판,세트2)" },
    { "arkbloc3", "블럭 (해적판,세트3)" },
    { "arkblock", "블럭 (해적판,세트1)" },
    { "arkgcbl", "알카노이드" },
    { "arkgcbla", "알카노이드 (해적판,세트2)" },
    { "arkmcubl", "알카노이드 (해적판 MCU)" },
    { "arknid2j", "알카노이드 - DOH의 복수 (일본판)" },
    { "arknid2u", "알카노이드 - DOH의 복수 (미국판)" },
    { "arknoid2", "알카노이드 - DOH의 복수 (세계판)" },
    { "arknoid2b", "알카노이드 - DOH의 복수 (일본판 해적판)" },
    { "arknoid2j", "알카노이드 - DOH의 복수 (일본판)" },
    { "arknoid2u", "알카노이드 - DOH의 복수 (미국판)" },
    { "arknoidj", "알카노이드 (일본판)" },
    { "arknoidu", "알카노이드 (미국판)" },
    { "arknoiuo", "알카노이드 (미국판,구형)" },
    { "arkretrn", "알카노이드 리턴즈 (버전2.02O)" },
    { "arkretrnj", "알카노이드 리턴즈 (버전2.02J)" },
    { "arkretrnu", "알카노이드 리턴즈 (버전2.02A)" },
    { "arktayt2", "알카노이드 (해적판,어려움)" },
    { "arlingtn", "알링턴 호스 레이싱" },
    { "arlingtna", "알링턴 호스 레이싱" },
    { "armchmp2", "암 챔프 2 v2.6" },
    { "armchmp2o", "암 챔프 2 v1.7" },
    { "armchmp2o2", "암 챔프 2 v2.6" },
    { "armedf", "암드 포메이션" },
    { "armedff", "암드 포메이션 (필름모어 라이센스)" },
    { "armora", "아머 어택" },
    { "armorap", "아머 어택 (시험판)" },
    { "armorar", "아머 어택 (락올라)" },
    { "armorca2", "아머드 카 (세트2)" },
    { "armorcar", "아머드 카 (세트1)" },
    { "armorcar2", "아머드 카 (세트2)" },
    { "armwar", "파워드 기어/ 아머드 워리어즈 (유럽판)" },
    { "armwar1d", "파워드 기어/ 아머드 워리어즈 (유럽판,피닉스에디션)" },
    { "armwara", "파워드 기어/ 아머드 워리어즈 (아시아판)" },
    { "armwarar1", "파워드 기어/ 아머드 워리어즈 (아시아판)" },
    { "armwarb", "파워드 기어/ 아머드 워리어즈 (브라질판)" },
    { "armwarr1", "파워드 기어/ 아머드 워리어즈 (유럽판)" },
    { "armwaru", "파워드 기어/ 아머드 워리어즈 (미국판)" },
    { "armwaru1", "파워드 기어/ 아머드 워리어즈 (미국판)" },
    { "armwrest", "팔씨름" },
    { "ashnojoe", "내일의 죠 (일본판)" },
    { "ashura", "아수라 블래스터 (세계판)" },
    { "ashuraj", "아수라 블래스터 (일본판)" },
    { "ashurau", "아수라 블래스터 (미국판)" },
    { "asideral", "유니워즈" },
    { "asndynmt", "아시안 다이나마이트/ 다이나마이트 데카 EX" },
    { "asndynmto", "아시안 다이나마이트/ 다이나마이트 데카 EX (구형)" },
    { "aso", "ASO 아머드 스크럼 오브젝트" },
    { "asoccer", "아메리칸 사커" },
    { "assault", "어썰트 (개정판B)" },
    { "assaultj", "어썰트 (일본판)" },
    { "assaultp", "어썰트 플러스 (일본판)" },
    { "astdelu1", "아스테로이즈 디럭스 (개정판1)" },
    { "astdelux", "아스테로이드 디럭스 (개정판3)" },
    { "astdelux1", "아스테로이즈 디럭스 (개정판1)" },
    { "astdelux2", "아스테로이즈 디럭스 (개정판2)" },
    { "asterion", "아스테리온" },
    { "asterix", "아스테릭스 (버전EAD)" },
    { "asterixaad", "아스테릭스 (버전AAD)" },
    { "asterixeaa", "아스테릭스 (버전EAA)" },
    { "asterixeac", "아스테릭스 (버전EAC)" },
    { "asterixj", "아스테릭스 (버전JAD)" },
    { "asterock", "아스테락" },
    { "asterockv", "아스테락" },
    { "asteroi1", "아스테로이즈 (개정판1)" },
    { "asteroib", "아스테로이즈" },
    { "asteroid", "아스테로이드 (개정판4)" },
    { "asteroid1", "아스테로이즈 (개정판1)" },
    { "asteroid2", "아스테로이즈 (개정판2)" },
    { "asteroidb", "아스테로이즈" },
    { "asteroidb1", "아스테로이즈 (해적판 세트1)" },
    { "asteroidb2", "아스테로이즈 (해적판 세트2)" },
    { "astinvad", "아스트로 인베이더" },
    { "astoneag", "스톤 에이지" },
    { "astorm", "에일리언 스톰 (세트4,세계판,2인용)" },
    { "astorm2p", "에일리언 스톰 (2인용)" },
    { "astorm3", "에일리언 스톰 (세트3,세계판,3인용)" },
    { "astorm3d", "에일리언 스톰 (세트3,세계판,3인용,암호해제)" },
    { "astormb2", "에일리언 스톰 (해적판,세트2)" },
    { "astormbl", "에일리언 스톰 (해적판,세트1)" },
    { "astormj", "에일리언 스톰 (세트1,일본판 개정판B,2인용)" },
    { "astormjd", "에일리언 스톰 (세트1,일본판 개정판B,2인용,암호해제)" },
    { "astormu", "에일리언 스톰 (세트2,미국판,3인용)" },
    { "astormud", "에일리언 스톰 (세트2,미국판,3인용,암호해제)" },
    { "astrass", "아스트라 슈퍼스타즈" },
    { "astrians", "아스트란스" },
    { "astroamb", "아스트로 앰부쉬" },
    { "astrob", "아스트로 블라스터" },
    { "astrob1", "아스트로 블라스터 (버전1)" },
    { "astrob2", "아스트로 블라스터 (버전2)" },
    { "astrob2a", "아스트로 블라스터 (버전2a)" },
    { "astrob2b", "아스트로 블라스터 (버전2b)" },
    { "astrobf", "아스트로 블라스터 (프랑스판)" },
    { "astrobg", "아스트로 블라스터 (독일판)" },
    { "astrof", "아스트로 파이터" },
    { "astrof2", "아스트로 파이터 (세트2)" },
    { "astrof3", "아스트로 파이터 (세트3)" },
    { "astroff", "아스트로 파이터" },
    { "astroff2", "아스트로 파이터" },
    { "astrofl", "트랜스포머/ 아스트로 플래쉬 (일본판)" },
    { "astroft", "아스트로 파이터 (타이토)" },
    { "astron", "아스트론 벨트" },
    { "astronp", "아스트론 벨트 (파이어니어 LDV1000)" },
    { "astropal", "아스트로팔" },
    { "astrowar", "아스트로 워즈" },
    { "astrxeaa", "아스테릭스 (버전EAA)" },
    { "astrxeac", "아스테릭스 (버전EAC)" },
    { "astyanax", "아스티아낙스" },
    { "astyanaxa", "아스티아낙스" },
    { "asuka", "아스카 & 아스카 (세계판)" },
    { "asukaj", "아스카 & 아스카 (일본판)" },
    { "asukaja", "아스카 & 아스카 (일본판)" },
    { "asurabld", "아수라 블레이드 - 왕조의 검 (일본판)" },
    { "asurabus", "아수라 버스터 - 영원한 전사들 (미국판)" },
    { "asurabusa", "아수라 버스터 - 영원한 전사들 (일본판)(아카디아 리뷰 빌드)" },
    { "asurabusj", "아수라 버스터 - 영원한 전사들 (일본판)" },
    { "asurabusja", "아수라 버스터 - 영원한 전사들 (일본판,세트2)" },
    { "asurabusjr", "아수라 버스터 - 영원한 전사들 (일본판)(아카디아 리뷰빌드)" },
    { "asylum", "어사일럼" },
    { "atamanot", "컴퓨터 퀴즈 머리의 체조" },
    { "ataqandr", "문 크레스타" },
    { "atarifb", "아타리 풋볼" },
    { "atarifb1", "아타리 풋볼 (개정판1)" },
    { "atarifb2", "아타리 풋볼 II" },
    { "atarifb4", "아타리 풋볼 (4인용)" },
    { "ataxx", "어택스" },
    { "ataxxa", "어택스 (세트2)" },
    { "ataxxe", "어택스 (유럽판)" },
    { "ataxxj", "어택스 (일본판)" },
    { "atehate", "아테나는 어디갔을까" },
    { "atetb3482", "테트리스 (해적판 세트6, with UM3482)" },
    { "atetb5205", "테트리스 (해적판 세트7, with OKI M5205)" },
    { "atetckt2", "테트리스 (칵테일 세트2)" },
    { "atetcktl", "테트리스 (칵테일 세트1)" },
    { "atetris", "테트리스 (세트1)" },
    { "atetrisa", "테트리스 (세트2)" },
    { "atetrisb", "테트리스 (해적판 세트1)" },
    { "atetrisb2", "테트리스 (해적판 세트2)" },
    { "atetrisb3", "테트리스 (해적판 세트3)" },
    { "atetrisb4", "테트리스 (해적판 세트4)" },
    { "atetrisbp", "테트리스 (바탑,시험판)" },
    { "atetrisc", "테트리스 (칵테일 세트1)" },
    { "atetrisc2", "테트리스 (칵테일 세트2)" },
    { "atetrsb2", "테트리스 (해적판 세트2)" },
    { "athena", "아테나" },
    { "athenab", "아테나" },
    { "atlantis", "아틀란티스 전투 (세트1)" },
    { "atlantis2", "아틀란티스 전투 (세트2)" },
    { "atlantisb", "아틀란티스 전투" },
    { "atlantol", "트랙 앤 필드/ 아틀랜타 올림픽" },
    { "atlants2", "아틀란티스 전투 (세트2)" },
    { "atombjt", "아톰 (봄잭 트윈 해적판)" },
    { "atomboy", "아토믹 보이 (개정판B)" },
    { "atomboya", "아토믹 보이 (개정판A)" },
    { "atomicp", "아토믹 포인트 (한국판)" },
    { "atompunk", "아토믹 펑크 (미국판)" },
    { "attackf", "어택" },
    { "attackfc", "어택 포스 (암호화)" },
    { "attackfcu", "어택 포스 (비암호화)" },
    { "attckufo", "어택 UFO" },
    { "atworld", "어라운드 더 월드" },
    { "atworldd1", "어라운드 더 월드 (버전1.3R CGA)" },
    { "atworlde1", "어라운드 더 월드 (버전1.3E CGA)" },
    { "au", "Au (로케이션 테스트)" },
    { "aurail", "오레일 (세트3,미국판,비보호됨)" },
    { "aurail1", "오레일 (세트2,세계판)" },
    { "aurail1d", "오레일 (세트2,세계판,해적판)" },
    { "auraila", "오레일 (세트2)" },
    { "aurailj", "오레일 (세트1,일본판)" },
    { "aurailjd", "오레일 (세트1,일본판,해적판)" },
    { "ausfache", "아카츠키 전광전기 Ausf. Achse (일본판)" },
    { "autmoon", "어텀 문" },
    { "automat", "오토매트" },
    { "av2mj1bb", "AV2 마작 No.1 베이브릿지의 성녀" },
    { "av2mj2rg", "AV2 마작 No.2 루즈의 향기" },
    { "avalnche", "아발란치" },
    { "avalon13", "키 오브 아발론 1.3 - 카오틱 사벳 - 클라이언트" },
    { "avalon20", "키 오브 아발론 2.0 - 유탁시 앤드 코맨드먼트 - 클라이언트" },
    { "avalons", "키 오브 아발론 - 위자드 마스터 - 서버" },
    { "avefenix", "아베 페닉스 (스페인어 해적판)" },
    { "avefenixl", "아베 페닉스" },
    { "avefenixrf", "아베 페닉스" },
    { "avenger2", "어벤져스 (미국판 세트2)" },
    { "avengers", "어벤저스 (미국판,세트1)" },
    { "avengers2", "어벤져스 (미국판 세트2)" },
    { "avengersa", "어벤저스 (미국판,개정판A)" },
    { "avengersb", "어벤저스 (미국판)" },
    { "avengersc", "어벤저스 (미국판,불명)" },
    { "avengrgj", "어벤져스 인 갤럭틱 스톰 (일본판)" },
    { "avengrgs", "어벤져스 인 갤럭틱 스톰 (미국판)" },
    { "avengrgsbh", "어벤져스 인 갤럭틱 스톰 (보스핵)" },
    { "avengrgsj", "어벤져스 인 갤럭틱 스톰 (일본판)" },
    { "avsp", "에일리언 vs 프레데터 (유럽판)" },
    { "avspa", "에일리언 vs 프레대터 (아시아판)" },
    { "avspd", "에일리언 vs 프레대터 (유럽판,피닉스에디션)" },
    { "avsph", "에일리언 vs 프레대터 (히스패닉판)" },
    { "avspirit", "어벤징 스피리트" },
    { "avspj", "에일리언 vs 프레대터 (일본판)" },
    { "avspk", "에일리언 vs 프레데터 (한글)" },
    { "avspu", "에일리언 vs 프레대터 (미국판)" },
    { "avtbingo", "애로우 빙고" },
    { "aztarac", "아즈타락" },
    { "azumanga", "아즈망가 대왕 퍼즐 버블 (GDL-0018)" },
    { "azurian", "아즈리안 어택" },
};

const size_t lookup_a_count = A_SIZE(lookup_a_table);

const char *lookup_a(const char *name) {
    if (!name) return NULL;
    for (size_t i = 0; i < lookup_a_count; i++) {
        if (strcmp(lookup_a_table[i].name, name) == 0) {
            return lookup_a_table[i].value;
        }
    }
    return NULL;
}

const char *r_lookup_a(const char *value) {
    if (!value) return NULL;
    for (size_t i = 0; i < lookup_a_count; i++) {
        if (strstr(lookup_a_table[i].value, value)) {
            return lookup_a_table[i].name;
        }
    }
    return NULL;
}

void lookup_a_multi(const char *term, void (*emit)(const char *name, const char *value, void *udata), void *udata) {
    if (!term) return;
    for (size_t i = 0; i < lookup_a_count; i++) {
        if (strcasestr(lookup_a_table[i].name, term))
            emit(lookup_a_table[i].name, lookup_a_table[i].value, udata);
    }
}

void r_lookup_a_multi(const char *term, void (*emit)(const char *name, const char *value, void *udata), void *udata) {
    if (!term) return;
    for (size_t i = 0; i < lookup_a_count; i++) {
        if (strcasestr(lookup_a_table[i].value, term))
            emit(lookup_a_table[i].name, lookup_a_table[i].value, udata);
    }
}
