#include <string.h>
#include "../common/common.h"
#include "lookup.h"

const LookupName lookup_r_table[] = {
    { "r2dtank", "R2D 탱크" },
    { "r2dx_v33", "라이덴 2 뉴/ 라이덴 DX (newer V33 PCB)(라이덴 DX EEPROM)" },
    { "r2dx_v33_r2", "라이덴 2 뉴/ 라이덴 DX (newer V33 PCB)(라이덴 2 EEPROM)" },
    { "raaspec", "스펙트럼 I+" },
    { "rabbit", "래빗 (아시아판)" },
    { "rabbita", "래빗 (아시아판)" },
    { "rabbitj", "래빗 (일본판)" },
    { "rabbitjt", "래빗 (일본판 1/28 location test)" },
    { "rabbitpk", "래빗 포커 (아리조나 포커 v1.1)" },
    { "rabiolep", "라비오 리퍼스 (일본판)" },
    { "raccoon", "라쿤 월드" },
    { "racedcb4", "레이스 드라이빙 (소형,영국판,개정판4)" },
    { "racedcg4", "레이스 드라이빙 (소형,독일판,개정판4)" },
    { "racedrb1", "레이스 드라이빙 (콕핏,영국판,개정판1)" },
    { "racedrb4", "레이스 드라이빙 (콕핏,영국판,개정판4)" },
    { "racedrc1", "레이스 드라이빙 (소형,개정판1)" },
    { "racedrc2", "레이스 드라이빙 (소형,개정판2)" },
    { "racedrc4", "레이스 드라이빙 (소형,개정판4)" },
    { "racedrcb", "레이스 드라이빙 (소형,영국판,개정판5)" },
    { "racedrcg", "레이스 드라이빙 (소형,독일판,개정판5)" },
    { "racedrg1", "레이스 드라이빙 (콕핏,독일판,개정판2)" },
    { "racedrg4", "레이스 드라이빙 (콕핏,독일판,개정판4)" },
    { "racedriv", "레이스 드라이빙" },
    { "racedriv1", "레이스 드라이빙 (콕핏,개정판1)" },
    { "racedriv2", "레이스 드라이빙 (콕핏,개정판2)" },
    { "racedriv3", "레이스 드라이빙 (콕핏,개정판3)" },
    { "racedriv4", "레이스 드라이빙 (콕핏,개정판4)" },
    { "racedrivb", "레이스 드라이빙 (콕핏,영국판,개정판5)" },
    { "racedrivb1", "레이스 드라이빙 (콕핏,영국판,개정판1)" },
    { "racedrivb4", "레이스 드라이빙 (콕핏,영국판,개정판4)" },
    { "racedrivc", "레이스 드라이빙 (소형,개정판5)" },
    { "racedrivc1", "레이스 드라이빙 (소형,개정판1)" },
    { "racedrivc2", "레이스 드라이빙 (소형,개정판2)" },
    { "racedrivc4", "레이스 드라이빙 (소형,개정판4)" },
    { "racedrivcb", "레이스 드라이빙 (소형,영국판,개정판5)" },
    { "racedrivcb4", "레이스 드라이빙 (소형,영국판,개정판4)" },
    { "racedrivcg", "레이스 드라이빙 (소형,독일판,개정판5)" },
    { "racedrivcg4", "레이스 드라이빙 (소형,독일판,개정판4)" },
    { "racedrivcp", "레이스 드라이빙 (소형,시험판)" },
    { "racedrivg", "레이스 드라이빙 (콕핏,독일판,개정판5)" },
    { "racedrivg1", "레이스 드라이빙 (콕핏,독일판,개정판2)" },
    { "racedrivg4", "레이스 드라이빙 (콕핏,독일판,개정판4)" },
    { "racedrivpan", "레이스 드라이빙 파노라마 (시험판,개정판2.1)" },
    { "racedrv1", "레이스 드라이빙 (콕핏,개정판1)" },
    { "racedrv2", "레이스 드라이빙 (콕핏,개정판2)" },
    { "racedrv3", "레이스 드라이빙 (콕핏,개정판3)" },
    { "racedrv4", "레이스 드라이빙 (콕핏,개정판4)" },
    { "racedrvb", "레이스 드라이빙 (콕핏,영국판,개정판5)" },
    { "racedrvc", "레이스 드라이빙 (소형,개정판5)" },
    { "racedrvg", "레이스 드라이빙 (콕핏,독일판,개정판5)" },
    { "rachero", "레이싱 히어로" },
    { "racherod", "레이싱 히어로 (암호해제)" },
    { "racinfrc", "레이싱 포스" },
    { "racinfrcu", "레이싱 포스 (버전UAB)" },
    { "racingb", "레이싱 비트 (세계판)" },
    { "racingbj", "레이싱 비트 (일본판)" },
    { "racingj", "레이싱 잼" },
    { "racingj2", "레이싱 잼 - 챕터 II" },
    { "racingj2a", "레이싱 잼 - 챕터 II" },
    { "racingj2e", "레이싱 잼 - 챕터 II" },
    { "racingj2j", "레이싱 잼 - 챕터 II" },
    { "racingj2m", "레이싱 잼 - 챕터 II" },
    { "racingj2ma", "레이싱 잼 - 챕터 II" },
    { "racingj2me", "레이싱 잼 - 챕터 II" },
    { "racingj2mj", "레이싱 잼 - 챕터 II" },
    { "racingj2n", "레이싱 잼 - 챕터 II" },
    { "racingj2na", "레이싱 잼 - 챕터 II" },
    { "racingj2ne", "레이싱 잼 - 챕터 II" },
    { "racingj2nj", "레이싱 잼 - 챕터 II" },
    { "racingja", "레이싱 잼" },
    { "racingje", "레이싱 잼" },
    { "racingjj", "레이싱 잼" },
    { "racingjm", "레이싱 잼" },
    { "racingjma", "레이싱 잼" },
    { "racingjme", "레이싱 잼" },
    { "racingjmj", "레이싱 잼" },
    { "racingjn", "레이싱 잼" },
    { "racingjna", "레이싱 잼" },
    { "racingjne", "레이싱 잼" },
    { "racingjnj", "레이싱 잼" },
    { "rackemup", "허슬러_락엠업 (프로그램 코드 L)" },
    { "racknrol", "랙+롤" },
    { "racoon", "라쿤 월드" },
    { "radarscp", "레이더 스코프" },
    { "radarscp1", "레이더 스코프 (TRS01)" },
    { "radarscpc", "레이더 스코프 (TRS02?)" },
    { "radarzn1", "레이더 존 (개정판1)" },
    { "radarznt", "레이더 존" },
    { "radarzon", "레이더 존" },
    { "radarzon1", "레이더 존 (개정판1)" },
    { "radarzont", "레이더 존" },
    { "radikalb", "라디칼 바이커즈" },
    { "radikalba", "라디칼 바이커즈 (아타리 라이선스)" },
    { "radirgy", "래디지 (일본판,개정판A)(GDL-0032A)" },
    { "radirgyn", "래디지 노아 (일본판)" },
    { "radirgyo", "래디지 (일본판)(GDL-0032)" },
    { "radm", "라드 모빌 (세계판)" },
    { "radmu", "라드 모빌 (미국판)" },
    { "radr", "라드 랠리 (세계판)" },
    { "radrad", "래디컬 래디얼 (미국판)" },
    { "radradj", "래디컬 래디얼 (일본판)" },
    { "radrj", "라드 랠리 (일본판)" },
    { "radru", "라드 랠리 (미국판)" },
    { "raf102j", "리얼 앤 페이크/ 포토 Y2K (버전102,일본판 보드)" },
    { "raflesia", "라플레시아" },
    { "raflesiau", "라플레시아 (비암호화)" },
    { "ragnagrd", "라그나가드/ 신황권" },
    { "ragtime", "부기 윙즈/ 그레이트 래그타임 쇼 (일본판 v1.5)" },
    { "ragtimea", "부기 윙즈/ 그레이트 래그타임 쇼 (일본판 v1.3)" },
    { "raiden", "라이덴 (세계판 세트1)" },
    { "raiden2", "라이덴 2 (미국판,세트1)" },
    { "raiden2a", "라이덴 2 (세트2,메트로테인먼트)" },
    { "raiden2au", "라이덴 2 (호주판)" },
    { "raiden2b", "라이덴 2 (세트3,일본판)" },
    { "raiden2c", "라이덴 2 (세트4,일본판)" },
    { "raiden2d", "라이덴 2 (세트5,Italy)" },
    { "raiden2dx", "라이덴 2 (어려움)" },
    { "raiden2e", "라이덴 2 (쉬움,한국판)" },
    { "raiden2ea", "라이덴 2 (쉬움,일본판)" },
    { "raiden2eg", "라이덴 2 (쉬움,독일판)" },
    { "raiden2es", "라이덴 2 (스페인판)" },
    { "raiden2eu", "라이덴 2 (쉬움,미국판 세트2)" },
    { "raiden2eua", "라이덴 2 (쉬움,미국판 세트1)" },
    { "raiden2eub", "라이덴 2 (쉬움,미국판,세트3)" },
    { "raiden2eup", "라이덴 2 (쉬움,미국판,시험판?)" },
    { "raiden2f", "라이덴 2 (프랑스판)" },
    { "raiden2g", "라이덴 2 (독일판)" },
    { "raiden2gb", "라이덴 2 (영국판)" },
    { "raiden2hk", "라이덴 2 (홍콩판)" },
    { "raiden2i", "라이덴 2 (이탈리아판)" },
    { "raiden2j", "라이덴 2 (일본판)" },
    { "raiden2k", "라이덴 2 (어려움,한국판)" },
    { "raiden2nl", "라이덴 2 (네덜란드판)" },
    { "raiden2sw", "라이덴 2 (스위스판)" },
    { "raiden2u", "라이덴 2 (미국판,세트2)" },
    { "raidena", "라이덴 (대체 하드웨어)" },
    { "raidenb", "라이덴 (세계판 세트2,신형하드웨어)" },
    { "raidendx", "라이덴 DX (영국판)" },
    { "raidendxa1", "라이덴 DX (홍콩판,세트1)" },
    { "raidendxa2", "라이덴 DX (홍콩판,세트2)" },
    { "raidendxch", "라이덴 DX (중국판)" },
    { "raidendxg", "라이덴 DX (독일판)" },
    { "raidendxj", "라이덴 DX (일본판,세트1)" },
    { "raidendxja", "라이덴 DX (일본판,세트2)" },
    { "raidendxk", "라이덴 DX (한국판)" },
    { "raidendxnl", "라이덴 DX (네덜란드판)" },
    { "raidendxpt", "라이덴 DX (포르투갈판)" },
    { "raidendxu", "라이덴 DX (미국판)" },
    { "raidenj", "라이덴 (일본판)" },
    { "raidenk", "라이덴 (한국판)" },
    { "raidenkb", "라이덴 (한국판,해적판)" },
    { "raidenm", "라이덴 (모듈라 시스템)" },
    { "raident", "라이덴 (대만판)" },
    { "raidenu", "라이덴 (미국판,세트1)" },
    { "raidenua", "라이덴 (미국판,세트2)" },
    { "raidenub", "라이덴 (미국판 세트3)" },
    { "raiders", "레이더스" },
    { "raiders5", "레이더스 5" },
    { "raiders5t", "레이더스 5 (일본판)" },
    { "raiders5ta", "레이더스 5 (일본판)" },
    { "raidersr3", "레이더스 (개정판3)" },
    { "raidndx", "라이덴 DX" },
    { "raidndxa", "라이덴 DX (세트2)" },
    { "raidndxa1", "라이덴 DX (아시아판 세트1)" },
    { "raidndxa2", "라이덴 DX (아시아판 세트2)" },
    { "raidndxb", "라이덴 DX (세트3,신형 V33 PCB)" },
    { "raidndxg", "라이덴 DX (독일판)" },
    { "raidndxj", "라이덴 DX (일본판)" },
    { "raidndxm", "라이덴 DX (메트로테인먼트 라이센스)" },
    { "raidndxu", "라이덴 DX (미국판)" },
    { "raidrs5t", "레이더스 5 (일본판)" },
    { "raiga", "라이가 - 스트레토 파이터 (일본판)" },
    { "raimais", "라이마이스 (세계판)" },
    { "raimaisj", "라이마이스 (일본판)" },
    { "raimaisjo", "라이마이스 (일본판,최초 개정판)" },
    { "rainbow", "레인보우 아일랜드 100-B" },
    { "rainbowe", "레인보우 아일랜드 (엑스트라)" },
    { "rainbowo", "레인보우 아일랜드 (구버전)" },
    { "rallybik", "랠리 바이크/ 대쉬 야로" },
    { "rallych", "랠리 체이스 (네오CD 컨버전)" },
    { "rallys", "랠리즈 (스펙타 해적판,세트1)" },
    { "rallysa", "랠리즈 (스펙타 해적판,세트1)" },
    { "rallyx", "랠리 X/ 방구차 (32k 버전.?)" },
    { "rallyxa", "랠리 X/ 방구차" },
    { "rallyxeg", "랠리 X/ 방구차 (비디오 게임 해적판)" },
    { "rallyxm", "랠리 X/ 방구차 (미드웨이)" },
    { "rallyxmr", "랠리 X/ 방구차 (모델 레이싱)" },
    { "rambo3", "람보 3 (유럽판)" },
    { "rambo3a", "람보 3 (미국판)" },
    { "rambo3ae", "람보 3 (유럽판 세트2)" },
    { "rambo3p", "람보 3" },
    { "rambo3u", "람보 3 (미국판)" },
    { "rampage", "램페이지 (개정판3)" },
    { "rampage2", "램페이지" },
    { "rampart", "램파트" },
    { "rampart2p", "램파트 (조이스틱)" },
    { "rampart2pa", "램파트 (조이스틱)" },
    { "rampartj", "램파트 (일본판,조이스틱)" },
    { "ramprt2p", "램파트 (조이스틱)" },
    { "rangrmsn", "레인저 미션" },
    { "raphero", "아르카디아/ 래피드 히어로 (NMK)" },
    { "rapheroa", "아르카디아/ 래피드 히어로" },
    { "rapidfir", "래피드 파이어" },
    { "rapidfira", "래피드 파이어" },
    { "rapidfire", "래피드 파이어" },
    { "rapidrvr", "래피드 리버" },
    { "rapidrvr2", "래피드 리버 (RD2 v.C)" },
    { "rastan", "라스탄 (세계판 개정판1)" },
    { "rastana", "라스탄 (세계판)" },
    { "rastanb", "라스탄 (세계판,초기 코드)" },
    { "rastanu", "라스탄 (미국판 개정판1)" },
    { "rastanu2", "라스탄 (미국판,세트2)" },
    { "rastanua", "라스탄 (미국판)" },
    { "rastanub", "라스탄 (미국판,초기)" },
    { "rastsag1", "라스탄 사가 (일본판 개정판1)" },
    { "rastsag2", "라스탄 사가 2 (일본판)" },
    { "rastsaga", "라스탄 사가 (일본판 개정판1)" },
    { "rastsaga1", "라스탄 사가 (일본판 개정판1)" },
    { "rastsagaa", "라스탄 사가 (일본판 개정판1,초기 코드)" },
    { "rastsagaabl", "라스탄 사가 (해적판,일본판 개정판1,초기 코드)" },
    { "rastsagab", "라스탄 사가 (일본판,초기 코드)" },
    { "rastsagabr", "라스탄 사가 (포르투갈 번역,핵)" },
    { "raverace", "레이브 레이서" },
    { "raveracej", "레이브 레이서" },
    { "raveraceja", "레이브 레이서" },
    { "raveracj", "레이브 레이서 (개정판RV1 버전B,일본판)" },
    { "raveracja", "레이브 레이서 (개정판RV1,일본판)" },
    { "raveracw", "레이브 레이서" },
    { "raveraja", "레이브 레이서 (개정판RV1,일본판)" },
    { "raycris", "레이 크라이시스" },
    { "raycrisj", "레이 크라이시스" },
    { "rayforce", "건락/ 래이 포스 (버전2.3A)" },
    { "rayforcej", "건락/ 래이 포스 (버전2.3J)" },
    { "rayforcj", "건락/ 래이 포스 (버전2.3J)" },
    { "raystorj", "레이 스톰 (버전2.05J)" },
    { "raystorm", "레이 스톰" },
    { "raystormj", "레이 스톰 (버전2.05J)" },
    { "raystormo", "레이 스톰 (Ver 2.05O)" },
    { "raystormu", "레이 스톰 (Ver 2.05A)" },
    { "razmataz", "레즈머태즈" },
    { "rbff1", "리얼바웃 아랑전설" },
    { "rbff1a", "리얼바웃 아랑전설 (버그수정 개정판)" },
    { "rbff1akr", "리얼바웃 아랑전설 (한글,버그수정 개정판)" },
    { "rbff1k", "리얼바웃 아랑전설 (한국 발매)" },
    { "rbff1ka", "리얼바웃 아랑전설 (한국 발매,버그수정 개정판)" },
    { "rbff1kr", "리얼바웃 아랑전설 (한글)" },
    { "rbff1uh", "리얼바웃 아랑전설 (AES 미검열 핵)" },
    { "rbff2", "리얼바웃 아랑전설 2 - 신인" },
    { "rbff2a", "리얼바웃 아랑전설 2 - 신인 (세트2)" },
    { "rbff2bh", "리얼바웃 아랑전설 2 - 신인 (핵)" },
    { "rbff2bs", "리얼바웃 아랑전설 2 - 신인 (시크릿 캐릭터,핵)" },
    { "rbff2h", "리얼바웃 아랑전설 2 - 신인 (NGH-2400)" },
    { "rbff2hb", "리얼바웃 아랑전설 2 - 신인 (히든 핵)" },
    { "rbff2k", "리얼바웃 아랑전설 2 - 신인 (한국 발매)" },
    { "rbff2uh", "리얼바웃 아랑전설 2 - 신인 (AES 미검열 핵)" },
    { "rbffspbh", "리얼바웃 아랑전설 스페셜 (보스,핵)" },
    { "rbffspbs", "리얼바웃 아랑전설 스페셜 (보스,핵)" },
    { "rbffspec", "리얼바웃 아랑전설 스페셜" },
    { "rbffspeck", "리얼바웃 아랑전설 스페셜 (한국 발매)" },
    { "rbffspecuh", "리얼바웃 아랑전설 스페셜 (AES 미검열 핵)" },
    { "rbffspeh", "리얼바웃 아랑전설 스페셜 (히든 핵)" },
    { "rbibb", "아타리 R.B.I. 베이스볼" },
    { "rbibba", "아타리 R.B.I. 베이스볼 (세트2)" },
    { "rbisland", "레인보우 아일랜드 (개정판 1)" },
    { "rbislande", "레인보우 아일랜드 - 엑스트라 버전" },
    { "rbislando", "레인보우 아일랜드" },
    { "rbmk", "리얼 배틀 마작 킹" },
    { "rbtapper", "탭퍼 (루트 비어)" },
    { "rcasino", "로얄 카지노" },
    { "rcasino1", "로얄 카지노" },
    { "rcasino2", "로얄 카지노" },
    { "rcasinoo", "로얄 카지노" },
    { "rcdego", "RC로 고 (V2.03J)" },
    { "rchase", "레일 체이스 (세계판)" },
    { "rchase2", "레일 체이스 2" },
    { "rchasej", "레일 체이스 (일본판)" },
    { "rchasejb", "레일 체이스 (일본판,개정판B)" },
    { "rcirulet", "루레타 RCI" },
    { "rckman2j", "록맨 2 - 파워 파이터즈 (일본판)" },
    { "rckmanj", "록맨 - 파워 배틀" },
    { "rclimb_3", "록 클라이머" },
    { "rclimb_3a", "록 클라이머 (백도어)" },
    { "rclimb_3b", "록 클라이머 (신 서비스메뉴)" },
    { "rcorsair", "레드 커세어" },
    { "rdaction", "라드 액션/ 닌자군 아수라의 장" },
    { "rdft", "라이덴 파이터즈 (독일판)" },
    { "rdft2", "라이덴 파이터즈 2 - 오퍼레이션 헬 다이브 (독일판)" },
    { "rdft22kc", "라이덴 파이터즈 2 - 오퍼레이션 헬 다이브 2000 (중국판)" },
    { "rdft2a", "라이덴 파이터즈 2 - 오퍼레이션 헬 다이브 (홍콩판)" },
    { "rdft2a2", "라이덴 파이터즈 2 - 오퍼레이션 헬 다이브 (한국판)" },
    { "rdft2aa", "라이덴 파이터즈 2 - 오퍼레이션 헬 다이브 (한국판)" },
    { "rdft2it", "라이덴 파이터즈 2 - 오퍼레이션 헬 다이브 (이탈리아판)" },
    { "rdft2j", "라이덴 파이터즈 2 - 오퍼레이션 헬 다이브 (일본판,세트1)" },
    { "rdft2j2", "라이덴 파이터즈 2 - 오퍼레이션 헬 다이브 (일본판,세트2)" },
    { "rdft2ja", "라이덴 파이터즈 2 - 오퍼레이션 헬 다이브 (일본판,세트2)" },
    { "rdft2jb", "라이덴 파이터즈 2 - 오퍼레이션 헬 다이브 (일본판,세트3)" },
    { "rdft2jc", "라이덴 파이터즈 2 - 오퍼레이션 헬 다이브 (일본판,세트4)" },
    { "rdft2s", "라이덴 파이터즈 2 - 오퍼레이션 헬 다이브 (스위스판)" },
    { "rdft2t", "라이덴 파이터즈 2 - 오퍼레이션 헬 다이브 (대만판)" },
    { "rdft2u", "라이덴 파이터즈 2 - 오퍼레이션 헬 다이브 (미국판)" },
    { "rdft2us", "라이덴 파이터즈 2 - 오퍼레이션 헬 다이브 (미국판,싱글 보드)" },
    { "rdfta", "라이덴 파이터즈 (오스트리아)" },
    { "rdftadi", "라이덴 파이터즈 (한국판)" },
    { "rdftadia", "라이덴 파이터즈 (한국판,서브2 카트)" },
    { "rdftam", "라이덴 파이터즈 (홍콩판)" },
    { "rdftau", "라이덴 파이터즈 (호주판)" },
    { "rdftauge", "라이덴 파이터즈 (독일판)" },
    { "rdftdi", "라이덴 파이터즈 (드림아일랜드 라이센스)" },
    { "rdftgb", "라이덴 파이터즈 (영국판)" },
    { "rdftgr", "라이덴 파이터즈 (그리스판)" },
    { "rdftit", "라이덴 파이터즈 (이탈리아판)" },
    { "rdftj", "라이덴 파이터즈 (일본판,초기형)" },
    { "rdftja", "라이덴 파이터즈 (일본판,최초형)" },
    { "rdftjb", "라이덴 파이터즈 (일본판,신형)" },
    { "rdfts", "라이덴 파이터즈 (대만판)" },
    { "rdftu", "라이덴 파이터즈 (미국판,초기형)" },
    { "rdftua", "라이덴 파이터즈 (미국판,신형)" },
    { "re800ea", "루레타 RE-800" },
    { "re800v1", "루레타 RE-800" },
    { "re800v1a", "루레타 RE-800" },
    { "re800v3", "루레타 RE-800" },
    { "re900", "루레타 RE-900" },
    { "reactor", "리액터" },
    { "reaktor", "릭터 (트랙 & 필드 변환)" },
    { "realbrk", "빌리어드 아카데미 리얼 브레이크" },
    { "realbrkj", "빌리어드 아카데미 리얼 브레이크 (일본판)" },
    { "realbrkk", "빌리어드 아카데미 리얼 브레이크 (한국판)" },
    { "realbrko", "빌리어드 아카데미 리얼 브레이크" },
    { "realbrod", "리얼 브로드웨이" },
    { "realbroda", "리얼 브로드웨이" },
    { "rebound", "리바운드" },
    { "rebus", "리버스" },
    { "recalh", "리콜혼 (버전1.42J,시제품)" },
    { "record", "레코드" },
    { "recordbr", "레코드브레이커 (세계판)" },
    { "redalert", "레드 얼럿" },
    { "redbaron", "레드 바론 (리바이스드 하드웨어)" },
    { "redbarona", "레드 바론" },
    { "redbird", "레드 버드" },
    { "redclash", "레드 클래쉬" },
    { "redclasha", "레드 클래쉬 (세트2)" },
    { "redclashk", "레드 클래쉬 (카네코)" },
    { "redclashs", "레드 클래쉬 (선트로닉스)" },
    { "redclasht", "레드 클래쉬 (Tehkan, 세트1)" },
    { "redclashta", "레드 클래쉬 (Tehkan, 세트2)" },
    { "redclask", "레드 클래쉬 (카네코)" },
    { "redclsha", "레드 클래쉬 (세트2)" },
    { "redearth", "레드 어스/ 워자드 (유럽판)" },
    { "redearthn", "레드 어스/ 워자드 (아시아판,노CD)" },
    { "redearthnr1", "레드 어스/ 워자드 (아시아판,노CD)" },
    { "redearthr1", "레드 어스/ 워자드 (유럽판)" },
    { "redeartn", "레드 어스/ 워자드 (NO CD)" },
    { "redfoxwp2", "홍호전예 2 (중국판,세트1)" },
    { "redfoxwp2a", "홍호전예 2 (중국판,세트2)" },
    { "redhawk", "스태거 I/ 레드 호크" },
    { "redhawkb", "스태거 I/ 레드 호크" },
    { "redhawke", "스태거 I/ 레드 호크 (엑설런트)" },
    { "redhawkg", "스태거 I/ 레드 호크" },
    { "redhawki", "스태거 I/ 레드 호크" },
    { "redhawkk", "스태거 I/ 레드 호크 (한국판)" },
    { "redhawks", "스태거 I/ 레드 호크" },
    { "redhawksa", "스태거 I/ 레드 호크" },
    { "redlin2p", "레드라인 레이서" },
    { "redline", "레드 라인" },
    { "redrobin", "레드 로빈" },
    { "redufo", "붉은 UFO의 지구 공격으로부터의 방어" },
    { "redufob", "붉은 UFO의 지구 공격으로부터의 방어 (해적판,세트1)" },
    { "redufob2", "붉은 UFO의 지구 공격으로부터의 방어 (해적판,세트2)" },
    { "redufob3", "붉은 UFO의 지구 공격으로부터의 방어 (해적판,세트3)" },
    { "reelfun", "릴 펀" },
    { "reelfun0", "릴 펀 (버전7.00)" },
    { "reelfun1", "릴 펀 (버전7.01)" },
    { "reelquak", "릴앤 퀘이크!" },
    { "reelrock", "릴인 앤 락킨" },
    { "regulus", "레굴루스 (개정판A)" },
    { "reguluso", "레굴루스" },
    { "regulusu", "레굴루스 (비암호화)" },
    { "reikaids", "영계도사" },
    { "relief", "릴리프 피처 (세트1)" },
    { "relief2", "릴리프 피처 (세트2)" },
    { "relief3", "릴리프 피처 (세트3)" },
    { "renaiclb", "마작 연애 클럽" },
    { "renegade", "열혈경파 쿠니오군/ 레니게이드 (미국판)" },
    { "renegadeb", "열혈경파 쿠니오군/ 레니게이드 (미국판 해적판)" },
    { "renju", "연주귀족" },
    { "repulse", "리펄스/ 99 더 라스트 워" },
    { "resclunar", "레스케이트 루나 (루나 레스큐의 스페인어 해적판)" },
    { "rescraid", "레스큐 레이더" },
    { "rescraida", "레스큐 레이더 (독립형)" },
    { "rescrdsa", "레스큐 레이더 (독립형)" },
    { "rescue", "구조대" },
    { "rescueb", "투오노 블루" },
    { "resdnt_2", "레지던트" },
    { "resdnt_2a", "레지던트 (040513,백도어)" },
    { "retofin1", "돌아온 인베이더 (해적판 세트1)" },
    { "retofin2", "돌아온 인베이더 (해적판 세트2)" },
    { "retofinv", "돌아온 인베이더" },
    { "retofinv1", "돌아온 인베이더 (해적판 세트1)" },
    { "retofinv2", "돌아온 인베이더 (해적판 세트2)" },
    { "retofinvb", "돌아온 인베이더 (해적판)" },
    { "retofinvb1", "돌아온 인베이더 (해적판 MCU제외 세트1)" },
    { "retofinvb2", "돌아온 인베이더 (해적판 MCU제외 세트2)" },
    { "retofinvb3", "돌아온 인베이더 (해적판 MCU제외 세트3)" },
    { "retofinvbv", "돌아온 인베이더 (비디오 덴스 해적판,MCU제외)" },
    { "revenger", "리벤져 84 (세트2)" },
    { "revlatns", "계시" },
    { "revngr84", "리벤져 84 (세트1)" },
    { "revx", "레볼루션 X (개정판1.0)" },
    { "revxp5", "레볼루션 X (시험판 5.0)" },
    { "rezon", "레존" },
    { "rezono", "레존 (초기형)" },
    { "rezont", "레존 (타이토)" },
    { "rf2", "코나미 RF2 - 레드 파이터" },
    { "rfjet", "라이덴 파이터즈 제트 (독일판)" },
    { "rfjet2kc", "라이덴 파이터즈 제트 - 2000 (중국판)" },
    { "rfjeta", "라이덴 파이터즈 제트 (한국판)" },
    { "rfjetj", "라이덴 파이터즈 제트 (일본판)" },
    { "rfjets", "라이덴 파이터즈 제트 (미국판)" },
    { "rfjetsa", "라이덴 파이터즈 제트 (미국판)" },
    { "rfjett", "라이덴 파이터즈 제트 (대만판)" },
    { "rfjetu", "라이덴 파이터즈 제트 (미국판)" },
    { "rfjetus", "라이덴 파이터즈 제트 (미국판,싱글 보드)" },
    { "rgum", "로얄 검" },
    { "rhytngk", "리듬 천국 (일본판)" },
    { "ribbit", "리빗" },
    { "ribbitj", "리빗 (일본판)" },
    { "ridefgtj", "라이딩 파이트 (버전1.0J)" },
    { "ridefgtu", "라이딩 파이트 (버전1.0A)" },
    { "ridger2a", "릿지 레이서 2 (개정판RRS1,버전B,일본판)" },
    { "ridger2b", "릿지 레이서 2 (개정판RRS1,일본판)" },
    { "ridger2j", "릿지 레이서 2" },
    { "ridgera2", "릿지 레이서 2" },
    { "ridgera28", "릿지 레이서 2" },
    { "ridgera2j", "릿지 레이서 2 (개정판RRS1,버전B,일본판)" },
    { "ridgera2ja", "릿지 레이서 2 (개정판RRS1,일본판)" },
    { "ridgerac", "릿지 레이서" },
    { "ridgerac3", "릿지 레이서 (개정판RR2,세계판)" },
    { "ridgeraca", "릿지 레이서" },
    { "ridgeracb", "릿지 레이서 (개정판RR2,세계판)" },
    { "ridgeracc", "릿지 레이서" },
    { "ridgeracf", "릿지 레이서 풀 스케일" },
    { "ridgeracj", "릿지 레이서 (개정판RR1,일본판)" },
    { "ridgeraj", "릿지 레이서 (개정판RR1,일본판)" },
    { "ridhero", "라이딩 히어로" },
    { "ridheroh", "라이딩 히어로 (세트2)" },
    { "ridingf", "라이딩 파이트 (버전1.0O)" },
    { "ridingfj", "라이딩 파이트 (버전1.0J)" },
    { "ridingfu", "라이딩 파이트 (버전1.0A)" },
    { "ridleofp", "피타고라스의 정리 (일본판)" },
    { "rimrck12", "림 락킨 베스킷볼 (v1.2)" },
    { "rimrck16", "림 락킨 베스킷볼 (v1.6)" },
    { "rimrck20", "림 락킨 베스킷볼 (v2.0)" },
    { "rimrockn", "림 락킨 베스킷볼 (v2.2)" },
    { "rimrockn12", "림 락킨 베스킷볼 (v1.2)" },
    { "rimrockn12b", "림 락킨 베스킷볼 (v1.2,해적판)" },
    { "rimrockn15", "림 락킨 베스킷볼 (v1.5)" },
    { "rimrockn16", "림 락킨 베스킷볼 (v1.6)" },
    { "rimrockn20", "림 락킨 베스킷볼 (v2.0)" },
    { "ringdest", "슬램 마스터즈 2 - 링 오브 디스트럭션 (유럽판)" },
    { "ringdesta", "슬램 마스터즈 2 - 링 오브 디스트럭션 (아시아판)" },
    { "ringdestb", "슬램 마스터즈 2 - 링 오브 디스트럭션 (브라질판)" },
    { "ringdesth", "슬램 마스터즈 2 - 링 오브 디스트럭션 (히스패닉판)" },
    { "ringdstd", "슬램 마스터즈 2 - 링 오브 디스트럭션 (유럽판,피닉스에디션)" },
    { "ringfgt", "VS 공 파이트/ 링 파이터 (세트1)" },
    { "ringfgt2", "VS 공 파이트/ 링 파이터 (세트2)" },
    { "ringfgta", "VS 공 파이트/ 링 파이터" },
    { "ringkin2", "링 킹 (미국판 세트2)" },
    { "ringkin3", "링 킹 (미국판 세트3)" },
    { "ringking", "링 킹 (미국판 세트1)" },
    { "ringking2", "링 킹 (미국판 세트2)" },
    { "ringking3", "링 킹 (미국판 세트3)" },
    { "ringkingw", "링 킹 (미국판,우드 플레이스)" },
    { "ringkinw", "링 킹 (미국판,우드플레이스 라이센스)" },
    { "ringohja", "메인 이벤트/ 링의 왕자 (일본판 2인용 N)" },
    { "ringout", "링 아웃 4x4 (개정판A)" },
    { "ringouto", "링 아웃 4x4" },
    { "ringrage", "링 레이지 (버전2.3O)" },
    { "ringragej", "링 레이지 (버전2.3J)" },
    { "ringrageu", "링 레이지 (버전2.3A)" },
    { "ringragj", "링 레이지 (버전2.3J)" },
    { "ringragu", "링 레이지 (버전2.3A)" },
    { "riot", "라이엇" },
    { "riotcity", "라이엇 시티 (일본판)" },
    { "riotw", "라이엇 (웅비 라이선스)" },
    { "ripcord", "립 코드" },
    { "ripoff", "립 오프" },
    { "ripribit", "리퍼 리빗" },
    { "ripribita", "리퍼 리빗 (버전2.8.4)" },
    { "riskchal", "리스키 챌린지" },
    { "rittam", "R&T (시험판)" },
    { "riviera", "리비에라 하이스코어" },
    { "rivieraa", "리비에라 하이스코어" },
    { "rivierab", "리비에라 하이스코어" },
    { "rjammer", "롤러 재머" },
    { "rkjanoh2", "로얄 킹 작왕 2" },
    { "rltennis", "리얼리티 테니스" },
    { "rltennisa", "리얼리티 테니스 (세트2)" },
    { "rmancp2j", "록맨 - 파워 배틀 (CPS2,일본판)" },
    { "rmancp2k", "록맨 - 파워 배틀 (CPS2,한글)" },
    { "rmgoldyh", "리얼 마작 골드 몽패/ 슈퍼 리얼 마작 골드 파트2" },
    { "rmhaihai", "리얼 마작 하이하이" },
    { "rmhaihai2", "리얼 마작 하이하이" },
    { "rmhaihib", "리얼 마작 하이하이 (일본판)" },
    { "rmhaijin", "리얼 마작 하이하이 인사이동편" },
    { "rmhaisei", "리얼 마작 하이하이 성장편" },
    { "rmpgwt", "램페이지 - 월드 투어 (개정판1.3)" },
    { "rmpgwt11", "램페이지 - 월드 투어" },
    { "roadblc1", "로드 블래스터스 (콕핏,개정판1)" },
    { "roadblcg", "로드 블래스터스 (콕핏,독일판,개정판1)" },
    { "roadblg1", "로드 블래스터스 (업라이트,독일판,개정판1)" },
    { "roadblg2", "로드 블래스터스 (업라이트,독일판,개정판2)" },
    { "roadbls1", "로드 블래스터스 (업라이트,개정판1)" },
    { "roadbls2", "로드 블래스터스 (업라이트,개정판2)" },
    { "roadbls3", "로드 블래스터스 (업라이트,개정판3)" },
    { "roadblsc", "로드 블래스터스 (콕핏,개정판2)" },
    { "roadblsg", "로드 블래스터스 (업라이트,독일판,개정판3)" },
    { "roadblst", "로드 블래스터스" },
    { "roadblst1", "로드 블래스터스 (업라이트,개정판1)" },
    { "roadblst2", "로드 블래스터스 (업라이트,개정판2)" },
    { "roadblst3", "로드 블래스터스 (업라이트,개정판3)" },
    { "roadblstc", "로드 블래스터스 (콕핏,개정판2)" },
    { "roadblstc1", "로드 블래스터스 (콕핏,개정판1)" },
    { "roadblstcg", "로드 블래스터스 (콕핏,독일판,개정판1)" },
    { "roadblstg", "로드 블래스터스 (업라이트,독일판,개정판3)" },
    { "roadblstg1", "로드 블래스터스 (업라이트,독일판,개정판1)" },
    { "roadblstg2", "로드 블래스터스 (업라이트,독일판,개정판2)" },
    { "roadblstgu", "로드 블래스터스 (업라이트,독일판,개정판?)" },
    { "roadburn", "로드 버너스" },
    { "roadburn1", "로드 버너스 (버전1.0)" },
    { "roadedge", "로드 엣지/ 라운드 트립" },
    { "roadf", "로드 파이터 (세트1)" },
    { "roadf2", "로드 파이터 (세트2)" },
    { "roadf3", "로드 파이터 (세트3,컨버전핵)" },
    { "roadfh", "로드 파이터 (해적판 GX330 컨버전)" },
    { "roadfu", "로드 파이터 (세트3,비암호화)" },
    { "roadriot", "로드 라이엇 4WD" },
    { "roadriota", "로드 라이엇 4WD" },
    { "roadriotb", "로드 라이엇 4WD" },
    { "roadrun1", "로드 러너 (개정판1)" },
    { "roadrun2", "로드 러너 (개정판1+)" },
    { "roadrunm", "로드 러너 (미드웨이)" },
    { "roadrunn", "로드 러너" },
    { "roadrunn1", "로드 러너 (개정판1)" },
    { "roadrunn2", "로드 러너 (개정판1+)" },
    { "robadv", "로빈의 모험" },
    { "robadv2", "로빈의 모험 2" },
    { "robadv2c1", "로빈의 모험 2 (버전1.7R,세트1)" },
    { "robadv2c2", "로빈의 모험 2 (버전1.7LT,세트1)" },
    { "robadv2c3", "로빈의 모험 2 (버전1.7SH,세트1)" },
    { "robadv2d1", "로빈의 모험 2 (버전1.7R,세트2)" },
    { "robadv2d2", "로빈의 모험 2 (버전1.7LT,세트2)" },
    { "robadv2d3", "로빈의 모험 2 (버전1.7SH,세트2)" },
    { "robadv2o", "로빈의 모험 2 (버전1.5SH)" },
    { "robadv2o2", "로빈의 모험 2 (버전1.5)" },
    { "robadv2v1", "로빈의 모험 2 (버전1.7R 듀얼)" },
    { "robadv2v2", "로빈의 모험 2 (버전1.7LT 듀얼)" },
    { "robadv2v3", "로빈의 모험 2 (버전1.7SH 듀얼)" },
    { "robadvc1", "로빈의 모험 (버전1.7R,세트1)" },
    { "robadvd1", "로빈의 모험 (버전1.7R,세트2)" },
    { "robadvo", "로빈의 모험 (버전1.5)" },
    { "robadvv1", "로빈의 모험 (버전1.7R 듀얼)" },
    { "robby", "러비 로토" },
    { "roboarma", "로보 아미 (세트2)" },
    { "roboarmy", "로보 아미 (세트1)" },
    { "roboarmya", "로보 아미 (세트2)" },
    { "robocop", "로보캅 (세계판 개정판4)" },
    { "robocop2", "로보캅 2 (유럽판/아시아판 v0.10)" },
    { "robocop2j", "로보캅 2 (일본판 v0.11)" },
    { "robocop2u", "로보캅 2 (미국판 v0.10)" },
    { "robocop2ua", "로보캅 2 (미국판 v0.05)" },
    { "robocopb", "로보캅 (세계판 해적판)" },
    { "robocopb2", "로보캅 (세계판 해적판)" },
    { "robocopi", "로보캅" },
    { "robocopj", "로보캅 (일본판)" },
    { "robocopu", "로보캅 (미국판 개정판1)" },
    { "robocopu0", "로보캅 (미국판 개정판0)" },
    { "robocopw", "로보캅 (세계판 개정판3)" },
    { "robocp2j", "로보캅 2 (일본판 v0.11)" },
    { "robocp2u", "로보캅 2 (미국판 v0.05)" },
    { "robocpu0", "로보캅 (미국판 개정판0)" },
    { "robokdj2", "아토믹 로보 키드 (일본판,세트2)" },
    { "robokid", "아토믹 로보 키드 (세계판,타입-2)" },
    { "robokidj", "아토믹 로보 키드 (일본판,타입 2,세트1)" },
    { "robokidj2", "아토믹 로보 키드 (일본판,타입 2,세트2)" },
    { "robokidj3", "아토믹 로보 키드 (일본판)" },
    { "robotbwl", "로봇 보울" },
    { "robotron", "로보트론 2084 (솔리드 블루 라벨)" },
    { "robotron12", "로보트론 2084 (2012 웨이브 201 스타트 해킹)" },
    { "robotron87", "로보트론 2084 (1987 버그수정)" },
    { "robotrontd", "로보트론 2084 (2015 티어-다이 V2 해킹)" },
    { "robotronun", "로보트론 2084 (유니데사 라이센스)" },
    { "robotronyo", "로보트론 2084 (노랑/오렌지 라벨)" },
    { "robotryo", "로보트론 (노랑/오렌지 라벨)" },
    { "robowrb", "로보트 레슬링 2001" },
    { "robowres", "로보트 레슬링 2001" },
    { "robowresb", "로보트 레슬링 2001" },
    { "rockclim", "록 클라이머" },
    { "rockduck", "록 덕 (시제품?)" },
    { "rockman2j", "록맨 2 - 파워 파이터즈 (일본판)" },
    { "rockman2k", "록맨 2 - 파워 파이터즈 (한글)" },
    { "rockmanj", "록맨 - 파워 배틀 (CPS1,일본판)" },
    { "rockmank", "록맨 - 파워 배틀 (CPS1,한글)" },
    { "rockn", "로큰 트래드 (일본판)" },
    { "rockn2", "로큰 트래드 2 (일본판)" },
    { "rockn3", "로큰 3 (일본판)" },
    { "rockn4", "로큰 4 (일본판,시제품)" },
    { "rockna", "로큰 트래드 (일본판,대체)" },
    { "rocknms", "로큰 메가세션" },
    { "rockraga", "로큰 레이지 (시험판?)" },
    { "rockrage", "로큰 레이지 (세계판)" },
    { "rockragea", "로큰 레이지 (시험판?)" },
    { "rockragej", "사랑의 핫 락 (일본판)" },
    { "rockragj", "사랑의 핫 락 (일본판)" },
    { "rocktris", "락 트리스" },
    { "rocktrv2", "MTV 락 앤 롤 트리비아 (파트 2)" },
    { "rocnrope", "락 앤 로프" },
    { "rocnropek", "락 앤 로프 (코수카)" },
    { "rocnropk", "락 앤 로프 (코수카)" },
    { "rodland", "로드 랜드 (세계판,세트1)" },
    { "rodlanda", "로드 랜드 (세계판,세트2)" },
    { "rodlandj", "로드 랜드 (일본판)" },
    { "rodlandjb", "로드 랜드 (일본판 해적판)" },
    { "rodlandjb2", "로드 랜드 (일본판 해적판)" },
    { "rodlndjb", "로드 랜드 (일본판 해적판)" },
    { "rohga", "공아2001/ 로가 아머 포스 (아시아판/유럽판 v5.0)" },
    { "rohga1", "공아2001/ 로가 아머 포스 (아시아판/유럽판 v3.0 세트1)" },
    { "rohga2", "공아2001/ 로가 아머 포스 (아시아판/유럽판 v3.0 세트2)" },
    { "rohgah", "공아2001/ 로가 아머 포스 (홍콩판 v3.0)" },
    { "rohgau", "공아2001/ 로가 아머 포스 (미국판 v1.0)" },
    { "roishtar", "이시타르의 귀환" },
    { "rolcrush", "롤링 크러쉬 (버전1.07,트러스트 라이센스)" },
    { "rolcrusha", "롤링 크러쉬 (버전1.03)" },
    { "roldfrga", "돌아온 개구리 숙녀 (세트2)" },
    { "roldfrog", "돌아온 개구리 숙녀" },
    { "roldfroga", "돌아온 개구리 숙녀 (세트2)" },
    { "rollace", "파이팅 롤러/ 롤러 에이스 (세트1)" },
    { "rollace2", "파이팅 롤러/ 롤러 에이스 (세트2)" },
    { "rollerg", "롤러게임스 (미국판)" },
    { "rollergj", "롤러게임스 (일본판)" },
    { "rollfr_2", "롤 프루트" },
    { "rollingc", "롤링 크래쉬/ 문 베이스" },
    { "rompers", "롬퍼즈 (일본판,신버전,개정판B)" },
    { "romperso", "롬퍼즈 (일본판,구버전)" },
    { "ron2", "후타리 마작 론 II" },
    { "rongrngg", "퍼즐 게임 롱롱 (독일판)" },
    { "rongrong", "퍼즐 게임 롱롱" },
    { "rongrongg", "퍼즐 게임 롱롱 (독일판)" },
    { "rongrongj", "퍼즐 게임 롱롱 (일본판)" },
    { "ronjan", "론 잔" },
    { "ronjans", "론 잔 슈퍼" },
    { "ropeman", "로프맨" },
    { "rotaryf", "로터리 파이터" },
    { "rotd", "레이지 오브 더 드래곤" },
    { "rotdbh", "레이지 오브 더 드래곤 (보스 핵)" },
    { "rotdbr", "레이지 오브 더 드래곤 (포르투갈어 에디션,핵)" },
    { "rotddh", "레이지 오브 더 드래곤 (보스 핵)" },
    { "rotdh", "레이지 오브 더 드래곤 (NGH-2640?)" },
    { "rotdnd", "레이지 오브 더 드래곤 (완전해독됨)" },
    { "rotr", "라이즈 오브 더 로봇" },
    { "rotra", "라이즈 오브 더 로봇" },
    { "roughrac", "러프 레이서 (일본판,플로피 기반)" },
    { "rougien", "루지엔" },
    { "roul", "슈퍼 럭키 룰렛" },
    { "roundup", "라운드 업" },
    { "roundup5", "라운드 업 5 - 슈퍼 델타 포스" },
    { "route16", "루트 16 (썬 일렉트로닉스)" },
    { "route16a", "루트 16" },
    { "route16b", "루트 16" },
    { "route16bl", "루트 16" },
    { "route16c", "루트 16" },
    { "route16d", "루트 16 (썬 일렉트로닉스,세트2)" },
    { "routex", "루트 X" },
    { "routexa", "루트 X (해적판,세트2)" },
    { "royal", "로얄 (풀 10 핵)" },
    { "royalcdb", "로얄 카드 (오스트리아,세트2)" },
    { "royalcrd", "로얄 카드" },
    { "royalcrda", "로얄 카드 (호주판,세트2)" },
    { "royalcrdb", "로얄 카드 (호주판,세트3)" },
    { "royalcrdc", "로얄 카드 (호주판,세트4)" },
    { "royalcrdd", "로얄 카드" },
    { "royalcrde", "로얄 카드 (호주판,세트6)" },
    { "royalcrdf", "로얄 카드 (슬로바키아,암호화)" },
    { "royalcrdp", "로얄 카드 2.0 프로페셔널" },
    { "royale", "로얄" },
    { "royalea", "로얄 (세트2)" },
    { "royalmah", "로얄 마작" },
    { "royalmj", "로얄 마작" },
    { "royalngt", "로얄 나이트 (일본판,RN 2-00)" },
    { "royalpk2", "로얄 포커 2" },
    { "royalqn", "로얄 퀸" },
    { "roylcrdn", "로얄 카드" },
    { "roylcrdna", "로얄 카드 파트-투" },
    { "roypok96", "로얄 포커 96" },
    { "roypok96a", "로얄 포커 96 (세트2)" },
    { "roypok96b", "로얄 포커 96 (세트3)" },
    { "rpanic", "롤링 패닉" },
    { "rpatrol", "리버 패트롤 (일본판)" },
    { "rpatrolb", "리버 패트롤" },
    { "rpatroln", "리버 패트롤 (일본판,비보호)" },
    { "rpatrolo", "리버 패트롤" },
    { "rpunch", "라비오 리퍼스/ 래빗 펀치 (미국판)" },
    { "rranger", "러프 레인져 (v2.0)" },
    { "rrangerb", "러프 레인져 (v2.0,해적판)" },
    { "rrf", "릿지 레이서 (1993-12-13,세계판)" },
    { "rrreveng", "로드 라이엇의 복수" },
    { "rrrevenga", "로드 라이엇의 복수 (시험판,세트1)" },
    { "rrrevengb", "로드 라이엇의 복수 (시험판,세트2)" },
    { "rrrevenp", "로드 라이엇의 복수 (시험판 대체)" },
    { "rsgun", "레디언트 실버건" },
    { "rshark", "R샤크" },
    { "rthun2", "롤링 썬더 2" },
    { "rthun2j", "롤링 썬더 2 (일본판)" },
    { "rthunder", "롤링 썬더 (개정판3)" },
    { "rthunder0", "롤링 썬더 (최종)" },
    { "rthunder1", "롤링 썬더 (개정판1)" },
    { "rthunder2", "롤링 썬더 (개정판2)" },
    { "rthundera", "롤링 썬더 (개정판3,핵)" },
    { "rthundero", "롤링 썬더 (구버전)" },
    { "rthundro", "롤링 썬더 (구버전)" },
    { "rtriv", "로마 트리브" },
    { "rtype", "R - 타입 (세계판)" },
    { "rtype2", "R - 타입 2 (세계판)" },
    { "rtype2j", "R - 타입 2 (일본판)" },
    { "rtype2jc", "R - 타입 2 (일본판,개정판C)" },
    { "rtype2m82b", "R - 타입 2 (일본판)" },
    { "rtypeb", "R - 타입 (세계판 해적판)" },
    { "rtypej", "R - 타입 (일본판)" },
    { "rtypejp", "R - 타입 (일본판 시험판)" },
    { "rtypelej", "R - 타입 레오 (일본판)" },
    { "rtypeleo", "R - 타입 레오 (세계판)" },
    { "rtypeleoj", "R - 타입 레오 (일본판)" },
    { "rtypem82b", "R - 타입 (일본판,해적판)" },
    { "rtypepj", "R - 타입 (일본판 시험판)" },
    { "rtypeu", "R - 타입 (미국판)" },
    { "rugrats", "러그 래츠" },
    { "rumba", "룸바 럼버" },
    { "rumblef", "럼블 피시" },
    { "rumblef2", "럼블 피시 2" },
    { "rumblefp", "럼블 피시 (시제품)" },
    { "rumblf2p", "럼블 피시 2 (시제품)" },
    { "runark", "그라울/ 루나크 (일본판)" },
    { "runaway", "런어웨이" },
    { "runaways", "런어웨이 (선 일렉트로닉,일본판)" },
    { "rundeep", "더 딥/ 런 딥 (복제품)" },
    { "rungun", "런 앤 건" },
    { "rungun2", "런 앤 건 2" },
    { "runguna", "런 앤 건 (버전EAA)" },
    { "rungunad", "런 앤 건 (버전EAA,듀얼스크린)" },
    { "rungunb", "런 앤 건 (버전EAA,프로토타입?)" },
    { "rungunbd", "런 앤 건 (버전EAA,프로토타입?,듀얼스크린)" },
    { "rungund", "런 앤 건 (버전EAA,듀얼스크린)" },
    { "rungunu", "런 앤 건 (버전UAB)" },
    { "rungunua", "런 앤 건 (버전UBA)" },
    { "rungunuad", "런 앤 건 (버전UBA,듀얼스크린)" },
    { "rungunud", "런 앤 건 (버전UAB,투캐비넷)" },
    { "runpuppy", "런 런 퍼피" },
    { "runrun", "런 런 (도! 런 런 해적판)" },
    { "rushatck", "러쉬 앤 어택 (미국판)" },
    { "rushbets", "러싱 비트 슈라 (SNES 해적판)" },
    { "rushcrsh", "러쉬 & 크래쉬 (일본판)" },
    { "rushhero", "러싱 히어로즈" },
    { "rvschola", "사립 저스티스 학원/ 라이벌 스쿨 (아시아판)" },
    { "rvschool", "사립 저스티스 학원/ 라이벌 스쿨" },
    { "rvschoola", "사립 저스티스 학원/ 라이벌 스쿨 (아시아판)" },
    { "rvschoolu", "사립 저스티스 학원/ 라이벌 스쿨 (미국판)" },
    { "rygar", "라이가/ 아르고스의 전사 (미국판 세트1)" },
    { "rygar2", "라이가/ 아르고스의 전사 (미국판 세트2)" },
    { "rygar3", "라이가/ 아르고스의 전사 (미국판 세트3 구버전)" },
    { "rygarb", "라이가/ 아르고스의 전사 (미국판,해적판)" },
    { "rygarj", "라이가/ 아르고스의 전사 (일본판,세트1)" },
    { "rygarj2", "라이가/ 아르고스의 전사 (일본판,세트2)" },
    { "rygark", "라이가/ 아르고스의 전사 (한글)" },
    { "ryorioh", "구르메 배틀 퀴즈 요리왕 쿠킹 (일본판)" },
    { "ryouran", "VS 마작 소녀 요란" },
    { "ryourano", "VS 마작 소녀 요란 (개정판1)" },
    { "ryujin", "류진 (일본판)" },
    { "ryujina", "류진 (일본판)" },
    { "ryukenda", "닌자 용검전 (일본판,세트2)" },
    { "ryukendn", "닌자 용검전 (일본판,세트1)" },
    { "ryukendna", "닌자 용검전 (일본판,세트2)" },
    { "ryukobou", "마작 용호매 (일본판,V030J)" },
    { "ryukyu", "유구 (일본판)" },
    { "ryukyua", "유구 (일본판)" },
    { "ryukyud", "유구 (일본판,암호해제)" },
    { "ryuuha", "류파 (일본판)" },
};

const size_t lookup_r_count = A_SIZE(lookup_r_table);

const char *lookup_r(const char *name) {
    if (!name) return NULL;
    for (size_t i = 0; i < lookup_r_count; i++) {
        if (strcmp(lookup_r_table[i].name, name) == 0) {
            return lookup_r_table[i].value;
        }
    }
    return NULL;
}

const char *r_lookup_r(const char *value) {
    if (!value) return NULL;
    for (size_t i = 0; i < lookup_r_count; i++) {
        if (strstr(lookup_r_table[i].value, value)) {
            return lookup_r_table[i].name;
        }
    }
    return NULL;
}

void lookup_r_multi(const char *term, void (*emit)(const char *name, const char *value, void *udata), void *udata) {
    if (!term) return;
    for (size_t i = 0; i < lookup_r_count; i++) {
        if (strcasestr(lookup_r_table[i].name, term))
            emit(lookup_r_table[i].name, lookup_r_table[i].value, udata);
    }
}

void r_lookup_r_multi(const char *term, void (*emit)(const char *name, const char *value, void *udata), void *udata) {
    if (!term) return;
    for (size_t i = 0; i < lookup_r_count; i++) {
        if (strcasestr(lookup_r_table[i].value, term))
            emit(lookup_r_table[i].name, lookup_r_table[i].value, udata);
    }
}
