#include <string.h>
#include "../common/common.h"
#include "lookup.h"

const LookupName lookup_b_table[] = {
    { "b2b", "뱅 뱅 버스터즈 (2010 NCI 발매)" },
    { "b3rinsya", "불타는 삼륜차" },
    { "babydad", "베이비 다도" },
    { "babypac", "베이비 팩-맨 (세트1)" },
    { "babypac2", "베이비 팩-맨 (세트2)" },
    { "babypkr", "베이비 포커" },
    { "bace", "벌룬 에이스" },
    { "backfira", "백파이어 (세트2)" },
    { "backfire", "백파이어 (세트1)" },
    { "backfirea", "백파이어 (세트2)" },
    { "backfirt", "백 파이어 (테크모,복제품)" },
    { "backgamn", "백게먼" },
    { "badapple", "배드 애플 (HB,테크-데모)" },
    { "baddudes", "배드 듀드스 vs 드래곤닌자 (미국판)" },
    { "badlands", "배드 랜드" },
    { "badlandsb", "배드 랜드" },
    { "bagman", "백맨" },
    { "bagmanf", "백맨" },
    { "bagmanj", "백맨 (타이토)" },
    { "bagmanm2", "백맨 (해적판 세트2)" },
    { "bagmanm3", "백맨 (해적판 세트3)" },
    { "bagmanmc", "백맨" },
    { "bagmans", "백맨 (스턴 일렉트로닉스,세트1)" },
    { "bagmans2", "백맨 (스턴 일렉트로닉스,세트2)" },
    { "bagmans3", "백맨 (스턴 일렉트로닉스 A3)" },
    { "bagmans4", "백맨 (스턴 일렉트로닉스 A4)" },
    { "bagnard", "르 바그나드 (세트1)" },
    { "bagnarda", "르 바그나드 (세트2)" },
    { "bagnardi", "르 바그나드 (스페인판)" },
    { "bagnardio", "르 바그나드 (스페인판, 구형)" },
    { "bakatono", "바보 성주님 마작 만유기" },
    { "bakubaku", "바쿠 바쿠 에니멀" },
    { "bakubrkr", "익스플로시브 브레이커/ 폭렬 브레이커 (일본판)" },
    { "bakuhatu", "마작 폭발 순정전 (일본판)" },
    { "bakutotu", "바라듀크 2 - 폭돌기총정" },
    { "balcube", "밸 큐브" },
    { "ballbomb", "벌룬 봄버" },
    { "ballboy", "볼 보이" },
    { "ballboy3p", "볼 보이" },
    { "ballbros", "벌룬 브라더스" },
    { "ballch", "볼 챌린지" },
    { "balonfgt", "벌룬 파이트" },
    { "baluba", "발바로크의 전설 (일본판)" },
    { "bam2", "버스트 어 무브 2" },
    { "bananadr", "마작 바나나 드림" },
    { "banbam", "반밤/ 펫탄 퓨" },
    { "bandido", "반디도" },
    { "bandit", "무법자" },
    { "bang", "뱅!" },
    { "banga", "뱅! (버전2)" },
    { "bangb", "뱅! (버전0)" },
    { "bangball", "뱅뱅볼 (v1.05)" },
    { "bangbead", "뱅 비드" },
    { "bangbedp", "뱅 비드 (시험판)" },
    { "bangbnd", "뱅 비드 (완전해독됨)" },
    { "bangj", "뱅!/ 건 가바초 (일본판)" },
    { "bankp", "뱅크패닉" },
    { "bankpt", "뱅크패닉 (테크프라이)" },
    { "baracuda", "바라쿠다" },
    { "baraduka", "바라듀크 (세트2)" },
    { "baraduke", "바라듀크" },
    { "barbball", "바룸 베이스볼" },
    { "barek2ch", "베어너클2" },
    { "barek2mb", "베어너클2" },
    { "barek3mb", "베어너클3" },
    { "barek3mba", "베어너클3" },
    { "barekch", "베어너클" },
    { "barline", "바라인" },
    { "barricad", "바리케이드" },
    { "barrier", "배리어" },
    { "baryon", "바욘 - 퓨처 어썰트 (세트1)" },
    { "baryona", "바욘 - 퓨처 어설트 (세트2)" },
    { "basebal2", "베이스볼 시즌 2" },
    { "basketbal", "농구" },
    { "bass", "세가 베스 피싱" },
    { "bassang2", "배스 앵글러 2 (GE865 버전JAA)" },
    { "bassangl", "배스 앵글러 (GE765 버전JAA)" },
    { "basschal", "세가 배스 피싱 챌린지 버전 A" },
    { "basschalo", "세가 배스 피싱 챌린지" },
    { "bassdx", "세가 배스 피싱 디럭스" },
    { "batcir", "배틀 서킷 (유럽판)" },
    { "batcira", "배틀 서킷 (아시아판)" },
    { "batcird", "배틀 서킷 (유럽판,피닉스에디션)" },
    { "batcirj", "배틀 서킷 (일본판)" },
    { "batlbala", "배틀 볼스 (아시아판)" },
    { "batlball", "배틀 볼스 (독일판)" },
    { "batlballa", "배틀 볼스 (아시아판)" },
    { "batlballe", "배틀 볼스 (홍콩판,초기형)" },
    { "batlballo", "배틀 볼스 (독일판)" },
    { "batlballpt", "배틀 볼스 (포르투갈판)" },
    { "batlballu", "배틀 볼스 (미국판)" },
    { "batlbubl", "뱅뱅볼/ 배틀 버블 (v2.00)" },
    { "batlgear", "배틀 기어" },
    { "batlgr2", "배틀 기어 2" },
    { "batlzone", "배틀 존" },
    { "batman", "배트맨" },
    { "batman2", "배트맨 파트 2" },
    { "batmanfr", "배트맨 포에버" },
    { "batrid", "암드 폴리스 배트라이더 (유럽판)" },
    { "batridc", "암드 폴리스 배트라이더 (중국판)" },
    { "batrider", "암드 폴리스 배트라이더 (유럽판)" },
    { "batriderc", "암드 폴리스 배트라이더 (중국판)" },
    { "batriderhk", "암드 폴리스 배트라이더 - A 버전(홍콩판)" },
    { "batriderj", "암드 폴리스 배트라이더 - B 버전(일본판)" },
    { "batriderja", "암드 폴리스 배트라이더 - A 버전(일본판)" },
    { "batriderk", "암드 폴리스 배트라이더 (한국판)" },
    { "batridert", "암드 폴리스 배트라이더 - A 버전(대만판)" },
    { "batrideru", "암드 폴리스 배트라이더 (미국판)" },
    { "batridj", "암드 폴리스 배트라이더 (B 버전)(일본판)" },
    { "batridja", "암드 폴리스 배트라이더 (A 버전)(일본판)" },
    { "batridk", "암드 폴리스 배트라이더 (한국판)" },
    { "batridra", "암드 폴리스 배트라이더 (일본판)" },
    { "batridrk", "암드 폴리스 배트라이더 (한국판)" },
    { "batridta", "암드 폴리스 배트라이더 (A 버전)(대만판)" },
    { "batridu", "암드 폴리스 배트라이더 (미국판)" },
    { "batsugna", "바츠군 (세트2)" },
    { "batsugun", "바츠군" },
    { "batsuguna", "바츠군 (구형,세트1)" },
    { "batsugunb", "바츠군 (한국판 PCB)" },
    { "batsugunbl", "바츠군 (해적판)" },
    { "batsugunc", "바츠군 (구형,세트2)" },
    { "batsugunsp", "바츠군 (특별판)" },
    { "battlan2", "배틀 레인! Vol. 5 (세트2)" },
    { "battlan3", "배틀 레인! Vol. 5 (세트3)" },
    { "battlane", "배틀 레인! Vol. 5 (세트1)" },
    { "battlane2", "배틀 레인! Vol. 5 (세트2)" },
    { "battlane3", "배틀 레인! Vol. 5 (세트3)" },
    { "battlcry", "배틀크라이" },
    { "battlcryc", "배틀크라이 (버전C)" },
    { "battlcryp", "배틀크라이 (시험판)" },
    { "battleg", "배틀 가레가 (타입 2)" },
    { "battlega", "배틀 가레가" },
    { "battlegb", "배틀 가레가 (오스트리아/ 홍콩판)" },
    { "battlegc", "배틀 가레가 (오스트리아/ 홍콩판)" },
    { "battlera", "배틀 레인져스" },
    { "battles", "배틀즈 (세트1)" },
    { "battles2", "배틀즈 (세트2)" },
    { "battlex", "배틀 크로스" },
    { "battlntj", "배틀란티스 (일본판)" },
    { "battlnts", "배틀란티스 (프로그램 코드 G)" },
    { "battlntsa", "배틀란티스 (프로그램 코드 F)" },
    { "battlntsj", "배틀란티스 (일본판,프로그램 코드 E)" },
    { "battroad", "배틀 로드" },
    { "batugnsp", "발군 (특별판)" },
    { "batwings", "배틀 윙스 (대체)" },
    { "bayrout1", "베이 루트 (세트1,US,비보호)" },
    { "bayrouta", "베이 루트 (세트2)" },
    { "bayroute", "베이 루트 (세트3,세계판)" },
    { "bayroute1", "베이 루트 (세트1,US,비보호)" },
    { "bayrouteb1", "베이 루트 (암호화,해적판)" },
    { "bayrouteb2", "베이 루트" },
    { "bayrouted", "베이 루트 (세트3,세계판,암호해제)" },
    { "bayroutej", "베이 루트 (세트2,일본판)" },
    { "bayroutejd", "베이 루트 (세트2,일본판,암호해제)" },
    { "bayroutj", "베이 루트 (세트2,일본판)" },
    { "bayrtbl1", "베이 루트 (해적판 세트1)" },
    { "bayrtbl2", "베이 루트 (해적판 세트2)" },
    { "bbakradu", "배틀 바크레이드 - 언리미티드 버전(일본판)" },
    { "bbakraid", "배틀 바크레이드 - 언리미티드 버전(미국판)" },
    { "bbakraidc", "배틀 바크레이드 - 언리미티드 버전(중국판)" },
    { "bbakraidj", "배틀 바크레이드 - 언리미티드 버전(일본판)" },
    { "bbakraidja", "배틀 바크레이드 (일본판)" },
    { "bballoon", "벌룬 & 벌룬" },
    { "bballs", "바운싱 볼즈" },
    { "bballsa", "바운싱 볼즈 (성인)" },
    { "bbbxing", "베스트 바우트 복싱 (버전1.3)" },
    { "bbh", "빅 벅 헌터" },
    { "bbh2sp", "빅 벅 헌터 II - 스포츠맨의 천국" },
    { "bbh2spa", "빅 벅 헌터 II - 스포츠맨의 천국" },
    { "bbh2spb", "빅 벅 헌터 II - 스포츠맨의 천국" },
    { "bbhcotw", "빅 벅 헌터 야생의 부름" },
    { "bbhsc", "빅 벅 헌터 - 슈터의 도전" },
    { "bbhsca", "빅 벅 헌터 - 슈터의 도전" },
    { "bbmanw", "봄버맨 월드_뉴 다이나 블래스터 - 글로벌 퀘스트" },
    { "bbmanwj", "봄버맨 월드 (일본판)" },
    { "bbmanwja", "봄버맨 월드 (일본판,개정판사운드 하드웨어)" },
    { "bbonk", "빅풋 본커스" },
    { "bbprot", "파이팅 게임" },
    { "bbredux", "보블 보블 (해적판 리덕스 핵)" },
    { "bbros", "팡/ 버스터 형제 (미국판)" },
    { "bbust2", "비스트 버스터즈 2nd 나이트매어" },
    { "bbusters", "비스트 버스터즈 (세계판)" },
    { "bbustersj", "비스트 버스터즈 (일본판,버전2,3인용)" },
    { "bbustersja", "비스트 버스터즈 (일본판,버전2,2인용)" },
    { "bbustersu", "비스트 버스터즈 (미국판,버전3)" },
    { "bbustersua", "비스트 버스터즈 (미국판,버전2)" },
    { "bchance", "본 샹스! (프랑스어/영어)" },
    { "bchancep", "본 샹스! (골든 포커 프리퀄 HW,세트1)" },
    { "bchanceq", "본 샹스! (골든 포커 프리퀄 HW,세트2)" },
    { "bchopper", "배틀 초퍼-미스터 헬리의 대모험 (세계판)" },
    { "bcrusher", "본 크러셔" },
    { "bcruzm12", "배틀 크루저 M-12" },
    { "bcstry", "B.C. 스토리 (세트1)" },
    { "bcstrya", "B.C. 스토리 (세트2)" },
    { "bdrdown", "보더 다운 (개정판A)(GDL-0023A)" },
    { "bdream97", "호접몽 97" },
    { "bdudes", "배드 듀드스 - 버거 에디션" },
    { "beachspi", "비치 스파이커" },
    { "beaminv", "빔 인베이더" },
    { "beaminva", "빔 인베이더 (세트2)" },
    { "beast", "쉐도우 오브 더 비스트 (네오지오 데모)" },
    { "beastf", "비스티 피스티" },
    { "beastfp", "비스티 피스티 (팩맨 컨버전)" },
    { "beastrzb", "비스토라이저" },
    { "beastrzr", "비스토라이저" },
    { "beastrzra", "비스토라이저" },
    { "beastrzrb", "비스토라이저" },
    { "beathead", "비트헤드" },
    { "beautyb", "뷰티 블록" },
    { "beeline", "비라인" },
    { "beezer", "비저" },
    { "beezer1", "비저 (세트2)" },
    { "begas", "베가의 전투" },
    { "begas1", "베가의 전투 (개정판1)" },
    { "bejpoker", "보난자 엔터프라이즈 조커 포커" },
    { "bel", "비하인드 에너미 라인스" },
    { "benberob", "벤 베로 베" },
    { "berabohm", "초절륜인 베라보맨 (일본판,개정판C)" },
    { "berabohmb", "초절륜인 베라보맨 (일본판,개정판B)" },
    { "berabohmo", "초절륜인 베라보맨 (일본판 버전B)" },
    { "beraboho", "초절륜인 베라보맨 (일본판 버전B)" },
    { "berenstn", "베런스타인 베어즈 인 빅 포우스 케이브" },
    { "berlwall", "베를린 장벽" },
    { "berlwallk", "베를린 장벽 (한국판)" },
    { "berlwallt", "베를린 장벽" },
    { "berlwalt", "베를린 장벽" },
    { "bermudaa", "월드 워즈/ 버뮤다 삼각지대 (미국판 구버전)" },
    { "bermudaj", "버뮤다 삼각지대 (일본판)" },
    { "bermudao", "버뮤다 삼각지대 (일본판 구버전)" },
    { "bermudat", "버뮤다 삼각지대 (세계판?)" },
    { "bermudata", "월드 워즈/ 버뮤다 삼각지대 (미국판)" },
    { "bermudatj", "버뮤다 삼각지대 (일본판)" },
    { "berzerk", "버저크 (개정판RC31A)" },
    { "berzerk1", "버저크 (세트2)" },
    { "berzerka", "버저크 (개정판RC31A)" },
    { "berzerkb", "버저크 (개정판RC28)" },
    { "berzerkf", "버저크 (프랑스판,개정판RC31A)" },
    { "berzerkg", "버저크 (독일판,개정판RC31A)" },
    { "berzerks", "버저크 (스페인판,개정판RC31A)" },
    { "bestbest", "베스트 오브 베스트" },
    { "bestleag", "베스트 리그 (해적판,이탈리아 시리즈 A)" },
    { "bestleaw", "베스트 리그 (해적판,월드컵)" },
    { "bestri", "베스트라이 (한국판,세트1)" },
    { "bestria", "베스트라이 (한국판,세트2)" },
    { "betafrce", "베타 포스" },
    { "bgaregcn", "배틀 가레가 (타입2)(덴마크판,중국판)" },
    { "bgaregga", "배틀 가레가" },
    { "bgareggabl", "배틀 가레가 (1945 파트2)(중국 핵)" },
    { "bgareggabla", "배틀 가레가 (뢰신전)(중국 핵)" },
    { "bgareggablj", "배틀 가레가 (일본판, 해적판)" },
    { "bgareggacn", "배틀 가레가 (타입2)(덴마크판,중국판)" },
    { "bgareggahk", "배틀 가레가 (오스트리아/ 홍콩판)" },
    { "bgareggak", "배틀 가레가 (한국판/ 그리스판)" },
    { "bgaregganv", "배틀 가레가 (신버전)(오스트리아/ 홍콩판)" },
    { "bgareggat", "배틀 가레가 (로케이션 테스트)" },
    { "bgareggat2", "배틀 가레가 (타입2)" },
    { "bgareggatw", "배틀 가레가 (대만판,독일판)" },
    { "bgareggaz", "배틀 가레가 (자크 버전)" },
    { "bgareghk", "배틀 가레가 (오스트리아/ 홍콩판)" },
    { "bgaregnv", "배틀 가레가 (신버전)(오스트리아/ 홍콩판)" },
    { "bgaregt2", "배틀 가레가 (타입2)" },
    { "big10", "빅 10" },
    { "big10a", "빅 10" },
    { "bigappg", "빅 애플 게임즈" },
    { "bigbang", "빅 뱅" },
    { "bigbanga", "빅 뱅 (세트2)" },
    { "bigbucks", "빅 벅스" },
    { "bigcsino", "빅 카지노" },
    { "bigd2", "빅 D2" },
    { "bigdeal", "빅 딜" },
    { "bigdealb", "빅 딜 (헝가리판,세트2)" },
    { "bigevglf", "빅 이벤트 골프" },
    { "bigevglfj", "빅 이벤트 골프 (일본판)" },
    { "bigfghtr", "스카이 스키퍼/ 싸워라! 빅 파이터 (일본판)" },
    { "bigfight", "빅 파이트 - 빅 트러블 인 아틀란틱 오션" },
    { "bigfightj", "빅 파이트 - 빅 트러블 인 아틀란틱 오션" },
    { "bigjoke", "빅 조크" },
    { "bigkarnk", "빅 카르나크" },
    { "bigkarnkm", "빅 카르나크" },
    { "bigkong", "빅 콩" },
    { "bigkonggx", "빅 콩" },
    { "bigprowr", "빅 프로 레슬링!" },
    { "bigprowra", "빅 프로 레슬링! (세트2)" },
    { "bigrun", "빅 런 (11th 랠리 버전)" },
    { "bigrunu", "빅 런 (11th 랠리 버전)" },
    { "bigstrik", "빅 스트라이커" },
    { "bigstrkb", "빅 스트라이커" },
    { "bigstrkba", "빅 스트라이커" },
    { "bigtwin", "빅 트윈" },
    { "bigtwinb", "빅 트윈 ( 노 걸스 컨버전)" },
    { "bijokkog", "미소녀 학원" },
    { "bijokkoy", "미소녀 꿈 이야기" },
    { "bikkuri", "빗쿠리 프로 레스링" },
    { "bikkuric", "빗쿠리 카드 (일본판)" },
    { "billiard", "당구" },
    { "billlist", "빌라드 리스트" },
    { "bilyard", "빌리어드" },
    { "bingo", "빙고" },
    { "bingoc", "빙고 서킷" },
    { "bingopd", "파라다이스 (브라질 산업,버전1.04)" },
    { "bingor1", "빙고 롤/ 벨 스타" },
    { "bingor2", "빙고 롤/ 벨 스타" },
    { "bingor3", "빙고 롤/ 벨 스타" },
    { "bingor4", "빙고 롤/ 벨 스타" },
    { "bingor5", "빙고 롤/ 벨 스타 v3" },
    { "bingowng", "빙고" },
    { "bingownga", "빙고 (세트2)" },
    { "bioatack", "바이오 어택" },
    { "biofreak", "바이오프릭스" },
    { "biomtoy", "바이오메카니컬 토이 (버전1.0.1885)" },
    { "biomtoya", "바이오메카니컬 토이 (버전1.0.1884)" },
    { "biomtoyb", "바이오메카니컬 토이 (버전1.0.1878)" },
    { "biomtoyc", "바이오메카니컬 토이 (버전1.0.1870)" },
    { "bionicc", "바이오닉 코만도 (유럽판)" },
    { "bionicc1", "바이오닉 코만도 (미국판 세트1)" },
    { "bionicc2", "바이오닉 코만도 (미국판 세트2)" },
    { "bioniccbl", "바이오닉 코만도 (해적판,세트1)" },
    { "bioniccbl2", "바이오닉 코만도 (해적판,세트2)" },
    { "bioplayc", "바이오플레이씽 캅 (버전1.0.1823,시험판)" },
    { "bioship", "바이오-쉽 팔라딘" },
    { "birdiy", "버디" },
    { "birdtry", "버디 트라이 (일본판 개정판2,개정판1 MCU)" },
    { "birdtrya", "버디 트라이 (일본판 개정판2)" },
    { "birdtryb", "버디 트라이 (일본판 개정판S)" },
    { "bishi", "비시바시 챔피언쉽 미니 게임 선수권 (버전JAA,3인용)" },
    { "bishjan", "미소작" },
    { "bjourney", "블루즈 저니/ 라가이" },
    { "bjourneyh", "블루즈 저니/ 라가이 (ALH-001)" },
    { "bjpoker", "포커/ 블랙 잭" },
    { "bjtwin", "봄잭 트윈 (세트1)" },
    { "bjtwina", "봄잭 트윈 (세트2)" },
    { "bjtwinp", "봄잭 트윈 (시제품? 성인용 사진 포함,세트1)" },
    { "bjtwinpa", "봄잭 트윈" },
    { "bk3ssrmb", "베어너클3" },
    { "bking", "버디 킹" },
    { "bking2", "버디 킹 2" },
    { "bking3", "버디 킹 3" },
    { "bkraidj", "배틀 바크레이드 (일본판)" },
    { "bkraidu", "배틀 바크레이드 - 언리미티드 버전" },
    { "bkraiduj", "배틀 바크레이드 - 언리미티드 버전(일본판)" },
    { "bkrtmaq", "폭렬 퀴즈 마Q 대모험 (일본판)" },
    { "bktigerb", "블랙 타이거" },
    { "bkungfu", "비욘드 쿵푸" },
    { "black", "크제르니시 카라뷔" },
    { "blackhol", "블랙 홀" },
    { "blackt96", "블랙 터치 96" },
    { "bladestl", "블레이드 오브 스틸 (버전T,조이스틱)" },
    { "bladestle", "블레이드 오브 스틸 (버전E,트랙볼)" },
    { "bladestll", "블레이드 오브 스틸 (버전L,트랙볼)" },
    { "bladstle", "블레이드 오브 스틸 (버전E)" },
    { "blandia", "황금성 2/ 블랜디아" },
    { "blandiap", "황금성 2/ 블랜디아 (시험판)" },
    { "blast30", "블래스터 (초기 30 웨이브 버전)" },
    { "blasted", "블래스티드" },
    { "blaster", "블래스터" },
    { "blaster30", "블래스터 (초기 30 웨이브 버전)" },
    { "blasterkit", "블래스터 (키트)" },
    { "blastero", "블래스터 (로케이션 테스트)" },
    { "blastkit", "블래스터 (키트)" },
    { "blasto", "블라스토" },
    { "blastoff", "블래스트 오프 (일본판)" },
    { "blazeon", "블레이즈 온 (세계판)" },
    { "blazeonj", "블레이즈 온 (일본판)" },
    { "blazer", "블레이저 (일본판)" },
    { "blazlaz", "블레이징 레이져스" },
    { "blazstar", "블레이징 스타" },
    { "blazstarcm", "블레이징 스타 (스테이지 선택핵)" },
    { "blckgalb", "블럭 갈 (해적판)" },
    { "blckjack", "블랙 잭" },
    { "blckout2", "블럭 아웃 (세트2)" },
    { "blckoutj", "블럭 아웃 (일본판)" },
    { "bldwolf", "블러디 울프 (미국판)" },
    { "bldwolfj", "불량 선동부대 블러디 울프 (일본판)" },
    { "bldyroar", "블러디 로어 (일본판)" },
    { "bldyror2", "블러디 로어 2" },
    { "bldyror2a", "블러디 로어 2 (아시아판)" },
    { "bldyror2j", "블러디 로어 2 (일본판)" },
    { "bldyror2u", "블러디 로어 2 (미국판)" },
    { "blitz", "NFL 블리츠" },
    { "blitz11", "NFL 블리츠 (부트 ROM 1.1)" },
    { "blitz2k", "NFL 블리츠 2000 골드 에디션" },
    { "blitz99", "NFL 블리츠 99" },
    { "blitz99a", "NFL 블리츠 99 (버전1.2, Aug 28 1998)" },
    { "blkbustr", "블럭 버스터/ 미스터 종" },
    { "blkdrgnb", "블랙 드래곤" },
    { "blkdrgnk", "블랙 드래곤 (한글)" },
    { "blkdrgon", "블랙 드래곤 (일본판)" },
    { "blkdrgonb", "블랙 드래곤" },
    { "blkhearj", "블랙 하트 (일본판)" },
    { "blkheart", "블랙 하트" },
    { "blkheartj", "블랙 하트 (일본판)" },
    { "blkhole", "블랙 홀" },
    { "blkpnthr", "블랙 팬서" },
    { "blkrhino", "블랙 라이노" },
    { "blktch2", "블랙 터치 2 (한국판)" },
    { "blktiger", "블랙 타이거" },
    { "blktigera", "블랙 타이거 (구형)" },
    { "blktigerb1", "블랙 타이거 (해적판 세트1)" },
    { "blktigerb2", "블랙 타이거 (해적판 세트2)" },
    { "blktigerb3", "블랙 타이거/ 블랙 드래곤" },
    { "blktouch", "블랙 터치" },
    { "blmbycar", "블롬비 카" },
    { "blmbycaru", "블롬비 카 (비암호화)" },
    { "blmbycau", "블롬비 카 (비암호화)" },
    { "block", "블럭 블럭 (세계판 조이스틱)" },
    { "block2", "블록 2" },
    { "blocka", "블럭 블럭 (세계판)" },
    { "blockade", "블록케이드" },
    { "blockbl", "블럭 블럭" },
    { "blockcar", "썬더 & 라이트닝 2/ 블럭 카니발" },
    { "blockcarb", "썬더 & 라이트닝 2/ 블럭 카니발 (해적판)" },
    { "blocken", "브로켄 (일본판)" },
    { "blockgal", "블럭 갈" },
    { "blockgalb", "블럭 갈 (해적판)" },
    { "blockhl", "블록 홀/ 쿼스" },
    { "blockj", "블럭 블럭 (일본판)" },
    { "blockjoy", "블럭 블럭 (세계판 조이스틱)" },
    { "blockout", "블럭 아웃 (세트1)" },
    { "blockout2", "블럭 아웃 (세트2)" },
    { "blockout3", "블럭 아웃 (유럽판/ 오세아니아판)" },
    { "blockoutj", "블럭 아웃 (일본판)" },
    { "blockr1", "블럭 블럭 (세계판 조이스틱)" },
    { "blockr2", "블럭 블럭 (세계판)" },
    { "blokpong", "블록 퐁 퐁" },
    { "bloodbra", "카발 2/ 블러드 브라더스 (세트2)" },
    { "bloodbro", "카발 2/ 블러드 브라더스 (세계판?)" },
    { "bloodbroa", "카발 2/ 블러드 브라더스 (세트2)" },
    { "bloodbrob", "카발 2/ 블러드 브라더스 (세트3)" },
    { "bloodbroj", "카발 2/ 블러드 브라더스 (일본판,개정판A)" },
    { "bloodbroja", "카발 2/ 블러드 브라더스 (일본판)" },
    { "bloodbrok", "카발 2/ 블러드 브라더스 (한국판)" },
    { "bloodbrom", "카발 2/ 블러드 브라더스 (모듈 시스템)" },
    { "bloodbrou", "카발 2/ 블러드 브라더스 (미국판)" },
    { "bloods11", "블러드 스톰 (v1.10)" },
    { "bloods21", "블러드 스톰 (v2.10)" },
    { "bloods22", "블러드 스톰 (v2.20)" },
    { "bloodstm", "블러드 스톰 (v2.22)" },
    { "bloodstm10", "블러드 스톰 (v1.04)" },
    { "bloodstm104", "블러드 스톰 (v1.04)" },
    { "bloodstm11", "블러드 스톰 (v1.10)" },
    { "bloodstm110", "블러드 스톰 (v1.10)" },
    { "bloodstm21", "블러드 스톰 (v2.10)" },
    { "bloodstm210", "블러드 스톰 (v2.10)" },
    { "bloodstm22", "블러드 스톰 (v2.20)" },
    { "bloodstm220", "블러드 스톰 (v2.20)" },
    { "bloodstm221", "블러드 스톰 (v2.21)" },
    { "bloodwar", "블러드 워리어" },
    { "blox", "블록스" },
    { "blox16b", "블록시드 (시스템16B,PS2 데이터)" },
    { "bloxd", "블록스 (v2.0,데이터팩)" },
    { "bloxeed", "블록시드 (일본판)" },
    { "bloxeeda", "블록시드 (일본판,초기형)" },
    { "bloxeedc", "블록시드 (세계판,C 시스템)" },
    { "bloxeedd", "블록시드 (일본판,암호해제)" },
    { "bloxeedu", "블록시드 (미국판,C 시스템)" },
    { "blsthead", "블래스테로이즈" },
    { "blstroi2", "블래스테로이즈 (개정판2)" },
    { "blstroi3", "블래스테로이즈 (개정판3)" },
    { "blstroid", "블래스터로이드 (개정판4)" },
    { "blstroid2", "블래스테로이즈 (개정판2)" },
    { "blstroid3", "블래스테로이즈 (개정판3)" },
    { "blstroidg", "블래스테로이즈 (독일판,개정판2)" },
    { "blstroidh", "블래스테로이즈" },
    { "blstroig", "블래스테로이즈 (독일판,개정판2)" },
    { "blswhstl", "나왔구나!! 트윈비/ 벨즈 & 휘슬즈 (세계판,버전L)" },
    { "blswhstla", "나왔구나!! 트윈비/ 벨즈 & 휘슬즈 (아시아판,버전M)" },
    { "bluehawk", "블루 호크" },
    { "bluehawkn", "블루 호크 (NTC)" },
    { "bluehawn", "블루 호크 (NTC)" },
    { "blueprnj", "블루 프린트 (자레코)" },
    { "blueprnt", "블루 프린트" },
    { "blueprntj", "블루 프린트 (자레코)" },
    { "blueshrk", "블루 샤크" },
    { "blueshrkmr", "블루 샤크" },
    { "blueshrkmr2", "블루 샤크" },
    { "blzntrnd", "블레이징 토네이도" },
    { "bm1stmix", "비트매니아" },
    { "bm2ndmix", "비트매니아 2nd 믹스" },
    { "bm2ndmxa", "비트매니아 2nd 믹스 (버전JA-A)" },
    { "bm3", "비트매니아 III" },
    { "bm36th", "비트매니아 III 어펜드 6th 믹스" },
    { "bm37th", "비트매니아 III 어펜드 7th 믹스" },
    { "bm3core", "비트매니아 III 어펜드 코어 리믹스" },
    { "bm3final", "비트매니아 III 더 파이널" },
    { "bm3rdeaa", "비트매니아 3rd 믹스" },
    { "bm3rdmix", "비트매니아 3rd 믹스" },
    { "bm4thmix", "비트매니아 4th 믹스" },
    { "bm5thmix", "비트매니아 5th 믹스" },
    { "bm6thmix", "비트매니아 6th 믹스" },
    { "bm7thmix", "비트매니아 7th 믹스" },
    { "bmaster", "블레이드 마스터 (세계판)" },
    { "bmcbowl", "BMC 볼링" },
    { "bmclubmx", "비트매니아 클럽 믹스" },
    { "bmcmxaac", "비트매니아 컴플리트 믹스" },
    { "bmcompm2", "비트매니아 컴플리트 믹스 2" },
    { "bmcompmx", "비트매니아 컴플리트 믹스" },
    { "bmcompmxb", "비트매니아 컴플리트 믹스" },
    { "bmcorerm", "비트매니아 코어 리믹스" },
    { "bmcpokr", "동방 신룡" },
    { "bmdct", "비트매니아 f. 드림스 컴 트루" },
    { "bmfinal", "비트매니아 더 파이널" },
    { "bmiidx", "비트매니아 IIDX" },
    { "bmiidx2", "비트매니아 IIDX 2nd 스타일" },
    { "bmiidx3", "비트매니아 IIDX 3th 스타일" },
    { "bmiidx3a", "비트매니아 IIDX 3th 스타일" },
    { "bmiidx3b", "비트매니아 IIDX 3th 스타일" },
    { "bmiidx4", "비트매니아 IIDX 4th 스타일" },
    { "bmiidx5", "비트매니아 IIDX 5th 스타일" },
    { "bmiidx6", "비트매니아 IIDX 6th 스타일" },
    { "bmiidx6a", "비트매니아 IIDX 6th 스타일" },
    { "bmiidx7", "비트매니아 IIDX 7th 스타일" },
    { "bmiidx7a", "비트매니아 IIDX 7th 스타일" },
    { "bmiidx8", "비트매니아 IIDX 8th 스타일" },
    { "bmiidxc", "비트매니아 IIDX DDR 2 클럽 버전" },
    { "bmiidxc2", "비트매니아 IIDX DDR 2 클럽 버전2" },
    { "bmiidxca", "비트매니아 IIDX DDR 2 클럽 버전(896 JAA)" },
    { "bmiidxs", "비트매니아 IIDX 서브스트림" },
    { "bmiidxsa", "비트매니아 IIDX 서브스트림" },
    { "bmxstunts", "BMX 스턴트" },
    { "bngbeadn", "뱅 비드 (해독됨 C)" },
    { "bnglngby", "헬기 대작전/ 반겔링만의 습격" },
    { "bngotime", "빙고 타임" },
    { "bnj", "버닝 러버/ 범프 앤 점프" },
    { "bnjm", "버닝 러버/ 범프 앤 점프 (미드웨이)" },
    { "bnstars", "잔시 브랜드뉴 스타 (메가시스템32 버전)" },
    { "bnstars1", "잔시 브랜드뉴 스타" },
    { "bnzabros", "보난자 형제/ 홀쭉이와 뚱뚱이 (미국판)" },
    { "bnzabrosj", "보난자 형제/ 홀쭉이와 뚱뚱이 (일본판)" },
    { "bnzabrsj", "보난자 형제/ 홀쭉이와 뚱뚱이 (일본판)" },
    { "boasorte", "보아 소르테! (골든 포커 프리퀄 HW)" },
    { "boblbobl", "보블 보블" },
    { "boblcave", "버블보블 - 잃어버린 동굴 V1.2" },
    { "bodyslam", "바디 슬램/ 여자 레슬링" },
    { "bogeyman", "보기 매너" },
    { "boggy84", "보기 84" },
    { "boggy84b", "보기 84" },
    { "bombbee", "봄비" },
    { "bomber", "봄버" },
    { "bombjac2", "봄 잭 (세트2)" },
    { "bombjack", "봄 잭 (세트1)" },
    { "bombjack2", "봄 잭 (세트2)" },
    { "bombjackbl", "봄 잭 (해적판)" },
    { "bombjackt", "봄 잭 (테크프라이,스페인)" },
    { "bombkick", "봄 킥 (세트1)" },
    { "bombkicka", "봄 킥 (세트2)" },
    { "bomblord", "봄버 로드" },
    { "bombrman", "봄버맨 (일본판)" },
    { "bombsa", "봄즈 어웨이" },
    { "bonanza", "보난자" },
    { "bonanzar2", "보난자 (개정판2)" },
    { "bongo", "봉고" },
    { "bongog", "봉고" },
    { "bonkadv", "B.C. 키드/봉크 어드벤처/구극!! PC 원인" },
    { "bonkadva", "봉크 어드벤처 (시험판)" },
    { "bonuspkr", "보너스 포커" },
    { "bonusstage", "보너스 스테이지 (HB)" },
    { "bonzeado", "본즈 어드벤처 (세계판,구형)" },
    { "bonzeadu", "본즈 어드벤처 (미국판)" },
    { "bonzeadv", "본즈 어드벤처 (세계판,신형)" },
    { "bonzeadvo", "본즈 어드벤처 (세계판,구형)" },
    { "bonzeadvp", "본즈 어드벤처 (세계판,시험판)" },
    { "bonzeadvp2", "본즈 어드벤처 (세계판,시험판,구형)" },
    { "bonzeadvu", "본즈 어드벤처 (미국판)" },
    { "boobhack", "부비 키즈 (이탈리아판 해적판)(해적판)" },
    { "boogwina", "부기 윙즈 (아시아판 v1.5)" },
    { "boogwing", "부기 윙즈 (유럽판 v1.5)" },
    { "boogwinga", "부기 윙즈 (아시아판 v1.5)" },
    { "boogwingu", "부기 윙즈 (미국판)" },
    { "bookthr", "북 시어터" },
    { "boomrang", "부메랑/ 제네시스 (세트1)" },
    { "boomranga", "부메랑/ 제네시스 (세트2)" },
    { "boonggab", "붕가 붕가 (스팽크'엠!)" },
    { "bootcamp", "부트 캠프" },
    { "bootcampa", "부트 캠프" },
    { "boothill", "부트 힐" },
    { "borench", "보렌치" },
    { "borencha", "보렌치 (세트2)" },
    { "borenchj", "보렌치 (일본판)" },
    { "borntofi", "본 투 파이트" },
    { "borntofia", "본 투 파이트" },
    { "borntofiv", "본 투 파이트" },
    { "bosco", "보스코니안 (버전5)" },
    { "bosco1", "보스코니안 (버전1,신형)" },
    { "bosco1o", "보스코니안 (버전1,구형)" },
    { "bosco3", "보스코니안 (버전3)" },
    { "boscomd", "보스코니안 (미드웨이,신버전)" },
    { "boscomdo", "보스코니안 (미드웨이,구버전)" },
    { "boscoo", "보스코니안 (구버전)" },
    { "boscoo2", "보스코니안 (구버전)" },
    { "botanic", "보터닉 (영어/ 스페인어)" },
    { "botanic2", "보터닉 (영어/ 스페인어,백맨 컨버전)" },
    { "botanicf", "보터닉 (프랑스판)" },
    { "botss", "배틀 오브 더 솔라 시스템/ 태양계 전투" },
    { "botss11", "배틀 오브 더 솔라 시스템/ 태양계 전투 (개정판1.1 3/24/92)" },
    { "botssa", "배틀 오브 더 솔라 시스템/ 태양계 전투 (개정판1.1a)" },
    { "bottl10b", "보틀 10 (이탈리아,세트2)" },
    { "bottle10", "보틀 10" },
    { "bottom9", "9회말 (버전T)" },
    { "bottom9n", "9회말 (버전N)" },
    { "bouldash", "볼더 대시 파트 2 (세계판)" },
    { "bouldashj", "볼더 대시 파트 2 (일본판)" },
    { "bouldshj", "볼더 대시 파트 2 (일본판)" },
    { "bounty", "바운티" },
    { "bounty2", "바운티 (세트2)" },
    { "bowl3d", "3D 볼링" },
    { "bowler", "볼링 어레이" },
    { "bowlgum", "볼링 검" },
    { "bowlrama", "보울 오 라마/ 볼링" },
    { "bowmen", "보우맨" },
    { "boxer", "복서" },
    { "boxingb", "복싱 벅스" },
    { "boxingm", "복싱 매니아" },
    { "boxyboy", "박시 보이 (세계판,SB2)" },
    { "boxyboya", "박시 보이 (SB?)" },
    { "bpanicdx", "블록 패닉 DX (HB)" },
    { "bradley", "브래들리 트레이너" },
    { "brain", "브레인" },
    { "brapboys", "B.랩 보이즈 (세계판)" },
    { "brapboysj", "B.랩 보이즈 스페셜 (일본판)" },
    { "brapboysp", "B.랩 보이즈 스페셜 (세계판)" },
    { "brapboysp2", "B.랩 보이즈 스페셜 (세계판,구형)" },
    { "brapboyspj", "B.랩 보이즈 스페셜 (일본판)" },
    { "brapboyspu", "B.랩 보이즈 스페셜 (미국판)" },
    { "brasil", "브라질" },
    { "brasil86", "브라질 86" },
    { "brasil87", "브라질 87" },
    { "brasil89", "브라질 89" },
    { "brasil89a", "브라질 89 (세트2)" },
    { "brasil93", "브라질 93" },
    { "brdrlinb", "보더라인 (카라테코 해적판)" },
    { "brdrline", "보더라인" },
    { "brdrlinet", "보더라인 (진정제 총 컨버전)" },
    { "brdrlins", "보더라인 (시담 해적판)" },
    { "breakerb", "브레이커즈 (보스 핵)" },
    { "breakers", "브레이커즈" },
    { "breakout", "브레이크아웃" },
    { "breakreb", "브레이커즈 리벤지 (보스 핵)" },
    { "breakrev", "브레이커즈 리벤지" },
    { "breakrevbh", "브레이커즈 리벤지 (보스 핵)" },
    { "breywood", "섀클드/ 브레이우드 (일본판 개정판2)" },
    { "brickyrd", "브릭야드" },
    { "brickzn", "브릭 존 (v6.0,조이스틱)" },
    { "brickzn11", "브릭 존 (v1.1,스피너)" },
    { "brickzn3", "브릭 존 (v3.0)" },
    { "brickznv4", "브릭 존 (v4.0,스피너)" },
    { "brickznv5", "브릭 존 (v5.0,조이스틱)" },
    { "brival", "버닝 라이벌 (세계판)" },
    { "brivalj", "버닝 라이벌 (일본판)" },
    { "brix", "브릭스" },
    { "brixian", "브릭시안" },
    { "brkball", "브레이크 볼" },
    { "brkblast", "브릭 블라스트 (월 크래시의 해적판)" },
    { "brkrevext", "브레이커즈 리벤지 (엑스트라 모드,핵)" },
    { "brkrevjq", "브레이커즈 리벤지 (강화된,핵)" },
    { "brkthru", "브레이크 드루/ 강공돌파 (미국판)" },
    { "brkthrubl", "브레이크 드루/ 강공돌파 (해적판)" },
    { "brkthruj", "브레이크 드루/ 강공돌파 (일본판)" },
    { "brkthrut", "브레이크 드루/ 강공돌파 (테크프라이 라이센스)" },
    { "brod", "브로드 자가" },
    { "bronx", "브롱크스" },
    { "brubber", "버닝 러버" },
    { "brutforc", "브루트 포스" },
    { "brvblade", "브레이브 블레이드" },
    { "brvbladea", "브레이브 블레이드 (아시아판)" },
    { "brvbladej", "브레이브 블레이드 (일본판)" },
    { "brvbladeu", "브레이브 블레이드 (미국판)" },
    { "bs4thmix", "비트스테이지 4th 믹스" },
    { "bs94", "브에나 스에르테 94" },
    { "bscompmx", "비트스테이지 컴플릿 믹스" },
    { "bsebman", "봄버맨 (버전6.6)" },
    { "bsebmanbl", "봄버맨 (버전6.6,아브람 해적판)" },
    { "bsebmanbl2", "봄버맨 (버전6.6,J.T.해적판)" },
    { "bshark", "배틀 샤크 (세계판)" },
    { "bsharkj", "배틀 샤크 (일본판)" },
    { "bsharkjjs", "배틀 샤크 (일본판,조이스틱)" },
    { "bsharku", "배틀 샤크 (미국판)" },
    { "bsktball", "농구" },
    { "bssoccer", "길거리 축구" },
    { "bssoccera", "길거리 축구 (KRB-0032A PCB)" },
    { "bstars", "베이스볼 스타즈 프로페셔널" },
    { "bstars2", "베이스볼 스타즈 2" },
    { "bstarsh", "베이스볼 스타즈 프로페셔널 (NGH-002)" },
    { "bsuerte", "브에나 스에르테" },
    { "bsuertea", "브에나 스에르테 (스페인어,세트2)" },
    { "bsuerteb", "브에나 스에르테 (스페인어,세트3)" },
    { "bsuertec", "브에나 스에르테 (스페인어,세트4)" },
    { "bsuerted", "브에나 스에르테 (스페인어,세트5)" },
    { "bsuertee", "브에나 스에르테 (스페인어,세트6)" },
    { "bsuertef", "브에나 스에르테 (스페인어,세트7)" },
    { "bsuerteg", "브에나 스에르테 (스페인어,세트8)" },
    { "bsuerteh", "브에나 스에르테 (스페인어,세트9)" },
    { "bsuertei", "브에나 스에르테 (스페인어,세트10)" },
    { "bsuertej", "브에나 스에르테 (스페인어,세트11)" },
    { "bsuertek", "브에나 스에르테 (스페인어,세트12)" },
    { "bsuertel", "브에나 스에르테 (스페인어,세트13)" },
    { "bsuertem", "브에나 스에르테 (스페인어,세트14)" },
    { "bsuerten", "브에나 스에르테 (스페인어,세트15)" },
    { "bsuerteo", "브에나 스에르테 (스페인어,세트16)" },
    { "bsuertep", "브에나 스에르테 (스페인어,세트17)" },
    { "bsuerteq", "브에나 스에르테 (스페인어,세트18)" },
    { "bsuerter", "브에나 스에르테 (스페인어,세트19)" },
    { "bsuertes", "브에나 스에르테 (스페인어,세트20)" },
    { "bsuertet", "브에나 스에르테 (스페인어,세트21)" },
    { "bsuerteu", "브에나 스에르테 (스페인어,세트22)" },
    { "bsuertev", "브에나 스에르테 (스페인어.포르투갈어,세트23)" },
    { "btchamp", "비트 더 챔프" },
    { "btime", "버거 타임 (데이터이스트 세트1)" },
    { "btime2", "버거 타임 (데이터이스트 세트2)" },
    { "btime3", "버거 타임 (데이터이스트)" },
    { "btimem", "버거 타임 (미드웨이)" },
    { "btlecity", "배틀 시티" },
    { "btlfield", "타임 솔져/ 배틀 필드 (일본판)" },
    { "btlfieldb", "타임 솔져/ 배틀 필드" },
    { "btlfildb", "타임 솔져/ 배틀 필드" },
    { "btlkroad", "배틀 K - 로드" },
    { "btlkroadk", "배틀 K - 로드 (한국판)" },
    { "btltryst", "배틀 트리스트" },
    { "btoads", "배틀 토드" },
    { "btplay2k", "비트 플레이어 2000" },
    { "bub68705", "버블보블 (해적판,세트1)" },
    { "bub68705a", "버블보블 (해적판,세트2)" },
    { "bubblem", "버블보블 3/ 버블 메모리즈 (버전2.4O)" },
    { "bubblembe", "버블보블 3/ 버블 메모리즈: 블랙에디션 (핵)" },
    { "bubblemj", "버블보블 3/ 버블 메모리즈 (버전2.3J)" },
    { "bubblemu", "버블보블 3/ 버블 메모리즈 (버전2.5A)" },
    { "bubbles", "버블스" },
    { "bubblesp", "버블스" },
    { "bubblesr", "버블스 (레드 라벨)" },
    { "bubbletr", "버블 트러블" },
    { "bubbletrj", "버블 트러블 (일본판,개정판C)" },
    { "bubbobr1", "버블보블 (미국판)" },
    { "bubbroul", "버블엔 룰렛 (일본판,메인버전1.8,비디오버전1.3)" },
    { "bubl2000", "버블 2000" },
    { "bubl2000a", "버블 2000 v1.2" },
    { "bublbob1", "버블보블 (구형)" },
    { "bublbob2", "버블보블 2/ 버블 심포니 (버전2.6O)" },
    { "bublbob2o", "버블보블 2/ 버블 심포니 (버전2.5O)" },
    { "bublbob2p", "버블보블 2/ 버블 심포니 (버전0.0J,시험판)" },
    { "bublbobl", "버블보블 (일본판,버전0.1)" },
    { "bublbobl1", "버블보블 (일본판,버전0.0)" },
    { "bublboblb", "버블보블" },
    { "bublboblp", "버블보블 (시험판 토키오 하드웨어)" },
    { "bublboblr", "버블보블 (미국판,버전5.1)" },
    { "bublboblr1", "버블보블 (미국판,버전1.0)" },
    { "bublboblu", "버블보블 (핵)" },
    { "bublbobr", "버블보블 (미국판 모드셀렉트)" },
    { "bublbust", "퍼즐 보블 /버블 버스터 (북미판,B-시스템)" },
    { "bublcave", "버블보블 - 잃어버린 동굴 V1.2" },
    { "bublcave10", "버블보블 - 잃어버린 동굴 V1.0" },
    { "bublcave11", "버블보블 - 잃어버린 동굴 V1.1" },
    { "bublpong", "버블 퐁퐁" },
    { "bubsympe", "버블보블 2/ 버블 심포니 (버전2.5O)" },
    { "bubsymph", "버블보블 2/ 버블 심포니 (버전2.5J)" },
    { "bubsymphb", "버블보블 2/ 버블 심포니" },
    { "bubsymphba", "버블보블 2/ 서울 심포니" },
    { "bubsymphe", "버블보블 2/ 버블 심포니 (버전2.5O)" },
    { "bubsymphj", "버블보블 2/ 버블 심포니 (버전2.5J)" },
    { "bubsymphu", "버블보블 2/ 버블 심포니 (버전2.5A)" },
    { "bubsympu", "버블보블 2/ 버블 심포니 (버전2.5A)" },
    { "bucaner", "버커니어" },
    { "bucanera", "버커니어 (세트2)" },
    { "buccanra", "버커니어스 (세트2)" },
    { "buccanrs", "버커니어스 (세트1)" },
    { "buccanrsa", "버커니어스 (세트2)" },
    { "buccanrsb", "버커니어스 (세트3,어려움)" },
    { "buckrog", "벅 로저스 - 플래닛 오브 줌" },
    { "buckrogn", "벅 로저스 - 플래닛 오브 줌" },
    { "buckrogn2", "벅 로저스 - 플래닛 오브 줌 (비암호화,세트2)" },
    { "bucky", "버키 오 헤어 (버전EAB)" },
    { "buckyaa", "버키 오 헤어 (버전AA)" },
    { "buckyaab", "버키 오 헤어 (버전AAB)" },
    { "buckyea", "버키 오 헤어 (버전EA)" },
    { "buckyjaa", "버키 오 헤어 (버전JAA)" },
    { "buckyua", "버키 오 헤어 (버전UA)" },
    { "buckyuab", "버키 오 헤어 (버전UAB)" },
    { "bugfever", "벅스 피버" },
    { "bugfeverd", "벅스 피버 (버전1.7E CGA)" },
    { "bugfevero", "벅스 피버 (버전1.6R CGA)" },
    { "bugfeverv", "벅스 피버 (버전1.7R 듀얼)" },
    { "bugfeverv2", "벅스 피버 (버전1.7E 듀얼)" },
    { "buggyb1", "버기 보이" },
    { "buggyboy", "버기 보이/ 스피드 버기" },
    { "buggyboyb", "버기 보이/ 스피드 버기 (콕핏,개정판B)" },
    { "buggyboyjr", "버기 보이 주니어/ 스피드 버기 (업라이트)" },
    { "buggychl", "버기 챌린지" },
    { "buggychlt", "버기 챌린지 (테크프라이)" },
    { "buggycht", "버기 챌린지 (테크프라이)" },
    { "bujutsu", "파이팅 우슈 2nd (버전JAA)" },
    { "bullet", "불릿" },
    { "bulletd", "블릿 (암호해제)" },
    { "bullfgt", "불파이트" },
    { "bullfgtj", "토우규 (일본판)" },
    { "bullfgtr", "불 파이터" },
    { "bullfgtrs", "불 파이터 (세가)" },
    { "bullfgts", "불 파이터 (세가)" },
    { "bullsdrt", "불스 아이 다트" },
    { "bullsdrtg", "불스 아이 다트 (갤럭시안 컨버전)" },
    { "bumba", "붐바 (헤드온의 해적판)" },
    { "buraiken", "어벤저스/ 필살 무뢰권 (일본판,개정판A)" },
    { "buraikenb", "어벤저스/ 필살 무뢰권 (일본판,해적판)" },
    { "burgkids", "버거 키즈 (일본판)" },
    { "burglarx", "버글라 X" },
    { "buriki", "무력 원" },
    { "burnforc", "버닝 포스 (일본판,신버전,개정판C)" },
    { "burnforco", "버닝포스 (일본판,구버전)" },
    { "burnfrco", "버닝포스 (일본판 구버전)" },
    { "burningf", "버닝 파이트" },
    { "burningfh", "버닝 파이트 (NGH-018)(미국판)" },
    { "burningfp", "버닝 파이트 (시험판,구형) [시험판]" },
    { "burningfpa", "버닝 파이트" },
    { "burningfpb", "버닝 파이트" },
    { "burningh", "버닝 파이트 (세트2)" },
    { "buster", "버스터" },
    { "butasan", "부타상 - 피그 & 봄버 (일본판,영어)" },
    { "butasanj", "부타상 (일본판,일본어)" },
    { "butrfly", "버터플라이 비디오 게임" },
    { "butrflybl", "버터플라이 비디오 게임 (버전U350C)" },
    { "buttobi", "부토비 스트라이커" },
    { "buzzard", "버자드" },
    { "bwcasino", "보드워크 카지노" },
    { "bwidow", "블랙 위도우" },
    { "bwidowp", "블랙 위도우 (시험판)" },
    { "bwing", "비-윙스" },
    { "bwings", "비-윙스 (일본판 신버전)" },
    { "bwingsa", "비-윙스 (교체 버전?)" },
    { "bwingso", "비-윙스 (일본판 구버전)" },
    { "bygone", "바이곤" },
    { "bzone", "배틀 존 (개정판2)" },
    { "bzone2", "배틀 존 (세트2)" },
    { "bzonea", "배틀 존 (개정판1)" },
    { "bzonec", "배틀 존" },
};

const size_t lookup_b_count = A_SIZE(lookup_b_table);

const char *lookup_b(const char *name) {
    if (!name) return NULL;
    for (size_t i = 0; i < lookup_b_count; i++) {
        if (strcmp(lookup_b_table[i].name, name) == 0) {
            return lookup_b_table[i].value;
        }
    }
    return NULL;
}

const char *r_lookup_b(const char *value) {
    if (!value) return NULL;
    for (size_t i = 0; i < lookup_b_count; i++) {
        if (strstr(lookup_b_table[i].value, value)) {
            return lookup_b_table[i].name;
        }
    }
    return NULL;
}

void lookup_b_multi(const char *term, void (*emit)(const char *name, const char *value, void *udata), void *udata) {
    if (!term) return;
    for (size_t i = 0; i < lookup_b_count; i++) {
        if (strcasestr(lookup_b_table[i].name, term))
            emit(lookup_b_table[i].name, lookup_b_table[i].value, udata);
    }
}

void r_lookup_b_multi(const char *term, void (*emit)(const char *name, const char *value, void *udata), void *udata) {
    if (!term) return;
    for (size_t i = 0; i < lookup_b_count; i++) {
        if (strcasestr(lookup_b_table[i].value, term))
            emit(lookup_b_table[i].name, lookup_b_table[i].value, udata);
    }
}
