#include <string.h>
#include "../common/common.h"
#include "lookup.h"

typedef struct {
    const char *name;
    const char *value;
} LookupName;

static const LookupName lookup_table[] = {
        {"ibara", "이바라 (마스터 버전)"},
        {"ibarablk", "이바라 흑 블랙 라벨 (마스터 버전)"},
        {"ibarablka", "이바라 흑 블랙 라벨 (마스터 버전)"},
        {"ibarao", "이바라 (마스터 버전)"},
        {"iceclimb", "Vs 아이스 클라이머"},
        {"iceclimba", "Vs 아이스 클라이머 (일본판)"},
        {"iceclmbj", "Vs 아이스 클라이머 (일본판)"},
        {"iceclmrd", "Vs 아이스 클라이머 듀얼"},
        {"iceclmrj", "Vs 아이스 클라이머 듀얼 (일본판)"},
        {"ichir", "퍼즐 앤 액션 - 이치탄트-R (세계판)"},
        {"ichirbl", "퍼즐 앤 액션 - 이치탄트-R (세계판)(해적판)"},
        {"ichirj", "퍼즐 앤 액션 - 이치탄트-R (일본판)"},
        {"ichirjbl", "퍼즐 앤 액션 - 이치탄트-R (일본판)(해적판)"},
        {"ichirk", "퍼즐 앤 액션 - 이치탄트-R (한국판)"},
        {"idhimitu", "아이돌의 비밀"},
        {"idolmj", "아이돌 마작 방송국"},
        {"idsoccer", "인도어 사커"},
        {"iemoto", "이에모토"},
        {"iemotom", "이에모토 (일본판 871118)"},
        {"iganinju", "닌자 카잔/ 이가 인술전 (일본판)"},
        {"iganinjub", "닌자 카잔/ 이가 인술전 (일본판,해적판)"},
        {"igmo", "IGMO"},
        {"igs_ncs", "뉴 챔피언 스킬"},
        {"igs_ncs2", "뉴 챔피언 스킬"},
        {"igstet341", "테트리스 (v341R)"},
        {"igstet342", "테트리스 (v342R)"},
        {"ii32in1", "인터렉트 32합"},
        {"ii8in1", "인터렉트 8합"},
        {"ikari", "이까리 (미국판 잠마)"},
        {"ikari3", "이까리 3 - 구출 (8 방향 조이스틱)"},
        {"ikari3j", "이카리 3 - 구출 (일본판,로터리 조이스틱)"},
        {"ikari3k", "이까리 3 - 구출 (한국판,8방향 조이스틱)"},
        {"ikari3nr", "이까리 3 - 구출 (8방향 조이스틱)"},
        {"ikari3u", "이까리 3 - 구출 (미국판,로터리 조이스틱)"},
        {"ikari3w", "이까리 3 - 구출 (세계판,로터리 조이스틱)"},
        {"ikaria", "이까리 (미국판,세트1)"},
        {"ikaria2", "이까리 (미국판,세트2)"},
        {"ikarijp", "이까리 (일본판 이어하기 안됨)"},
        {"ikarijpb", "이까리 (일본판,조이스틱 핵 복제품)"},
        {"ikarinc", "이까리 (미국판 이어하기 안됨)"},
        {"ikariram", "람보 3"},
        {"ikaruga", "이카루가"},
        {"ikki", "잇키 (일본판)"},
        {"imago", "이마고 (칵테일 세트)"},
        {"imagoa", "이마고 (비칵테일 세트)"},
        {"imekura", "이메쿠라 마작"},
        {"imgfight", "이미지 파이트 (세계판)"},
        {"imgfightj", "이미지 파이트 (일본판)"},
        {"imgfightjb", "이미지 파이트 (일본판,해적판)"},
        {"imolagp", "이몰라 그랑프리"},
        {"imolagpo", "이몰라 그랑프리 (세트2)"},
        {"imsorry", "아이엠 쏘리 (미국판)"},
        {"imsorryj", "곤베에의 아임 쏘리 (일본판)"},
        {"inca", "잉카"},
        {"indianbt", "인디언 배틀"},
        {"indianbtbr", "인디언 배틀 (브라질판)"},
        {"indy500", "인디 500 트윈"},
        {"indy500d", "인디 500 딜럭스 (개정판A)"},
        {"indy500to", "인디 500 트윈 (개정판A)"},
        {"indyheat", "대니 설리반의 인디 히트"},
        {"indytem2", "인디아나 존스와 저주의 사원 (세트2)"},
        {"indytem3", "인디아나 존스와 저주의 사원 (세트3)"},
        {"indytem4", "인디아나 존스와 저주의 사원 (세트4)"},
        {"indytemd", "인디아나 존스와 저주의 사원 (독일판)"},
        {"indytemp", "인디아나 존스와 저주의 사원"},
        {"indytemp2", "인디아나 존스와 저주의 사원 (세트2)"},
        {"indytemp3", "인디아나 존스와 저주의 사원 (세트3)"},
        {"indytemp4", "인디아나 존스와 저주의 사원 (세트4)"},
        {"indytempc", "인디아나 존스와 저주의 사원 (칵테일)"},
        {"indytempd", "인디아나 존스와 저주의 사원 (독일판)"},
        {"inferno", "인페르노"},
        {"insector", "인섹터"},
        {"insectx", "인섹터 X (세계판)"},
        {"insectxbl", "인섹터 X (해적판)"},
        {"insectxj", "인섹터 X (일본판)"},
        {"intact89", "인터렉트 컴플리트 비디오 게임 89합"},
        {"intcup94", "해트트릭 히어로 94_인터네셔널 컵 94 (버전2.2O)"},
        {"intg5410", "인터렉트 컴플리트 비디오 게임 111합 42곡"},
        {"inthehunt", "인 더 헌트"},
        {"inthunt", "인 더 헌트 (세계판)"},
        {"inthuntu", "인 더 헌트 (미국판)"},
        {"intlaser", "인터네셔널 팀 레이져 (시험판)"},
        {"intrepi2", "인트리피드 (세트2)"},
        {"intrepid", "인트리피드 (세트1)"},
        {"intrepid2", "인트리피드 (세트2)"},
        {"intrepidb", "인트리피드 (엘시스 해적판,세트1)"},
        {"intrepidb2", "인트리피드 (루이스 해적판)"},
        {"intrepidb3", "인트리피드 (엘시스 해적판,세트2)"},
        {"intrgirl", "인터걸"},
        {"introdon", "가라오케 퀴즈 인트로 돈 돈!"},
        {"intruder", "인트루더"},
        {"inttoote2", "인터네셔널 투테 2 (v1.24)"},
        {"inufuku", "퀴즈 앤 버라이어티 스쿠스쿠 견복 (일본판)"},
        {"invad2ct", "스페이스 인베이더 2"},
        {"invaddlx", "스페이스 인베이더 디럭스"},
        {"invader4", "스페이스 인베이더 파트 4"},
        {"invaderl", "스페이스 인베이더 (로지텍)"},
        {"invadernc", "스페이스 인베이더 (나스 코프 해적판)"},
        {"invaders", "스페이스 인베이더/ 스페이스 인베이더 M"},
        {"invadersem", "스페이스 인베이더 (일렉트로마,스페인어)"},
        {"invadpt2", "스페이스 인베이더 파트 2 (타이토,비거ROMs)"},
        {"invadpt2a", "스페이스 인베이더 파트 2 (타이토,스몰러ROMs)"},
        {"invadpt2br", "스페이스 인베이더 파트 2 (브라질판)"},
        {"invadrmr", "스페이스 인베이더 (모델 레이싱)"},
        {"invasioa", "인베이젼 (해적판,세트1,일반 그래픽)"},
        {"invasiob", "인베이젼 (해적판,세트2,저작권 없음)"},
        {"invasion", "인베이젼 (시담)"},
        {"invasiona", "UFO 로봇 어택 (인베이젼의 해적판,신형세트)"},
        {"invasiona2", "UFO 로봇 어택 (인베이젼의 해적판,구형세트)"},
        {"invasionb", "인베이젼 (이탈리안 해적판)"},
        {"invasionrz", "인베이젼 (해적판세트1,R Z SRL 볼로냐)"},
        {"invasnab", "인베이젼 - 납치자들"},
        {"invasnab3", "인베이젼 - 납치자들 (버전3.0)"},
        {"invasnab4", "인베이젼 - 납치자들 (버전4.0)"},
        {"invcarht", "인빈코/ 카 헌트 (독일판)"},
        {"invds", "인빈코/ 딥 스캔"},
        {"invho2", "인빈코/ 헤드 온 2"},
        {"invho2a", "인빈코/ 헤드 온 2 (세트2)"},
        {"invinco", "인빈코"},
        {"invmulti", "스페이스 인베이더 멀티게임"},
        {"invmultim1a", "스페이스 인베이더 멀티게임"},
        {"invmultim2a", "스페이스 인베이더 멀티게임"},
        {"invmultim2c", "스페이스 인베이더 멀티게임"},
        {"invmultim3a", "스페이스 인베이더 멀티게임"},
        {"invmultip", "스페이스 인베이더 멀티게임"},
        {"invmultis1a", "스페이스 인베이더 멀티게임"},
        {"invmultis2a", "스페이스 인베이더 멀티게임"},
        {"invmultis3a", "스페이스 인베이더 멀티게임"},
        {"invmultit3d", "스페이스 인베이더 멀티게임"},
        {"invqix", "스페이스 인베이더/ 퀵스 실버 기념판"},
        {"invrvnga", "인베이더의 복수 (더치포드)"},
        {"invrvnge", "인베이더의 복수"},
        {"invrvngea", "인베이더의 복수 (세트2)"},
        {"invrvngeb", "인베이더의 복수 (세트3)"},
        {"invrvngedu", "인베이더의 복수 (더치포드,싱글PCB)"},
        {"invrvngegw", "인베이더의 복수 (게임월드,싱글PCB)"},
        {"inyourfa", "인 유어 페이스 (미국판,시제품)"},
        {"iowapp", "아이오와 프리미엄 플레이어"},
        {"ipminvad", "IPM 인베이더"},
        {"ippatsu", "일발역전"},
        {"ippo2", "하드 펀쳐 시작의 일보 2 - 더 파이팅 "},
        {"iqblock", "IQ-블록 (V100U)"},
        {"iqblocka", "IQ 블록 (V127M)"},
        {"iqblockf", "IQ 블록 (V113FR)"},
        {"irion", "아이리온"},
        {"irobot", "아이 로봇"},
        {"iron", "아이언"},
        {"ironclad", "초철 브리킹거 - 아이언 클래드 (시제품)"},
        {"ironclado", "초철 브리킹거/ 아이언 클래드 (시험판,구형) [시험판]"},
        {"ironfort", "아이언 포트리스"},
        {"ironfortc", "아이언 포트리스 (홍콩판)"},
        {"ironhors", "아이언 홀스 (세계판,버전K)"},
        {"ironhorsh", "아이언 홀스 (세계판,버전H)"},
        {"irrmaze", "일리테이팅 메이즈/ 울트라 찌릿찌릿 봉"},
        {"istreb", "전투기"},
        {"itaten", "장난천사 (일본판)"},
        {"itazuram", "이타즈라 몽키"},
        {"itvg48", "인터렉티브 TV 게임 48합 (PAL)"},
        {"ixion", "익시온"},
};

const char *lookup_i(const char *name) {
    if (!name) return NULL;
    for (size_t i = 0; i < A_SIZE(lookup_table); i++) {
        if (strcmp(lookup_table[i].name, name) == 0) {
            return lookup_table[i].value;
        }
    }
    return NULL;
}

const char *r_lookup_i(const char *value) {
    if (!value) return NULL;
    for (size_t i = 0; i < A_SIZE(lookup_table); i++) {
        if (strstr(lookup_table[i].value, value)) {
            return lookup_table[i].name;
        }
    }
    return NULL;
}
