#include <string.h>
#include "../common/common.h"
#include "lookup.h"

const LookupName lookup_e_table[] = {
    { "eagle", "이글 (세트1)" },
    { "eagle2", "이글 (세트2)" },
    { "eagle3", "이글 (세트3)" },
    { "eaglshot", "이글 샷 골프 (미국판)" },
    { "eaglshotj", "이글 샷 골프" },
    { "eaglshta", "이글 샷 골프 (대체)" },
    { "earthinv", "슈퍼 어스 인베이젼" },
    { "earthjkr", "U.N. 수비대 - 어스 조커 (미국판/일본판,세트1)" },
    { "earthjkra", "U.N. 수비대 - 어스 조커" },
    { "earthjkrb", "U.N. 수비대 - 어스 조커 (미국판/일본판,세트3)" },
    { "earthjkrp", "U.N. 수비대 - 어스 조커 (일본판,시험판?)" },
    { "ebases", "엑스트라 베이시스" },
    { "eca", "이머전시 콜 엠블런스" },
    { "ecaj", "이머전시 콜 엠블런스 (일본판)" },
    { "ecau", "이머전시 콜 엠블런스 (미국판)" },
    { "ecax", "이머전시 콜 엠블런스 (수출판)" },
    { "ecofghta", "에코 파이터즈 (아시아판)" },
    { "ecofghtr", "에코 파이터즈" },
    { "ecofghtra", "에코 파이터즈 (아시아판)" },
    { "ecofghtrd", "에코 파이터즈 (세계판,피닉스에디션)" },
    { "ecofghtrh", "에코 파이터즈 (히스패닉판)" },
    { "ecofghtru", "에코 파이터즈 (미국판)" },
    { "ecofghtru1", "에코 파이터즈 (미국판)" },
    { "ecofghtu", "에코 파이터즈 (미국판)" },
    { "ecofgtu1", "에코 파이터즈 (미국판)" },
    { "edf", "E.D.F. - 지구방위군 (세트1)" },
    { "edfa", "E.D.F. - 지구방위군 (세트2)" },
    { "edfbl", "E.D.F. - 지구방위군" },
    { "edfp", "E.D.F. - 지구방위군 (일본판,시험판)" },
    { "edfu", "E.D.F. - 지구방위군 (북미)" },
    { "edrandy", "클리프행어 - 에드워드 랜디 (세계판 버전3)" },
    { "edrandy1", "클리프행어 - 에드워드 랜디 (세계판 버전1)" },
    { "edrandy2", "클리프행어 - 에드워드 랜디 (세계판 버전2)" },
    { "edrandyj", "클리프행어 - 에드워드 랜디 (일본판 버전3)" },
    { "eeekk", "에이크!" },
    { "eeekkp", "에이크! (팩맨 변환)" },
    { "efdt", "엘 핀 델 티엠포" },
    { "eforest", "마법의 숲 (미국판)" },
    { "eforesta", "마법의 숲 (NSW)" },
    { "eforestb", "마법의 숲 (뉴질랜드판)" },
    { "egghunt", "에그 헌트" },
    { "eggor", "에거" },
    { "eggs", "에그" },
    { "eggsplc", "에그 플레잉 치킨" },
    { "eggvent7", "에그 벤처 (발매 7)" },
    { "eggventr", "에그 벤처" },
    { "eggventr1", "에그 벤처 (발매1)" },
    { "eggventr2", "에그 벤처 (발매2)" },
    { "eggventr7", "에그 벤처 (발매 7)" },
    { "eggventr8", "에그 벤처 (발매 8)" },
    { "eggventra", "에그 벤처 (A.L. 발매)" },
    { "eggventrd", "에그 벤처 디럭스" },
    { "eggvntdx", "에그 벤처 디럭스" },
    { "ehrgeiz", "에어가이츠" },
    { "ehrgeiza", "에어가이츠 (EG2/버전A)" },
    { "ehrgeizj", "에어가이츠 (일본판,EG1/v.A)" },
    { "ehrgeizja", "에어가이츠 (일본판)" },
    { "ehrgeizua", "에어가이츠 (미국판)" },
    { "eibise", "에비세 (일본판)" },
    { "eightfrc", "에이트 포스" },
    { "eightman", "에이트맨" },
    { "einning", "엑스트라 이닝" },
    { "einnings", "엑스트라 이닝" },
    { "ejanhs", "E작 하이스쿨" },
    { "ejihon", "에지혼 탐정 사무소" },
    { "ejollyx5", "유로 졸리 X5" },
    { "ejsakura", "E작 벚꽃여관" },
    { "ejsakura12", "E작 벚꽃여관 (v1.2)" },
    { "elandore", "투용전설 엘란도리" },
    { "elecyoy2", "전자 요요 (세트2)" },
    { "elecyoyo", "전자 요요 (세트1)" },
    { "elecyoyo2", "전자 요요 (세트2)" },
    { "elecyoyoa", "전자 요요" },
    { "elephfam", "엘러펀트 패밀리/ 코끼리 가족" },
    { "elephfmb", "엘러펀트 패밀리/ 코끼리 가족 (이탈리아,구버전)" },
    { "elevatob", "엘리베이터 액션" },
    { "elevator", "엘리베이터 액션 (5 PCB 버전,1.1)" },
    { "elevatora", "엘리베이터 액션" },
    { "elevatorb", "엘리베이터 액션" },
    { "elfin", "엘핀" },
    { "elgrande", "엘그란데 - 5카드 드로우" },
    { "elim2", "엘리미네이터" },
    { "elim2a", "엘리미네이터 (2인용,세트2)" },
    { "elim2c", "엘리미네이터 (2인용,칵테일)" },
    { "elim4", "엘리미네이터 (4인용)" },
    { "elim4p", "엘리미네이터 (4인용,시험판)" },
    { "elvact2u", "엘리베이터 액션 2 (버전2.2A)" },
    { "elvactr", "엘리베이터 액션 리턴즈 (버전2.2O)" },
    { "elvactrj", "엘리베이터 액션 리턴즈 (버전2.2J)" },
    { "elvis", "엘비스" },
    { "embargo", "엠바고" },
    { "emeralda", "에메랄디아 (세계판)" },
    { "emeraldah", "에메랄디아 (뱅크뱅크 새 회전 핵)" },
    { "emeraldaj", "에메랄디아 (일본판 버전B)" },
    { "emeraldaja", "에메랄디아 (일본판)" },
    { "emerldaa", "에메랄디아 (일본판)" },
    { "empcity", "엠파이어 시티 - 1931" },
    { "empcityfr", "엠파이어 시티 - 1931 (프랑스판)" },
    { "empcityi", "엠파이어 시티 - 1931 (이탈리아판)" },
    { "empcityj", "엠파이어 시티 - 1931 (일본판)" },
    { "empcityu", "엠파이어 시티 - 1931 (미국판)" },
    { "enchfrst", "마법의 숲 (로컬)" },
    { "endless", "건담 윙 - 엔드리스 듀얼" },
    { "endlessa", "건담 윙 - 엔드리스 듀얼" },
    { "endrichs", "엔드리스 리치스" },
    { "endrichsa", "엔드리스 리치스 (버전1.20)" },
    { "endurob2", "엔듀로 레이서 (해적판 세트2)" },
    { "endurobl", "엔듀로 레이서 (해적판 세트1)" },
    { "enduror", "엔듀로 레이서 (개정판A)" },
    { "enduror1", "엔듀로 레이서 (YM2203)" },
    { "enduror1d", "엔듀로 레이서" },
    { "endurora", "엔듀로 레이서" },
    { "endurorb", "엔듀로 레이서 (YM2151)" },
    { "endurord", "엔듀로 레이서" },
    { "enforce", "엔포스 (세계판)" },
    { "enforcej", "엔포스 (일본판)" },
    { "enforceja", "엔포스 (일본판,아날로그)" },
    { "enigma2", "이니그마 2" },
    { "enigma2a", "이니그마 2 (스페이스 인베이더 하드웨어)" },
    { "enigma2b", "판토마스 2 (스페이스 인베이더 하드웨어)" },
    { "enmadaio", "염라대왕 (일본판)" },
    { "eprom", "로봇 괴수들의 별에서의 탈출 (세트1)" },
    { "eprom2", "로봇 괴수들의 별에서의 탈출 (세트2)" },
    { "equites", "에쿼티즈" },
    { "equitess", "에쿼티즈 (세가)" },
    { "ertictac", "에로틱택/택틱" },
    { "ertictaca", "에로틱택/택틱 (버전01)" },
    { "ertictacb", "에로틱택/택틱 (세트2)" },
    { "esb", "스타 워즈 - 제국의 역습" },
    { "esckids", "이스케이프 키즈 (아시아판,4인용)" },
    { "esckidsj", "이스케이프 키즈 (일본판,2인용)" },
    { "escmars", "이스케이프 프롬 마르스 (루나 레스큐의 해적판)" },
    { "escounts", "에브리 세컨드 카운츠" },
    { "esh", "에쉬의 어론밀라" },
    { "esha", "에쉬의 어론밀라" },
    { "eshb", "에쉬의 어론밀라 (세트3)" },
    { "espgal", "에스프가루다 (일본판,마스터 버전)" },
    { "espgal2", "에스프가루다 II (마스터 버전,신형CV1000-B PCB)" },
    { "espgal2a", "에스프가루다 II (마스터 버전,원형CV1000-B PCB)" },
    { "espgal2b", "에스프가루다 II (마스터 버전,원형CV1000-B PCB)" },
    { "espgalbl", "에스프가루다 (마스터 버전,카트리지 컨버전해적판)" },
    { "espial", "에스파이얼 (유럽판)" },
    { "espiale", "에스파이얼 (유럽판)" },
    { "espialj", "에스파이얼 (일본판)" },
    { "espialn", "에스파이얼 (노바 아퍼레이트 라이센스)" },
    { "espialu", "에스파이얼 (미국판?)" },
    { "esprade", "에스프레이드 - A.D. 2018 도쿄 (세계판)" },
    { "espradej", "에스프레이드 (일본판)" },
    { "espradejo", "에스프레이드 (일본판)" },
    { "espradeo", "에스프레이드 (일본판)" },
    { "eswat", "E스와트 - 사이버 폴리스 (세트4,세계판)" },
    { "eswatbl", "E스와트 - 사이버 폴리스 (해적판,세트1)" },
    { "eswatbl2", "E스와트 - 사이버 폴리스 (해적판,세트2)" },
    { "eswatd", "E스와트 - 사이버 폴리스 (세트4,세계판,암호해제)" },
    { "eswatj", "E스와트 - 사이버 폴리스 (세트2,일본판)" },
    { "eswatj1", "E스와트 - 사이버 폴리스 (세트1,일본판)" },
    { "eswatj1d", "E스와트 - 사이버 폴리스 (세트1,일본판,암호해제)" },
    { "eswatjd", "E스와트 - 사이버 폴리스 (세트2,일본판,암호해제)" },
    { "eswatu", "E스와트 - 사이버 폴리스 (세트3,US)" },
    { "eswatud", "E스와트 - 사이버 폴리스 (세트3,US,암호해제)" },
    { "eto", "고금동서 십이지 이야기 (일본판)" },
    { "etoa", "고금동서 십이지 이야기 (일본판,시험판?)" },
    { "euro2k2", "유로파 2002" },
    { "euro2k2a", "유로파 2002" },
    { "euro2k2s", "유로파 2002 스페이스 (버전3.0)" },
    { "euroch92", "유로 챔프 92 (세계판)" },
    { "euroch92j", "유로 챔프 92 (일본판)" },
    { "eurogael", "유로 리그 (자레코 해적판)" },
    { "europass", "유로 패스" },
    { "evilngt", "이블 나이트" },
    { "evilston", "이블 스톤" },
    { "evosocc", "에볼루션 축구" },
    { "excelsr", "엑셀시어 (세트1)" },
    { "excelsra", "엑셀시어 (세트2)" },
    { "excitbkj", "익사이트 바이크 (일본판)" },
    { "excitebk", "익사이트 바이크" },
    { "excitebkj", "익사이트 바이크" },
    { "excitebko", "익사이트 바이크" },
    { "excthour", "매트매니아/ 익사이팅 아워" },
    { "exctleag", "익사이트 리그" },
    { "exctleagd", "익사이트 리그 (암호해제)" },
    { "exctscc2", "익사이팅 사커 2" },
    { "exctscca", "익사이팅 사커 (대체 음악)" },
    { "exctsccb", "익사이팅 사커" },
    { "exctsccr", "익사이팅 사커" },
    { "exctsccra", "익사이팅 사커 (대체 음악)" },
    { "exctsccrb", "익사이팅 사커" },
    { "exctsccrj", "익사이팅 사커 (일본판)" },
    { "exctsccrj2", "익사이팅 사커 (일본판 세트2)" },
    { "exctsccrjo", "익사이팅 사커 (일본판,구형)" },
    { "exctsccru", "익사이팅 사커 (미국판)" },
    { "exedexes", "엑시드 엑시즈" },
    { "exerion", "엑시리온" },
    { "exerionb", "엑시리온 (해적판,세트1)" },
    { "exerionb2", "엑시리온 (해적판,세트2)" },
    { "exerionba", "엑시리온 (아싸,해적판)" },
    { "exeriont", "엑시리온 (타이토)" },
    { "exerizer", "스카이 폭스/ 엑서라이저 (일본판)" },
    { "exerizerb", "스카이 폭스/ 엑서라이저" },
    { "exerizrb", "스카이 폭스/ 엑서라이저 (일본판)(해적판)" },
    { "exodus", "엑소더스" },
    { "explbrkr", "익스플로시브 브레이커" },
    { "explbrkrk", "익스플로시브 브레이커 (한국판)" },
    { "explorer", "익스플로러" },
    { "exprrada", "익스프레스 레이더 (미국판 세트2)" },
    { "exprraid", "익스프레스 레이더 (세계판,개정판4)" },
    { "exprraida", "익스프레스 레이더 (미국판 세트2)" },
    { "exprraidi", "익스프레스 레이더 (이탈리아판)" },
    { "exprraidu", "익스프레스 레이더 (미국판,개정판5)" },
    { "exsprt48", "익사이트 스포츠 와이어리스 인터렉티브 TV 게임 48합 (NTSC)" },
    { "extdwnhl", "익스트림 다운힐 (v1.5)" },
    { "exterm", "익스터미네이터" },
    { "extrmatn", "익스터미네이션 (세계판)" },
    { "extrmatnj", "익스터미네이션 (일본판)" },
    { "extrmatnu", "익스터미네이션 (미국판,세트1)" },
    { "extrmatnur", "익스터미네이션 (미국판,롬스타)" },
    { "exvania", "엑스베니아 (세계판)" },
    { "exvaniaj", "엑스베니아 (일본판)" },
    { "exzisus", "엑스지서스 (일본판,헌정됨)" },
    { "exzisusa", "엑스지서스 (일본판,컨버젼)" },
    { "exzisust", "엑스지서스 (TAD 라이센스)" },
    { "eyes", "아이즈 (디지트렉스 테크스타)" },
    { "eyes2", "아이즈 (테크스타)" },
    { "eyesb", "아이즈 (해적판 세트1)" },
    { "eyesdown", "아이즈 다운" },
    { "eyesdownd", "아이즈 다운 (v1.3,데이터팩)" },
    { "eyeszac", "아이즈 (자카리아)" },
    { "eyeszacb", "아이즈 (해적판 세트2,암호해제)" },
};

const size_t lookup_e_count = A_SIZE(lookup_e_table);

const char *lookup_e(const char *name) {
    if (!name) return NULL;
    for (size_t i = 0; i < lookup_e_count; i++) {
        if (strcmp(lookup_e_table[i].name, name) == 0) {
            return lookup_e_table[i].value;
        }
    }
    return NULL;
}

const char *r_lookup_e(const char *value) {
    if (!value) return NULL;
    for (size_t i = 0; i < lookup_e_count; i++) {
        if (strstr(lookup_e_table[i].value, value)) {
            return lookup_e_table[i].name;
        }
    }
    return NULL;
}

void lookup_e_multi(const char *term, void (*emit)(const char *name, const char *value, void *udata), void *udata) {
    if (!term) return;
    for (size_t i = 0; i < lookup_e_count; i++) {
        if (strcasestr(lookup_e_table[i].name, term))
            emit(lookup_e_table[i].name, lookup_e_table[i].value, udata);
    }
}

void r_lookup_e_multi(const char *term, void (*emit)(const char *name, const char *value, void *udata), void *udata) {
    if (!term) return;
    for (size_t i = 0; i < lookup_e_count; i++) {
        if (strcasestr(lookup_e_table[i].value, term))
            emit(lookup_e_table[i].name, lookup_e_table[i].value, udata);
    }
}
