#include <string.h>
#include "../common/common.h"
#include "lookup.h"

const LookupName lookup_h_table[] = {
    { "hachamf", "하차 메차 파이터" },
    { "hachamfa", "하차 메차 파이터 (세트2)" },
    { "hachamfb", "하차 메차 파이터 (비보호,썬더드래곤 컨버젼)" },
    { "hachamfp", "하차 메차 파이터 (로케이션 테스트 시험판)" },
    { "hacher", "하처 (윈 윈 빙고의 핵)" },
    { "hachoo", "하쿠!" },
    { "hachooa", "하쿠! (세계판,세트2)" },
    { "hachooj", "하쿠! (일본판)" },
    { "haekaka", "해해 카카카" },
    { "hal21", "할21" },
    { "hal21j", "할21 (일본판)" },
    { "halfway", "하프웨이 투 헬 - 프로기어 레드 라벨 (2016-1-17 빨간색 라벨 버전)" },
    { "halley87", "헬리 혜성 97" },
    { "halleycj", "핼리 혜성 (일본판,구형)" },
    { "halleys", "핼리 혜성" },
    { "halleysc", "핼리 혜성 (일본판,신형)" },
    { "halleysc87", "핼리 혜성 '87" },
    { "halleyscj", "핼리 혜성 (일본판,개정판1)" },
    { "halleyscja", "핼리 혜성 (일본판)" },
    { "halleyscjp", "핼리 혜성 (일본판,시험판)" },
    { "hamaway", "해머 어웨이 (시제품)" },
    { "hamboy", "해머 보이" },
    { "hamhouse", "햄버거 하우스" },
    { "hamhouse9", "햄버거 하우스 9" },
    { "hammer", "해머 어웨이" },
    { "hana6pt2", "화투놀이 6 파트II" },
    { "hanaawas", "화투놀이" },
    { "hanagumi", "화조대전 컬럼스 - 사쿠라 대전" },
    { "hanakanz", "꽃비녀" },
    { "hanamai", "꽃의 춤 (일본판)" },
    { "hanamomb", "마작 꽃의 모모코구미 (일본판)" },
    { "hanamomo", "마작 꽃의 모모코구미" },
    { "hanaoji", "꽃과 아저씨" },
    { "hanaojia", "꽃과 아저씨" },
    { "hanaroku", "하나로쿠" },
    { "hanayara", "화투를 안할거면!" },
    { "hangly", "행글리맨 (세트1)" },
    { "hangly2", "행글리맨 (세트2)" },
    { "hangly3", "행글리맨 (세트3)" },
    { "hangman", "행맨" },
    { "hangon", "행온 (개정판A)" },
    { "hangon1", "행온" },
    { "hangon2", "행온 (라이드 온)" },
    { "hangonjr", "행온 주니어 (개정판B)" },
    { "hangonvf", "VF (행온 해적판)" },
    { "hangplt", "행 파일럿" },
    { "hangpltu", "행 파일럿" },
    { "hangzo", "행조 (일본판,시제품)" },
    { "happy6", "해피 식스 인 원 (V102 - V101MK,중국판)" },
    { "happy6100cn", "해피 식스 인 원" },
    { "happy6100hk", "해피 식스 인 원" },
    { "happy6101", "해피 식스 인 원 (V101 - V100MK,중국판)" },
    { "happyskl", "해피 스킬" },
    { "hapytour", "해피 투어" },
    { "harddrb5", "하드 드라이빙 (콕핏,영국판,개정판5)" },
    { "harddrb6", "하드 드라이빙 (콕핏,영국판,개정판6)" },
    { "harddrc1", "하드 드라이빙 (소형,개정판1)" },
    { "harddrcb", "하드 드라이빙 (소형,영국판,개정판2)" },
    { "harddrcg", "하드 드라이빙 (소형,독일판,개정판2)" },
    { "harddrg4", "하드 드라이빙 (콕핏,독일판,개정판4)" },
    { "harddriv", "하드 드라이빙" },
    { "harddriv1", "하드 드라이빙 (콕핏,개정판1)" },
    { "harddriv2", "하드 드라이빙 (콕핏,개정판2)" },
    { "harddriv3", "하드 드라이빙 (콕핏,개정판3)" },
    { "harddrivb", "하드 드라이빙 (콕핏,영국판,개정판7)" },
    { "harddrivb5", "하드 드라이빙 (콕핏,영국판,개정판5)" },
    { "harddrivb6", "하드 드라이빙 (콕핏,영국판,개정판6)" },
    { "harddrivc", "하드 드라이빙 (소형,개정판2)" },
    { "harddrivc1", "하드 드라이빙 (소형,개정판1)" },
    { "harddrivcb", "하드 드라이빙 (소형,영국판,개정판2)" },
    { "harddrivcbl", "하드 드라이빙 (소형,개정판2 해적판)" },
    { "harddrivcg", "하드 드라이빙 (소형,독일판,개정판2)" },
    { "harddrivg", "하드 드라이빙 (콕핏,독일판,개정판7)" },
    { "harddrivg4", "하드 드라이빙 (콕핏,독일판,개정판4)" },
    { "harddrivj", "하드 드라이빙 (콕핏,일본판,개정판7)" },
    { "harddrivj6", "하드 드라이빙 (콕핏,일본판,개정판6)" },
    { "harddrj6", "하드 드라이빙 (콕핏,일본판,개정판6)" },
    { "harddrv1", "하드 드라이빙 (콕핏,개정판1)" },
    { "harddrv2", "하드 드라이빙 (콕핏,개정판2)" },
    { "harddrv3", "하드 드라이빙 (콕핏,개정판3)" },
    { "harddrvb", "하드 드라이빙 (콕핏,영국판,개정판7)" },
    { "harddrvc", "하드 드라이빙 (소형,개정판2)" },
    { "harddrvg", "하드 드라이빙 (콕핏,독일판,개정판7)" },
    { "harddrvj", "하드 드라이빙 (콕핏,일본판,개정판7)" },
    { "harddunj", "하드 덩크 (일본판)" },
    { "harddunk", "하드 덩크 (세계판)" },
    { "harddunkj", "하드 덩크 (일본판)" },
    { "hardhat", "하드 햇" },
    { "hardhea2", "하드 헤드 2/ 짱구박사 2" },
    { "hardhea2a", "하드 헤드 2/ 짱구박사 2 (v2.0,뮤직 프로그램 v2.0)" },
    { "hardhead", "하드 헤드/ 짱구박사" },
    { "hardheadb", "하드 헤드/ 짱구박사 (해적판,세트1)" },
    { "hardheadb3", "하드 헤드/ 짱구박사 (해적판,세트3)" },
    { "hardhedb", "하드 헤드/ 짱구박사 (해적판)" },
    { "hardyard", "하드 야디지 (v1.20)" },
    { "hardyard10", "하드 야디지 (v1.00)" },
    { "hardyard11", "하드 야디지 (v1.10)" },
    { "hardyd10", "하드 야디지 (v1.00)" },
    { "harem", "하렘" },
    { "haremchl", "하렘 챌린지" },
    { "harley", "할리데이비슨과 L.A. 라이더스" },
    { "hasamu", "패사몽 (일본판)" },
    { "hatena", "어드벤처 퀴즈 2 - 하테나?의 대모험 (일본판)" },
    { "hatris", "햇트리스 (미국판)" },
    { "hatrisj", "햇트리스 (일본판)" },
    { "hatrisp", "햇트리스 (쇼버전)" },
    { "hattrick", "해트트릭" },
    { "hayaosi1", "빨리누르기 퀴즈 왕자 결정전" },
    { "hayaosi2", "빨리 누르기 퀴즈 그랜드 챔피언십 대결" },
    { "hayaosi3", "빨리 누르기 퀴즈 열투생방송 (버전1.5)" },
    { "hayaosi3a", "빨리 누르기 퀴즈 열투생방송 (버전1.2)" },
    { "hbarrel", "헤비 배럴 (세계판)" },
    { "hbarrelu", "헤비 배럴 (미국판,개정판3)" },
    { "hbarrelua", "헤비 배럴 (미국판,개정판1)" },
    { "hbarrelw", "헤비 배럴 (세계판)" },
    { "hcastle", "악마성 드라큘라/ 헌티드 캐슬 (버전M)" },
    { "hcastlea", "악마성 드라큘라/ 헌티드 캐슬 (세트2)" },
    { "hcastlee", "악마성 드라큘라/ 헌티드 캐슬 (버전E)" },
    { "hcastlej", "악마성 드라큘라 (일본판 버전P)" },
    { "hcastlek", "악마성 드라큘라/ 헌티드 캐슬 (버전K)" },
    { "hcastleo", "악마성 드라큘라/ 헌티드 캐슬 (버전K)" },
    { "hcastljo", "악마성 드라큘라 (일본판 버전N)" },
    { "hcrash", "하이퍼 크래쉬 (버전D)" },
    { "hcrashc", "하이퍼 크래쉬 (버전C)" },
    { "hdrivaip", "하드 드라이빙 에어본 (시험판,초기 개정판)" },
    { "hdrivair", "하드 드라이빙 에어본" },
    { "hdrivairp", "하드 드라이빙 에어본 (시험판,초기 개정판)" },
    { "headon", "헤드 온 (2인용)" },
    { "headon1", "헤드 온 (1인용) (사운드 없음)" },
    { "headon2", "헤드 온 2" },
    { "headon2s", "헤드 온 2" },
    { "headonb", "헤드 온" },
    { "headonch", "모니타와 리모코의 헤드 온 채널 (시제품,핵)" },
    { "headoni", "헤드 온" },
    { "headonmz", "헤드 온 (해적판,메이즈 대체)" },
    { "headonn", "헤드 온 N" },
    { "headons", "헤드 온" },
    { "headonsa", "헤드 온" },
    { "heartatk", "하트 어택" },
    { "heatbrl", "히티드 베럴 (세계판 버전3)" },
    { "heatbrl2", "히티드 베럴 (세계판 버전2)" },
    { "heatbrl3", "히티드 베럴 (세계판 버전3)" },
    { "heatbrle", "히티드 베럴" },
    { "heatbrlo", "히티드 베럴 (세계판 구버전)" },
    { "heatbrlu", "히티드 베럴 (미국판)" },
    { "heatof11", "히트 오브 일레븐 98" },
    { "heberpop", "헤베레케의 팝푼 (일본판)" },
    { "hedpanic", "헤드 패닉 (버전0117)" },
    { "hedpanic830", "헤드 패닉 (버전8.30)" },
    { "hedpanica", "헤드 패닉 (버전0702)" },
    { "hedpanicf", "헤드 패닉 (버전0315)" },
    { "hedpanico", "헤드 패닉 (버전0615)" },
    { "heiankyo", "헤이안쿄 에일리언" },
    { "helifira", "헬리파이어 (세트2)" },
    { "helifire", "헬리파이어" },
    { "helifirea", "헬리파이어 (세트2)" },
    { "hellfir1", "헬파이어 (1인 버전)" },
    { "hellfir2", "헬파이어 (2인 버전,초판)" },
    { "hellfire", "헬파이어 (2P 세트)" },
    { "hellfire1", "헬파이어 (1인 세트)" },
    { "hellfire1a", "헬파이어 (1인 세트,구형)" },
    { "hellfire2", "헬파이어 (2인 버전,초판)" },
    { "hellfire2a", "헬파이어 (2인 세트,구형)" },
    { "hellfire3", "헬파이어 (1인,대체)" },
    { "hellngt", "헬 나이트 (버전EAA)" },
    { "herbiedk", "꼽추 올림픽/ 올림픽의 허비 (DK 컨버젼)" },
    { "hero", "히어로" },
    { "herodk", "암흑성의 영웅 (DK 컨버젼)" },
    { "herodku", "암흑성의 영웅 (DK 컨버젼 비암호화)" },
    { "heuksun", "흑선백사 (한국판)" },
    { "hexa", "헥사" },
    { "hexaa", "헥사" },
    { "hexion", "헥시온 (일본판 버전JAB)" },
    { "hexionb", "헥시온 (해적판,아시아판 버전AAA)" },
    { "hexpool", "랙+롤/ 헥스 풀 (신카이)" },
    { "hexpoola", "랙+롤/ 헥스 풀 (센코)" },
    { "hfh", "황비홍" },
    { "hginga", "화투 화은하" },
    { "hgkairak", "대전 핫 기믹 쾌락천 (일본판)" },
    { "hgokbang", "화투 화오광 번외편 (일본판)" },
    { "hgokou", "화투 화오광" },
    { "hharry", "해머링 해리 (세계판,M81 PCB 버전)" },
    { "hharryb", "해머링 해리" },
    { "hharryu", "해머링 해리" },
    { "hidctch2", "틀린그림 찾기 2 (PCB 버전3.03,한국어/영어,AT89C52 보호됨)" },
    { "hidctch2a", "틀린그림 찾기 2 (PCB 버전1.00,한국어/영어/일어/중국어)" },
    { "hidctch3", "틀린그림 찾기 3 (버전1.00/ PCB 버전3.05)" },
    { "hidnc2k", "틀린그림 찾기 2000 (AT89C52 보호됨)" },
    { "hidnctch", "틀린그림 찾기 98(세계판)(한국판)(PCB 버전3.03)" },
    { "hidnctcha", "틀린그림 찾기 98(세계판)(한국판)(PCB 버전3.02)" },
    { "higemaru", "히게마루 해적선" },
    { "highspla", "스페이스 피버 하이 스플리터 (세트2)" },
    { "highsplt", "스페이스 피버 하이 스플리터" },
    { "highsplta", "스페이스 피버 하이 스플리터 (세트2)" },
    { "highspltb", "스페이스 피버 하이 스플리터 (대체 사운드)" },
    { "hiimpac3", "하이 임팩트 풋볼 (개정판LA3)" },
    { "hiimpacp", "하이 임팩트 풋볼 (시험판,개정판8.6)" },
    { "hiimpact", "하이 임팩트 풋볼 (개정판LA5)" },
    { "hiimpact1", "하이 임팩트 풋볼 (개정판LA1)" },
    { "hiimpact2", "하이 임팩트 풋볼 (개정판LA2)" },
    { "hiimpact3", "하이 임팩트 풋볼 (개정판LA3)" },
    { "hiimpact4", "하이 임팩트 풋볼 (개정판LA4)" },
    { "hiimpactp", "하이 임팩트 풋볼 (시험판,개정판8.6)" },
    { "himesiki", "희사계무 (일본판)" },
    { "hipai", "하이 파이 파라다이스" },
    { "hipai2", "하이 파이 파라다이스 2" },
    { "hipoly", "히폴리" },
    { "hippodrm", "파이팅 판타지/ 히포드롬 (미국판)" },
    { "hiryuken", "상하이 키드/ 북파 소림 비룡의 권" },
    { "hishouza", "플라잉 샤크/ 비상 상어 (일본판)" },
    { "hishouzab", "플라잉 샤크/ 비상 상어 (일본판,해적판)" },
    { "histryma", "히스토리 오브 마샬 아츠" },
    { "histryma2", "히스토리 오브 마샬 아츠 (세트2)" },
    { "hitice", "힛 더 아이스 (미국판)" },
    { "hiticej", "힛 더 아이스 (일본판)" },
    { "hiticerb", "힛 더 아이스 (미국판,라이저 보드)" },
    { "hitme", "히트 미" },
    { "hitme1", "히트 미 (세트2)" },
    { "hitnmis2", "히트 앤 미스 (버전2.0)" },
    { "hitnmiss", "히트 앤 미스" },
    { "hitnmiss2", "히트 앤 미스 (버전2.0)" },
    { "hitpoker", "히트 포커" },
    { "hjingi", "화인의" },
    { "hjingia", "화인의 (일본판,세트2)" },
    { "hkagerou", "하나 카게로" },
    { "hldspin1", "홀드 앤 스핀" },
    { "hldspin1dt", "홀드 앤 스핀 (버전2.7T,세트2)" },
    { "hldspin1o", "홀드 앤 스핀 (버전2.5T)" },
    { "hldspin1vt", "홀드 앤 스핀 (버전2.7T 듀얼)" },
    { "hldspin2", "홀드 앤 스핀 2" },
    { "hldspin2d1", "홀드 앤 스핀 2 (버전2.8R,세트2)" },
    { "hldspin2o", "홀드 앤 스핀 2 (버전2.6)" },
    { "hldspin2v1", "홀드 앤 스핀 2 (버전2.8R 듀얼)" },
    { "hmcompm2", "힙합매니아 컴플리트 믹스 2 (버전UA-A)" },
    { "hmcompmx", "힙합매니아 컴플리트 믹스 (버전UA-B)" },
    { "hmgeo", "헤비 메탈 지오매트릭스" },
    { "hnageman", "AV화투 꽃의 행운" },
    { "hnayayoi", "하나 야요이" },
    { "hncholms", "꼽추 올림픽 (스크램블 하드웨어)" },
    { "hndlchmp", "핸들 챔프 (버전SAA)" },
    { "hndlchmpj", "핸들 챔프 (버전JAB)" },
    { "hnfubuki", "하나 후부키 (일본판)" },
    { "hngmnjpm", "행맨" },
    { "hngmnjpmd", "행맨 (JPM,프로토콜)" },
    { "hnkochou", "꽃나비" },
    { "hnoridur", "꽃학종이 (일본판)" },
    { "hnxmasev", "AV화투 꽃의 크리스마스 이브" },
    { "hoccer", "하커 (세트1)" },
    { "hoccer2", "하커 (세트2)" },
    { "hocrash", "크래쉬 (헤드온 해적판)" },
    { "hogalley", "호건즈 앨리" },
    { "holeland", "홀랜드 (일본판)" },
    { "holeland2", "홀랜드 (스페인판)" },
    { "holo", "홀로세움 (미국판,개정판A)" },
    { "homerun", "불타라 프로야구 홈런" },
    { "homo", "호모" },
    { "honeydol", "허니 돌" },
    { "hook", "후크 (세계판)" },
    { "hook1v4", "후크 (1v4,핵)" },
    { "hook6h", "후크 (6번째 엠페러,핵)" },
    { "hookbo", "후크 (가이 가이,핵)" },
    { "hookdj", "후크 (아이템,핵)" },
    { "hookdszz", "후크 (서밋 워,핵)" },
    { "hookdw", "후크 (워리어스,핵)" },
    { "hookgs", "후크 (익스펜더블,핵)" },
    { "hookgs2", "후크 (익스펜더블II,핵)" },
    { "hookhd", "후크 (파이어릿 워즈,핵)" },
    { "hookhd2", "후크 (파이어릿 워즈II,핵)" },
    { "hookj", "후크 (일본판)" },
    { "hookjy", "후크 (엘리트,핵)" },
    { "hookjyds", "후크 (엘리트 컴피티션,핵)" },
    { "hookk", "후크 (한글)" },
    { "hooknx", "후크 (후크의 리버설,핵)" },
    { "hooknx2", "후크 (후크의 리버설II,핵)" },
    { "hookpj", "후크 (POK KAI,핵)" },
    { "hookpls", "후크 (플러스,핵)" },
    { "hooksw", "후크 (SW,핵)" },
    { "hooksw2", "후크 (SW2, 핵)" },
    { "hooku", "후크 (미국판)" },
    { "hookx2", "후크 (X2,핵)" },
    { "hookxr", "후크 (Xin Er,핵)" },
    { "hookxx", "후크 (XX,핵)" },
    { "hoops95", "후프스/ 덩크 드림 95 (유럽판/아시아판 1.7)" },
    { "hoops96", "후프스 96 (유럽판/아시아판 2.0)" },
    { "hopmappy", "호핑 마피" },
    { "hopprobo", "하퍼 로보" },
    { "horekid", "키드의 호레호레 대작전" },
    { "horekidb", "키드의 호레호레 대작전 (해적판,세트1)" },
    { "horekidb2", "키드의 호레호레 대작전 (해적판,세트2)" },
    { "horekidb3", "키드의 호레호레 대작전 네오지오 컨버전 (HB)" },
    { "horizon", "호라이즌" },
    { "horshoes", "아메리칸 호스슈즈 (미국판)" },
    { "hotblock", "핫 블럭스 - 테트릭스 2" },
    { "hotblocka", "핫 블럭스 - 테트릭스 2 (세트2)" },
    { "hotblockb", "핫 블럭스 - 테트릭스 2 (세트3)" },
    { "hotbody", "핫 바디 I" },
    { "hotbubl", "핫 버블 (한국판,성인)" },
    { "hotbubla", "핫 버블 (한국판)" },
    { "hotchase", "핫 체이스 (세트1)" },
    { "hotchasea", "핫 체이스 (세트2)" },
    { "hotchili", "핫 칠리" },
    { "hotd", "하우스 오브 더 데드" },
    { "hotd2", "하우스 오브 더 데드 2 (미국판)" },
    { "hotd2e", "하우스 오브 더 데드 2 (수출)" },
    { "hotd2o", "하우스 오브 더 데드 2" },
    { "hotd2p", "하우스 오브 더 데드 2 (시험판)" },
    { "hotd3", "하우스 오브 데드 3" },
    { "hotdebut", "퀴즈 데 아이돌! 핫 데뷰 (일본판)" },
    { "hotdogst", "핫도그 스톰 (한국판)" },
    { "hotgm4ev", "대전 핫 기믹 4 에버 (일본판)" },
    { "hotgmck", "대전 핫 기믹 (일본판)" },
    { "hotgmck3", "대전 핫 기믹 3 디지털 서핑 (일본판)" },
    { "hotgmcki", "대전 핫 기믹 인테그럴 (일본판)" },
    { "hotmemry", "핫 메모리" },
    { "hotmemry11", "핫 메모리 (V1.1,독일판,11/30/94)" },
    { "hotmind", "핫 마인드 (하드 타임즈 하드웨어)" },
    { "hotminda", "핫 마인드 (상품 조작가능)" },
    { "hotmindff", "핫 마인드 (핏 오브 파이팅 하드웨어)" },
    { "hotnight", "핫 나이트" },
    { "hotpinbl", "핫 핀볼" },
    { "hotrod", "핫 로드 (세계판,3인용,터보 세트1,플로피 기반)" },
    { "hotroda", "핫 로드 (세계판,3인용,터보 세트2,플로피)" },
    { "hotrodj", "핫 로드 (일본판,4인용,플로피 기반,개정판C)" },
    { "hotrodja", "핫 로드" },
    { "hotshock", "핫 쇼커" },
    { "hotshockb", "핫 쇼커" },
    { "hotslot", "핫 슬롯" },
    { "hotsmash", "핫 스매쉬" },
    { "hourouki", "마작 방랑기 파트 1 - 청춘편" },
    { "housecard", "하우스 오브 카드" },
    { "housemn2", "하우스 마네킹 록본기 라이브편" },
    { "housemnq", "하우스 마네킹" },
    { "hparadis", "슈퍼 하나 파라다이스" },
    { "hpolym84", "하이퍼 스포츠/ 하이퍼 올림픽 84" },
    { "hpuncher", "파이널 라운드/ 하드 펀처 (일본판)" },
    { "hrclass", "홈런 클래식" },
    { "hrdtimes", "하트 타임즈" },
    { "hrdtimesa", "하트 타임즈 (세트2)" },
    { "hsf2", "하이퍼 스트리트 파이터2 - 기념판 (미국판)" },
    { "hsf230b", "하이퍼 스트리트 파이터2 - 기념판 (30% 블러드,핵)" },
    { "hsf2a", "하이퍼 스트리트 파이터2 - 기념판 (아시아판)" },
    { "hsf2app", "하이퍼 스트리트 파이터2 플러스 플러스 (아시아버전)" },
    { "hsf2d", "하이퍼 스트리트 파이터2 - 기념판 (아시아 피닉스에디션,해적판)" },
    { "hsf2da", "하이퍼 스트리트 파이터2 - 기념판 (아시아 대체 피닉스에디션,해적판)" },
    { "hsf2df", "하이퍼 스트리트 파이터2 - 기념판 (난이도 픽스,핵)" },
    { "hsf2ev2", "하이퍼 스트리트 파이터2 - 기념판 (이지무브v2,핵)" },
    { "hsf2j", "하이퍼 스트리트 파이터2 - 기념판 (일본판)" },
    { "hsf2j1", "하이퍼 스트리트 파이터2 - 기념판 (일본판)" },
    { "hsf2j2", "하이퍼 스트리트 파이터2 - 기념판 (일본판)" },
    { "hsf2jh", "하이퍼 스트리트 파이터2 - 기념판 (일본판,히든핵)" },
    { "hsf2jpp", "하이퍼 스트리트 파이터2 플러스 플러스 (일본버전)" },
    { "hsf2pp", "하이퍼 스트리트 파이터2 플러스 플러스 (미국버전)" },
    { "hshavoc", "하이 시즈 하복" },
    { "hstenn10", "핫 샷 테니스 (v1.0)" },
    { "hstennis", "핫 샷 테니스" },
    { "hstennis10", "핫 샷 테니스 (v1.0)" },
    { "htchctch", "해치 캐치" },
    { "htengoku", "화투 화천국" },
    { "hthero", "해트트릭 히어로 (일본판)" },
    { "hthero93", "해트트릭 히어로 93 (버전1.0J)" },
    { "hthero93u", "해트트릭 히어로 93 (버전1.0A)" },
    { "hthero94", "해트트릭 히어로 94 (버전2.2A)" },
    { "hthero95", "해트트릭 히어로 95 (버전2.5J)" },
    { "hthero95a", "해트트릭 히어로 95 (버전2.6A)" },
    { "hthero95u", "해트트릭 히어로 95 (버전2.5A)" },
    { "htheroj", "해트트릭 히어로 (일본판)" },
    { "htherou", "해트트릭 히어로 (미국판)" },
    { "hthro95u", "해트트릭 히어로 95 (버전2.5A)" },
    { "humlan", "험란의 휠 오브 포춘" },
    { "hunchbak", "꼽추" },
    { "hunchbaka", "꼽추 (세트2)" },
    { "hunchbgb", "꼽추 (FAR S.A. 갤럭시안 하드웨어 해적판)" },
    { "hunchbkd", "꼽추 (DK 컨버젼)" },
    { "hunchbkg", "꼽추 (갤럭시안 하드웨어)" },
    { "hunchbks", "꼽추 (스크램블 하드웨어)" },
    { "hunchbks2", "꼽추 (스크램블 하드웨어,해적판)" },
    { "huncholy", "꼽추 올림픽" },
    { "hustle", "허슬" },
    { "hustler", "비디오 허슬러" },
    { "hustlerb", "비디오 허슬러" },
    { "hustlerb2", "팻지 갬블러 (비디오 허슬러 해적판)" },
    { "hustlerb3", "비디오 풀 (비디오 허슬러 해적판)" },
    { "hustlerb4", "비디오 허슬러 (세트2)" },
    { "hustlerb5", "비디오 허슬러 (세트3)" },
    { "hustlerb7", "비디오 허슬러 (세트5)" },
    { "hustlerd", "비디오 허슬러 (다이나모 게임즈)" },
    { "hvnsgate", "헤븐즈 게이트" },
    { "hvoltage", "하이 볼티지" },
    { "hvymetal", "헤비 메탈" },
    { "hvysmsh", "헤비 스매시 (유럽판 버전-2)" },
    { "hvysmsha", "헤비 스매시 (아시아 버전-4)" },
    { "hvysmshj", "헤비 스매시 (일본판 버전-2)" },
    { "hvyunit", "헤비 유닛 (세계판)" },
    { "hvyunitj", "헤비 유닛 (일본판,신형)" },
    { "hvyunitja", "헤비 유닛" },
    { "hvyunitjo", "헤비 유닛 (일본판,구형)" },
    { "hvyunito", "헤비 유닛 (일본판,구형)" },
    { "hvyunitu", "헤비 유닛 - 미국버전(미국판)" },
    { "hwchamp", "헤비웨이트 챔프" },
    { "hwchampa", "헤비웨이트 챔프" },
    { "hwchampj", "헤비웨이트 챔프 (일본판)" },
    { "hwchampjd", "헤비웨이트 챔프 (일본판,암호해제)" },
    { "hwrace", "하이 웨이 레이스" },
    { "hydra", "하이드라" },
    { "hydrap", "하이드라 (시험판)" },
    { "hydrap2", "하이드라 (시험판)" },
    { "hyhoo", "하야오시 빨리 누르기 퀴즈" },
    { "hyhoo2", "하야오시 빨리 누르기 퀴즈 2" },
    { "hyouban", "마작 빙판 소녀 (일본판)" },
    { "hypbbc2p", "하이퍼 비시바시 챔프 - 2 플레이어 (버전JAA)" },
    { "hypbbc2pk", "하이퍼 비시바시 챔프 - 2 플레이어 (버전KAA)" },
    { "hyperath", "하이퍼 애슬리트" },
    { "hyperbbc", "하이퍼 비시바시 챔프 (버전EAA)" },
    { "hyperbbca", "하이퍼 비시바시 챔프 (버전AAA)" },
    { "hyperbbck", "하이퍼 비시바시 챔프 (버전KAA)" },
    { "hypernoid", "하이퍼노이드 (HB)" },
    { "hyperpac", "하이퍼 팩맨" },
    { "hyperpacb", "하이퍼 팩맨" },
    { "hyperpcb", "하이퍼 팩맨" },
    { "hyperspc", "하이퍼스페이스" },
    { "hyperspt", "하이퍼 스포츠" },
    { "hypersptb", "하이퍼 스포츠" },
    { "hyprdelj", "하이퍼 듀얼 (일본판 세트2)" },
    { "hyprdriv", "하이퍼드라이브" },
    { "hyprduel", "하이퍼 듀얼" },
    { "hyprduel2", "하이퍼 듀얼 (일본판 세트2)" },
    { "hypreac2", "마작 하이퍼 리액션 2 (일본판)" },
    { "hypreact", "마작 하이퍼 리액션 (일본판)" },
    { "hyprolyb", "트랙 앤 필드/ 하이퍼 올림픽 (해적판)" },
    { "hyprolym", "트랙 앤 필드/ 하이퍼 올림픽" },
    { "hyprolyma", "트랙 앤 필드/ 하이퍼 올림픽 (버그픽스드)" },
    { "hyprolymb", "트랙 앤 필드/ 하이퍼 올림픽 (해적판,세트1)" },
    { "hyprolymba", "트랙 앤 필드/ 하이퍼 올림픽 (해적판,세트2)" },
    { "hypsptsp", "88 올림픽/ 하이퍼 스포츠 스페셜 (일본판)" },
};

const size_t lookup_h_count = A_SIZE(lookup_h_table);

const char *lookup_h(const char *name) {
    if (!name) return NULL;
    for (size_t i = 0; i < lookup_h_count; i++) {
        if (strcmp(lookup_h_table[i].name, name) == 0) {
            return lookup_h_table[i].value;
        }
    }
    return NULL;
}

const char *r_lookup_h(const char *value) {
    if (!value) return NULL;
    for (size_t i = 0; i < lookup_h_count; i++) {
        if (strstr(lookup_h_table[i].value, value)) {
            return lookup_h_table[i].name;
        }
    }
    return NULL;
}

void lookup_h_multi(const char *term, void (*emit)(const char *name, const char *value, void *udata), void *udata) {
    if (!term) return;
    for (size_t i = 0; i < lookup_h_count; i++) {
        if (strcasestr(lookup_h_table[i].name, term))
            emit(lookup_h_table[i].name, lookup_h_table[i].value, udata);
    }
}

void r_lookup_h_multi(const char *term, void (*emit)(const char *name, const char *value, void *udata), void *udata) {
    if (!term) return;
    for (size_t i = 0; i < lookup_h_count; i++) {
        if (strcasestr(lookup_h_table[i].value, term))
            emit(lookup_h_table[i].name, lookup_h_table[i].value, udata);
    }
}
